// Russian text for lesson-07, matching shape.ts's keys. Typed as
// `PartialByKey<LessonShape>`.
// Not translated yet -- every `ru` is the empty-array placeholder.
import type { PartialByKey } from "../../lib/chapter-shape-types.ts";
import type { LessonShape } from "./shape.ts";

const ru: PartialByKey<LessonShape> = {
  title: { ru: [] },
  summary: { ru: [] },
  vocabYao: { ru: [] },
  vocabNeng: { ru: [] },
  vocabZhidao: { ru: [] },
  vocabAi: { ru: [] },
  vocabKeneng: { ru: [] },
  vocabDeng: { ru: [] },
  vocabYifu: { ru: [] },
  proseWant: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleWant1: { ru: [] },
  exampleWant2: { ru: [] },
  exampleWant3: { ru: [] },
  exampleWant4: { ru: [] },
  exampleWant5: { ru: [] },
  proseCan: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleCan1: { ru: [] },
  exampleCan2: { ru: [] },
  exampleCan3: { ru: [] },
  exampleCan4: { ru: [] },
  proseKnowHow: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleKnowHow1: { ru: [] },
  exampleKnowHow2: { ru: [] },
  exampleKnowHow3: { ru: [] },
  exampleKnowHow4: { ru: [] },
  proseLove: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleLove1: { ru: [] },
  exampleLove2: { ru: [] },
  exampleLove3: { ru: [] },
  exampleLove4: { ru: [] },
  exampleLove5: { ru: [] },
  proseMaybe: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleMaybe1: { ru: [] },
  exampleMaybe2: { ru: [] },
  exampleMaybe3: { ru: [] },
  exampleMaybe4: { ru: [] },
  infoPreVerbs: {
    title: { ru: [] },
    items: [
      { ru: [] },
      { ru: [] },
      { ru: [] },
      { ru: [] },
      { ru: [] },
      { ru: [] },
    ],
  },
  exercise1: { ru: [] },
  exercise2: { ru: [] },
  exercise3: { ru: [] },
  exercise4: { ru: [] },
  exercise5: { ru: [] },
  exercise6: { ru: [] },
  exercise7: { ru: [] },
  exercise8: { ru: [] },
  answer1: { ru: [] },
  answer2: { ru: [] },
  answer3: { ru: [] },
  answer4: { ru: [] },
  answer5: { ru: [] },
  answer6: { ru: [] },
  answer7: { ru: [] },
  answer8: { ru: [] },
};

export default ru;
