// Chinese text for lesson-07, matching shape.ts's keys. Typed as
// `PartialByKey<LessonShape>`.
// Not translated yet -- every `zh` is the empty-array placeholder.
import type { PartialByKey } from "../../lib/chapter-shape-types.ts";
import type { LessonShape } from "./shape.ts";

const zh: PartialByKey<LessonShape> = {
  title: { zh: [] },
  summary: { zh: [] },
  vocabYao: { zh: [] },
  vocabNeng: { zh: [] },
  vocabZhidao: { zh: [] },
  vocabAi: { zh: [] },
  vocabKeneng: { zh: [] },
  vocabDeng: { zh: [] },
  vocabYifu: { zh: [] },
  proseWant: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleWant1: { zh: [] },
  exampleWant2: { zh: [] },
  exampleWant3: { zh: [] },
  exampleWant4: { zh: [] },
  exampleWant5: { zh: [] },
  proseCan: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleCan1: { zh: [] },
  exampleCan2: { zh: [] },
  exampleCan3: { zh: [] },
  exampleCan4: { zh: [] },
  proseKnowHow: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleKnowHow1: { zh: [] },
  exampleKnowHow2: { zh: [] },
  exampleKnowHow3: { zh: [] },
  exampleKnowHow4: { zh: [] },
  proseLove: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleLove1: { zh: [] },
  exampleLove2: { zh: [] },
  exampleLove3: { zh: [] },
  exampleLove4: { zh: [] },
  exampleLove5: { zh: [] },
  proseMaybe: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleMaybe1: { zh: [] },
  exampleMaybe2: { zh: [] },
  exampleMaybe3: { zh: [] },
  exampleMaybe4: { zh: [] },
  infoPreVerbs: {
    title: { zh: [] },
    items: [
      { zh: [] },
      { zh: [] },
      { zh: [] },
      { zh: [] },
      { zh: [] },
      { zh: [] },
    ],
  },
  exercise1: { zh: [] },
  exercise2: { zh: [] },
  exercise3: { zh: [] },
  exercise4: { zh: [] },
  exercise5: { zh: [] },
  exercise6: { zh: [] },
  exercise7: { zh: [] },
  exercise8: { zh: [] },
  answer1: { zh: [] },
  answer2: { zh: [] },
  answer3: { zh: [] },
  answer4: { zh: [] },
  answer5: { zh: [] },
  answer6: { zh: [] },
  answer7: { zh: [] },
  answer8: { zh: [] },
};

export default zh;
