// Russian text for lesson-10, matching shape.ts's keys. Typed as
// `PartialByKey<LessonShape>`.
// Not translated yet -- every `ru` is the empty-array placeholder.
import type { PartialByKey } from "../../lib/chapter-shape-types.ts";
import type { LessonShape } from "./shape.ts";

const ru: PartialByKey<LessonShape> = {
  title: { ru: [] },
  summary: { ru: [] },
  vocabLi: { ru: [] },
  proseWhere: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleWhere1: { ru: [] },
  exampleWhere2: { ru: [] },
  exampleWhere3: { ru: [] },
  exampleWhere4: { ru: [] },
  exampleWhere5: { ru: [] },
  vocabNali: { ru: [] },
  proseWhereQuestion: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleWhereQuestion1: { ru: [] },
  exampleWhereQuestion2: { ru: [] },
  exampleWhereQuestion3: { ru: [] },
  vocabShang: { ru: [] },
  vocabXia: { ru: [] },
  vocabMian: { ru: [] },
  vocabDi: { ru: [] },
  proseInOnUnder: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleInOnUnder1: { ru: [] },
  exampleInOnUnder2: { ru: [] },
  exampleInOnUnder3: { ru: [] },
  exampleInOnUnder4: { ru: [] },
  exampleInOnUnder5: { ru: [] },
  exampleInOnUnder6: { ru: [] },
  exampleInOnUnder7: { ru: [] },
  vocabQian: { ru: [] },
  vocabPang: { ru: [] },
  vocabBian: { ru: [] },
  vocabPangbian: { ru: [] },
  proseSides: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleSides1: { ru: [] },
  exampleSides2: { ru: [] },
  exampleSides3: { ru: [] },
  exampleSides4: { ru: [] },
  exampleSides5: { ru: [] },
  exampleSides6: { ru: [] },
  exampleSides7: { ru: [] },
  exampleSides8: { ru: [] },
  exampleSides9: { ru: [] },
  infoWhereThingsAre: {
    title: { ru: [] },
    items: [{ ru: [] }, { ru: [] }, { ru: [] }, { ru: [] }],
  },
  exercise1: { ru: [] },
  exercise2: { ru: [] },
  exercise3: { ru: [] },
  exercise4: { ru: [] },
  exercise5: { ru: [] },
  exercise6: { ru: [] },
  exercise7: { ru: [] },
  exercise8: { ru: [] },
  answer1: { ru: [] },
  answer2: { ru: [] },
  answer3: { ru: [] },
  answer4: { ru: [] },
  answer5: { ru: [] },
  answer6: { ru: [] },
  answer7: { ru: [] },
  answer8: { ru: [] },
  faqZaiSameWord: { question: { ru: [] }, ru: [] },
  faqThingNeedsLi: { question: { ru: [] }, ru: [] },
  faqLiOrLimian: { question: { ru: [] }, ru: [] },
};

export default ru;
