// Chinese text for lesson-10, matching shape.ts's keys. Typed as
// `PartialByKey<LessonShape>`.
// Not translated yet -- every `zh` is the empty-array placeholder.
import type { PartialByKey } from "../../lib/chapter-shape-types.ts";
import type { LessonShape } from "./shape.ts";

const zh: PartialByKey<LessonShape> = {
  title: { zh: [] },
  summary: { zh: [] },
  vocabLi: { zh: [] },
  vocabShang: { zh: [] },
  vocabXia: { zh: [] },
  vocabQian: { zh: [] },
  vocabPang: { zh: [] },
  vocabBian: { zh: [] },
  vocabPangbian: { zh: [] },
  vocabMian: { zh: [] },
  vocabNali: { zh: [] },
  vocabDi: { zh: [] },
  proseWhere: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleWhere1: { zh: [] },
  exampleWhere2: { zh: [] },
  exampleWhere3: { zh: [] },
  exampleWhere4: { zh: [] },
  proseWhereQuestion: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleWhereQuestion1: { zh: [] },
  exampleWhereQuestion2: { zh: [] },
  exampleWhereQuestion3: { zh: [] },
  proseInOnUnder: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleInOnUnder1: { zh: [] },
  exampleInOnUnder2: { zh: [] },
  exampleInOnUnder3: { zh: [] },
  exampleInOnUnder4: { zh: [] },
  exampleInOnUnder5: { zh: [] },
  exampleInOnUnder6: { zh: [] },
  exampleInOnUnder7: { zh: [] },
  proseSides: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleSides1: { zh: [] },
  exampleSides2: { zh: [] },
  exampleSides3: { zh: [] },
  exampleSides4: { zh: [] },
  exampleSides5: { zh: [] },
  exampleSides6: { zh: [] },
  exampleSides7: { zh: [] },
  exampleSides8: { zh: [] },
  exampleSides9: { zh: [] },
  infoWhereThingsAre: {
    title: { zh: [] },
    items: [{ zh: [] }, { zh: [] }, { zh: [] }, { zh: [] }],
  },
  exercise1: { zh: [] },
  exercise2: { zh: [] },
  exercise3: { zh: [] },
  exercise4: { zh: [] },
  exercise5: { zh: [] },
  exercise6: { zh: [] },
  exercise7: { zh: [] },
  exercise8: { zh: [] },
  answer1: { zh: [] },
  answer2: { zh: [] },
  answer3: { zh: [] },
  answer4: { zh: [] },
  answer5: { zh: [] },
  answer6: { zh: [] },
  answer7: { zh: [] },
  answer8: { zh: [] },
};

export default zh;
