// Chinese text for lesson-05, matching shape.ts's keys. Typed as
// `PartialByKey<LessonShape>`. Not translated yet -- every `zh` is the
// empty-array placeholder.
import type { PartialByKey } from "../../lib/chapter-shape-types.ts";
import type { LessonShape } from "./shape.ts";

const zh: PartialByKey<LessonShape> = {
  title: { zh: [] },
  summary: { zh: [] },
  vocabYou: { zh: [] },
  vocabMei: { zh: [] },
  vocabTing: { zh: [] },
  vocabChi: { zh: [] },
  vocabZuo: { zh: [] },
  vocabZhidao: { zh: [] },
  vocabShuo: { zh: [] },
  proseVerbs: { zh: [] },
  verbsExample1: { zh: [] },
  verbsExample2: { zh: [] },
  verbsExample3: { zh: [] },
  proseVerbNegation: { zh: [] },
  negationExample1: { zh: [] },
  negationExample2: { zh: [] },
  negationExample3: { zh: [] },
  proseWordOrderObject: { zh: [] },
  wordOrderExample1: { zh: [] },
  wordOrderExample2: { zh: [] },
  vocabLe: { zh: [] },
  vocabGuo: { zh: [] },
  vocabularyZai: { zh: [] },
  vocabHui: { zh: [] },
  proseLeCompletion: { zh: [] },
  infoCompletionMarker: { items: [{zh:[]}] },
  leExample1: { zh: [] },
  proseGuo: { zh: [] },
  guoExample1: { zh: [] },
  proseZai: { zh: [] },
  zaiExample1: { zh: [] },
  proseHui: { zh: [] },
  huiExample1: { zh: [] },
  completionMarkers: { zh: [] },
  infoCompletionMarkers: { items: [{zh:[]},{zh:[]},{zh:[]}] },
  exampleCompletionMarker1: { zh: [] },
  exampleCompletionMarker2: { zh: [] },
  exampleCompletionMarker3: { zh: [] },
  vocabQi: { zh: [] },
  vocabXia: { zh: [] },
  vocabShang: { zh: [] },
  vocabLai: { zh: [] },
  proseDirectionalComplements: { zh: [] },
  infoDirectionalComplements: { items: [{zh:[]},{zh:[]},{zh:[]}] },
  directionalExample1: { zh: [] },
  directionalExample2: { zh: [] },
  directionalExample3: { zh: [] },
  example1: { zh: [] },
  example2: { zh: [] },
  example3: { zh: [] },
  example4: { zh: [] },
  example5: { zh: [] },
  example6: { zh: [] },
  example7: { zh: [] },
  exercise1: { zh: [] },
  exercise2: { zh: [] },
  exercise3: { zh: [] },
  exercise4: { zh: [] },
  answer1: { zh: [] },
  answer2: { zh: [] },
  answer3: { zh: [] },
  answer4: { zh: [] },
};

export default zh;
