// Chinese text for colors, matching shape.ts's keys. Typed as
// `PartialByKey<LessonShape>`.
// Not translated yet -- every `zh` is the empty-array placeholder.
import type { PartialByKey } from "../../../lib/chapter-shape-types.ts";
import type { LessonShape } from "./shape.ts";

const zh: PartialByKey<LessonShape> = {
  title: { zh: [] },
  summary: { zh: [] },
  vocabBaise: { zh: [] },
  vocabHeise: { zh: [] },
  vocabHongse: { zh: [] },
  vocabHuangse: { zh: [] },
  proseColorThing: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleColorThing1: { zh: [] },
  exampleColorThing2: { zh: [] },
  exampleColorThing3: { zh: [] },
  exampleColorThing4: { zh: [] },
  exampleColorThing5: { zh: [] },
  exampleColorThing6: { zh: [] },
  vocabLanse: { zh: [] },
  proseIsColor: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleIsColor1: { zh: [] },
  exampleIsColor3: { zh: [] },
  exampleIsColor5: { zh: [] },
  exampleIsColor7: { zh: [] },
  exampleIsColor9: { zh: [] },
  exampleIsColor10: { zh: [] },
  exampleIsColor12: { zh: [] },
  exampleIsColor13: { zh: [] },
  vocabYanse: { zh: [] },
  proseWhatColor: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleWhatColor1: { zh: [] },
  exampleWhatColor2: { zh: [] },
  exampleWhatColor3: { zh: [] },
  exampleWhatColor5: { zh: [] },
  exampleWhatColor6: { zh: [] },
  exampleWhatColor7: { zh: [] },
  exampleWhatColor8: { zh: [] },
  exampleWhatColor9: { zh: [] },
  infoColors: {
    title: { zh: [] },
    items: [{ zh: [] }, { zh: [] }, { zh: [] }],
  },
  exercise1: { zh: [] },
  exercise2: { zh: [] },
  exercise3: { zh: [] },
  exercise4: { zh: [] },
  exercise5: { zh: [] },
  exercise6: { zh: [] },
  answer1: { zh: [] },
  answer2: { zh: [] },
  answer3: { zh: [] },
  answer4: { zh: [] },
  answer5: { zh: [] },
  answer6: { zh: [] },
  faqLanBlueGreen: { question: { zh: [] }, zh: [] },
  faqColorNoHen: { question: { zh: [] }, zh: [] },
};

export default zh;
