// Russian text for words-and-sentences, matching shape.ts's keys. Typed as
// `PartialByKey<LessonShape>`.
// Not translated yet -- every `ru` is the empty-array placeholder.
import type { PartialByKey } from "../../../lib/chapter-shape-types.ts";
import type { LessonShape } from "./shape.ts";

const ru: PartialByKey<LessonShape> = {
  title: { ru: [] },
  summary: { ru: [] },
  vocabShi: { ru: [] },
  vocabDongxi: { ru: [] },
  vocabRen: { ru: [] },
  vocabNuren: { ru: [] },
  vocabNanren: { ru: [] },
  vocabDongwu: { ru: [] },
  vocabShuiguo: { ru: [] },
  proseIs: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleIs1: { ru: [] },
  exampleIs2: { ru: [] },
  exampleIs3: { ru: [] },
  exampleIs4: { ru: [] },
  vocabZhe: { ru: [] },
  proseThis: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleThis1: { ru: [] },
  exampleThis2: { ru: [] },
  exampleThis3: { ru: [] },
  exampleThis4: { ru: [] },
  vocabBu: { ru: [] },
  proseNot: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleNot1: { ru: [] },
  exampleNot2: { ru: [] },
  exampleNot3: { ru: [] },
  exampleNot4: { ru: [] },
  infoIsAndIsNot: { title: { ru: [] }, items: [{ ru: [] }, { ru: [] }] },
  exercise1: { ru: [] },
  exercise2: { ru: [] },
  exercise3: { ru: [] },
  exercise4: { ru: [] },
  exercise5: { ru: [] },
  exercise6: { ru: [] },
  exercise7: { ru: [] },
  exercise8: { ru: [] },
  answer1: { ru: [] },
  answer2: { ru: [] },
  answer3: { ru: [] },
  answer4: { ru: [] },
  answer5: { ru: [] },
  answer6: { ru: [] },
  answer7: { ru: [] },
  answer8: { ru: [] },
  faqAOrThe: { question: { ru: [] }, ru: [] },
  faqShiNeverChanges: { question: { ru: [] }, ru: [] },
};

export default ru;
