// Chinese text for words-and-sentences, matching shape.ts's keys. Typed as
// `PartialByKey<LessonShape>`.
// Not translated yet -- every `zh` is the empty-array placeholder.
import type { PartialByKey } from "../../../lib/chapter-shape-types.ts";
import type { LessonShape } from "./shape.ts";

const zh: PartialByKey<LessonShape> = {
  title: { zh: [] },
  summary: { zh: [] },
  vocabShi: { zh: [] },
  vocabDongxi: { zh: [] },
  vocabRen: { zh: [] },
  vocabNuren: { zh: [] },
  vocabNanren: { zh: [] },
  vocabDongwu: { zh: [] },
  vocabShuiguo: { zh: [] },
  proseIs: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleIs1: { zh: [] },
  exampleIs2: { zh: [] },
  exampleIs3: { zh: [] },
  exampleIs4: { zh: [] },
  vocabZhe: { zh: [] },
  proseThis: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleThis1: { zh: [] },
  exampleThis2: { zh: [] },
  exampleThis3: { zh: [] },
  exampleThis4: { zh: [] },
  vocabBu: { zh: [] },
  proseNot: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleNot1: { zh: [] },
  exampleNot2: { zh: [] },
  exampleNot3: { zh: [] },
  exampleNot4: { zh: [] },
  infoIsAndIsNot: { title: { zh: [] }, items: [{ zh: [] }, { zh: [] }] },
  exercise1: { zh: [] },
  exercise2: { zh: [] },
  exercise3: { zh: [] },
  exercise4: { zh: [] },
  exercise5: { zh: [] },
  exercise6: { zh: [] },
  exercise7: { zh: [] },
  exercise8: { zh: [] },
  answer1: { zh: [] },
  answer2: { zh: [] },
  answer3: { zh: [] },
  answer4: { zh: [] },
  answer5: { zh: [] },
  answer6: { zh: [] },
  answer7: { zh: [] },
  answer8: { zh: [] },
  faqAOrThe: { question: { zh: [] }, zh: [] },
  faqShiNeverChanges: { question: { zh: [] }, zh: [] },
};

export default zh;
