// Russian text for lesson-10, matching shape.ts's keys. Typed as
// `PartialByKey<LessonShape>`. Not translated yet -- every `ru` is the
// empty-array placeholder.
import type { PartialByKey } from "../../../../lib/chapter-shape-types.ts";
import type { LessonShape } from "./shape.ts";

const ru: PartialByKey<LessonShape> = {
  title: { ru: [] },
  summary: { ru: [] },
  vocabBu: { ru: [] },
  vocabHuai: { ru: [] },
  vocabDuo: { ru: [] },
  vocabFumu: { ru: [] },
  vocabYi: { ru: [] },
  vocabLiliang: { ru: [] },
  proseBuildingAdjective: { ru: [] },
  infoBuildingAdjective: { items: [{ru:[]}] },
  proseAdjectivesAsAdverbs: { ru: [] },
  infoAdjectivesAsAdverbs: { items: [{ru:[]}] },
  proseStateChange: { ru: [] },
  infoStateChange: { items: [{ru:[]}] },
  infoCausative: { items: [{ru:[],items:[{ru:[]}]}] },
  example1: { ru: [] },
  example2: { ru: [] },
  example3: { ru: [] },
  example4: { ru: [] },
  example5: { ru: [] },
  example6: { ru: [] },
  example7: { ru: [] },
  example8: { ru: [] },
  exercise1: { ru: [] },
  exercise2: { ru: [] },
  exercise3: { ru: [] },
  exercise4: { ru: [] },
  answer1: { ru: [] },
  answer2: { ru: [] },
  answer3: { ru: [] },
  answer4: { ru: [] },
  vocabGei: { ru: [] },
  vocabZai: { ru: [] },
  vocabYong: { ru: [] },
  vocabYinwei: { ru: [] },
  proseRelationshipWords: { ru: [] },
  infoRelationshipWordOrder: { items: [{ru:[]}] },
  proseWordAsPredicate: { ru: [] },
  example9: { ru: [] },
  example10: { ru: [] },
  example11: { ru: [] },
  example12: { ru: [] },
  example13: { ru: [] },
  example14: { ru: [] },
  example15: { ru: [] },
  exercise5: { ru: [] },
  exercise6: { ru: [] },
  exercise7: { ru: [] },
  answer5: { ru: [] },
  answer6: { ru: [] },
  answer7: { ru: [] },
};

export default ru;
