// Chinese text for lesson-10, matching shape.ts's keys. Typed as
// `PartialByKey<LessonShape>`. Not translated yet -- every `zh` is the
// empty-array placeholder.
import type { PartialByKey } from "../../../../lib/chapter-shape-types.ts";
import type { LessonShape } from "./shape.ts";

const zh: PartialByKey<LessonShape> = {
  title: { zh: [] },
  summary: { zh: [] },
  vocabBu: { zh: [] },
  vocabHuai: { zh: [] },
  vocabDuo: { zh: [] },
  vocabFumu: { zh: [] },
  vocabYi: { zh: [] },
  vocabLiliang: { zh: [] },
  proseBuildingAdjective: { zh: [] },
  infoBuildingAdjective: { items: [{zh:[]}] },
  proseAdjectivesAsAdverbs: { zh: [] },
  infoAdjectivesAsAdverbs: { items: [{zh:[]}] },
  proseStateChange: { zh: [] },
  infoStateChange: { items: [{zh:[]}] },
  infoCausative: { items: [{zh:[],items:[{zh:[]}]}] },
  example1: { zh: [] },
  example2: { zh: [] },
  example3: { zh: [] },
  example4: { zh: [] },
  example5: { zh: [] },
  example6: { zh: [] },
  example7: { zh: [] },
  example8: { zh: [] },
  exercise1: { zh: [] },
  exercise2: { zh: [] },
  exercise3: { zh: [] },
  exercise4: { zh: [] },
  answer1: { zh: [] },
  answer2: { zh: [] },
  answer3: { zh: [] },
  answer4: { zh: [] },
  vocabGei: { zh: [] },
  vocabZai: { zh: [] },
  vocabYong: { zh: [] },
  vocabYinwei: { zh: [] },
  proseRelationshipWords: { zh: [] },
  infoRelationshipWordOrder: { items: [{zh:[]}] },
  proseWordAsPredicate: { zh: [] },
  example9: { zh: [] },
  example10: { zh: [] },
  example11: { zh: [] },
  example12: { zh: [] },
  example13: { zh: [] },
  example14: { zh: [] },
  example15: { zh: [] },
  exercise5: { zh: [] },
  exercise6: { zh: [] },
  exercise7: { zh: [] },
  answer5: { zh: [] },
  answer6: { zh: [] },
  answer7: { zh: [] },
};

export default zh;
