// Russian text for also-and-all, matching shape.ts's keys. Typed as
// `PartialByKey<LessonShape>`.
// Not translated yet -- every `ru` is the empty-array placeholder.
import type { PartialByKey } from "../../../lib/chapter-shape-types.ts";
import type { LessonShape } from "./shape.ts";

const ru: PartialByKey<LessonShape> = {
  title: { ru: [] },
  summary: { ru: [] },
  vocabYe: { ru: [] },
  vocabZhiwu: { ru: [] },
  vocabHuo: { ru: [] },
  vocabKongqi: { ru: [] },
  vocabKai: { ru: [] },
  vocabGuan: { ru: [] },
  proseAlsoDo: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleAlsoDo1: { ru: [] },
  exampleAlsoDo2: { ru: [] },
  exampleAlsoDo3: { ru: [] },
  exampleAlsoDo4: { ru: [] },
  exampleAlsoDo5: { ru: [] },
  exampleAlsoDo6: { ru: [] },
  exampleAlsoDo7: { ru: [] },
  exampleAlsoDo8: { ru: [] },
  exampleAlsoDo9: { ru: [] },
  exampleAlsoDo10: { ru: [] },
  proseAlsoIs: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleAlsoIs1: { ru: [] },
  exampleAlsoIs2: { ru: [] },
  exampleAlsoIs3: { ru: [] },
  exampleAlsoIs4: { ru: [] },
  exampleAlsoIs5: { ru: [] },
  vocabDou: { ru: [] },
  proseAll: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleAll1: { ru: [] },
  exampleAll2: { ru: [] },
  exampleAll3: { ru: [] },
  exampleAll4: { ru: [] },
  exampleAll5: { ru: [] },
  exampleAll6: { ru: [] },
  exampleAll7: { ru: [] },
  exampleAll8: { ru: [] },
  proseEverything: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleEverything1: { ru: [] },
  exampleEverything2: { ru: [] },
  exampleEverything3: { ru: [] },
  exampleEverything4: { ru: [] },
  exampleEverything5: { ru: [] },
  vocabBufen: { ru: [] },
  prosePart: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  examplePart1: { ru: [] },
  examplePart2: { ru: [] },
  examplePart3: { ru: [] },
  examplePart4: { ru: [] },
  infoAlsoAndAll: {
    title: { ru: [] },
    items: [
      { ru: [] },
      { ru: [] },
      { ru: [] },
      { ru: [] },
      { ru: [] },
    ],
  },
  exercise1: { ru: [] },
  exercise2: { ru: [] },
  exercise3: { ru: [] },
  exercise4: { ru: [] },
  exercise5: { ru: [] },
  exercise6: { ru: [] },
  exercise7: { ru: [] },
  exercise8: { ru: [] },
  exercise9: { ru: [] },
  exercise10: { ru: [] },
  answer1: { ru: [] },
  answer2: { ru: [] },
  answer3: { ru: [] },
  answer4: { ru: [] },
  answer5: { ru: [] },
  answer6: { ru: [] },
  answer7: { ru: [] },
  answer8: { ru: [] },
  answer9: { ru: [] },
  answer10: { ru: [] },
  faqMeToo: { question: { ru: [] }, ru: [] },
  faqMeiDidnt: { question: { ru: [] }, ru: [] },
  faqAllPeople: { question: { ru: [] }, ru: [] },
};

export default ru;
