// Chinese text for also-and-all, matching shape.ts's keys. Typed as
// `PartialByKey<LessonShape>`.
// Not translated yet -- every `zh` is the empty-array placeholder.
import type { PartialByKey } from "../../../lib/chapter-shape-types.ts";
import type { LessonShape } from "./shape.ts";

const zh: PartialByKey<LessonShape> = {
  title: { zh: [] },
  summary: { zh: [] },
  vocabYe: { zh: [] },
  vocabZhiwu: { zh: [] },
  vocabHuo: { zh: [] },
  vocabKongqi: { zh: [] },
  vocabKai: { zh: [] },
  vocabGuan: { zh: [] },
  proseAlsoDo: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleAlsoDo1: { zh: [] },
  exampleAlsoDo2: { zh: [] },
  exampleAlsoDo3: { zh: [] },
  exampleAlsoDo4: { zh: [] },
  exampleAlsoDo5: { zh: [] },
  exampleAlsoDo6: { zh: [] },
  exampleAlsoDo7: { zh: [] },
  exampleAlsoDo8: { zh: [] },
  exampleAlsoDo9: { zh: [] },
  exampleAlsoDo10: { zh: [] },
  proseAlsoIs: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleAlsoIs1: { zh: [] },
  exampleAlsoIs2: { zh: [] },
  exampleAlsoIs3: { zh: [] },
  exampleAlsoIs4: { zh: [] },
  exampleAlsoIs5: { zh: [] },
  vocabDou: { zh: [] },
  proseAll: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleAll1: { zh: [] },
  exampleAll2: { zh: [] },
  exampleAll3: { zh: [] },
  exampleAll4: { zh: [] },
  exampleAll5: { zh: [] },
  exampleAll6: { zh: [] },
  exampleAll7: { zh: [] },
  exampleAll8: { zh: [] },
  proseEverything: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleEverything1: { zh: [] },
  exampleEverything2: { zh: [] },
  exampleEverything3: { zh: [] },
  exampleEverything4: { zh: [] },
  exampleEverything5: { zh: [] },
  vocabBufen: { zh: [] },
  prosePart: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  examplePart1: { zh: [] },
  examplePart2: { zh: [] },
  examplePart3: { zh: [] },
  examplePart4: { zh: [] },
  infoAlsoAndAll: {
    title: { zh: [] },
    items: [
      { zh: [] },
      { zh: [] },
      { zh: [] },
      { zh: [] },
      { zh: [] },
    ],
  },
  exercise1: { zh: [] },
  exercise2: { zh: [] },
  exercise3: { zh: [] },
  exercise4: { zh: [] },
  exercise5: { zh: [] },
  exercise6: { zh: [] },
  exercise7: { zh: [] },
  exercise8: { zh: [] },
  exercise9: { zh: [] },
  exercise10: { zh: [] },
  answer1: { zh: [] },
  answer2: { zh: [] },
  answer3: { zh: [] },
  answer4: { zh: [] },
  answer5: { zh: [] },
  answer6: { zh: [] },
  answer7: { zh: [] },
  answer8: { zh: [] },
  answer9: { zh: [] },
  answer10: { zh: [] },
  faqMeToo: { question: { zh: [] }, zh: [] },
  faqMeiDidnt: { question: { zh: [] }, zh: [] },
  faqAllPeople: { question: { zh: [] }, zh: [] },
};

export default zh;
