// Russian text for lesson-17, matching shape.ts's keys. Typed as
// `PartialByKey<LessonShape>`.
// Not translated yet -- every `ru` is the empty-array placeholder.
import type { PartialByKey } from "../../lib/chapter-shape-types.ts";
import type { LessonShape } from "./shape.ts";

const ru: PartialByKey<LessonShape> = {
  title: { ru: [] },
  summary: { ru: [] },
  vocabYanse: { ru: [] },
  vocabBaise: { ru: [] },
  vocabHeise: { ru: [] },
  vocabHongse: { ru: [] },
  vocabHuangse: { ru: [] },
  vocabLanse: { ru: [] },
  proseColorThing: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleColorThing1: { ru: [] },
  exampleColorThing2: { ru: [] },
  exampleColorThing3: { ru: [] },
  exampleColorThing4: { ru: [] },
  proseIsColor: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleIsColor1: { ru: [] },
  exampleIsColor2: { ru: [] },
  exampleIsColor3: { ru: [] },
  exampleIsColor4: { ru: [] },
  exampleIsColor5: { ru: [] },
  exampleIsColor6: { ru: [] },
  exampleIsColor7: { ru: [] },
  exampleIsColor8: { ru: [] },
  exampleIsColor9: { ru: [] },
  exampleIsColor10: { ru: [] },
  exampleIsColor11: { ru: [] },
  proseWhatColor: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleWhatColor1: { ru: [] },
  exampleWhatColor2: { ru: [] },
  exampleWhatColor3: { ru: [] },
  exampleWhatColor4: { ru: [] },
  exampleWhatColor5: { ru: [] },
  exampleWhatColor6: { ru: [] },
  exampleWhatColor7: { ru: [] },
  exampleWhatColor8: { ru: [] },
  infoColors: {
    title: { ru: [] },
    items: [{ ru: [] }, { ru: [] }, { ru: [] }],
  },
  exercise1: { ru: [] },
  exercise2: { ru: [] },
  exercise3: { ru: [] },
  exercise4: { ru: [] },
  exercise5: { ru: [] },
  exercise6: { ru: [] },
  answer1: { ru: [] },
  answer2: { ru: [] },
  answer3: { ru: [] },
  answer4: { ru: [] },
  answer5: { ru: [] },
  answer6: { ru: [] },
};

export default ru;
