// D61 (BOOK_PLAN.md D61, as decided with the author): roots that bring the
// composites closer to Mandarin, chosen by `npm run report-heads` (which
// roots would let the most composites say Mandarin's own word, and take
// load off generic heads like dōng-xi, zuò and rén).
//   - 22 new words: ràng (let, make), yǐ, hái, xiē, zhǐ, shéi, tóng, ér, zi,
//     shū, zì, xiǎng, zǒu, fàn, wǎn, zuó, bǎi, zhòng, jiàn, tí, huà, cháng.
//   - New senses: zài 再 (zài-jiàn), xiào 校 (xué-xiào), shí 实 (shì-shí,
//     zhēn-shí, xiàn-shí), xīn 新 (xīn-nián), hái 孩 (hái-zi), and 名 now
//     also in míng-zi.
//   - gùnzi leaves: a stick is cháng-de dōng-xi.
//   - Sentences: chī dōng-xi -> chī fàn, shénme rén -> shéi, hair
//     (tóu-shàng-de máo) -> tóu-fā. jiàzhí, máo, dēng, tōng and qíguài stay.
//   - The compound rule then puts each Mandarin word the new roots can write
//     first in the composite dictionary (proposed).
// Run: npm run refactor -- refactors/D61.ts [--write]

const POS = {
  noun: { eng: "noun", rus: "существительное", zh: "名词" },
  verb: { eng: "verb", rus: "глагол", zh: "动词" },
  adj: { eng: "adjective", rus: "прилагательное", zh: "形容词" },
  adv: { eng: "adverb", rus: "наречие", zh: "副词" },
  pron: { eng: "pronoun", rus: "местоимение", zh: "代词" },
  num: { eng: "number", rus: "числительное", zh: "数词" },
  part: { eng: "particle", rus: "частица", zh: "助词" },
  suffix: { eng: "suffix", rus: "суффикс", zh: "后缀" },
  measure: { eng: "measure word", rus: "счётное слово", zh: "量词" },
};
const add = (id, hanzi, category, pos, eng, rus, zh, index, needEng, needRus) => ({
  op: "add", id, hanzi, category, pos, definition: { eng, rus, zh }, necessity: { index, eng: needEng, rus: needRus },
});
const card = (id, to, en, ru, sense) => ({ op: "card", id, to, en, ru, ...(sense ? { sense } : {}) });
const W = (id) => `{{word:${id}}}`;
const L = (id) => `{{light:${id}}}`;

export default [
  // -- the new words ---------------------------------------------------------------
  add("rang4", "让", "state-change-general", POS.verb,
    `to let, allow; to make (someone do or feel something): ${W("rang4")} ${W("ta1")} ${W("jin4")}-${W("lai2")}, let him in; ${W("rang4")} ${W("wo3")} ${W("kan4")}-kan, let me see`,
    `позволять, давать; заставлять (что-то сделать или почувствовать): ${W("rang4")} ${W("ta1")} ${W("jin4")}-${W("lai2")} — впусти его; ${W("rang4")} ${W("wo3")} ${W("kan4")}-kan — дай посмотреть`,
    "让，允许，使", 4,
    `Let and make: without it, letting someone do something, or making them feel something, takes a roundabout phrase.`,
    `«Позволять» и «заставлять»: без него, чтобы кому-то что-то позволить или вызвать чувство, нужна длинная фраза.`),
  add("yi3", "以", "modality", POS.part,
    `by, with; it builds ${W("ke3")}-${W("yi3")} (can, may), ${W("yi3")}-${W("qian2")} (before) and ${W("yi3")}-${W("hou4")} (after)`,
    `посредством; из него ${W("ke3")}-${W("yi3")} (можно), ${W("yi3")}-${W("qian2")} (раньше) и ${W("yi3")}-${W("hou4")} (потом)`,
    "以，用", 3,
    `Can and may (${W("ke3")}-${W("yi3")}), before and after (${W("yi3")}-${W("qian2")}, ${W("yi3")}-${W("hou4")}) are built from it.`,
    `Из него строятся «можно» (${W("ke3")}-${W("yi3")}), «раньше» и «потом» (${W("yi3")}-${W("qian2")}, ${W("yi3")}-${W("hou4")}).`),
  add("hai2", "还", "conjunction", POS.adv,
    `still, also, yet: ${W("ta1")} ${W("hai2")} ${W("zai4")} ${W("jia1")}, he's still at home; ${W("hai2")}-${W("shi4")}, or (in a question)`,
    `ещё, всё ещё, также: ${W("ta1")} ${W("hai2")} ${W("zai4")} ${W("jia1")} — он всё ещё дома; ${W("hai2")}-${W("shi4")} — или (в вопросе)`,
    "还，仍然", 4,
    `Still and yet: without it, "it's still going on" and "or?" in a question have no word.`,
    `«Ещё» и «всё ещё»: без него не сказать «это всё ещё идёт» и «или?» в вопросе.`),
  add("xie1", "些", "amount", POS.measure,
    `some, a few (several of them): ${W("zhe4")}-${W("xie1")}, these; ${W("na4")}-${W("xie1")}, those; ${W("yi1")}-${W("xie1")}, some`,
    `несколько (о многих): ${W("zhe4")}-${W("xie1")} — эти; ${W("na4")}-${W("xie1")} — те; ${W("yi1")}-${W("xie1")} — некоторые`,
    "些，一些", 4,
    `These and those for many things (${W("zhe4")}-${W("xie1")}, ${W("na4")}-${W("xie1")}), and some (${W("yi1")}-${W("xie1")}).`,
    `«Эти» и «те» для многих вещей (${W("zhe4")}-${W("xie1")}, ${W("na4")}-${W("xie1")}) и «некоторые» (${W("yi1")}-${W("xie1")}).`),
  add("zhi3", "只", "amount", POS.adv,
    `only, just: before the verb (${W("wo3")} ${W("zhi3")} ${W("yao4")} ${W("shui3")}, I only want water); ${W("zhi3")}-${W("you3")}, only`,
    `только: перед глаголом (${W("wo3")} ${W("zhi3")} ${W("yao4")} ${W("shui3")} — я хочу только воды); ${W("zhi3")}-${W("you3")} — только`,
    "只，仅仅", 4,
    `Only: without it, "just this and nothing else" takes a whole sentence.`,
    `«Только»: без него «это и больше ничего» требует целого предложения.`),
  add("shei2", "谁", "interrogatives", POS.pron,
    `who: it stays where the person would be (${W("ta1")} ${W("shi4")} ${W("shei2")}? who is he?)`,
    `кто: стоит там, где был бы человек (${W("ta1")} ${W("shi4")} ${W("shei2")}? — кто он?)`,
    "谁", 5,
    `Who: the question word for a person, said in one word.`,
    `«Кто»: вопросительное слово о человеке, одним словом.`),
  add("tong2", "同", "determiners", POS.adj,
    `same, together: ${W("bu4")}-${W("tong2")}, different; ${W("tong2")}-${W("xue2")}, classmate; ${W("tong2")}-${W("yang4")}, the same way`,
    `одинаковый, вместе: ${W("bu4")}-${W("tong2")} — разный; ${W("tong2")}-${W("xue2")} — одноклассник; ${W("tong2")}-${W("yang4")} — так же`,
    "同，相同", 3,
    `Different (${W("bu4")}-${W("tong2")}) and the people you share something with (${W("tong2")}-${W("xue2")}) are built from it.`,
    `Из него строятся «разный» (${W("bu4")}-${W("tong2")}) и те, с кем что-то делишь (${W("tong2")}-${W("xue2")}).`),
  add("er2", "儿", "people-kinship", POS.noun,
    `child, son: ${W("nv3")}-${W("er2")}, daughter; ${W("er2")}-${L("zi")}, son`,
    `ребёнок, сын: ${W("nv3")}-${W("er2")} — дочь; ${W("er2")}-${L("zi")} — сын`,
    "儿，儿子", 3,
    `Sons and daughters (${W("er2")}-${L("zi")}, ${W("nv3")}-${W("er2")}).`,
    `Сыновья и дочери (${W("er2")}-${L("zi")}, ${W("nv3")}-${W("er2")}).`),
  add("zi", "子", "grammatical-particles", POS.suffix,
    `a light ending that makes a thing word: ${W("hai2")}-${L("zi")}, child; ${W("er2")}-${L("zi")}, son; ${W("yang4")}-${L("zi")}, the way something looks; ${W("ri4")}-${L("zi")}, days, life`,
    `лёгкое окончание существительных: ${W("hai2")}-${L("zi")} — ребёнок; ${W("er2")}-${L("zi")} — сын; ${W("yang4")}-${L("zi")} — вид; ${W("ri4")}-${L("zi")} — дни, жизнь`,
    "子（名词后缀）", 3,
    `Many everyday nouns end in it: child, son, looks, days.`,
    `Им кончаются многие обычные существительные: ребёнок, сын, вид, дни.`),
  add("shu1", "书", "general", POS.noun,
    `book: ${W("kan4")} ${W("shu1")}, read; ${W("xie3")} ${W("shu1")}, write a book`,
    `книга: ${W("kan4")} ${W("shu1")} — читать; ${W("xie3")} ${W("shu1")} — писать книгу`,
    "书", 4,
    `Books and reading (${W("kan4")} ${W("shu1")}): before it, a book was "the written thing".`,
    `Книги и чтение (${W("kan4")} ${W("shu1")}): раньше книга была «написанной вещью».`),
  add("zi4", "字", "abstract-substantives", POS.noun,
    `written character (hanzi): ${W("xie3")} ${W("zi4")}, write characters; ${W("ming2")}-${L("zi4")}, name`,
    `иероглиф, знак письма: ${W("xie3")} ${W("zi4")} — писать иероглифы; ${W("ming2")}-${L("zi4")} — имя`,
    "字", 3,
    `Characters, and names (${W("ming2")}-${L("zi4")}).`,
    `Иероглифы и имена (${W("ming2")}-${L("zi4")}).`),
  add("xiang3", "想", "cognition", POS.verb,
    `to think; to want to, would like to (before a verb: ${W("wo3")} ${W("xiang3")} ${W("chi1")} ${W("fan4")}, I'd like to eat); to miss`,
    `думать; хотеть (перед глаголом: ${W("wo3")} ${W("xiang3")} ${W("chi1")} ${W("fan4")} — я хочу есть); скучать`,
    "想", 5,
    `Think and would like to: one of the most used verbs in Mandarin.`,
    `«Думать» и «хотеть»: один из самых частых глаголов китайского.`),
  add("zou3", "走", "motion", POS.verb,
    `to walk; to leave, go away: ${W("wo3")} ${W("zou3")} ${W("le")}, I'm off; ${W("zou3")}-${W("lu4")}, walk`,
    `идти пешком; уходить: ${W("wo3")} ${W("zou3")} ${W("le")} — я пошёл; ${W("zou3")}-${W("lu4")} — идти пешком`,
    "走", 4,
    `Walking and leaving: ${W("qu4")} says where to, ${W("zou3")} says you're off.`,
    `Ходьба и уход: ${W("qu4")} говорит куда, ${W("zou3")} — что вы уходите.`),
  add("fan4", "饭", "food-drink", POS.noun,
    `meal; cooked rice: ${W("chi1")} ${W("fan4")}, eat (a meal); ${W("zuo4")} ${W("fan4")}, cook`,
    `еда, трапеза; варёный рис: ${W("chi1")} ${W("fan4")} — есть; ${W("zuo4")} ${W("fan4")} — готовить`,
    "饭，米饭", 4,
    `Meals: ${W("chi1")} ${W("fan4")} is how Mandarin says eating, and cooking is ${W("zuo4")} ${W("fan4")}.`,
    `Еда: ${W("chi1")} ${W("fan4")} — так по-китайски говорят «есть», а готовить — ${W("zuo4")} ${W("fan4")}.`),
  add("wan3", "晚", "time", POS.adj,
    `late; evening: ${W("wan3")}-${L("shang4")}, evening, night; ${W("hen3")} ${W("wan3")} ${W("le")}, it's late`,
    `поздний; вечер: ${W("wan3")}-${L("shang4")} — вечер, ночь; ${W("hen3")} ${W("wan3")} ${W("le")} — уже поздно`,
    "晚，晚上", 3,
    `Evening and night (${W("wan3")}-${L("shang4")}), and being late.`,
    `Вечер и ночь (${W("wan3")}-${L("shang4")}) и опоздание.`),
  add("zuo2", "昨", "time", POS.noun,
    `the day before: only in ${W("zuo2")}-${W("tian1")}, yesterday`,
    `прошлый (о дне): только в ${W("zuo2")}-${W("tian1")} — вчера`,
    "昨", 3,
    `Yesterday (${W("zuo2")}-${W("tian1")}), next to ${W("jin1")}-${W("tian1")} and ${W("ming2")}-${W("tian1")}.`,
    `«Вчера» (${W("zuo2")}-${W("tian1")}) рядом с ${W("jin1")}-${W("tian1")} и ${W("ming2")}-${W("tian1")}.`),
  add("bai3", "百", "numbers-ordinals", POS.num,
    `hundred: ${W("yi1")}-${W("bai3")}, a hundred; ${W("san1")}-${W("bai3")}, three hundred`,
    `сто: ${W("yi1")}-${W("bai3")} — сто; ${W("san1")}-${W("bai3")} — триста`,
    "百", 3,
    `Numbers past ninety-nine.`,
    `Числа больше девяноста девяти.`),
  add("zhong4", "重", "physical-property", POS.adj,
    `heavy: ${W("hen3")} ${W("zhong4")}, very heavy; ${W("zhong4")}-${W("yao4")}, important`,
    `тяжёлый: ${W("hen3")} ${W("zhong4")} — очень тяжёлый; ${W("zhong4")}-${W("yao4")} — важный`,
    "重", 3,
    `Heavy, and important (${W("zhong4")}-${W("yao4")}).`,
    `«Тяжёлый» и «важный» (${W("zhong4")}-${W("yao4")}).`),
  add("jian4", "见", "perception", POS.verb,
    `to see, meet: after a verb, says you caught it (${W("kan4")}-${W("jian4")}, see; ${W("ting1")}-${W("jian4")}, hear); ${W("jian4")}-${W("mian4")}, meet`,
    `видеть, встречать: после глагола говорит, что вы уловили (${W("kan4")}-${W("jian4")} — увидеть; ${W("ting1")}-${W("jian4")} — услышать); ${W("jian4")}-${W("mian4")} — встретиться`,
    "见", 4,
    `Seeing and hearing something (${W("kan4")}-${W("jian4")}, ${W("ting1")}-${W("jian4")}), meeting, and goodbye (${W("zai4")}-${W("jian4")}).`,
    `Увидеть и услышать (${W("kan4")}-${W("jian4")}, ${W("ting1")}-${W("jian4")}), встретиться и «до свидания» (${W("zai4")}-${W("jian4")}).`),
  add("ti2", "题", "abstract-substantives", POS.noun,
    `question, problem, topic: ${W("wen4")}-${W("ti2")}, a question, a problem`,
    `вопрос, задача, тема: ${W("wen4")}-${W("ti2")} — вопрос, проблема`,
    "题，问题", 3,
    `Questions and problems (${W("wen4")}-${W("ti2")}): "no problem" is ${W("mei2")}-${W("you3")} ${W("wen4")}-${W("ti2")}.`,
    `Вопросы и проблемы (${W("wen4")}-${W("ti2")}): «без проблем» — ${W("mei2")}-${W("you3")} ${W("wen4")}-${W("ti2")}.`),
  add("hua4", "话", "speech", POS.noun,
    `words, speech, what is said: ${W("shuo1")} ${W("hua4")}, talk; ${W("dui4")}-${W("hua4")}, a conversation`,
    `слова, речь, сказанное: ${W("shuo1")} ${W("hua4")} — разговаривать; ${W("dui4")}-${W("hua4")} — разговор`,
    "话", 4,
    `Talk (${W("shuo1")} ${W("hua4")}): what is said, as a thing.`,
    `Разговор (${W("shuo1")} ${W("hua4")}): сказанное как вещь.`),
  add("chang2", "长", "size", POS.adj,
    `long: ${W("hen3")} ${W("chang2")}, very long; ${W("chang2")}-${W("de")} ${W("dong1")}-${L("xi1")}, a stick; ${W("chang2")} ${W("shi2")}-${W("jian1")}, a long time`,
    `длинный: ${W("hen3")} ${W("chang2")} — очень длинный; ${W("chang2")}-${W("de")} ${W("dong1")}-${L("xi1")} — палка; ${W("chang2")} ${W("shi2")}-${W("jian1")} — долго`,
    "长", 4,
    `Long things and a long time: before it, long was just ${W("da4")}.`,
    `Длинные вещи и долгое время: раньше «длинный» было просто ${W("da4")}.`),

  // -- senses ------------------------------------------------------------------------
  { op: "sense", id: "zai4", key: "again", hanzi: "再", eng: "again, once more", rus: "снова, ещё раз",
    why: { eng: `Written 再, ${W("zai4")} means once more in ${W("zai4")}-${W("jian4")} (goodbye: see you again); on its own it is be at.`, rus: `Записанное как 再, ${W("zai4")} значит «ещё раз» в ${W("zai4")}-${W("jian4")} (до свидания: увидимся снова); само по себе — «находиться».` },
    compounds: ["zai4 jian4"] },
  { op: "sense", id: "xiao4", key: "school", hanzi: "校", eng: "school", rus: "школа",
    why: { eng: `Written 校, ${W("xiao4")} means school in ${W("xue2")}-${W("xiao4")}; on its own it is laugh.`, rus: `Записанное как 校, ${W("xiao4")} значит «школа» в ${W("xue2")}-${W("xiao4")}; само по себе — «смеяться».` },
    compounds: ["xue2 xiao4"] },
  { op: "sense", id: "shi2", key: "real", hanzi: "实", eng: "real, solid", rus: "настоящий, реальный",
    why: { eng: `Written 实, ${W("shi2")} means real in ${W("shi4")}-${W("shi2")} (fact), ${W("zhen1")}-${W("shi2")} (true) and ${W("xian4")}-${W("shi2")} (reality); on its own it is ten.`, rus: `Записанное как 实, ${W("shi2")} значит «настоящий» в ${W("shi4")}-${W("shi2")} (факт), ${W("zhen1")}-${W("shi2")} (правдивый) и ${W("xian4")}-${W("shi2")} (реальность); само по себе — «десять».` },
    compounds: ["shi4 shi2", "zhen1 shi2", "xian4 shi2"] },
  { op: "sense", id: "xin1", key: "new", hanzi: "新", eng: "new", rus: "новый",
    why: { eng: `Written 新, ${W("xin1")} means new in ${W("xin1")}-${W("nian2")} (New Year); on its own it is heart.`, rus: `Записанное как 新, ${W("xin1")} значит «новый» в ${W("xin1")}-${W("nian2")} (Новый год); само по себе — «сердце».` },
    compounds: ["xin1 nian2"] },
  { op: "sense", id: "hai2", key: "child", hanzi: "孩", eng: "child", rus: "ребёнок",
    why: { eng: `Written 孩, ${W("hai2")} means child in ${W("hai2")}-${L("zi")}; on its own it is still.`, rus: `Записанное как 孩, ${W("hai2")} значит «ребёнок» в ${W("hai2")}-${L("zi")}; само по себе — «ещё».` },
    compounds: ["hai2 zi"] },
  // 事 (matter), 现 (now) and 名 (name) write more compounds now
  { op: "senseCompounds", id: "shi4", key: "matter", add: ["shi4 shi2"] },
  { op: "senseCompounds", id: "xian4", key: "now", add: ["xian4 shi2"] },
  { op: "senseCompounds", id: "ming2", key: "name", add: ["ming2 zi4"] },

  // -- cards -------------------------------------------------------------------------
  card("fan4", "who-does-what/do", `meal, rice; ${W("chi1")} ${W("fan4")}: eat`, `еда, рис; ${W("chi1")} ${W("fan4")} — есть`),
  card("zi4", "who-does-what/do", "written character", "иероглиф"),
  card("shu1", "who-does-what/have", "book", "книга"),
  card("hua4", "who-does-what/not", `words, speech; ${W("shuo1")} ${W("hua4")}: talk`, `слова, речь; ${W("shuo1")} ${W("hua4")} — разговаривать`),
  card("shei2", "questions/what", "who", "кто"),
  card("ti2", "questions/yes-no", `question; ${W("wen4")}-${W("ti2")}: a question, a problem`, `вопрос; ${W("wen4")}-${W("ti2")} — вопрос, проблема`),
  card("xie1", "pointing/plural-pointers", `some; ${W("zhe4")}-${W("xie1")}: these`, `несколько; ${W("zhe4")}-${W("xie1")} — эти`),
  card("xiang3", "pre-verbs/want", "think; would like to", "думать; хотеть"),
  card("yi3", "pre-verbs/can", `${W("ke3")}-${W("yi3")}: can, may`, `${W("ke3")}-${W("yi3")} — можно`),
  card("xiao4", "moving/road", `school (in ${W("xue2")}-${W("xiao4")})`, `школа (в ${W("xue2")}-${W("xiao4")})`, "school"),
  card("zhi3", "how-much/really", "only", "только"),
  card("tong2", "comparing/different", `same; ${W("bu4")}-${W("tong2")}: different`, `одинаковый; ${W("bu4")}-${W("tong2")} — разный`),
  card("zhong4", "comparing/shape-feel", "heavy", "тяжёлый"),
  card("chang2", "comparing/than", "long", "длинный"),
  card("hai2", "also-and-all/also-is", "still, also", "ещё, всё ещё"),
  card("jian4", "direction-and-result/result", `see; ${W("kan4")}-${W("jian4")}: see`, `видеть; ${W("kan4")}-${W("jian4")} — увидеть`),
  card("zuo2", "numbers/days-years", `${W("zuo2")}-${W("tian1")}: yesterday`, `${W("zuo2")}-${W("tian1")} — вчера`),
  card("wan3", "numbers/days-years", `late; ${W("wan3")}-${L("shang4")}: evening`, `поздний; ${W("wan3")}-${L("shang4")} — вечер`),
  card("xin1", "numbers/days-years", `new (in ${W("xin1")}-${W("nian2")}: New Year)`, `новый (в ${W("xin1")}-${W("nian2")} — Новый год)`, "new"),
  card("bai3", "numbers/teens", "hundred", "сто"),
  card("er2", "roles-of-a-word/person", `child, son; ${W("nv3")}-${W("er2")}: daughter`, `ребёнок, сын; ${W("nv3")}-${W("er2")} — дочь`),
  card("zi", "roles-of-a-word/person", `a noun ending: ${W("er2")}-${L("zi")}, son`, `окончание существительного: ${W("er2")}-${L("zi")} — сын`),
  card("hai2", "roles-of-a-word/person", `child (in ${W("hai2")}-${L("zi")})`, `ребёнок (в ${W("hai2")}-${L("zi")})`, "child"),
  card("zai4", "greetings-and-feelings/hello", `again (in ${W("zai4")}-${W("jian4")}: goodbye)`, `снова (в ${W("zai4")}-${W("jian4")} — до свидания)`, "again"),
  card("rang4", "everyday-patterns/have-someone", "let, make", "позволять, заставлять"),

  // -- gùnzi leaves: a stick is a long thing ---------------------------------------------
  { op: "replace", id: "gun4zi", with: `${W("chang2")}-${W("de")} ${W("dong1")}-${L("xi1")}`, hanzi: { "棍子": "长的东西" } },

  // -- sentences that now have the word -----------------------------------------------
  { op: "refs", label: "chī dōng-xi -> chī fàn", pattern: "\\{\\{(w|W)ord:chi1\\}\\} \\{\\{word:dong1\\}\\}-\\{\\{light:xi1\\}\\}", to: "{{$1ord:chi1}} {{word:fan4}}", hanzi: ["吃东西", "吃饭"] },
  { op: "refs", label: "shénme rén -> shéi", pattern: "\\{\\{(w|W)ord:shen2me\\}\\} \\{\\{word:ren2\\}\\}", to: "{{$1ord:shei2}}", hanzi: ["什么人", "谁"] },
  { op: "refs", label: "tóu-shàng-de máo -> tóu-fā", pattern: "\\{\\{(w|W)ord:tou2\\}\\}-\\{\\{word:shang4\\}\\}-\\{\\{word:de\\}\\} \\{\\{word:mao2\\}\\}", to: "{{$1ord:tou2}}-{{word:fa1}}", hanzi: ["头上的毛", "头发"] },

  // -- composites: Mandarin's own word first ----------------------------------------------
  { op: "composite", zh: "吃饭", create: { rank: 5404, phase: 4, py: "chīfàn", en: "eat (a meal)", ru: "есть, кушать", pos: "verb" }, set: { hsd: [`${W("chi1")} ${W("fan4")}`], tts: ["吃饭"], fit: "natural", transparent: true } },
  { op: "compounds" },
  // where Mandarin says the second syllable light
  { op: "refs", label: "míng-zi light", pattern: "\\{\\{(w|W)ord:ming2\\}\\}-\\{\\{word:zi4\\}\\}", to: "{{$1ord:ming2}}-{{light:zi4}}" },
  { op: "refs", label: "wǎn-shang light", pattern: "\\{\\{(w|W)ord:wan3\\}\\}-\\{\\{word:shang4\\}\\}", to: "{{$1ord:wan3}}-{{light:shang4}}" },
  { op: "refs", label: "hái-zi, ér-zi light", pattern: "\\{\\{(w|W)ord:(hai2|er2)\\}\\}-\\{\\{word:zi\\}\\}", to: "{{$1ord:$2}}-{{light:zi}}" },
];
