// Russian text for lesson-16, matching shape.ts's keys. Typed as
// `PartialByKey<LessonShape>`.
// Not translated yet -- every `ru` is the empty-array placeholder.
import type { PartialByKey } from "../../lib/chapter-shape-types.ts";
import type { LessonShape } from "./shape.ts";

const ru: PartialByKey<LessonShape> = {
  title: { ru: [] },
  summary: { ru: [] },
  vocabYi: { ru: [] },
  vocabLiang: { ru: [] },
  vocabEr: { ru: [] },
  vocabHao: { ru: [] },
  vocabSan: { ru: [] },
  vocabSi: { ru: [] },
  vocabWu: { ru: [] },
  vocabLiu: { ru: [] },
  vocabQi: { ru: [] },
  vocabBa: { ru: [] },
  vocabJiu: { ru: [] },
  vocabShi: { ru: [] },
  proseAloud: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleAloud1: { ru: [] },
  exampleAloud2: { ru: [] },
  exampleAloud3: { ru: [] },
  proseCount: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleCount1: { ru: [] },
  exampleCount2: { ru: [] },
  exampleCount3: { ru: [] },
  exampleCount4: { ru: [] },
  exampleCount5: { ru: [] },
  exampleCount6: { ru: [] },
  exampleCount7: { ru: [] },
  exampleCount8: { ru: [] },
  exampleCount9: { ru: [] },
  exampleCount10: { ru: [] },
  exampleCount11: { ru: [] },
  exampleCount12: { ru: [] },
  exampleCount13: { ru: [] },
  exampleCount14: { ru: [] },
  exampleCount15: { ru: [] },
  exampleCount16: { ru: [] },
  proseTeens: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleTeens1: { ru: [] },
  exampleTeens2: { ru: [] },
  exampleTeens3: { ru: [] },
  exampleTeens4: { ru: [] },
  exampleTeens5: { ru: [] },
  exampleTeens6: { ru: [] },
  proseLabel: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleLabel1: { ru: [] },
  exampleLabel2: { ru: [] },
  exampleLabel3: { ru: [] },
  exampleLabel4: { ru: [] },
  infoCounting: {
    title: { ru: [] },
    items: [{ ru: [] }, { ru: [] }, { ru: [] }, { ru: [] }],
  },
  exercise1: { ru: [] },
  exercise2: { ru: [] },
  exercise3: { ru: [] },
  exercise4: { ru: [] },
  exercise5: { ru: [] },
  exercise6: { ru: [] },
  exercise7: { ru: [] },
  exercise8: { ru: [] },
  exercise9: { ru: [] },
  exercise10: { ru: [] },
  exercise11: { ru: [] },
  exercise12: { ru: [] },
  exercise13: { ru: [] },
  answer1: { ru: [] },
  answer2: { ru: [] },
  answer3: { ru: [] },
  answer4: { ru: [] },
  answer5: { ru: [] },
  answer6: { ru: [] },
  answer7: { ru: [] },
  answer8: { ru: [] },
  answer9: { ru: [] },
  answer10: { ru: [] },
  answer11: { ru: [] },
  answer12: { ru: [] },
  answer13: { ru: [] },
};

export default ru;
