// Chinese text for lesson-16, matching shape.ts's keys. Typed as
// `PartialByKey<LessonShape>`.
// Not translated yet -- every `zh` is the empty-array placeholder.
import type { PartialByKey } from "../../lib/chapter-shape-types.ts";
import type { LessonShape } from "./shape.ts";

const zh: PartialByKey<LessonShape> = {
  title: { zh: [] },
  summary: { zh: [] },
  vocabYi: { zh: [] },
  vocabLiang: { zh: [] },
  vocabEr: { zh: [] },
  vocabHao: { zh: [] },
  vocabSan: { zh: [] },
  vocabSi: { zh: [] },
  vocabWu: { zh: [] },
  vocabLiu: { zh: [] },
  vocabQi: { zh: [] },
  vocabBa: { zh: [] },
  vocabJiu: { zh: [] },
  vocabShi: { zh: [] },
  proseAloud: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleAloud1: { zh: [] },
  exampleAloud2: { zh: [] },
  exampleAloud3: { zh: [] },
  exampleAloud4: { zh: [] },
  proseCount: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleCount1: { zh: [] },
  exampleCount2: { zh: [] },
  exampleCount3: { zh: [] },
  exampleCount4: { zh: [] },
  exampleCount5: { zh: [] },
  exampleCount6: { zh: [] },
  exampleCount7: { zh: [] },
  exampleCount8: { zh: [] },
  exampleCount9: { zh: [] },
  exampleCount10: { zh: [] },
  exampleCount11: { zh: [] },
  exampleCount12: { zh: [] },
  exampleCount13: { zh: [] },
  exampleCount14: { zh: [] },
  exampleCount15: { zh: [] },
  exampleCount16: { zh: [] },
  exampleCount17: { zh: [] },
  exampleCount18: { zh: [] },
  exampleCount19: { zh: [] },
  proseTeens: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleTeens1: { zh: [] },
  exampleTeens2: { zh: [] },
  exampleTeens3: { zh: [] },
  exampleTeens4: { zh: [] },
  exampleTeens5: { zh: [] },
  exampleTeens6: { zh: [] },
  proseLabel: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleLabel1: { zh: [] },
  exampleLabel2: { zh: [] },
  exampleLabel3: { zh: [] },
  exampleLabel4: { zh: [] },
  exampleLabel5: { zh: [] },
  infoCounting: {
    title: { zh: [] },
    items: [{ zh: [] }, { zh: [] }, { zh: [] }, { zh: [] }],
  },
  exercise1: { zh: [] },
  exercise2: { zh: [] },
  exercise3: { zh: [] },
  exercise4: { zh: [] },
  exercise5: { zh: [] },
  exercise6: { zh: [] },
  exercise7: { zh: [] },
  exercise8: { zh: [] },
  exercise9: { zh: [] },
  exercise10: { zh: [] },
  exercise11: { zh: [] },
  exercise12: { zh: [] },
  exercise13: { zh: [] },
  answer1: { zh: [] },
  answer2: { zh: [] },
  answer3: { zh: [] },
  answer4: { zh: [] },
  answer5: { zh: [] },
  answer6: { zh: [] },
  answer7: { zh: [] },
  answer8: { zh: [] },
  answer9: { zh: [] },
  answer10: { zh: [] },
  answer11: { zh: [] },
  answer12: { zh: [] },
  answer13: { zh: [] },
};

export default zh;
