// Russian text for lesson-09, matching shape.ts's keys. Typed as
// `PartialByKey<LessonShape>`.
// Not translated yet -- every `ru` is the empty-array placeholder.
import type { PartialByKey } from "../../lib/chapter-shape-types.ts";
import type { LessonShape } from "./shape.ts";

const ru: PartialByKey<LessonShape> = {
  title: { ru: [] },
  summary: { ru: [] },
  vocabWanr: { ru: [] },
  proseWhen: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleWhen1: { ru: [] },
  exampleWhen2: { ru: [] },
  exampleWhen3: { ru: [] },
  vocabWan: { ru: [] },
  proseFinished: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleFinished1: { ru: [] },
  exampleFinished2: { ru: [] },
  exampleFinished3: { ru: [] },
  vocabHou: { ru: [] },
  vocabLiu: { ru: [] },
  proseAfter: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleAfter1: { ru: [] },
  exampleAfter2: { ru: [] },
  exampleAfter3: { ru: [] },
  exampleAfter4: { ru: [] },
  exampleAfter5: { ru: [] },
  exampleAfter6: { ru: [] },
  vocabKaishi: { ru: [] },
  proseStart: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleStart1: { ru: [] },
  exampleStart2: { ru: [] },
  exampleStart3: { ru: [] },
  exampleStart4: { ru: [] },
  exampleStart5: { ru: [] },
  vocabYixia: { ru: [] },
  proseMoment: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleMoment1: { ru: [] },
  exampleMoment2: { ru: [] },
  exampleMoment3: { ru: [] },
  exampleMoment4: { ru: [] },
  vocabYou: { ru: [] },
  proseAgain: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleAgain1: { ru: [] },
  exampleAgain2: { ru: [] },
  exampleAgain3: { ru: [] },
  exampleAgain4: { ru: [] },
  vocabCi: { ru: [] },
  proseTimes: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleTimes1: { ru: [] },
  exampleTimes2: { ru: [] },
  exampleTimes3: { ru: [] },
  exampleTimes4: { ru: [] },
  infoAroundAnAction: {
    title: { ru: [] },
    items: [
      { ru: [] },
      { ru: [] },
      { ru: [] },
      { ru: [] },
      { ru: [] },
      { ru: [] },
      { ru: [] },
    ],
  },
  exercise1: { ru: [] },
  exercise2: { ru: [] },
  exercise3: { ru: [] },
  exercise4: { ru: [] },
  exercise5: { ru: [] },
  exercise6: { ru: [] },
  exercise7: { ru: [] },
  exercise8: { ru: [] },
  exercise9: { ru: [] },
  answer1: { ru: [] },
  answer2: { ru: [] },
  answer3: { ru: [] },
  answer4: { ru: [] },
  answer5: { ru: [] },
  answer6: { ru: [] },
  answer7: { ru: [] },
  answer8: { ru: [] },
  answer9: { ru: [] },
  faqWanOrWanr: { question: { ru: [] }, ru: [] },
  faqWanAndLe: { question: { ru: [] }, ru: [] },
};

export default ru;
