// Chinese text for lesson-09, matching shape.ts's keys. Typed as
// `PartialByKey<LessonShape>`.
// Not translated yet -- every `zh` is the empty-array placeholder.
import type { PartialByKey } from "../../lib/chapter-shape-types.ts";
import type { LessonShape } from "./shape.ts";

const zh: PartialByKey<LessonShape> = {
  title: { zh: [] },
  summary: { zh: [] },
  vocabWan: { zh: [] },
  vocabKaishi: { zh: [] },
  vocabHou: { zh: [] },
  vocabWanr: { zh: [] },
  vocabLiu: { zh: [] },
  vocabYixia: { zh: [] },
  proseWhen: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleWhen1: { zh: [] },
  exampleWhen2: { zh: [] },
  exampleWhen3: { zh: [] },
  proseFinished: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleFinished1: { zh: [] },
  exampleFinished2: { zh: [] },
  exampleFinished3: { zh: [] },
  proseAfter: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleAfter1: { zh: [] },
  exampleAfter2: { zh: [] },
  exampleAfter3: { zh: [] },
  exampleAfter4: { zh: [] },
  proseStart: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleStart1: { zh: [] },
  exampleStart2: { zh: [] },
  exampleStart3: { zh: [] },
  exampleStart4: { zh: [] },
  proseStay: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleStay1: { zh: [] },
  exampleStay2: { zh: [] },
  exampleStay3: { zh: [] },
  proseMoment: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleMoment1: { zh: [] },
  exampleMoment2: { zh: [] },
  exampleMoment3: { zh: [] },
  exampleMoment4: { zh: [] },
  infoAroundAnAction: {
    title: { zh: [] },
    items: [
      { zh: [] },
      { zh: [] },
      { zh: [] },
      { zh: [] },
      { zh: [] },
    ],
  },
  exercise1: { zh: [] },
  exercise2: { zh: [] },
  exercise3: { zh: [] },
  exercise4: { zh: [] },
  exercise5: { zh: [] },
  exercise6: { zh: [] },
  exercise7: { zh: [] },
  answer1: { zh: [] },
  answer2: { zh: [] },
  answer3: { zh: [] },
  answer4: { zh: [] },
  answer5: { zh: [] },
  answer6: { zh: [] },
  answer7: { zh: [] },
};

export default zh;
