// Russian text for comparing, matching shape.ts's keys. Typed as
// `PartialByKey<LessonShape>`.
// Not translated yet -- every `ru` is the empty-array placeholder.
import type { PartialByKey } from "../../../lib/chapter-shape-types.ts";
import type { LessonShape } from "./shape.ts";

const ru: PartialByKey<LessonShape> = {
  title: { ru: [] },
  summary: { ru: [] },
  vocabBi: { ru: [] },
  vocabYing: { ru: [] },
  vocabYuan: { ru: [] },
  vocabGunzi: { ru: [] },
  vocabXian: { ru: [] },
  proseThan: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleThan1: { ru: [] },
  exampleThan5: { ru: [] },
  exampleThan6: { ru: [] },
  exampleThan7: { ru: [] },
  exampleThan9: { ru: [] },
  exampleThan11: { ru: [] },
  exampleThan12: { ru: [] },
  exampleThan13: { ru: [] },
  vocabZui: { ru: [] },
  proseMost: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleMost1: { ru: [] },
  exampleMost2: { ru: [] },
  exampleMost3: { ru: [] },
  exampleMost4: { ru: [] },
  exampleMost5: { ru: [] },
  vocabYiyang: { ru: [] },
  proseSame: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleSame1: { ru: [] },
  exampleSame2: { ru: [] },
  exampleSame3: { ru: [] },
  vocabButong: { ru: [] },
  vocabBiede: { ru: [] },
  proseDifferent: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleDifferent1: { ru: [] },
  exampleDifferent2: { ru: [] },
  exampleDifferent3: { ru: [] },
  exampleDifferent4: { ru: [] },
  exampleDifferent5: { ru: [] },
  exampleDifferent6: { ru: [] },
  vocabZhong: { ru: [] },
  proseKind: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleKind1: { ru: [] },
  exampleKind2: { ru: [] },
  exampleKind3: { ru: [] },
  proseShapeFeel: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleShapeFeel1: { ru: [] },
  exampleShapeFeel2: { ru: [] },
  exampleShapeFeel3: { ru: [] },
  exampleShapeFeel4: { ru: [] },
  exampleShapeFeel5: { ru: [] },
  infoComparing: {
    title: { ru: [] },
    items: [
      { ru: [] },
      { ru: [] },
      { ru: [] },
      { ru: [] },
      { ru: [] },
      { ru: [] },
    ],
  },
  exercise1: { ru: [] },
  exercise2: { ru: [] },
  exercise3: { ru: [] },
  exercise4: { ru: [] },
  exercise5: { ru: [] },
  exercise6: { ru: [] },
  exercise7: { ru: [] },
  exercise8: { ru: [] },
  exercise9: { ru: [] },
  exercise10: { ru: [] },
  exercise11: { ru: [] },
  answer1: { ru: [] },
  answer2: { ru: [] },
  answer3: { ru: [] },
  answer4: { ru: [] },
  answer5: { ru: [] },
  answer6: { ru: [] },
  answer7: { ru: [] },
  answer8: { ru: [] },
  answer9: { ru: [] },
  answer10: { ru: [] },
  answer11: { ru: [] },
  faqMuchBigger: { question: { ru: [] }, ru: [] },
  faqNotAsBig: { question: { ru: [] }, ru: [] },
  faqButongOrBiede: { question: { ru: [] }, ru: [] },
};

export default ru;
