// Russian text for roles-of-a-word, matching shape.ts's keys. Typed as
// `PartialByKey<LessonShape>`.
// Not translated yet -- every `ru` is the empty-array placeholder.
import type { PartialByKey } from "../../../lib/chapter-shape-types.ts";
import type { LessonShape } from "./shape.ts";

const ru: PartialByKey<LessonShape> = {
  title: { ru: [] },
  summary: { ru: [] },
  vocabCi: { ru: [] },
  proseThing: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleThing1: { ru: [] },
  exampleThing2: { ru: [] },
  exampleThing3: { ru: [] },
  exampleThing4: { ru: [] },
  exampleThing5: { ru: [] },
  exampleThing6: { ru: [] },
  exampleThing7: { ru: [] },
  prosePerson: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  examplePerson1: { ru: [] },
  examplePerson2: { ru: [] },
  examplePerson3: { ru: [] },
  proseHow: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleHow1: { ru: [] },
  exampleHow2: { ru: [] },
  exampleHow3: { ru: [] },
  exampleHow4: { ru: [] },
  vocabFangfa: { ru: [] },
  proseName: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleName1: { ru: [] },
  exampleName2: { ru: [] },
  exampleName3: { ru: [] },
  exampleName4: { ru: [] },
  exampleName5: { ru: [] },
  exampleName12: { ru: [] },
  exampleName13: { ru: [] },
  vocabBizi: { ru: [] },
  vocabPifu: { ru: [] },
  vocabMao: { ru: [] },
  proseParts: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleName6: { ru: [] },
  exampleName7: { ru: [] },
  exampleName8: { ru: [] },
  exampleName9: { ru: [] },
  exampleName10: { ru: [] },
  exampleHair1: { ru: [] },
  exampleHair2: { ru: [] },
  exampleHair3: { ru: [] },
  infoJobsOfDe: {
    title: { ru: [] },
    items: [
      { ru: [] },
      { ru: [] },
      { ru: [] },
      { ru: [] },
      { ru: [] },
    ],
  },
  exercise1: { ru: [] },
  exercise2: { ru: [] },
  exercise3: { ru: [] },
  exercise4: { ru: [] },
  exercise5: { ru: [] },
  exercise6: { ru: [] },
  exercise7: { ru: [] },
  exercise8: { ru: [] },
  answer1: { ru: [] },
  answer2: { ru: [] },
  answer3: { ru: [] },
  answer4: { ru: [] },
  answer5: { ru: [] },
  answer6: { ru: [] },
  answer7: { ru: [] },
  answer8: { ru: [] },
  faqWhichDe: { question: { ru: [] }, ru: [] },
  faqDeSameWord: { question: { ru: [] }, ru: [] },
};

export default ru;
