// Russian text for lesson-12, matching shape.ts's keys. Typed as
// `PartialByKey<LessonShape>`.
// Not translated yet -- every `ru` is the empty-array placeholder.
import type { PartialByKey } from "../../lib/chapter-shape-types.ts";
import type { LessonShape } from "./shape.ts";

const ru: PartialByKey<LessonShape> = {
  title: { ru: [] },
  summary: { ru: [] },
  vocabZhen: { ru: [] },
  vocabRe: { ru: [] },
  vocabLeng: { ru: [] },
  vocabTian: { ru: [] },
  vocabQiguai: { ru: [] },
  vocabShenti: { ru: [] },
  vocabJiazhi: { ru: [] },
  proseVery: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleVery1: { ru: [] },
  exampleVery2: { ru: [] },
  exampleVery3: { ru: [] },
  exampleVery4: { ru: [] },
  exampleVery5: { ru: [] },
  exampleVery6: { ru: [] },
  exampleVery7: { ru: [] },
  exampleVery8: { ru: [] },
  proseReally: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleReally1: { ru: [] },
  exampleReally2: { ru: [] },
  exampleReally3: { ru: [] },
  proseNot: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleNot1: { ru: [] },
  exampleNot2: { ru: [] },
  exampleNot3: { ru: [] },
  vocabXin: { ru: [] },
  proseAsk: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleAsk1: { ru: [] },
  exampleAsk2: { ru: [] },
  exampleAsk3: { ru: [] },
  exampleAsk4: { ru: [] },
  exampleAsk5: { ru: [] },
  exampleAsk6: { ru: [] },
  exampleAsk7: { ru: [] },
  infoHowMuch: {
    title: { ru: [] },
    items: [
      { ru: [] },
      { ru: [] },
      { ru: [] },
      { ru: [] },
      { ru: [] },
    ],
  },
  exercise1: { ru: [] },
  exercise2: { ru: [] },
  exercise3: { ru: [] },
  exercise4: { ru: [] },
  exercise5: { ru: [] },
  exercise6: { ru: [] },
  exercise7: { ru: [] },
  exercise8: { ru: [] },
  answer1: { ru: [] },
  answer2: { ru: [] },
  answer3: { ru: [] },
  answer4: { ru: [] },
  answer5: { ru: [] },
  answer6: { ru: [] },
  answer7: { ru: [] },
  answer8: { ru: [] },
};

export default ru;
