// See src/lib/chapter-content.js for the schema this is transformed by.
// zh/ru intentionally blank -- carried over English-only from lesson-03.yaml.
// A '' entry inside a sentence array is a deliberate paragraph break (joins
// to '\n\n', which markdown reads as a new <p>), not a missing sentence.
import type { Entry } from '../../lib/chapter-entry-types.ts';

export const meta = {
  id: 'lesson-03',
  type: 'lesson',
  lessonNumber: 3,
  order: 3,
};

const content: Entry[] = [
  {
    type: 'title',
    en: ['Sentences'],
    zh: [],
    ru: ['Предложения'],
  },
  {
    type: 'summary',
    en: [
      'Hao-shuo-de sentences follow a fixed Subject-Verb-Object order with no case marking; the copula {{word:shi4}} links a subject to a classifying noun, and quantity (like {{word:duo1}}) is expressed by a separate word, never by the noun itself.',
    ],
    zh: [],
    ru: [
      'Предложения Hao-shuo-de строятся по неизменному порядку Подлежащее-Глагол-Дополнение без падежных окончаний; связка {{word:shi4}} соединяет подлежащее с классифицирующим существительным, а количество (например {{word:duo1}}) выражается отдельным словом, а не самим существительным.',
    ],
  },
  {
    type: 'prose',
    en: [
      'Hao-shuo-de has no case endings — no special ending on a noun to mark "the one doing this" versus "the one this is being done to."',
      'All of that information lives in exactly one place: word order.',
      'Every Hao-shuo-de sentence follows the same fixed shape:',
      '',
      'Subject + Verb + Object',
      '',
      "Swap the order and you don't get emphasis or a different flavor of the same sentence — you get a different sentence, possibly a wrong one.",
      "Position isn't a stylistic choice; it's the grammar.",
      '',
      'The simplest sentence you can build has no object at all — just a subject, the verb <audio-example zh="是">{{word:shi4}}</audio-example> ("is/am/are"), and a noun that describes or classifies it:',
      '',
      'Subject + <audio-example zh="是">{{word:shi4}}</audio-example> + Noun',
      '',
      'This "verb" never changes shape.',
      'Whoever is speaking, whatever is being described, <audio-example zh="是">{{word:shi4}}</audio-example> stays <audio-example zh="是">{{word:shi4}}</audio-example>.',
    ],
    zh: [],
    ru: [
      'В Hǎo-shuō-de нет падежных окончаний — никакого специального окончания на существительном, которое бы отмечало «тот, кто делает это» в отличие от «тот, с кем это делают».',
      'Вся эта информация живёт ровно в одном месте: в порядке слов.',
      'Каждое предложение Hǎo-shuō-de следует одной и той же неизменной форме:',
      '',
      'Подлежащее + Глагол + Дополнение',
      '',
      'Поменяйте порядок — и вы не получите другой оттенок того же предложения, вы получите другое предложение, возможно, неверное.',
      'Порядок слов — это не стилистический выбор, это грамматика.',
      '',
      'Самое простое предложение, которое можно построить, вообще обходится без дополнения — только подлежащее, глагол <audio-example zh="是">{{word:shi4}}</audio-example> («являться/быть») и существительное, которое описывает или классифицирует подлежащее:',
      '',
      'Подлежащее + <audio-example zh="是">{{word:shi4}}</audio-example> + Именное сказуемое',
      '',
      'Этот «глагол» никогда не меняет форму.',
      'Кто бы ни говорил, о ком бы ни шла речь, <audio-example zh="是">{{word:shi4}}</audio-example> остаётся <audio-example zh="是">{{word:shi4}}</audio-example>.',
    ],
    tldr: {
      en: ['Sentences follow a fixed Subject-Verb-Object order; the simplest sentence uses {{word:shi4}} to link a subject to a classifying noun.'],
      zh: [],
      ru: ['Предложения строятся в неизменном порядке Подлежащее-Глагол-Дополнение; самое простое предложение использует {{word:shi4}}, чтобы связать подлежащее с классифицирующим существительным.'],
    },
    necessity: {
      en: ['Establishes word order as the only signal for grammatical role, since Hao-shuo-de has no case endings to mark it instead.'],
      zh: [],
      ru: ['Устанавливает порядок слов как единственный сигнал грамматической роли, поскольку в Hao-shuo-de нет падежных окончаний, которые могли бы её отметить.'],
    },
  },
  {
    type: 'example',
    pinyin: '{{Word:zhe4}}-ge {{word:shi4}} {{word:ren2}}.',
    ttsText: '这个是人。',
    en: ['This is a person.'],
    zh: [],
    ru: ['Это человек.'],
  },
  {
    type: 'example',
    pinyin: '{{Word:zhe4}}-ge {{word:shi4}} {{word:shui3guo3}}.',
    ttsText: '这个是水果。',
    en: ['This is a fruit.'],
    zh: [],
    ru: ['Это фрукт.'],
  },
  {
    type: 'example',
    pinyin: '{{Word:yi1}}-ge {{word:xie3}}-{{word:de}} {{word:dong1xi}} {{word:shi4}} {{word:dong1xi}}.',
    ttsText: '一个写的东西是东西。',
    en: ['A written thing (book/document) is a thing.'],
    zh: [],
    ru: ['Написанная вещь (книга/документ) является вещью.'],
  },
  {
    type: 'example',
    pinyin: '{{Word:ren2}} {{word:shi4}} {{word:nv3ren2}}.',
    ttsText: '人是女人。',
    en: ['The person is a woman.'],
    zh: [],
    ru: ['Человек — женщина.'],
  },
  {
    type: 'example',
    pinyin: '{{Word:dong4wu4}} {{word:shi4}} {{word:dong1xi}}.',
    ttsText: '动物是东西。',
    en: ['Animals are things.'],
    zh: [],
    ru: ['Животные — это вещи.'],
  },
  {
    type: 'example',
    pinyin: '{{Word:nv3ren2}} {{word:shi4}} {{word:ren2}}.',
    ttsText: '女人是人。',
    en: ['Women are people.'],
    zh: [],
    ru: ['Женщины — это люди.'],
  },
  {
    type: 'prose',
    en: [
      'Look closely at two of the examples above: <audio-example zh="人是女人">{{Word:ren2}} {{word:shi4}} {{word:nv3ren2}}</audio-example> ("the person is a woman") and <audio-example zh="女人是人">{{Word:nv3ren2}} {{word:shi4}} {{word:ren2}}</audio-example> ("women are people").',
      'Same three words, same pattern, opposite scope — one is about a single, specific person; the other is a general statement about the whole category.',
      "Nothing in the sentence marks the difference; nothing needs to.",
      'Hao-shuo-de nouns already carry no number and no article — recall Lesson 2, context decides how many.',
      'The same discipline applies here: context decides whether you mean one particular thing or the whole class of things.',
      "The words don't change; only what you already know about the situation does.",
    ],
    zh: [],
    ru: [
      'Присмотритесь к двум примерам выше: <audio-example zh="人是女人">{{Word:ren2}} {{word:shi4}} {{word:nv3ren2}}</audio-example> («человек — женщина») и <audio-example zh="女人是人">{{Word:nv3ren2}} {{word:shi4}} {{word:ren2}}</audio-example> («женщины — это люди»).',
      'Те же три слова, тот же порядок, но противоположный охват — одно предложение о конкретном, отдельном человеке; другое — общее утверждение о целой категории.',
      'Ничто в самом предложении не отмечает эту разницу; в этом и нет нужды.',
      'Существительные Hǎo-shuō-de и так не несут ни числа, ни артикля — вспомните Урок 2: количество определяет контекст.',
      'Здесь действует та же дисциплина: контекст решает, идёт ли речь об одной конкретной вещи или о целом классе вещей.',
      'Слова не меняются — меняется только то, что вы уже знаете о ситуации.',
    ],
    tldr: {
      en: ['The same words can express a claim about one specific thing or about a whole category — context decides which, not the words.'],
      zh: [],
      ru: ['Одни и те же слова могут выражать утверждение об одном конкретном предмете или обо всей категории — какой смысл имеется в виду, решает контекст, а не сами слова.'],
    },
    necessity: {
      en: ["Shows that the number/specificity ambiguity already established for nouns in Lesson 2 carries through into full sentences too."],
      zh: [],
      ru: ['Показывает, что неоднозначность числа/конкретности, уже установленная для существительных в Уроке 2, распространяется и на целые предложения.'],
    },
  },
  {
    type: 'prose',
    en: [
      "And when you do need to make quantity explicit, the job still doesn't fall on the noun — it falls on a separate word in the sentence.",
      '<audio-example zh="这多的东西是写的东西">{{Word:zhe4}} {{word:duo1}}-{{word:de}} {{word:dong1xi}} {{word:shi4}} {{word:xie3}}-{{word:de}} {{word:dong1xi}}.</audio-example> ("These [many] things are written things," i.e. "These are the books") uses <audio-example zh="多">{{word:duo1}}</audio-example> ("many"), bound with `-{{word:de}}` the same way an adjective would be.',
      "Notice what's missing: <audio-example zh=\"个\">-ge</audio-example>.",
      "Its whole job, from Lesson 2, is to individuate one countable unit — <audio-example zh=\"这个\">{{word:zhe4}}-ge</audio-example> points at exactly one thing.",
      "<audio-example zh=\"多\">{{word:duo1}}</audio-example> isn't pointing at one of anything; it names a bulk quantity instead, so there's nothing left for <audio-example zh=\"个\">-ge</audio-example> to individuate, and it simply drops out.",
      "Number, in other words, is never a property the noun itself carries — it's a decision made elsewhere in the sentence, one word at a time, depending on what job that word is doing.",
    ],
    zh: [],
    ru: [
      'А когда количество всё же нужно сделать явным, эта работа по-прежнему не ложится на существительное — она ложится на отдельное слово в предложении.',
      '<audio-example zh="这多的东西是写的东西">{{Word:zhe4}} {{word:duo1}}-{{word:de}} {{word:dong1xi}} {{word:shi4}} {{word:xie3}}-{{word:de}} {{word:dong1xi}}.</audio-example> («Эти [многие] вещи являются написанными вещами», то есть «Это книги») использует <audio-example zh="多">{{word:duo1}}</audio-example> («много»), присоединённое через `-{{word:de}}` точно так же, как присоединяется прилагательное.',
      'Обратите внимание, чего здесь не хватает: <audio-example zh="个">-ge</audio-example>.',
      'Его единственная задача, как мы помним из Урока 2, — выделить одну исчисляемую единицу: <audio-example zh="这个">{{word:zhe4}}-ge</audio-example> указывает ровно на одну вещь.',
      '<audio-example zh="多">{{word:duo1}}</audio-example> не указывает ни на одну конкретную вещь — оно называет объёмное количество, и выделять здесь попросту нечего, поэтому <audio-example zh="个">-ge</audio-example> исчезает сам собой.',
      'Число, другими словами, никогда не является свойством самого существительного — это решение, которое принимается в другом месте предложения, слово за словом, в зависимости от того, какую работу это слово выполняет.',
    ],
    tldr: {
      en: ['To make quantity explicit, add a separate word like {{word:duo1}} — and once {{word:duo1}} names a bulk amount, the individuating measure word -ge drops out.'],
      zh: [],
      ru: ['Чтобы явно указать количество, добавляется отдельное слово вроде {{word:duo1}} — а когда {{word:duo1}} называет объёмное количество, выделяющее счётное слово -ge исчезает.'],
    },
    necessity: {
      en: ['Extends Lesson 2\'s {{word:ge4}} rule: -ge only individuates single countable units, so it has nothing to do once {{word:duo1}} names a bulk amount instead.'],
      zh: [],
      ru: ['Расширяет правило {{word:ge4}} из Урока 2: -ge выделяет только одну исчисляемую единицу, поэтому ему нечего делать, когда {{word:duo1}} обозначает объёмное количество.'],
    },
  },
  {
    type: 'exercise',
    en: ['This is a document.'],
    zh: [],
    ru: ['Это документ.'],
  },
  {
    type: 'exercise',
    en: ['A woman is a human.'],
    zh: [],
    ru: ['Женщина — человек.'],
  },
  {
    type: 'exercise',
    en: ['Animals are beings.'],
    zh: [],
    ru: ['Животные — существа.'],
  },
  {
    type: 'answer',
    en: ['{{Word:zhe4}}-ge {{word:shi4}} {{word:xie3}}-{{word:de}} {{word:dong1xi}}.'],
    zh: [],
    ru: ['{{Word:zhe4}}-ge {{word:shi4}} {{word:xie3}}-{{word:de}} {{word:dong1xi}}.'],
    ttsText: '这个是写的东西。',
  },
  {
    type: 'answer',
    en: ['{{Word:nv3ren2}} {{word:shi4}} {{word:ren2}}.'],
    zh: [],
    ru: ['{{Word:nv3ren2}} {{word:shi4}} {{word:ren2}}.'],
    ttsText: '女人是人。',
  },
  {
    type: 'answer',
    en: ['{{Word:dong4wu4}} {{word:shi4}} {{word:dong1xi}}.'],
    zh: [],
    ru: ['{{Word:dong4wu4}} {{word:shi4}} {{word:dong1xi}}.'],
    ttsText: '动物是东西。',
  },
];

export default content;
