// Chinese text for lesson-03, matching shape.ts's keys. Typed as
// `PartialByKey<LessonShape>`.
// Not translated yet -- every `zh` is the empty-array placeholder.
import type { PartialByKey } from "../../lib/chapter-shape-types.ts";
import type { LessonShape } from "./shape.ts";

const zh: PartialByKey<LessonShape> = {
  title: { zh: [] },
  summary: { zh: [] },
  vocabHen: { zh: [] },
  vocabDe: { zh: [] },
  vocabDuo: { zh: [] },
  vocabShao: { zh: [] },
  vocabHao: { zh: [] },
  vocabDa: { zh: [] },
  vocabXiao: { zh: [] },
  vocabShui: { zh: [] },
  vocabDifang: { zh: [] },
  vocabFumu: { zh: [] },
  proseLike: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleLike1: { zh: [] },
  exampleLike2: { zh: [] },
  exampleLike3: { zh: [] },
  exampleLike4: { zh: [] },
  exampleLike5: { zh: [] },
  proseBefore: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleBefore1: { zh: [] },
  exampleBefore2: { zh: [] },
  exampleBefore3: { zh: [] },
  exampleBefore4: { zh: [] },
  exampleBefore5: { zh: [] },
  proseMany: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleMany1: { zh: [] },
  exampleMany2: { zh: [] },
  exampleMany3: { zh: [] },
  exampleMany4: { zh: [] },
  exampleMany5: { zh: [] },
  exampleMany6: { zh: [] },
  infoDescribing: {
    title: { zh: [] },
    items: [{ zh: [] }, { zh: [] }, { zh: [] }, { zh: [] }],
  },
  exercise1: { zh: [] },
  exercise2: { zh: [] },
  exercise3: { zh: [] },
  exercise4: { zh: [] },
  exercise5: { zh: [] },
  exercise6: { zh: [] },
  exercise7: { zh: [] },
  exercise8: { zh: [] },
  answer1: { zh: [] },
  answer2: { zh: [] },
  answer3: { zh: [] },
  answer4: { zh: [] },
  answer5: { zh: [] },
  answer6: { zh: [] },
  answer7: { zh: [] },
  answer8: { zh: [] },
};

export default zh;
