// Russian text for lesson-21, matching shape.ts's keys. Typed as
// `PartialByKey<LessonShape>`.
// Not translated yet -- every `ru` is the empty-array placeholder.
import type { PartialByKey } from "../../lib/chapter-shape-types.ts";
import type { LessonShape } from "./shape.ts";

const ru: PartialByKey<LessonShape> = {
  title: { ru: [] },
  summary: { ru: [] },
  vocabJuede: { ru: [] },
  vocabPa: { ru: [] },
  vocabJiao: { ru: [] },
  vocabShengyin: { ru: [] },
  vocabChongzi: { ru: [] },
  vocabXing: { ru: [] },
  proseHello: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleHello1: { ru: [] },
  exampleHello2: { ru: [] },
  exampleHello3: { ru: [] },
  exampleHello4: { ru: [] },
  proseName: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleName1: { ru: [] },
  exampleName2: { ru: [] },
  exampleName3: { ru: [] },
  proseOrder: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleOrder1: { ru: [] },
  exampleOrder2: { ru: [] },
  exampleOrder3: { ru: [] },
  exampleOrder4: { ru: [] },
  proseFeel: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleFeel1: { ru: [] },
  exampleFeel2: { ru: [] },
  exampleFeel3: { ru: [] },
  exampleFeel4: { ru: [] },
  exampleFeel5: { ru: [] },
  exampleFeel6: { ru: [] },
  exampleFeel7: { ru: [] },
  proseHear: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleHear1: { ru: [] },
  exampleHear2: { ru: [] },
  exampleHear3: { ru: [] },
  exampleHear4: { ru: [] },
  infoGreetingsAndFeelings: {
    title: { ru: [] },
    items: [
      { ru: [] },
      { ru: [] },
      { ru: [] },
      { ru: [] },
      { ru: [] },
    ],
  },
  exercise1: { ru: [] },
  exercise2: { ru: [] },
  exercise3: { ru: [] },
  exercise4: { ru: [] },
  exercise5: { ru: [] },
  exercise6: { ru: [] },
  exercise7: { ru: [] },
  exercise8: { ru: [] },
  answer1: { ru: [] },
  answer2: { ru: [] },
  answer3: { ru: [] },
  answer4: { ru: [] },
  answer5: { ru: [] },
  answer6: { ru: [] },
  answer7: { ru: [] },
  answer8: { ru: [] },
};

export default ru;
