// Chinese text for lesson-21, matching shape.ts's keys. Typed as
// `PartialByKey<LessonShape>`.
// Not translated yet -- every `zh` is the empty-array placeholder.
import type { PartialByKey } from "../../lib/chapter-shape-types.ts";
import type { LessonShape } from "./shape.ts";

const zh: PartialByKey<LessonShape> = {
  title: { zh: [] },
  summary: { zh: [] },
  proseHello: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleHello1: { zh: [] },
  exampleHello2: { zh: [] },
  exampleHello3: { zh: [] },
  exampleHello4: { zh: [] },
  exampleHello5: { zh: [] },
  vocabJiao: { zh: [] },
  proseName: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleName1: { zh: [] },
  exampleName2: { zh: [] },
  exampleName3: { zh: [] },
  exampleName4: { zh: [] },
  vocabPa: { zh: [] },
  proseOrder: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleOrder1: { zh: [] },
  exampleOrder2: { zh: [] },
  exampleOrder3: { zh: [] },
  exampleOrder4: { zh: [] },
  exampleOrder5: { zh: [] },
  exampleOrder6: { zh: [] },
  exampleOrder7: { zh: [] },
  exampleOrder8: { zh: [] },
  exampleOrder9: { zh: [] },
  exampleOrder10: { zh: [] },
  vocabJuede: { zh: [] },
  vocabChongzi: { zh: [] },
  vocabXing: { zh: [] },
  proseFeel: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleFeel1: { zh: [] },
  exampleFeel2: { zh: [] },
  exampleFeel3: { zh: [] },
  exampleFeel4: { zh: [] },
  exampleFeel5: { zh: [] },
  exampleFeel6: { zh: [] },
  exampleFeel7: { zh: [] },
  exampleFeel8: { zh: [] },
  exampleFeel9: { zh: [] },
  exampleFeel10: { zh: [] },
  exampleFeel11: { zh: [] },
  exampleFeel12: { zh: [] },
  vocabShengyin: { zh: [] },
  proseHear: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleHear1: { zh: [] },
  exampleHear2: { zh: [] },
  exampleHear3: { zh: [] },
  exampleHear4: { zh: [] },
  exampleHear5: { zh: [] },
  exampleHear6: { zh: [] },
  infoGreetingsAndFeelings: {
    title: { zh: [] },
    items: [
      { zh: [] },
      { zh: [] },
      { zh: [] },
      { zh: [] },
      { zh: [] },
    ],
  },
  exercise1: { zh: [] },
  exercise2: { zh: [] },
  exercise3: { zh: [] },
  exercise4: { zh: [] },
  exercise5: { zh: [] },
  exercise6: { zh: [] },
  exercise7: { zh: [] },
  exercise8: { zh: [] },
  answer1: { zh: [] },
  answer2: { zh: [] },
  answer3: { zh: [] },
  answer4: { zh: [] },
  answer5: { zh: [] },
  answer6: { zh: [] },
  answer7: { zh: [] },
  answer8: { zh: [] },
};

export default zh;
