// Claude's proposals for review batch 6 (composite ranks 501-600), checked by hand:
// zh -> { hsd: forms (refs), tts: their hanzi, literal, fit?, transparent?, why }.
// Entries not listed are proposed as they are. Shown at /__review/?batch=6.
const W = (id) => `{{word:${id}}}`;
const L = (id) => `{{light:${id}}}`;
const PLACE = `${W("di4")}-${L("fang1")}`;
const THING = `${W("dong1")}-${L("xi1")}`;
const KID = `${W("hai2")}-${L("zi")}`;

export default {
  "刚才": {
    hsd: [`${W("bu4")} ${W("yuan3")}-${W("de")} ${W("yi3")}-${W("qian2")}`],
    tts: ["不远的以前"],
    literal: "the not-far past",
    why: "Just now is the past that isn't far: bù yuǎn-de yǐ-qián, instead of a time near xiàn-zài.",
  },
  "别": {
    hsd: [W("bie2")],
    tts: ["别"],
    fit: "word",
    why: "bié is a core word and says don't before a verb; bú-yào is the same thing, so one form is enough.",
  },
  "午饭": {
    hsd: [`${W("shi2")}-${W("er4")}-${W("dian3")}-${W("chi1")}-${W("de")} ${W("fan4")}`],
    tts: ["十二点吃的饭"],
    literal: "the meal eaten at twelve",
    why: "fàn is the meal now (D61), so it replaces dōng-xi; the description up to -de is one chain.",
  },
  "早饭": {
    hsd: [`${W("ri4")}-${W("qi3")}-${W("lai2")}-${W("chi1")}-${W("de")} ${W("fan4")}`],
    tts: ["日起来吃的饭"],
    literal: "the meal eaten when the sun comes up",
    why: "The sun coming up is the morning; fàn is the meal, and the chain is joined.",
  },
  "晚饭": {
    hsd: [`${W("wan3")}-${W("fan4")}`],
    tts: ["晚饭"],
    literal: "late meal",
    fit: "natural",
    transparent: true,
    why: "wǎn-fàn is Mandarin's own word and says itself; the yuè-de shí-jiān description isn't needed.",
  },
  "厕所": {
    hsd: [`${W("shen1ti3")} ${W("bu4")}-${W("yao4")}-${W("de")} ${THING} ${W("chu1")}-${W("qu4")}-${W("de")} ${PLACE}`],
    tts: ["身体不要的东西出去的地方"],
    literal: "the place where what the body doesn't want goes out",
    fit: "plain",
    why: "The old form (water, hand, place) read like a sink; this one says what the place is for, kindly.",
  },
  "卫生间": {
    hsd: [`${W("wei4")}-${W("sheng1")}-${W("jian1")}`],
    tts: ["卫生间"],
    fit: "natural",
    transparent: true,
    why: "wèi-shēng-jiān is the real word (wèi reads 卫 in it); the second description was wrong and isn't needed.",
  },
  "司机": {
    hsd: [`${W("kai1")}-${W("che1")}-${W("de")} ${W("ren2")}`],
    tts: ["开车的人"],
    literal: "a person who drives",
    why: "A driver is the person who drives: kāi-chē-de rén, built on 开车 (rank 521) instead of a tool description.",
  },
  "周末": {
    hsd: [`${W("qi1")}-${W("tian1")}-${W("de")} ${W("zui4")}-${W("hou4")} ${W("liang3")}-${W("tian1")}`],
    tts: ["七天的最后两天"],
    literal: "the last two of seven days",
    why: "Days are tiān (san1 tian1); rì is the sun, so a week is seven tiān.",
  },
  "哥哥": {
    hsd: [`${W("jia1")}-${W("li3")} ${W("bi3")}-${W("wo3")}-${W("da4")}-${W("de")} ${W("nan2")}-${W("ren2")}`],
    tts: ["家里比我大的男人"],
    literal: "the man in the family who is older than me",
    why: "Only the joining: the part before -de is one chain, bǐ-wǒ-dà-de.",
  },
  "姐姐": {
    hsd: [`${W("jia1")}-${W("li3")} ${W("bi3")}-${W("wo3")}-${W("da4")}-${W("de")} ${W("nv3")}-${W("ren2")}`],
    tts: ["家里比我大的女人"],
    literal: "the woman in the family who is older than me",
    why: "As for 哥哥: only the joining.",
  },
  "妹妹": {
    hsd: [`${W("jia1")}-${W("li3")} ${W("bi3")}-${W("wo3")}-${W("xiao3")}-${W("de")} ${W("nv3")}-${W("ren2")}`],
    tts: ["家里比我小的女人"],
    literal: "the woman in the family who is younger than me",
    why: "As for 哥哥: only the joining.",
  },
  "奶奶": {
    hsd: [`${W("ba4ba")}-${W("de")} ${W("ma1ma")}`],
    tts: ["爸爸的妈妈"],
    literal: "dad's mom",
    why: "奶奶 is the father's mother in Mandarin itself: bàba-de māma says it in two core words.",
  },
  "爷爷": {
    hsd: [`${W("ba4ba")}-${W("de")} ${W("ba4ba")}`],
    tts: ["爸爸的爸爸"],
    literal: "dad's dad",
    why: "爷爷 is the father's father: bàba-de bàba.",
  },
  "墙": {
    hsd: [`${W("fang2")}-${W("jian1")}-${W("de")} ${W("ying4")}-${W("de")} ${W("bian1")}`],
    tts: ["房间的硬的边"],
    literal: "the hard side of a room",
    why: "jiā-de biān could be a fence or a street side; a room's hard side is a wall.",
  },
  "夏天": {
    hsd: [`${W("nian2")}-${W("li3")} ${W("zui4")} ${W("re4")}-${W("de")} ${W("shi2")}-${W("jian1")}`],
    tts: ["年里最热的时间"],
    literal: "the hottest time of the year",
    why: "The year is nián, not twelve counted months; the rest is as it was.",
  },
  "大人": {
    hsd: [`${W("da4")}-${W("ren2")}`],
    tts: ["大人"],
    literal: "big person",
    transparent: true,
    why: "Only the joining: dà-rén is one word, like lǎo-rén.",
  },
  "好多": {
    hsd: [`${W("hao3")}-${W("duo1")}`],
    tts: ["好多"],
    literal: "good-many",
    transparent: true,
    why: "Only the joining: hǎo-duō is one word.",
  },
  "小孩儿": {
    hsd: [`${W("xiao3")}-${KID}`],
    tts: ["小孩子"],
    literal: "little child",
    fit: "natural",
    transparent: true,
    why: "hái-zi (child) is a core compound, so xiǎo-hái-zi is Mandarin's own word.",
  },
  "女孩儿": {
    hsd: [`${W("nv3")}-${KID}`],
    tts: ["女孩子"],
    literal: "girl child",
    fit: "natural",
    transparent: true,
    why: "nǚ-hái-zi is 女孩子, the everyday word for girl.",
  },
  "男孩儿": {
    hsd: [`${W("nan2")}-${KID}`],
    tts: ["男孩子"],
    literal: "boy child",
    fit: "natural",
    transparent: true,
    why: "nán-hái-zi is 男孩子, the everyday word for boy (nán is already a sense of the dictionary).",
  },
  "小朋友": {
    hsd: [`${W("he2")} ${W("wo3")} ${W("yi1")}-${W("qi3")} ${W("wan2r")}-${W("de")} ${W("xiao3")}-${KID}`],
    tts: ["和我一起玩儿的小孩子"],
    literal: "a little child who plays with me",
    fit: "plain",
    why: "The same xiǎo-de rén as 小孩儿 would clash; a friend is one who plays with you.",
  },
  "好玩儿": {
    hsd: [`${W("hao3")}-${W("wan2r")}`],
    tts: ["好玩儿"],
    literal: "good to play",
    transparent: true,
    why: "Only the joining: hǎo-wánr is one word, like hǎo-kàn.",
  },
  "饮料": {
    hsd: [`${W("he1")}-${W("de")} ${THING}`],
    tts: ["喝的东西"],
    literal: "a thing to drink",
    why: "chī-de shuǐ said eat-water; hē-de dōng-xi is the drinkable counterpart of chī-de.",
  },
  "渴": {
    hsd: [`${W("yao4")} ${W("he1")} ${W("shui3")}`],
    tts: ["要喝水"],
    literal: "want to drink water",
    why: "The old form said chī shuǐ (eat water); you drink: hē.",
  },
  "苹果": {
    hsd: [`${W("yuan2")}-${W("de")} ${W("hong2")}-${W("se4")}-${W("de")} ${W("shui3")}-${W("guo3")}`],
    tts: ["圆的红色的水果"],
    literal: "a round red fruit",
    why: "shuǐ-guǒ is in the core, so an apple is a round red fruit instead of 'a plant's born thing'.",
  },
  "米饭": {
    hsd: [`${W("bai2")}-${W("se4")}-${W("de")} ${W("fan4")}`],
    tts: ["白色的饭"],
    literal: "white fàn",
    why: "fàn is cooked rice and the meal at once; white fàn is the plain Mandarin way to say rice.",
  },
  "看病": {
    hsd: [`${W("qu4")} ${W("zhao3")} ${W("ren2")} ${W("kan4")} ${W("shen1ti3")}`],
    tts: ["去找人看身体"],
    literal: "go find someone to look at the body",
    fit: "plain",
    why: "Seeing a doctor is going to someone who looks at the body; short and said as people say it.",
  },
  "遇见": {
    hsd: [`${W("mei2")} ${W("xiang3")}-${W("dao4")} ${W("hui4")} ${W("kan4")}-${W("dao4")}`],
    tts: ["没想到会看到"],
    literal: "didn't think I'd see",
    fit: "plain",
    why: "kàn-dào is only see; meeting by chance is not having expected it: méi xiǎng-dào huì kàn-dào.",
  },
  "跑步": {
    hsd: [`${W("zou3")}-${W("de")} ${W("hen3")} ${W("kuai4")}`],
    tts: ["走得很快"],
    literal: "walk very fast",
    fit: "plain",
    why: "Running is walking very fast; it uses zǒu-de, the pattern of the examples (tā zǒu-de bù kuài).",
  },
  "聊天儿": {
    hsd: [`${W("yi1")}-${W("qi3")} ${W("shuo1")}-${W("hua4")}`],
    tts: ["一起说话"],
    literal: "talk together",
    fit: "plain",
    why: "shuō-shuo isn't a core word; chatting is talking together, shuō-huà.",
  },
  "呢": {
    hsd: ['"ne"'],
    tts: ["呢"],
    fit: "natural",
    why: "A sound, written in quotes like 啊 (\"a\"): it asks 'and you?' with no word of its own.",
  },
  "吧": {
    hsd: ['"ba"'],
    tts: ["吧"],
    fit: "natural",
    why: "A sound, written in quotes like 啊: it softens a suggestion.",
  },
  "嗯": {
    hsd: ['"ng"', W("dui4")],
    tts: ["嗯", "对"],
    fit: "natural",
    why: "The sound itself goes in quotes like 啊; duì says what it means (yes, right).",
  },
  "专家": {
    hsd: [`${W("zhi1dao4")} ${W("hen3")}-${W("duo1")}-${W("de")} ${W("ren2")}`],
    tts: ["知道很多的人"],
    literal: "a person who knows a lot",
    why: "Only the joining: hěn-duō-de + noun is the book's rule.",
  },
  "政府": {
    hsd: [`${W("shuo1")} ${W("guo2")}-${W("jia1")} ${W("yao4")} ${W("zuo4")} ${W("shen2me")}-${W("de")} ${W("ren2")}`],
    tts: ["说国家要做什么的人"],
    literal: "the people who say what the country will do",
    why: "guó-jiā (nation) is made of core words, so it replaces the long guó-yào chain.",
  },
  "汉字": {
    hsd: [`"Zhōngguó"-${W("de")} ${W("zi4")}`],
    tts: ["中国的字"],
    literal: "China's characters",
    why: "zì is the written character now, so it replaces xiě-de cí.",
  },
};
