// Chinese text for lesson-18, matching shape.ts's keys. Typed as
// `PartialByKey<LessonShape>`.
// Not translated yet -- every `zh` is the empty-array placeholder.
import type { PartialByKey } from "../../lib/chapter-shape-types.ts";
import type { LessonShape } from "./shape.ts";

const zh: PartialByKey<LessonShape> = {
  title: { zh: [] },
  summary: { zh: [] },
  vocabCi: { zh: [] },
  vocabFangfa: { zh: [] },
  vocabBizi: { zh: [] },
  vocabPifu: { zh: [] },
  proseThing: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleThing1: { zh: [] },
  exampleThing2: { zh: [] },
  exampleThing3: { zh: [] },
  exampleThing4: { zh: [] },
  exampleThing5: { zh: [] },
  exampleThing6: { zh: [] },
  exampleThing7: { zh: [] },
  prosePerson: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  examplePerson1: { zh: [] },
  examplePerson2: { zh: [] },
  examplePerson3: { zh: [] },
  proseHow: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleHow1: { zh: [] },
  exampleHow2: { zh: [] },
  exampleHow3: { zh: [] },
  exampleHow4: { zh: [] },
  proseName: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleName1: { zh: [] },
  exampleName2: { zh: [] },
  exampleName3: { zh: [] },
  exampleName4: { zh: [] },
  exampleName5: { zh: [] },
  exampleName6: { zh: [] },
  exampleName7: { zh: [] },
  exampleName8: { zh: [] },
  exampleName9: { zh: [] },
  exampleName10: { zh: [] },
  exampleName11: { zh: [] },
  exampleName12: { zh: [] },
  infoJobsOfDe: {
    title: { zh: [] },
    items: [
      { zh: [] },
      { zh: [] },
      { zh: [] },
      { zh: [] },
      { zh: [] },
    ],
  },
  exercise1: { zh: [] },
  exercise2: { zh: [] },
  exercise3: { zh: [] },
  exercise4: { zh: [] },
  exercise5: { zh: [] },
  exercise6: { zh: [] },
  exercise7: { zh: [] },
  answer1: { zh: [] },
  answer2: { zh: [] },
  answer3: { zh: [] },
  answer4: { zh: [] },
  answer5: { zh: [] },
  answer6: { zh: [] },
  answer7: { zh: [] },
};

export default zh;
