// Russian text for everyday-patterns, matching shape.ts's keys. Typed as
// `PartialByKey<LessonShape>`.
// Not translated yet -- every `ru` is the empty-array placeholder.
import type { PartialByKey } from "../../../lib/chapter-shape-types.ts";
import type { LessonShape } from "./shape.ts";

const ru: PartialByKey<LessonShape> = {
  title: { ru: [] },
  summary: { ru: [] },
  proseLetMe: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleLetMe1: { ru: [] },
  exampleLetMe2: { ru: [] },
  exampleLetMe3: { ru: [] },
  exampleLetMe4: { ru: [] },
  exampleLetMe5: { ru: [] },
  exampleLetMe6: { ru: [] },
  proseMyTurn: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleMyTurn1: { ru: [] },
  exampleMyTurn2: { ru: [] },
  exampleMyTurn3: { ru: [] },
  exampleMyTurn4: { ru: [] },
  exampleMyTurn5: { ru: [] },
  exampleMyTurn6: { ru: [] },
  vocabBang: { ru: [] },
  proseHelp: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleHelp1: { ru: [] },
  exampleHelp3: { ru: [] },
  exampleHelp7: { ru: [] },
  exampleHelp8: { ru: [] },
  exampleHelp9: { ru: [] },
  exampleHelp10: { ru: [] },
  exampleHelp11: { ru: [] },
  exampleHelp12: { ru: [] },
  vocabTeach: { ru: [] },
  proseTeach: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleTeach1: { ru: [] },
  exampleTeach2: { ru: [] },
  exampleTeach3: { ru: [] },
  exampleTeach4: { ru: [] },
  proseHaveSomeone: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleHaveSomeone1: { ru: [] },
  exampleHaveSomeone2: { ru: [] },
  exampleHaveSomeone3: { ru: [] },
  exampleHaveSomeone4: { ru: [] },
  exampleHaveSomeone5: { ru: [] },
  proseMayI: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleMayI1: { ru: [] },
  exampleMayI2: { ru: [] },
  exampleMayI3: { ru: [] },
  exampleMayI4: { ru: [] },
  exampleMayI5: { ru: [] },
  exampleMayI6: { ru: [] },
  exampleMayI7: { ru: [] },
  exampleMayI8: { ru: [] },
  infoEveryday: { title: { ru: [] }, items: [{ ru: [] }, { ru: [] }, { ru: [] }, { ru: [] }, { ru: [] }, { ru: [] }] },
  exercise1: { ru: [] },
  exercise2: { ru: [] },
  exercise3: { ru: [] },
  exercise4: { ru: [] },
  exercise5: { ru: [] },
  exercise6: { ru: [] },
  exercise7: { ru: [] },
  exercise8: { ru: [] },
  exercise9: { ru: [] },
  exercise10: { ru: [] },
  exercise11: { ru: [] },
  exercise12: { ru: [] },
  exercise13: { ru: [] },
  answer1: { ru: [] },
  answer2: { ru: [] },
  answer3: { ru: [] },
  answer4: { ru: [] },
  answer5: { ru: [] },
  answer6: { ru: [] },
  answer7: { ru: [] },
  answer8: { ru: [] },
  answer9: { ru: [] },
  answer10: { ru: [] },
  answer11: { ru: [] },
  answer12: { ru: [] },
  answer13: { ru: [] },
  faqLetWord: { question: { ru: [] }, ru: [] },
  faqJiaoName: { question: { ru: [] }, ru: [] },
  faqWhyYixia: { question: { ru: [] }, ru: [] },
};

export default ru;
