// Chinese text for everyday-patterns, matching shape.ts's keys. Typed as
// `PartialByKey<LessonShape>`.
// Not translated yet -- every `zh` is the empty-array placeholder.
import type { PartialByKey } from "../../../lib/chapter-shape-types.ts";
import type { LessonShape } from "./shape.ts";

const zh: PartialByKey<LessonShape> = {
  title: { zh: [] },
  summary: { zh: [] },
  proseLetMe: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleLetMe1: { zh: [] },
  exampleLetMe2: { zh: [] },
  exampleLetMe3: { zh: [] },
  exampleLetMe4: { zh: [] },
  exampleLetMe5: { zh: [] },
  exampleLetMe6: { zh: [] },
  proseMyTurn: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleMyTurn1: { zh: [] },
  exampleMyTurn2: { zh: [] },
  exampleMyTurn3: { zh: [] },
  exampleMyTurn4: { zh: [] },
  exampleMyTurn5: { zh: [] },
  exampleMyTurn6: { zh: [] },
  vocabBang: { zh: [] },
  proseHelp: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleHelp1: { zh: [] },
  exampleHelp2: { zh: [] },
  exampleHelp3: { zh: [] },
  exampleHelp4: { zh: [] },
  exampleHelp5: { zh: [] },
  exampleHelp6: { zh: [] },
  exampleHelp7: { zh: [] },
  exampleHelp8: { zh: [] },
  exampleHelp9: { zh: [] },
  exampleHelp10: { zh: [] },
  exampleHelp11: { zh: [] },
  exampleHelp12: { zh: [] },
  vocabTeach: { zh: [] },
  proseTeach: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleTeach1: { zh: [] },
  exampleTeach2: { zh: [] },
  exampleTeach3: { zh: [] },
  exampleTeach4: { zh: [] },
  proseHaveSomeone: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleHaveSomeone1: { zh: [] },
  exampleHaveSomeone2: { zh: [] },
  exampleHaveSomeone3: { zh: [] },
  exampleHaveSomeone4: { zh: [] },
  exampleHaveSomeone5: { zh: [] },
  proseMayI: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleMayI1: { zh: [] },
  exampleMayI2: { zh: [] },
  exampleMayI3: { zh: [] },
  exampleMayI4: { zh: [] },
  exampleMayI5: { zh: [] },
  exampleMayI6: { zh: [] },
  exampleMayI7: { zh: [] },
  infoEveryday: { title: { zh: [] }, items: [{ zh: [] }, { zh: [] }, { zh: [] }, { zh: [] }, { zh: [] }, { zh: [] }] },
  exercise1: { zh: [] },
  exercise2: { zh: [] },
  exercise3: { zh: [] },
  exercise4: { zh: [] },
  exercise5: { zh: [] },
  exercise6: { zh: [] },
  exercise7: { zh: [] },
  exercise8: { zh: [] },
  exercise9: { zh: [] },
  exercise10: { zh: [] },
  exercise11: { zh: [] },
  exercise12: { zh: [] },
  exercise13: { zh: [] },
  answer1: { zh: [] },
  answer2: { zh: [] },
  answer3: { zh: [] },
  answer4: { zh: [] },
  answer5: { zh: [] },
  answer6: { zh: [] },
  answer7: { zh: [] },
  answer8: { zh: [] },
  answer9: { zh: [] },
  answer10: { zh: [] },
  answer11: { zh: [] },
  answer12: { zh: [] },
  answer13: { zh: [] },
  faqLetWord: { question: { zh: [] }, zh: [] },
  faqJiaoName: { question: { zh: [] }, zh: [] },
  faqWhyYixia: { question: { zh: [] }, zh: [] },
};

export default zh;
