// Chinese text for lesson-20, matching shape.ts's keys. Typed as
// `PartialByKey<LessonShape>`.
// Not translated yet -- every `zh` is the empty-array placeholder.
import type { PartialByKey } from "../../lib/chapter-shape-types.ts";
import type { LessonShape } from "./shape.ts";

const zh: PartialByKey<LessonShape> = {
  title: { zh: [] },
  summary: { zh: [] },
  vocabYinwei: { zh: [] },
  vocabDanshi: { zh: [] },
  vocabYan: { zh: [] },
  vocabSi: { zh: [] },
  vocabHuo: { zh: [] },
  vocabHua: { zh: [] },
  proseBecause: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleBecause1: { zh: [] },
  exampleBecause2: { zh: [] },
  exampleBecause3: { zh: [] },
  exampleBecause4: { zh: [] },
  exampleBecause5: { zh: [] },
  exampleBecause6: { zh: [] },
  exampleBecause7: { zh: [] },
  proseBut: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleBut1: { zh: [] },
  exampleBut2: { zh: [] },
  exampleBut3: { zh: [] },
  exampleBut4: { zh: [] },
  exampleBut5: { zh: [] },
  exampleBut6: { zh: [] },
  exampleBut7: { zh: [] },
  exampleBut8: { zh: [] },
  proseIf: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleIf1: { zh: [] },
  exampleIf2: { zh: [] },
  exampleIf3: { zh: [] },
  exampleIf4: { zh: [] },
  exampleIf5: { zh: [] },
  exampleIf6: { zh: [] },
  exampleIf7: { zh: [] },
  exampleIf8: { zh: [] },
  exampleIf9: { zh: [] },
  infoLinkingSentences: {
    title: { zh: [] },
    items: [{ zh: [] }, { zh: [] }, { zh: [] }],
  },
  exercise1: { zh: [] },
  exercise2: { zh: [] },
  exercise3: { zh: [] },
  exercise4: { zh: [] },
  exercise5: { zh: [] },
  exercise6: { zh: [] },
  exercise7: { zh: [] },
  answer1: { zh: [] },
  answer2: { zh: [] },
  answer3: { zh: [] },
  answer4: { zh: [] },
  answer5: { zh: [] },
  answer6: { zh: [] },
  answer7: { zh: [] },
};

export default zh;
