// See src/lib/chapter-content.js for the schema this is transformed by.
// zh/ru intentionally blank -- carried over English-only from lesson-04.yaml.
import type { Entry } from '../../lib/chapter-entry-types.ts';

export const meta = {
  id: 'lesson-04',
  type: 'lesson',
  lessonNumber: 4,
  order: 4,
};

const content: Entry[] = [
  {
    type: 'title',
    en: ['Nouns and Adjectives'],
    zh: [],
    ru: ['Существительные и прилагательные'],
  },
  {
    type: 'summary',
    en: [
      'Adjectives connect to a subject with {{word:hen3}} instead of {{word:shi4}} ({{Word:shui3}} {{word:hen3}} {{word:hao3}} — "Water is good"), and bind onto a noun with -{{word:de}} instead when describing it as a unit ({{word:hen3}}-{{word:xiao3}}-{{word:de}} {{word:di4fang1}} — "a small place").',
    ],
    zh: [],
    ru: [
      'Прилагательные соединяются с подлежащим через {{word:hen3}}, а не через {{word:shi4}} ({{Word:shui3}} {{word:hen3}} {{word:hao3}} — «Вода хорошая»), а когда описывают существительное как единое целое, присоединяются к нему через -{{word:de}} ({{word:hen3}}-{{word:xiao3}}-{{word:de}} {{word:di4fang1}} — «маленькое место»).',
    ],
  },
  {
    type: 'vocab',
    term: '{{word:shui3}}',
    ttsText: '水',
    en: ['water, liquid'],
    zh: [],
    ru: ['вода, жидкость'],
  },
  {
    type: 'vocab',
    term: '{{word:di4fang1}}',
    ttsText: '地方',
    en: ['a place (both in space or metaphorical to mean part of something)'],
    zh: [],
    ru: ['место (как в пространстве, так и в переносном смысле — часть чего-либо)'],
  },
  {
    type: 'vocab',
    term: '{{word:xiao3}}',
    ttsText: '小',
    en: ['little, small'],
    zh: [],
    ru: ['маленький, небольшой'],
  },
  {
    type: 'vocab',
    term: '{{word:hao3}}',
    ttsText: '好',
    en: ['good, simple, friendly'],
    zh: [],
    ru: ['хороший, простой, дружелюбный'],
  },
  {
    type: 'vocab',
    term: '{{word:da4}}',
    ttsText: '大',
    en: ['big, important, tall'],
    zh: [],
    ru: ['большой, важный, высокий (о росте)'],
  },
  {
    type: 'prose',
    en: [
      'Lesson 3 gave you <audio-example zh="是">{{word:shi4}}</audio-example>, the word that connects a subject to a noun (<audio-example zh="人是女人">{{Word:ren2}} {{word:shi4}} {{word:nv3ren2}}</audio-example> — "the person is a woman").',
      "Adjectives need a connector too, but Mandarin doesn't reuse <audio-example zh=\"是\">{{word:shi4}}</audio-example> for the job — it uses a different word instead: <audio-example zh=\"很\">{{word:hen3}}</audio-example>.",
      '',
      'Subject + <audio-example zh="很">{{word:hen3}}</audio-example> + Adjective',
      '',
      'A bare adjective predicate like <audio-example zh="水好">{{word:shui3}} {{word:hao3}}</audio-example> or <audio-example zh="我好">{{word:wo3}} {{word:hao3}}</audio-example> isn\'t a neutral statement.',
      'In natural Mandarin, it sounds like a contrast ("Water is good, but…" or "I am good, [unlike someone else]") or a subordinate clause ("When I am good…" or "If I am good…").',
      'To make a plain, complete statement, you need a degree adverb to fill the predicate slot.',
      'That\'s where <audio-example zh="很">{{word:hen3}}</audio-example> comes in: it\'s the default, neutral degree adverb.',
      'Its literal translation is "very," but in this position it\'s semantically bleached — it doesn\'t add emphasis.',
      'So <audio-example zh="水很好">{{Word:shui3}} {{word:hen3}} {{word:hao3}}</audio-example> is simply "Water is good," not "Water is very good."',
      '',
      'To hear the difference, compare these pairs (listen to how a native would interpret them):',
      '',
      '1. <audio-example zh="水好">{{Word:shui3}} {{word:hao3}}</audio-example> — without 很 → sounds like a contrast or condition: "Water is good (but something else isn\'t)" or "If/When the water is good…" It begs for a follow-up.\n   <audio-example zh="水很好">{{Word:shui3}} {{word:hen3}} {{word:hao3}}</audio-example> — with 很 → a complete, neutral statement: "Water is good."',
      '',
      '2. <audio-example zh="我好">{{Word:wo3}} {{word:hao3}}</audio-example> — without 很 → sounds like "I\'m fine (in contrast to someone who isn\'t)" or "If I\'m fine…" — it leaves the listener waiting.\n   <audio-example zh="我很好">{{Word:wo3}} {{word:hen3}} {{word:hao3}}</audio-example> — with 很 → a natural reply to "How are you?" — "I\'m fine."',
      '',
      '3. <audio-example zh="地方小">{{Word:di4fang1}} {{word:xiao3}}</audio-example> — without 很 → sounds like "The place is small (but maybe convenient)" — the but is implied; it\'s a comparative or concessive setup.\n   <audio-example zh="地方很小">{{Word:di4fang1}} {{word:hen3}} {{word:xiao3}}</audio-example> — with 很 → a plain observation: "The place is small."',
      '',
      "So omitting 很 doesn't create ambiguity in the sense of multiple meanings — it creates a different grammatical function: a contrastive/conditional clause rather than a main declarative sentence.",
      'A native hears <audio-example zh="水好">{{word:shui3}} {{word:hao3}}</audio-example> and immediately expects a second half, like <audio-example zh="水好，但人不好">{{word:shui3}} {{word:hao3}}, dàn {{word:ren2}} {{word:bu4}} {{word:hao3}}</audio-example> ("The water is good, but the people are not").',
      'With <audio-example zh="很">{{word:hen3}}</audio-example>, the sentence stands on its own.',
    ],
    zh: [],
    ru: [
      'Урок 3 дал вам <audio-example zh="是">{{word:shi4}}</audio-example> — слово, которое связывает подлежащее с существительным (<audio-example zh="人是女人">{{Word:ren2}} {{word:shi4}} {{word:nv3ren2}}</audio-example> — «человек — женщина»).',
      'Прилагательным тоже нужен связующий элемент, но мандаринский не использует для этого <audio-example zh="是">{{word:shi4}}</audio-example> повторно — вместо этого используется другое слово: <audio-example zh="很">{{word:hen3}}</audio-example>.',
      '',
      'Подлежащее + <audio-example zh="很">{{word:hen3}}</audio-example> + Прилагательное',
      '',
      'Голое прилагательное в роли сказуемого, например <audio-example zh="水好">{{word:shui3}} {{word:hao3}}</audio-example> или <audio-example zh="我好">{{word:wo3}} {{word:hao3}}</audio-example>, не является нейтральным утверждением.',
      'В естественном мандаринском это звучит как противопоставление («Вода хорошая, но…» или «Я хороший, [в отличие от кого-то другого]») или как придаточное предложение («Когда я хороший…» или «Если я хороший…»).',
      'Чтобы сделать простое, законченное утверждение, нужно заполнить позицию сказуемого наречием степени.',
      'Именно здесь и появляется <audio-example zh="很">{{word:hen3}}</audio-example>: это стандартное, нейтральное наречие степени.',
      'Буквально оно переводится как «очень», но в этой позиции его смысл ослаблен — оно не добавляет усиления.',
      'Так что <audio-example zh="水很好">{{Word:shui3}} {{word:hen3}} {{word:hao3}}</audio-example> — это просто «Вода хорошая», а не «Вода очень хорошая».',
      '',
      'Чтобы услышать разницу, сравните эти пары (обратите внимание, как носитель их поймёт):',
      '',
      '1. <audio-example zh="水好">{{Word:shui3}} {{word:hao3}}</audio-example> — без 很 → звучит как противопоставление или условие: «Вода хорошая (но что-то другое — нет)» или «Если/когда вода хорошая…» — просит продолжения.\n   <audio-example zh="水很好">{{Word:shui3}} {{word:hen3}} {{word:hao3}}</audio-example> — с 很 → законченное, нейтральное утверждение: «Вода хорошая».',
      '',
      '2. <audio-example zh="我好">{{Word:wo3}} {{word:hao3}}</audio-example> — без 很 → звучит как «Я в порядке (в отличие от кого-то, кто не в порядке)» или «Если я в порядке…» — оставляет слушателя в ожидании.\n   <audio-example zh="我很好">{{Word:wo3}} {{word:hen3}} {{word:hao3}}</audio-example> — с 很 → естественный ответ на «Как дела?» — «Я в порядке».',
      '',
      '3. <audio-example zh="地方小">{{Word:di4fang1}} {{word:xiao3}}</audio-example> — без 很 → звучит как «Место маленькое (но, возможно, удобное)» — подразумевается «но»; это установка на сравнение или уступку.\n   <audio-example zh="地方很小">{{Word:di4fang1}} {{word:hen3}} {{word:xiao3}}</audio-example> — с 很 → простое наблюдение: «Место маленькое».',
      '',
      'Таким образом, пропуск 很 не создаёт неоднозначности в смысле множества значений — он создаёт другую грамматическую функцию: противопоставительное/условное придаточное вместо главного повествовательного предложения.',
      'Носитель слышит <audio-example zh="水好">{{word:shui3}} {{word:hao3}}</audio-example> и сразу ожидает вторую половину, например <audio-example zh="水好，但人不好">{{word:shui3}} {{word:hao3}}, dàn {{word:ren2}} {{word:bu4}} {{word:hao3}}</audio-example> («Вода хорошая, но люди — нет»).',
      'С <audio-example zh="很">{{word:hen3}}</audio-example> предложение самодостаточно.',
    ],
    tldr: {
      en: ['Adjectives use {{word:hen3}} as a neutral predicate connector to avoid sounding like a contrast or condition; in this role {{word:hen3}} is required and not emphatic.'],
      zh: [],
      ru: ['Прилагательные используют {{word:hen3}} как нейтральную связку в сказуемом, чтобы не звучать как противопоставление или условие; в этой роли {{word:hen3}} обязателен и не является усилительным.'],
    },
    necessity: {
      en: ['Explains that {{word:hen3}} is a neutral predicate filler, not an intensifier, and that omitting it creates a contrastive or conditional reading rather than a plain statement, with three minimal pairs to illustrate.'],
      zh: [],
      ru: ['Объясняет, что {{word:hen3}} — это нейтральный заполнитель сказуемого, а не усилитель, и что его пропуск создаёт значение противопоставления или условия, а не простое утверждение, с тремя минимальными парами для иллюстрации.'],
    },
  },
  {
    type: 'prose',
    en: [
      'When an adjective sits right next to a noun instead of making its own statement — describing it as a single unit, the way <audio-example zh="很小的地方">{{word:hen3}}-{{word:xiao3}}-{{word:de}} {{word:di4fang1}}</audio-example> describes "a small place" — it binds on with <code>-{{word:de}}</code>, the same connecting particle from Lesson 2.',
      '',
      'But why is <code>-{{word:de}}</code> required here?',
      'For a bare adjective like <audio-example zh="大">{{word:da4}}</audio-example> or <audio-example zh="小">{{word:xiao3}}</audio-example>, you can sometimes drop <code>-{{word:de}}</code> and form a close compound: <audio-example zh="大地方">{{word:da4}}-{{word:di4fang1}}</audio-example> ("big place") is acceptable.',
      "However, once the adjective is modified by a degree word like <audio-example zh=\"很\">{{word:hen3}}</audio-example>, or once it's a multi-character adjective, you can't attach it directly.",
      '<audio-example zh="很小地方">{{word:hen3}}-{{word:xiao3}} {{word:di4fang1}}</audio-example> is ungrammatical — you need <audio-example zh="很小的地方">{{word:hen3}}-{{word:xiao3}}-{{word:de}} {{word:di4fang1}}</audio-example>.',
      'Moreover, even with bare adjectives, <code>-{{word:de}}</code> can signal a descriptive, non‑inherent property: <audio-example zh="好动物">{{word:hao3}}-{{word:dong4wu4}}</audio-example> can mean a "good animal" in the sense of a beneficial species or a moral animal (a fixed category), whereas <audio-example zh="好的动物">{{word:hao3}}-{{word:de}} {{word:dong4wu4}}</audio-example> simply describes an animal that happens to be good (a specific modification).',
      '',
      'To hear the difference, compare these pairs (listen to how a native would interpret them):',
      '',
      '1. <audio-example zh="大地方">{{Word:da4}} {{word:di4fang1}}</audio-example> — without 的 → tends to be heard as a compound noun: "a big place" as a category (e.g., a major city, a large venue as a type).\n   <audio-example zh="大的地方">{{Word:da4}}-{{word:de}} {{word:di4fang1}}</audio-example> — with 的 → a descriptive phrase: "a place which is big" — the bigness is a contingent property, not the name of the place.',
      '',
      '2. <audio-example zh="小动物">{{Word:xiao3}} {{word:dong4wu4}}</audio-example> — without 的 → often means "small animal" as a biological class or common term (like a kitten, a mouse — it\'s almost a compound word).\n   <audio-example zh="小的动物">{{Word:xiao3}}-{{word:de}} {{word:dong4wu4}}</audio-example> — with 的 → means "an animal that is small" — you\'re picking out an animal by its size right now.',
      '',
      '3. <audio-example zh="好水">{{Word:hao3}} {{word:shui3}}</audio-example> — without 的 → could mean "good water" as a known brand, a type, or "plain water" (as opposed to tea) in some dialects — it\'s a fixed category.\n   <audio-example zh="好的水">{{Word:hao3}}-{{word:de}} {{word:shui3}}</audio-example> — with 的 → means "water that is good" — a specific instance, not a category label.',
      '',
      "So omitting <code>-{{word:de}}</code> doesn't make the phrase ungrammatical for all adjectives — but it shifts the meaning toward a fixed compound or a category label.",
      'Adding <code>-{{word:de}}</code> keeps it a descriptive modification.',
      "When the adjective has its own modifier (like <audio-example zh=\"很\">{{word:hen3}}</audio-example>), <code>-{{word:de}}</code> is mandatory, otherwise the phrase is simply ungrammatical and a native won't understand it as a noun phrase at all.",
    ],
    zh: [],
    ru: [
      'Когда прилагательное стоит прямо рядом с существительным, а не образует отдельное высказывание, — описывая его как единое целое, так же как <audio-example zh="很小的地方">{{word:hen3}}-{{word:xiao3}}-{{word:de}} {{word:di4fang1}}</audio-example> описывает «маленькое место», — оно присоединяется через <code>-{{word:de}}</code>, ту же связующую частицу из Урока 2.',
      '',
      'Но почему здесь требуется <code>-{{word:de}}</code>?',
      'Для голого прилагательного, например <audio-example zh="大">{{word:da4}}</audio-example> или <audio-example zh="小">{{word:xiao3}}</audio-example>, иногда можно опустить <code>-{{word:de}}</code> и образовать тесное сложное слово: <audio-example zh="大地方">{{word:da4}}-{{word:di4fang1}}</audio-example> («большое место») допустимо.',
      'Однако как только прилагательное сопровождается словом степени, например <audio-example zh="很">{{word:hen3}}</audio-example>, или когда оно состоит из нескольких слогов, прикреплять его напрямую уже нельзя.',
      '<audio-example zh="很小地方">{{word:hen3}}-{{word:xiao3}} {{word:di4fang1}}</audio-example> — грамматически неверно; нужно <audio-example zh="很小的地方">{{word:hen3}}-{{word:xiao3}}-{{word:de}} {{word:di4fang1}}</audio-example>.',
      'Кроме того, даже с голыми прилагательными <code>-{{word:de}}</code> может указывать на описательное, непостоянное свойство: <audio-example zh="好动物">{{word:hao3}}-{{word:dong4wu4}}</audio-example> может означать «хорошее животное» в смысле полезного вида или нравственного животного (устойчивая категория), тогда как <audio-example zh="好的动物">{{word:hao3}}-{{word:de}} {{word:dong4wu4}}</audio-example> просто описывает животное, которое оказалось хорошим (конкретное уточнение).',
      '',
      'Чтобы услышать разницу, сравните эти пары (обратите внимание, как носитель их поймёт):',
      '',
      '1. <audio-example zh="大地方">{{Word:da4}} {{word:di4fang1}}</audio-example> — без 的 → скорее воспринимается как сложное существительное: «большое место» как категория (например, крупный город, большой зал как тип).\n   <audio-example zh="大的地方">{{Word:da4}}-{{word:de}} {{word:di4fang1}}</audio-example> — с 的 → описательное словосочетание: «место, которое большое» — большой размер — это случайное свойство, а не название места.',
      '',
      '2. <audio-example zh="小动物">{{Word:xiao3}} {{word:dong4wu4}}</audio-example> — без 的 → часто означает «маленькое животное» как биологический класс или обиходный термин (котёнок, мышь — почти сложное слово).\n   <audio-example zh="小的动物">{{Word:xiao3}}-{{word:de}} {{word:dong4wu4}}</audio-example> — с 的 → означает «животное, которое маленькое» — вы выделяете животное по его размеру в данный момент.',
      '',
      '3. <audio-example zh="好水">{{Word:hao3}} {{word:shui3}}</audio-example> — без 的 → может означать «хорошая вода» как известный бренд, тип или просто «вода» (в отличие от чая) в некоторых диалектах — это устойчивая категория.\n   <audio-example zh="好的水">{{Word:hao3}}-{{word:de}} {{word:shui3}}</audio-example> — с 的 → означает «вода, которая хорошая» — конкретный экземпляр, а не ярлык категории.',
      '',
      'Таким образом, пропуск <code>-{{word:de}}</code> не делает фразу неграмматичной для всех прилагательных — но смещает значение в сторону устойчивого сложного слова или категории.',
      'Добавление <code>-{{word:de}}</code> сохраняет описательное значение.',
      'Когда у прилагательного есть собственное определение (например, <audio-example zh="很">{{word:hen3}}</audio-example>), <code>-{{word:de}}</code> обязательно, иначе фраза становится просто неграмматичной, и носитель вообще не поймёт её как именную группу.',
    ],
    tldr: {
      en: ['-{{word:de}} is required when the adjective has modifiers like {{word:hen3}}, or to distinguish a descriptive phrase from a fixed compound; without it, phrases like 很小地方 are ungrammatical, and bare adjectives can shift to compound-noun readings — three pairs show the contrast.'],
      zh: [],
      ru: ['-{{word:de}} требуется, когда прилагательное имеет при себе определения, такие как {{word:hen3}}, или чтобы отличить описательное словосочетание от устойчивого сложного слова; без него фразы вроде 很小地方 грамматически неверны, а голые прилагательные могут восприниматься как часть сложного существительного — три пары показывают контраст.'],
    },
    necessity: {
      en: ['Clarifies that -{{word:de}} is grammatically required when an adjective is modified (e.g., by {{word:hen3}}) and that its presence or absence can shift meaning between a fixed compound and a descriptive phrase, with three minimal pairs illustrating the native perception.'],
      zh: [],
      ru: ['Разъясняет, что -{{word:de}} грамматически обязательно, когда прилагательное имеет определение (например, {{word:hen3}}), и что его наличие или отсутствие может менять значение между устойчивым сложным словом и описательным словосочетанием, с тремя минимальными парами, иллюстрирующими восприятие носителя.'],
    },
  },
  {
    type: 'example',
    pinyin: '{{Word:shui3}} {{word:hen3}} {{word:hao3}}.',
    ttsText: '水很好。',
    en: ['Water is good.'],
    zh: [],
    ru: ['Вода хорошая.'],
  },
  {
    type: 'example',
    pinyin: '{{Word:zhe4}}-ge {{word:shi4}} {{word:hen3}}-{{word:xiao3}}-{{word:de}} {{word:di4fang1}}.',
    ttsText: '这个是很小的地方。',
    en: ['This is a small place.'],
    zh: [],
    ru: ['Это маленькое место.'],
  },
  {
    type: 'example',
    pinyin: '{{Word:zhe4}}-ge {{word:shi4}} {{word:yi1}}-ge {{word:hen3}}-{{word:da4}}-{{word:de}} {{word:dong4wu4}}.',
    ttsText: '这个是一个很大的动物。',
    en: ['This is a very big animal.'],
    zh: [],
    ru: ['Это очень большое животное.'],
  },
  {
    type: 'exercise',
    en: ['The place is small.'],
    zh: [],
    ru: ['Место маленькое.'],
  },
  {
    type: 'exercise',
    en: ['This is a good animal.'],
    zh: [],
    ru: ['Это хорошее животное.'],
  },
  {
    type: 'exercise',
    en: ['This is a big fruit.'],
    zh: [],
    ru: ['Это большой фрукт.'],
  },
  {
    type: 'answer',
    en: ['{{Word:di4fang1}} {{word:hen3}} {{word:xiao3}}.'],
    zh: [],
    ru: ['{{Word:di4fang1}} {{word:hen3}} {{word:xiao3}}.'],
    ttsText: '地方很小。',
  },
  {
    type: 'answer',
    en: ['{{Word:zhe4}}-ge {{word:shi4}} {{word:hao3}}-{{word:de}} {{word:dong4wu4}}.'],
    zh: [],
    ru: ['{{Word:zhe4}}-ge {{word:shi4}} {{word:hao3}}-{{word:de}} {{word:dong4wu4}}.'],
    ttsText: '这个是好的动物。',
  },
  {
    type: 'answer',
    en: ['{{Word:zhe4}}-ge {{word:shi4}} {{word:yi1}}-ge {{word:hen3}}-{{word:da4}}-{{word:de}} {{word:shui3guo3}}.'],
    zh: [],
    ru: ['{{Word:zhe4}}-ge {{word:shi4}} {{word:yi1}}-ge {{word:hen3}}-{{word:da4}}-{{word:de}} {{word:shui3guo3}}.'],
    ttsText: '这个是一个很大的水果。',
  },
];

export default content;
