// Chinese text for lesson-04, matching shape.ts's keys. Typed as
// `PartialByKey<LessonShape>`.
// Not translated yet -- every `zh` is the empty-array placeholder.
import type { PartialByKey } from "../../lib/chapter-shape-types.ts";
import type { LessonShape } from "./shape.ts";

const zh: PartialByKey<LessonShape> = {
  title: { zh: [] },
  summary: { zh: [] },
  vocabNa: { zh: [] },
  prosePointersAreNouns: { zh: [] },
  pointersExample01: { zh: [] },
  pointersExample02: { zh: [] },
  proseMandarinMeasureWords: { zh: [] },
  vocabGe: { zh: [] },
  proseGeIsUniversal: { zh: [] },
  infoUniversalClassifier: { items: [{ zh: [] }] },
  example1L11: { zh: [] },
  example2L11: { zh: [] },
  example3L11: { zh: [] },
  example4L11: { zh: [] },
  example5L11: { zh: [] },
  vocabWo: { zh: [] },
  vocabNi: { zh: [] },
  vocabTa: { zh: [] },
  prosePointingToPeople: { zh: [] },
  pointToPeopleExample01: { zh: [] },
  pointToPeopleExample02: { zh: [] },
  pointToPeopleExample03: { zh: [] },
  vocabMen: { zh: [] },
  prosePluralPointers: { zh: [] },
  pluralPointersExample01: { zh: [] },
  pluralPointersExample02: { zh: [] },
  pluralPointersExample03: { zh: [] },
  vocabJia: { zh: [] },
  vocabTou: { zh: [] },
  vocabShou: { zh: [] },
  vocabJiao: { zh: [] },
  prosePossessionDe: { zh: [] },
  posessionDeExample01: { zh: [] },
  posessionDeExample02: { zh: [] },
  posessionDeExample03: { zh: [] },
  posessionDeExample04: { zh: [] },
  posessionDeExample05: { zh: [] },
  posessionDeExample06: { zh: [] },
  posessionDeExample07: { zh: [] },
  posessionDeExample08: { zh: [] },
  exercise1L03: { zh: [] },
  exercise2L03: { zh: [] },
  exercise1L11: { zh: [] },
  exercise2L11: { zh: [] },
  exercise3L11: { zh: [] },
  exercise1: { zh: [] },
  exercise2: { zh: [] },
  exercise3: { zh: [] },
  exercise4: { zh: [] },
  exercise5: { zh: [] },
  exercise6: { zh: [] },
  exercise7: { zh: [] },
  answer1L03: { zh: [] },
  answer2L03: { zh: [] },
  answer1L11: { zh: [] },
  answer2L11: { zh: [] },
  answer3L11: { zh: [] },
  answer1: { zh: [] },
  answer2: { zh: [] },
  answer3: { zh: [] },
  answer4: { zh: [] },
  answer5: { zh: [] },
  answer6: { zh: [] },
  answer7: { zh: [] },
  faqGeForEverything: { question: { zh: [] }, zh: [] },
  faqTaHeOrShe: { question: { zh: [] }, zh: [] },
  faqDropDe: { question: { zh: [] }, zh: [] },
};

export default zh;
