// Russian text for lesson-05, matching shape.ts's keys. Typed as
// `PartialByKey<LessonShape>`. Not translated yet -- every `ru` is the
// empty-array placeholder.
import type { PartialByKey } from "../../../../lib/chapter-shape-types.ts";
import type { LessonShape } from "./shape.ts";

const ru: PartialByKey<LessonShape> = {
  title: { ru: [] },
  summary: { ru: [] },
  vocabYou: { ru: [] },
  vocabMei: { ru: [] },
  vocabTing: { ru: [] },
  vocabChi: { ru: [] },
  vocabZuo: { ru: [] },
  vocabZhidao: { ru: [] },
  vocabShuo: { ru: [] },
  proseVerbs: { ru: [] },
  verbsExample1: { ru: [] },
  verbsExample2: { ru: [] },
  verbsExample3: { ru: [] },
  proseVerbNegation: { ru: [] },
  negationExample1: { ru: [] },
  negationExample2: { ru: [] },
  negationExample3: { ru: [] },
  proseWordOrderObject: { ru: [] },
  wordOrderExample1: { ru: [] },
  wordOrderExample2: { ru: [] },
  vocabLe: { ru: [] },
  vocabGuo: { ru: [] },
  vocabularyZai: { ru: [] },
  vocabHui: { ru: [] },
  proseLeCompletion: { ru: [] },
  infoCompletionMarker: { items: [{ru:[]}] },
  leExample1: { ru: [] },
  proseGuo: { ru: [] },
  guoExample1: { ru: [] },
  proseZai: { ru: [] },
  zaiExample1: { ru: [] },
  proseHui: { ru: [] },
  huiExample1: { ru: [] },
  completionMarkers: { ru: [] },
  infoCompletionMarkers: { items: [{ru:[]},{ru:[]},{ru:[]}] },
  exampleCompletionMarker1: { ru: [] },
  exampleCompletionMarker2: { ru: [] },
  exampleCompletionMarker3: { ru: [] },
  vocabQi: { ru: [] },
  vocabXia: { ru: [] },
  vocabShang: { ru: [] },
  vocabLai: { ru: [] },
  proseDirectionalComplements: { ru: [] },
  infoDirectionalComplements: { items: [{ru:[]},{ru:[]},{ru:[]}] },
  directionalExample1: { ru: [] },
  directionalExample2: { ru: [] },
  directionalExample3: { ru: [] },
  example1: { ru: [] },
  example2: { ru: [] },
  example3: { ru: [] },
  example4: { ru: [] },
  example5: { ru: [] },
  example6: { ru: [] },
  example7: { ru: [] },
  exercise1: { ru: [] },
  exercise2: { ru: [] },
  exercise3: { ru: [] },
  exercise4: { ru: [] },
  answer1: { ru: [] },
  answer2: { ru: [] },
  answer3: { ru: [] },
  answer4: { ru: [] },
};

export default ru;
