// See src/lib/chapter-content.js for the schema this is transformed by.
// zh/ru intentionally blank -- carried over English-only from lesson-06.yaml.
// A '' entry inside a sentence array is a deliberate paragraph break.
import type { Entry } from '../../lib/chapter-entry-types.ts';

export const meta = {
  id: 'lesson-06',
  type: 'lesson',
  lessonNumber: 6,
  order: 6,
};

const content: Entry[] = [
  {
    type: 'title',
    en: ['Dongzuo (Verbs)'],
    zh: [],
    ru: [],
  },
  {
    type: 'summary',
    en: [
      'Verbs carry no tense; `{{word:le}}` marks completion (not simply "the past"), words shift category by context alone, and directional complements like `{{word:qi3}}`, `{{word:xia4}}`, and `{{word:shang4}}` bind onto verbs via a hyphen to add direction and completion nuance.',
    ],
    zh: [],
    ru: [],
  },
  {
    type: 'vocab',
    term: '{{word:you3}}',
    ttsText: '有',
    en: ['to have, contain, carry'],
    zh: [],
    ru: [],
  },
  {
    type: 'vocab',
    term: '{{word:ting1}}',
    ttsText: '听',
    en: ['to listen to, hear, obey'],
    zh: [],
    ru: [],
  },
  {
    type: 'vocab',
    term: '{{word:chi1}}',
    ttsText: '吃',
    en: ['to eat, drink, consume; food'],
    zh: [],
    ru: [],
  },
  {
    type: 'vocab',
    term: '{{word:zuo4}}',
    ttsText: '做',
    en: ['to make, do, work on'],
    zh: [],
    ru: [],
  },
  {
    type: 'vocab',
    term: '{{word:zhi1dao4}}',
    ttsText: '知道',
    en: ['to know'],
    zh: [],
    ru: [],
  },
  {
    type: 'vocab',
    term: '{{word:shuo1}}',
    ttsText: '说',
    en: ['to talk, speak, communicate'],
    zh: [],
    ru: [],
  },
  {
    type: 'vocab',
    term: '{{word:qi3}}',
    ttsText: '起',
    en: ['to rise, get up; begin'],
    zh: [],
    ru: [],
  },
  {
    type: 'vocab',
    term: '{{word:xia4}}',
    ttsText: '下',
    en: ['down, below, under'],
    zh: [],
    ru: [],
  },
  {
    type: 'vocab',
    term: '{{word:shang4}}',
    ttsText: '上',
    en: ['up, above, on'],
    zh: [],
    ru: [],
  },
  {
    type: 'vocab',
    term: '{{word:lai2}}',
    ttsText: '来',
    en: ['to come, arrive, happen'],
    zh: [],
    ru: [],
  },
  {
    type: 'prose',
    en: [
      "Every sentence you've built so far -- with `{{word:shi4}}`, with `{{word:hen3}}`, with `-{{word:de}}` -- has relied on one fixed habit: words always sit in the same order, subject first, then the action, then whatever the action touches.",
      "Verbs don't break that habit; they lean on it completely.",
      "Because word order alone already tells you what's doing the action and what's being acted on, Hao-shuo-de never needs a special marker word standing in front of the object to flag it.",
      "If a word shows up right after the verb, it's the object -- that's the whole rule, and it doesn't need any more machinery than that.",
    ],
    zh: [],
    ru: [],
    tldr: {
      en: ["Word order alone marks the object -- nothing comes after the verb by accident."],
      zh: [],
      ru: [],
    },
    necessity: {
      en: ["Confirms Lesson 3's fixed word order carries real grammatical weight -- it's not just a style choice, it's replacing work a marker particle would otherwise have to do."],
      zh: [],
      ru: [],
    },
  },
  {
    type: 'info',
    subtype: 'grammar',
    tag: 'verbs/word-order',
    title: { en: ['No Object Marker Needed'], zh: [], ru: [] },
    items: [
      {
        text: {
          en: ["Subject + Verb + Object. Whatever sits directly after the verb is what's being acted on -- word order alone marks it, so no extra particle is required."],
          zh: [],
          ru: [],
        },
      },
    ],
  },
  {
    type: 'prose',
    en: [
      'Hao-shuo-de verbs never change shape to show when something happened.',
      'There is no separate "did," no separate "will do" -- the verb `{{word:chi1}}` means "eat" whether that eating happened yesterday, is happening now, or has not happened yet.',
      'Context, and a small set of markers, carry that weight instead.',
      '',
      'The most important of these markers is `{{word:le}}`.',
      'It is easy to mistake `{{word:le}}` for a simple stand-in for the English past tense, but that is not quite what it is doing.',
      '`{{word:le}}` marks that a change has actually taken place -- an action reached completion, or a state flipped from one thing to another.',
      'Most of the time that lines up with "the past," since a finished action usually did happen earlier.',
      'But `{{word:le}}` is about completion, not time: a sentence can use `{{word:le}}` to describe something that just finished a second ago, or something expected to be finished by tomorrow.',
      'What `{{word:le}}` never does is turn a verb into a "past-tense form" the way English `-ed` does -- it simply marks the point where a change became real.',
    ],
    zh: [],
    ru: [],
    tldr: {
      en: ['`{{word:le}}` marks that a change or action reached completion -- not simply "the past."'],
      zh: [],
      ru: [],
    },
    necessity: {
      en: ["This distinction avoids a very common early mistake: treating `{{word:le}}` as English `-ed`. It marks completion, and completion usually happens in the past, but they aren't the same thing."],
      zh: [],
      ru: [],
    },
  },
  {
    type: 'info',
    subtype: 'grammar',
    tag: 'verbs/aspect',
    title: { en: ['The Completion Marker `{{word:le}}`'], zh: [], ru: [] },
    items: [
      {
        text: {
          en: ['Attach `{{word:le}}` after a verb to mark that an action or change has reached completion. `{{word:le}}` marks completion, not tense -- it can describe something finished a moment ago or something expected to be finished by a future point.'],
          zh: [],
          ru: [],
        },
      },
    ],
  },
  {
    type: 'prose',
    en: [
      'One more habit worth noticing: Hao-shuo-de words do not come pre-labeled as "this one is only ever a verb" or "this one is only ever a noun."',
      'The same word slides between roles depending on where it sits in the sentence.',
      '`{{word:chi1}}`, for example, is the action "to eat" when it is doing something in a sentence -- but the very same word, sitting where a noun belongs, means "food."',
      'Nothing about the spelling changes; only the job the word is doing changes.',
      'The same thing happens with `-{{word:de}}`: `{{word:zhi1dao4}}-{{word:de}} {{word:ren2}}` does not build a new word for "someone who knows things" -- it just takes the verb `{{word:zhi1dao4}}` ("to know") and, bound to `{{word:ren2}}` ("person") with `-{{word:de}}`, lets it describe a noun directly, the same way `{{word:xie3}}-{{word:de}} {{word:dong1xi}}` ("a written thing") worked back in Lesson 2.',
    ],
    zh: [],
    ru: [],
    tldr: {
      en: ["The same word shifts between verb and noun roles depending on its position in the sentence -- no separate forms needed."],
      zh: [],
      ru: [],
    },
    necessity: {
      en: ["This is why Hao-shuo-de's small dictionary goes further than its word count suggests -- every verb is already a potential noun, for free."],
      zh: [],
      ru: [],
    },
  },
  {
    type: 'info',
    subtype: 'grammar',
    tag: 'words/category-flexibility',
    title: { en: ['One Word, Several Jobs'], zh: [], ru: [] },
    items: [
      {
        text: {
          en: ["A Hao-shuo-de word's category (verb, noun, etc.) is not fixed -- it's determined by where the word sits in the sentence. The same spelling can act as a verb in one sentence and a noun-describing phrase (via `-{{word:de}}`) in another."],
          zh: [],
          ru: [],
        },
      },
    ],
  },
  {
    type: 'prose',
    en: [
      'Verbs can pick up an extra layer of meaning by binding a small directional word onto them with a hyphen -- the same hyphen that has been doing grammar work since Lesson 1.',
      'Three of these are worth knowing early, all built on `{{word:lai2}}` ("to come"):',
      '',
      '- `{{word:qi3}}-{{word:lai2}}` ("rise-come") marks the start of something. Bound onto another verb the same way, `{{word:qi3}}` alone marks a beginning: `{{word:shuo1}}-{{word:qi3}}` does not just mean "speak" -- it means "bring something up," the moment a topic starts existing in a conversation.',
      '- `{{word:xia4}}-{{word:lai2}}` ("down-come") marks something settling into place, or continuing on steadily from where it already was.',
      '- `{{word:shang4}}-{{word:lai2}}` ("up-come") marks something arriving toward you, or finally succeeding at reaching a point.',
      '',
      'None of this needed a new word class or a new particle.',
      'It is the same hyphen-composition rule from Lesson 1 -- gluing two known pieces into one working unit -- just pointed at direction instead of description.',
    ],
    zh: [],
    ru: [],
    tldr: {
      en: ['`{{word:qi3}}`, `{{word:xia4}}`, and `{{word:shang4}}` bind onto `{{word:lai2}}` (or other verbs) via a hyphen to add direction/completion nuance -- rise, settle, or arrive.'],
      zh: [],
      ru: [],
    },
    necessity: {
      en: ["Extends the hyphen-composition principle from Lesson 1 into a new domain (verb direction), without adding new grammar machinery."],
      zh: [],
      ru: [],
    },
  },
  {
    type: 'info',
    subtype: 'grammar',
    tag: 'verbs/directional-complements',
    title: { en: ['Directional Complements'], zh: [], ru: [] },
    items: [
      {
        text: {
          en: ['`{{word:qi3}}-{{word:lai2}}` -- marks the beginning of an action or state (e.g. `{{word:shuo1}}-{{word:qi3}}`, "bring up/mention")'],
          zh: [],
          ru: [],
        },
      },
      {
        text: {
          en: ['`{{word:xia4}}-{{word:lai2}}` -- marks a state settling into place or continuing on'],
          zh: [],
          ru: [],
        },
      },
      {
        text: {
          en: ['`{{word:shang4}}-{{word:lai2}}` -- marks something arriving toward the speaker, or succeeding at reaching a point'],
          zh: [],
          ru: [],
        },
      },
    ],
  },
  {
    type: 'example',
    pinyin: '{{Word:wo3}} {{word:zhi1dao4}} {{word:hao3}} {{word:shuo1}}-{{word:de}}.',
    ttsText: '我知道好说的。',
    en: ['I know a simple language / good speech.'],
    zh: [],
    ru: [],
  },
  {
    type: 'example',
    pinyin: '{{Word:na4}}-ge {{word:nan2ren2}} {{word:shi4}} {{word:shuo1}}-{{word:de}} {{word:ren2}}.',
    ttsText: '那个男人是说的人。',
    en: ['That man is a messenger / speaking person.'],
    zh: [],
    ru: [],
  },
  {
    type: 'example',
    pinyin: '{{Word:da4}}-{{word:de}} {{word:dong4wu4}} {{word:zai4}} {{word:chi1}} {{word:ni3}}.',
    ttsText: '大的动物在吃你。',
    en: ['A large animal is eating you.'],
    zh: [],
    ru: [],
  },
  {
    type: 'example',
    pinyin: '{{Word:qun2}}-{{word:de}} {{word:xie3}}-{{word:de}} {{word:dong1xi}} {{word:hen3}} {{word:hao3}}.',
    ttsText: '群的写的东西很好。',
    en: ["The community's book is reliable."],
    zh: [],
    ru: [],
  },
  {
    type: 'example',
    pinyin: '{{Word:ni3}} {{word:zuo4}} {{word:le}} {{word:xin1}}-{{word:de}} {{word:chi1}}.',
    ttsText: '你做了新的吃。',
    en: ['You made new food.'],
    zh: [],
    ru: [],
  },
  {
    type: 'example',
    pinyin: '{{Word:zhi1dao4}}-{{word:de}} {{word:ren2}} {{word:ting1}}.',
    ttsText: '知道的人听。',
    en: ['A person of knowledge listens.'],
    zh: [],
    ru: [],
  },
  {
    type: 'example',
    pinyin: '{{Word:zhi1dao4}}-{{word:de}} {{word:di4fang1}} {{word:you3}} {{word:xie3}}-{{word:de}} {{word:dong1xi}}.',
    ttsText: '知道的地方有写的东西。',
    en: ['The school / house of knowledge has books.'],
    zh: [],
    ru: [],
  },
  {
    type: 'example',
    pinyin: '{{Word:ta1}} {{word:shuo1}}-{{word:qi3}} Hǎo-shuō-de.',
    ttsText: '他说起好说的。',
    en: ['He brings up Hao-shuo-de / mentions Hao-shuo-de.'],
    zh: [],
    ru: [],
  },
  {
    type: 'exercise',
    en: ['I will listen to you.'],
    zh: [],
    ru: [],
  },
  {
    type: 'exercise',
    en: ['The woman obeyed the man.'],
    zh: [],
    ru: [],
  },
  {
    type: 'exercise',
    en: ['The friends ate meat.'],
    zh: [],
    ru: [],
  },
  {
    type: 'exercise',
    en: ['She mentions the community.'],
    zh: [],
    ru: [],
  },
  {
    type: 'answer',
    en: ['{{Word:wo3}} {{word:ting1}} {{word:ni3}}.'],
    zh: [],
    ru: [],
    ttsText: '我听你。',
  },
  {
    type: 'answer',
    en: ['{{Word:nv3ren2}} {{word:ting1}} {{word:le}} {{word:nan2ren2}}.'],
    zh: [],
    ru: [],
    ttsText: '女人听了男人。',
  },
  {
    type: 'answer',
    en: ['{{Word:hao3}}-{{word:de}} {{word:ren2}} {{word:chi1}} {{word:le}} {{word:dong4wu4}}.'],
    zh: [],
    ru: [],
    ttsText: '好的人吃了动物。',
  },
  {
    type: 'answer',
    en: ['{{Word:ta1}} {{word:shuo1}}-{{word:qi3}} {{word:qun2}}.'],
    zh: [],
    ru: [],
    ttsText: '她说起群。',
  },
];

export default content;
