// Russian text for lesson-06, matching shape.ts's keys. Typed as
// `PartialByKey<LessonShape>`.
// Not translated yet -- every `ru` is the empty-array placeholder.
import type { PartialByKey } from "../../lib/chapter-shape-types.ts";
import type { LessonShape } from "./shape.ts";

const ru: PartialByKey<LessonShape> = {
  title: { ru: [] },
  summary: { ru: [] },
  vocabShenme: { ru: [] },
  vocabMa: { ru: [] },
  vocabWeishenme: { ru: [] },
  vocabZenme: { ru: [] },
  vocabWen: { ru: [] },
  vocabZhao: { ru: [] },
  vocabGongju: { ru: [] },
  vocabHezi: { ru: [] },
  proseYesNo: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleYesNo1: { ru: [] },
  exampleYesNo2: { ru: [] },
  exampleYesNo3: { ru: [] },
  exampleYesNo4: { ru: [] },
  exampleYesNo5: { ru: [] },
  proseWhat: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleWhat1: { ru: [] },
  exampleWhat2: { ru: [] },
  exampleWhat3: { ru: [] },
  exampleWhat4: { ru: [] },
  exampleWhat5: { ru: [] },
  proseWhyHow: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleWhyHow1: { ru: [] },
  exampleWhyHow2: { ru: [] },
  exampleWhyHow3: { ru: [] },
  exampleWhyHow4: { ru: [] },
  exampleWhyHow5: { ru: [] },
  exampleWhyHow6: { ru: [] },
  proseAnswer: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleAnswer1: { ru: [] },
  exampleAnswer2: { ru: [] },
  exampleAnswer3: { ru: [] },
  exampleAnswer4: { ru: [] },
  infoAskingQuestions: {
    title: { ru: [] },
    items: [
      { ru: [] },
      { ru: [] },
      { ru: [] },
      { ru: [] },
      { ru: [] },
    ],
  },
  exercise1: { ru: [] },
  exercise2: { ru: [] },
  exercise3: { ru: [] },
  exercise4: { ru: [] },
  exercise5: { ru: [] },
  exercise6: { ru: [] },
  exercise7: { ru: [] },
  answer1: { ru: [] },
  answer2: { ru: [] },
  answer3: { ru: [] },
  answer4: { ru: [] },
  answer5: { ru: [] },
  answer6: { ru: [] },
  answer7: { ru: [] },
};

export default ru;
