// Chinese text for lesson-06, matching shape.ts's keys. Typed as
// `PartialByKey<LessonShape>`.
// Not translated yet -- every `zh` is the empty-array placeholder.
import type { PartialByKey } from "../../lib/chapter-shape-types.ts";
import type { LessonShape } from "./shape.ts";

const zh: PartialByKey<LessonShape> = {
  title: { zh: [] },
  summary: { zh: [] },
  vocabMa: { zh: [] },
  vocabGongju: { zh: [] },
  vocabHezi: { zh: [] },
  proseYesNo: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleYesNo1: { zh: [] },
  exampleYesNo2: { zh: [] },
  exampleYesNo3: { zh: [] },
  exampleYesNo4: { zh: [] },
  exampleYesNo5: { zh: [] },
  vocabShenme: { zh: [] },
  vocabWen: { zh: [] },
  vocabZhao: { zh: [] },
  proseWhat: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleWhat1: { zh: [] },
  exampleWhat2: { zh: [] },
  exampleWhat3: { zh: [] },
  exampleWhat4: { zh: [] },
  exampleWhat5: { zh: [] },
  vocabWeishenme: { zh: [] },
  vocabZenme: { zh: [] },
  proseWhyHow: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleWhyHow1: { zh: [] },
  exampleWhyHow2: { zh: [] },
  exampleWhyHow3: { zh: [] },
  exampleWhyHow4: { zh: [] },
  exampleWhyHow5: { zh: [] },
  exampleWhyHow6: { zh: [] },
  proseAnswer: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleAnswer1: { zh: [] },
  exampleAnswer2: { zh: [] },
  exampleAnswer3: { zh: [] },
  infoAskingQuestions: {
    title: { zh: [] },
    items: [
      { zh: [] },
      { zh: [] },
      { zh: [] },
      { zh: [] },
      { zh: [] },
    ],
  },
  exercise1: { zh: [] },
  exercise2: { zh: [] },
  exercise3: { zh: [] },
  exercise4: { zh: [] },
  exercise5: { zh: [] },
  exercise6: { zh: [] },
  exercise7: { zh: [] },
  answer1: { zh: [] },
  answer2: { zh: [] },
  answer3: { zh: [] },
  answer4: { zh: [] },
  answer5: { zh: [] },
  answer6: { zh: [] },
  answer7: { zh: [] },
  faqMaAndVerbBuVerb: { question: { zh: [] }, zh: [] },
  faqYouMeiYou: { question: { zh: [] }, zh: [] },
  faqWeishenmeFirst: { question: { zh: [] }, zh: [] },
};

export default zh;
