// Russian text for lesson-11, matching shape.ts's keys. Typed as
// `PartialByKey<LessonShape>`.
// Not translated yet -- every `ru` is the empty-array placeholder.
import type { PartialByKey } from "../../lib/chapter-shape-types.ts";
import type { LessonShape } from "./shape.ts";

const ru: PartialByKey<LessonShape> = {
  title: { ru: [] },
  summary: { ru: [] },
  vocabCong: { ru: [] },
  vocabLai: { ru: [] },
  vocabQu: { ru: [] },
  vocabQi: { ru: [] },
  vocabWai: { ru: [] },
  vocabShichang: { ru: [] },
  vocabKou: { ru: [] },
  vocabDao: { ru: [] },
  proseComeGo: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleComeGo1: { ru: [] },
  exampleComeGo2: { ru: [] },
  exampleComeGo3: { ru: [] },
  exampleComeGo4: { ru: [] },
  exampleComeGo5: { ru: [] },
  exampleComeGo6: { ru: [] },
  exampleComeGo7: { ru: [] },
  proseFrom: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleFrom1: { ru: [] },
  exampleFrom2: { ru: [] },
  exampleFrom3: { ru: [] },
  exampleFrom4: { ru: [] },
  proseArrive: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleArrive1: { ru: [] },
  exampleArrive2: { ru: [] },
  exampleArrive3: { ru: [] },
  proseDirection: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleDirection1: { ru: [] },
  exampleDirection2: { ru: [] },
  exampleDirection3: { ru: [] },
  exampleDirection4: { ru: [] },
  exampleDirection5: { ru: [] },
  exampleDirection6: { ru: [] },
  exampleDirection7: { ru: [] },
  exampleDirection8: { ru: [] },
  exampleDirection9: { ru: [] },
  infoComingAndGoing: {
    title: { ru: [] },
    items: [{ ru: [] }, { ru: [] }, { ru: [] }, { ru: [] }],
  },
  exercise1: { ru: [] },
  exercise2: { ru: [] },
  exercise3: { ru: [] },
  exercise4: { ru: [] },
  exercise5: { ru: [] },
  exercise6: { ru: [] },
  exercise7: { ru: [] },
  answer1: { ru: [] },
  answer2: { ru: [] },
  answer3: { ru: [] },
  answer4: { ru: [] },
  answer5: { ru: [] },
  answer6: { ru: [] },
  answer7: { ru: [] },
};

export default ru;
