// Russian text for lesson-11, matching shape.ts's keys. Typed as
// `PartialByKey<LessonShape>`.
// Not translated yet -- every `ru` is the empty-array placeholder.
import type { PartialByKey } from "../../lib/chapter-shape-types.ts";
import type { LessonShape } from "./shape.ts";

const ru: PartialByKey<LessonShape> = {
  title: { ru: [] },
  summary: { ru: [] },
  vocabLai: { ru: [] },
  vocabQu: { ru: [] },
  vocabShichang: { ru: [] },
  proseComeGo: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleComeGo1: { ru: [] },
  exampleComeGo2: { ru: [] },
  exampleComeGo3: { ru: [] },
  exampleComeGo4: { ru: [] },
  exampleComeGo5: { ru: [] },
  exampleComeGo6: { ru: [] },
  exampleComeGo7: { ru: [] },
  exampleComeGo8: { ru: [] },
  exampleComeGo9: { ru: [] },
  vocabCong: { ru: [] },
  proseFrom: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleFrom1: { ru: [] },
  exampleFrom2: { ru: [] },
  exampleFrom3: { ru: [] },
  exampleFrom4: { ru: [] },
  vocabDao: { ru: [] },
  proseArrive: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleArrive1: { ru: [] },
  exampleArrive2: { ru: [] },
  exampleArrive3: { ru: [] },
  vocabQi: { ru: [] },
  vocabWai: { ru: [] },
  vocabKou: { ru: [] },
  proseDirection: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleDirection1: { ru: [] },
  exampleDirection2: { ru: [] },
  exampleDirection3: { ru: [] },
  exampleDirection4: { ru: [] },
  exampleDirection5: { ru: [] },
  exampleDirection6: { ru: [] },
  exampleDirection7: { ru: [] },
  exampleDirection8: { ru: [] },
  exampleDirection9: { ru: [] },
  vocabDong: { ru: [] },
  proseMove: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleMove1: { ru: [] },
  exampleMove2: { ru: [] },
  exampleMove3: { ru: [] },
  exampleMove4: { ru: [] },
  vocabYuan: { ru: [] },
  vocabJin: { ru: [] },
  proseFar: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleFar1: { ru: [] },
  exampleFar2: { ru: [] },
  exampleFar3: { ru: [] },
  exampleFar4: { ru: [] },
  exampleFar5: { ru: [] },
  infoComingAndGoing: {
    title: { ru: [] },
    items: [
      { ru: [] },
      { ru: [] },
      { ru: [] },
      { ru: [] },
      { ru: [] },
      { ru: [] },
    ],
  },
  exercise1: { ru: [] },
  exercise2: { ru: [] },
  exercise3: { ru: [] },
  exercise4: { ru: [] },
  exercise5: { ru: [] },
  exercise6: { ru: [] },
  exercise7: { ru: [] },
  exercise8: { ru: [] },
  exercise9: { ru: [] },
  exercise10: { ru: [] },
  answer1: { ru: [] },
  answer2: { ru: [] },
  answer3: { ru: [] },
  answer4: { ru: [] },
  answer5: { ru: [] },
  answer6: { ru: [] },
  answer7: { ru: [] },
  answer8: { ru: [] },
  answer9: { ru: [] },
  answer10: { ru: [] },
  faqDaoOrQu: { question: { ru: [] }, ru: [] },
  faqCongOrder: { question: { ru: [] }, ru: [] },
  faqLaiOrQu: { question: { ru: [] }, ru: [] },
};

export default ru;
