// Chinese text for lesson-11, matching shape.ts's keys. Typed as
// `PartialByKey<LessonShape>`.
// Not translated yet -- every `zh` is the empty-array placeholder.
import type { PartialByKey } from "../../lib/chapter-shape-types.ts";
import type { LessonShape } from "./shape.ts";

const zh: PartialByKey<LessonShape> = {
  title: { zh: [] },
  summary: { zh: [] },
  vocabLai: { zh: [] },
  vocabQu: { zh: [] },
  vocabShichang: { zh: [] },
  proseComeGo: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleComeGo1: { zh: [] },
  exampleComeGo2: { zh: [] },
  exampleComeGo3: { zh: [] },
  exampleComeGo4: { zh: [] },
  exampleComeGo5: { zh: [] },
  exampleComeGo6: { zh: [] },
  exampleComeGo7: { zh: [] },
  exampleComeGo8: { zh: [] },
  exampleComeGo9: { zh: [] },
  vocabCong: { zh: [] },
  proseFrom: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleFrom1: { zh: [] },
  exampleFrom2: { zh: [] },
  exampleFrom3: { zh: [] },
  exampleFrom4: { zh: [] },
  vocabDao: { zh: [] },
  proseArrive: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleArrive1: { zh: [] },
  exampleArrive2: { zh: [] },
  exampleArrive3: { zh: [] },
  vocabQi: { zh: [] },
  vocabWai: { zh: [] },
  vocabKou: { zh: [] },
  proseDirection: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleDirection1: { zh: [] },
  exampleDirection2: { zh: [] },
  exampleDirection3: { zh: [] },
  exampleDirection4: { zh: [] },
  exampleDirection5: { zh: [] },
  exampleDirection6: { zh: [] },
  exampleDirection7: { zh: [] },
  exampleDirection8: { zh: [] },
  exampleDirection9: { zh: [] },
  vocabDong: { zh: [] },
  proseMove: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleMove1: { zh: [] },
  exampleMove2: { zh: [] },
  exampleMove3: { zh: [] },
  exampleMove4: { zh: [] },
  vocabYuan: { zh: [] },
  vocabJin: { zh: [] },
  proseFar: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleFar1: { zh: [] },
  exampleFar2: { zh: [] },
  exampleFar3: { zh: [] },
  exampleFar4: { zh: [] },
  exampleFar5: { zh: [] },
  infoComingAndGoing: {
    title: { zh: [] },
    items: [
      { zh: [] },
      { zh: [] },
      { zh: [] },
      { zh: [] },
      { zh: [] },
      { zh: [] },
    ],
  },
  exercise1: { zh: [] },
  exercise2: { zh: [] },
  exercise3: { zh: [] },
  exercise4: { zh: [] },
  exercise5: { zh: [] },
  exercise6: { zh: [] },
  exercise7: { zh: [] },
  exercise8: { zh: [] },
  exercise9: { zh: [] },
  exercise10: { zh: [] },
  answer1: { zh: [] },
  answer2: { zh: [] },
  answer3: { zh: [] },
  answer4: { zh: [] },
  answer5: { zh: [] },
  answer6: { zh: [] },
  answer7: { zh: [] },
  answer8: { zh: [] },
  answer9: { zh: [] },
  answer10: { zh: [] },
};

export default zh;
