// GENERATED by scripts/build-data.js from the files in this folder -- don't edit.
// Add or delete a file instead; `npm run data` (or the dev server) rewrites this list.
import w0 from "./ai4.ts";
import w1 from "./ba1.ts";
import w2 from "./ba3.ts";
import w3 from "./ba4ba.ts";
import w4 from "./bai2.ts";
import w5 from "./bang1.ts";
import w6 from "./bao1.ts";
import w7 from "./bi2zi.ts";
import w8 from "./bi3.ts";
import w9 from "./bian1.ts";
import w10 from "./bian4.ts";
import w11 from "./bie2.ts";
import w12 from "./bu4.ts";
import w13 from "./chang2.ts";
import w14 from "./che1.ts";
import w15 from "./chi1.ts";
import w16 from "./chu1.ts";
import w17 from "./ci2.ts";
import w18 from "./ci4.ts";
import w19 from "./cong2.ts";
import w20 from "./da3.ts";
import w21 from "./da4.ts";
import w22 from "./dan4.ts";
import w23 from "./dao4.ts";
import w24 from "./de.ts";
import w25 from "./de2.ts";
import w26 from "./deng1.ts";
import w27 from "./deng3.ts";
import w28 from "./di4.ts";
import w29 from "./dian3.ts";
import w30 from "./ding4.ts";
import w31 from "./dong1.ts";
import w32 from "./dong4.ts";
import w33 from "./dou1.ts";
import w34 from "./dui4.ts";
import w35 from "./duo1.ts";
import w36 from "./er3duo.ts";
import w37 from "./er4.ts";
import w38 from "./fa1.ts";
import w39 from "./fa3.ts";
import w40 from "./fan4.ts";
import w41 from "./fang1.ts";
import w42 from "./fang2.ts";
import w43 from "./fang4.ts";
import w44 from "./fei1.ts";
import w45 from "./fen1.ts";
import w46 from "./fu4jin4.ts";
import w47 from "./gan1jing4.ts";
import w48 from "./gao1.ts";
import w49 from "./ge4.ts";
import w50 from "./gei3.ts";
import w51 from "./gong1.ts";
import w52 from "./guan1.ts";
import w53 from "./guan1xi.ts";
import w54 from "./guo2.ts";
import w55 from "./guo3.ts";
import w56 from "./guo4.ts";
import w57 from "./hai2.ts";
import w58 from "./hao3.ts";
import w59 from "./hao4.ts";
import w60 from "./he1.ts";
import w61 from "./he2.ts";
import w62 from "./hei1.ts";
import w63 from "./hen3.ts";
import w64 from "./hong2.ts";
import w65 from "./hou4.ts";
import w66 from "./hua4.ts";
import w67 from "./huai4.ts";
import w68 from "./huang2.ts";
import w69 from "./hui2.ts";
import w70 from "./hui4.ts";
import w71 from "./huo2.ts";
import w72 from "./huo3.ts";
import w73 from "./huo4.ts";
import w74 from "./ji1.ts";
import w75 from "./jia1.ts";
import w76 from "./jia4zhi2.ts";
import w77 from "./jian1.ts";
import w78 from "./jian4.ts";
import w79 from "./jiao3.ts";
import w80 from "./jiao4.ts";
import w81 from "./jin1.ts";
import w82 from "./jin4.ts";
import w83 from "./jiu3.ts";
import w84 from "./jiu4.ts";
import w85 from "./ju4.ts";
import w86 from "./jue2.ts";
import w87 from "./kai1.ts";
import w88 from "./kai1shi3.ts";
import w89 from "./kan4.ts";
import w90 from "./ke3.ts";
import w91 from "./kong1.ts";
import w92 from "./kou3.ts";
import w93 from "./kuai4.ts";
import w94 from "./lai2.ts";
import w95 from "./lan2.ts";
import w96 from "./lao3.ts";
import w97 from "./le.ts";
import w98 from "./leng3.ts";
import w99 from "./li3.ts";
import w100 from "./li4.ts";
import w101 from "./liang3.ts";
import w102 from "./ling2.ts";
import w103 from "./liu2.ts";
import w104 from "./liu4.ts";
import w105 from "./lu4.ts";
import w106 from "./luan4.ts";
import w107 from "./ma.ts";
import w108 from "./ma1ma.ts";
import w109 from "./mai3.ts";
import w110 from "./mao2.ts";
import w111 from "./mei2.ts";
import w112 from "./men.ts";
import w113 from "./men2.ts";
import w114 from "./mian4.ts";
import w115 from "./ming2.ts";
import w116 from "./mo1.ts";
import w117 from "./na2.ts";
import w118 from "./na3.ts";
import w119 from "./na4.ts";
import w120 from "./nan2.ts";
import w121 from "./neng2.ts";
import w122 from "./ni3.ts";
import w123 from "./nian2.ts";
import w124 from "./nv3.ts";
import w125 from "./pa4.ts";
import w126 from "./pang2bian1.ts";
import w127 from "./qi1.ts";
import w128 from "./qi3.ts";
import w129 from "./qi4.ts";
import w130 from "./qian2.ts";
import w131 from "./qu4.ts";
import w132 from "./rang4.ts";
import w133 from "./re4.ts";
import w134 from "./ren2.ts";
import w135 from "./ri4.ts";
import w136 from "./ru2guo3.ts";
import w137 from "./san1.ts";
import w138 from "./se4.ts";
import w139 from "./shang4.ts";
import w140 from "./shao3.ts";
import w141 from "./shei2.ts";
import w142 from "./shen1ti3.ts";
import w143 from "./shen2me.ts";
import w144 from "./sheng1.ts";
import w145 from "./sheng1yin1.ts";
import w146 from "./shi2.ts";
import w147 from "./shi4.ts";
import w148 from "./shou3.ts";
import w149 from "./shu1.ts";
import w150 from "./shui3.ts";
import w151 from "./shui4jiao4.ts";
import w152 from "./shuo1.ts";
import w153 from "./si3.ts";
import w154 from "./si4.ts";
import w155 from "./suan4.ts";
import w156 from "./ta1.ts";
import w157 from "./tang3.ts";
import w158 from "./ti2.ts";
import w159 from "./tian1.ts";
import w160 from "./tian2.ts";
import w161 from "./ting1.ts";
import w162 from "./tong1.ts";
import w163 from "./tong2.ts";
import w164 from "./tou2.ts";
import w165 from "./wai4.ts";
import w166 from "./wan2.ts";
import w167 from "./wan2r.ts";
import w168 from "./wan3.ts";
import w169 from "./wang3.ts";
import w170 from "./wei4.ts";
import w171 from "./wen4.ts";
import w172 from "./wo3.ts";
import w173 from "./wu3.ts";
import w174 from "./wu4.ts";
import w175 from "./xi1.ts";
import w176 from "./xia4.ts";
import w177 from "./xian4.ts";
import w178 from "./xiang3.ts";
import w179 from "./xiao3.ts";
import w180 from "./xiao4.ts";
import w181 from "./xie1.ts";
import w182 from "./xie3.ts";
import w183 from "./xie4.ts";
import w184 from "./xin1.ts";
import w185 from "./xue2.ts";
import w186 from "./yan2se4.ts";
import w187 from "./yan3jing.ts";
import w188 from "./yang4.ts";
import w189 from "./yao4.ts";
import w190 from "./ye3.ts";
import w191 from "./yi1.ts";
import w192 from "./yi1fu.ts";
import w193 from "./yi3.ts";
import w194 from "./yin1wei4.ts";
import w195 from "./ying4.ts";
import w196 from "./yong4.ts";
import w197 from "./you3.ts";
import w198 from "./you4.ts";
import w199 from "./yuan2.ts";
import w200 from "./yuan3.ts";
import w201 from "./yue4.ts";
import w202 from "./zai4.ts";
import w203 from "./zen3me.ts";
import w204 from "./zhan4.ts";
import w205 from "./zhao3.ts";
import w206 from "./zhe3.ts";
import w207 from "./zhe4.ts";
import w208 from "./zhen1.ts";
import w209 from "./zhi1dao4.ts";
import w210 from "./zhi2wu4.ts";
import w211 from "./zhi3.ts";
import w212 from "./zhong1.ts";
import w213 from "./zhong3.ts";
import w214 from "./zhong4.ts";
import w215 from "./zi.ts";
import w216 from "./zi4.ts";
import w217 from "./zou3.ts";
import w218 from "./zui4.ts";
import w219 from "./zuo3.ts";
import w220 from "./zuo4.ts";

export const WORDS = {
  "ai4": w0,
  "ba1": w1,
  "ba3": w2,
  "ba4ba": w3,
  "bai2": w4,
  "bang1": w5,
  "bao1": w6,
  "bi2zi": w7,
  "bi3": w8,
  "bian1": w9,
  "bian4": w10,
  "bie2": w11,
  "bu4": w12,
  "chang2": w13,
  "che1": w14,
  "chi1": w15,
  "chu1": w16,
  "ci2": w17,
  "ci4": w18,
  "cong2": w19,
  "da3": w20,
  "da4": w21,
  "dan4": w22,
  "dao4": w23,
  "de": w24,
  "de2": w25,
  "deng1": w26,
  "deng3": w27,
  "di4": w28,
  "dian3": w29,
  "ding4": w30,
  "dong1": w31,
  "dong4": w32,
  "dou1": w33,
  "dui4": w34,
  "duo1": w35,
  "er3duo": w36,
  "er4": w37,
  "fa1": w38,
  "fa3": w39,
  "fan4": w40,
  "fang1": w41,
  "fang2": w42,
  "fang4": w43,
  "fei1": w44,
  "fen1": w45,
  "fu4jin4": w46,
  "gan1jing4": w47,
  "gao1": w48,
  "ge4": w49,
  "gei3": w50,
  "gong1": w51,
  "guan1": w52,
  "guan1xi": w53,
  "guo2": w54,
  "guo3": w55,
  "guo4": w56,
  "hai2": w57,
  "hao3": w58,
  "hao4": w59,
  "he1": w60,
  "he2": w61,
  "hei1": w62,
  "hen3": w63,
  "hong2": w64,
  "hou4": w65,
  "hua4": w66,
  "huai4": w67,
  "huang2": w68,
  "hui2": w69,
  "hui4": w70,
  "huo2": w71,
  "huo3": w72,
  "huo4": w73,
  "ji1": w74,
  "jia1": w75,
  "jia4zhi2": w76,
  "jian1": w77,
  "jian4": w78,
  "jiao3": w79,
  "jiao4": w80,
  "jin1": w81,
  "jin4": w82,
  "jiu3": w83,
  "jiu4": w84,
  "ju4": w85,
  "jue2": w86,
  "kai1": w87,
  "kai1shi3": w88,
  "kan4": w89,
  "ke3": w90,
  "kong1": w91,
  "kou3": w92,
  "kuai4": w93,
  "lai2": w94,
  "lan2": w95,
  "lao3": w96,
  "le": w97,
  "leng3": w98,
  "li3": w99,
  "li4": w100,
  "liang3": w101,
  "ling2": w102,
  "liu2": w103,
  "liu4": w104,
  "lu4": w105,
  "luan4": w106,
  "ma": w107,
  "ma1ma": w108,
  "mai3": w109,
  "mao2": w110,
  "mei2": w111,
  "men": w112,
  "men2": w113,
  "mian4": w114,
  "ming2": w115,
  "mo1": w116,
  "na2": w117,
  "na3": w118,
  "na4": w119,
  "nan2": w120,
  "neng2": w121,
  "ni3": w122,
  "nian2": w123,
  "nv3": w124,
  "pa4": w125,
  "pang2bian1": w126,
  "qi1": w127,
  "qi3": w128,
  "qi4": w129,
  "qian2": w130,
  "qu4": w131,
  "rang4": w132,
  "re4": w133,
  "ren2": w134,
  "ri4": w135,
  "ru2guo3": w136,
  "san1": w137,
  "se4": w138,
  "shang4": w139,
  "shao3": w140,
  "shei2": w141,
  "shen1ti3": w142,
  "shen2me": w143,
  "sheng1": w144,
  "sheng1yin1": w145,
  "shi2": w146,
  "shi4": w147,
  "shou3": w148,
  "shu1": w149,
  "shui3": w150,
  "shui4jiao4": w151,
  "shuo1": w152,
  "si3": w153,
  "si4": w154,
  "suan4": w155,
  "ta1": w156,
  "tang3": w157,
  "ti2": w158,
  "tian1": w159,
  "tian2": w160,
  "ting1": w161,
  "tong1": w162,
  "tong2": w163,
  "tou2": w164,
  "wai4": w165,
  "wan2": w166,
  "wan2r": w167,
  "wan3": w168,
  "wang3": w169,
  "wei4": w170,
  "wen4": w171,
  "wo3": w172,
  "wu3": w173,
  "wu4": w174,
  "xi1": w175,
  "xia4": w176,
  "xian4": w177,
  "xiang3": w178,
  "xiao3": w179,
  "xiao4": w180,
  "xie1": w181,
  "xie3": w182,
  "xie4": w183,
  "xin1": w184,
  "xue2": w185,
  "yan2se4": w186,
  "yan3jing": w187,
  "yang4": w188,
  "yao4": w189,
  "ye3": w190,
  "yi1": w191,
  "yi1fu": w192,
  "yi3": w193,
  "yin1wei4": w194,
  "ying4": w195,
  "yong4": w196,
  "you3": w197,
  "you4": w198,
  "yuan2": w199,
  "yuan3": w200,
  "yue4": w201,
  "zai4": w202,
  "zen3me": w203,
  "zhan4": w204,
  "zhao3": w205,
  "zhe3": w206,
  "zhe4": w207,
  "zhen1": w208,
  "zhi1dao4": w209,
  "zhi2wu4": w210,
  "zhi3": w211,
  "zhong1": w212,
  "zhong3": w213,
  "zhong4": w214,
  "zi": w215,
  "zi4": w216,
  "zou3": w217,
  "zui4": w218,
  "zuo3": w219,
  "zuo4": w220,
};

export type WordId = keyof typeof WORDS;
