// Russian text for inside-a-sentence, matching shape.ts's keys. Typed as
// `PartialByKey<LessonShape>`.
// Not translated yet -- every `ru` is the empty-array placeholder.
import type { PartialByKey } from "../../../lib/chapter-shape-types.ts";
import type { LessonShape } from "./shape.ts";

const ru: PartialByKey<LessonShape> = {
  title: { ru: [] },
  summary: { ru: [] },
  vocabGei: { ru: [] },
  proseGive: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleGive1: { ru: [] },
  exampleGive2: { ru: [] },
  exampleGive3: { ru: [] },
  exampleGive5: { ru: [] },
  exampleGive6: { ru: [] },
  exampleGive7: { ru: [] },
  exampleGive8: { ru: [] },
  exampleGive9: { ru: [] },
  vocabYong: { ru: [] },
  vocabMo: { ru: [] },
  vocabDa: { ru: [] },
  proseWith: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleWith1: { ru: [] },
  exampleWith2: { ru: [] },
  exampleWith4: { ru: [] },
  exampleWith6: { ru: [] },
  exampleWith8: { ru: [] },
  exampleWith9: { ru: [] },
  exampleWith13: { ru: [] },
  exampleWith14: { ru: [] },
  vocabHe: { ru: [] },
  vocabHuozhe: { ru: [] },
  proseAndOr: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleAndOr1: { ru: [] },
  exampleAndOr2: { ru: [] },
  exampleAndOr3: { ru: [] },
  exampleAndOr4: { ru: [] },
  exampleAndOr5: { ru: [] },
  exampleAndOr6: { ru: [] },
  exampleAndOr7: { ru: [] },
  vocabDui: { ru: [] },
  proseToward: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleToward1: { ru: [] },
  exampleToward2: { ru: [] },
  exampleToward3: { ru: [] },
  exampleToward4: { ru: [] },
  vocabQun: { ru: [] },
  proseGroup: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleGroup1: { ru: [] },
  exampleGroup2: { ru: [] },
  exampleGroup3: { ru: [] },
  exampleGroup4: { ru: [] },
  vocabGuanxi: { ru: [] },
  proseRelation: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleRelation1: { ru: [] },
  exampleRelation2: { ru: [] },
  exampleRelation3: { ru: [] },
  exampleRelation4: { ru: [] },
  infoInsideASentence: {
    title: { ru: [] },
    items: [
      { ru: [] },
      { ru: [] },
      { ru: [] },
      { ru: [] },
      { ru: [] },
      { ru: [] },
    ],
  },
  exercise1: { ru: [] },
  exercise2: { ru: [] },
  exercise3: { ru: [] },
  exercise4: { ru: [] },
  exercise5: { ru: [] },
  exercise6: { ru: [] },
  exercise7: { ru: [] },
  exercise8: { ru: [] },
  exercise9: { ru: [] },
  exercise10: { ru: [] },
  answer1: { ru: [] },
  answer2: { ru: [] },
  answer3: { ru: [] },
  answer4: { ru: [] },
  answer5: { ru: [] },
  answer6: { ru: [] },
  answer7: { ru: [] },
  answer8: { ru: [] },
  answer9: { ru: [] },
  answer10: { ru: [] },
  faqAndSentences: { question: { ru: [] }, ru: [] },
  faqGeiForOrTo: { question: { ru: [] }, ru: [] },
  faqHuozheQuestion: { question: { ru: [] }, ru: [] },
};

export default ru;
