// Chinese text for inside-a-sentence, matching shape.ts's keys. Typed as
// `PartialByKey<LessonShape>`.
// Not translated yet -- every `zh` is the empty-array placeholder.
import type { PartialByKey } from "../../../lib/chapter-shape-types.ts";
import type { LessonShape } from "./shape.ts";

const zh: PartialByKey<LessonShape> = {
  title: { zh: [] },
  summary: { zh: [] },
  vocabGei: { zh: [] },
  proseGive: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleGive1: { zh: [] },
  exampleGive2: { zh: [] },
  exampleGive3: { zh: [] },
  exampleGive5: { zh: [] },
  exampleGive6: { zh: [] },
  exampleGive7: { zh: [] },
  exampleGive8: { zh: [] },
  exampleGive9: { zh: [] },
  vocabYong: { zh: [] },
  vocabMo: { zh: [] },
  vocabDa: { zh: [] },
  proseWith: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleWith1: { zh: [] },
  exampleWith2: { zh: [] },
  exampleWith4: { zh: [] },
  exampleWith6: { zh: [] },
  exampleWith8: { zh: [] },
  exampleWith9: { zh: [] },
  exampleWith13: { zh: [] },
  exampleWith14: { zh: [] },
  vocabHe: { zh: [] },
  vocabHuozhe: { zh: [] },
  proseAndOr: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleAndOr1: { zh: [] },
  exampleAndOr2: { zh: [] },
  exampleAndOr3: { zh: [] },
  exampleAndOr4: { zh: [] },
  exampleAndOr5: { zh: [] },
  exampleAndOr6: { zh: [] },
  exampleAndOr7: { zh: [] },
  vocabDui: { zh: [] },
  proseToward: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleToward1: { zh: [] },
  exampleToward2: { zh: [] },
  exampleToward3: { zh: [] },
  exampleToward4: { zh: [] },
  vocabQun: { zh: [] },
  proseGroup: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleGroup1: { zh: [] },
  exampleGroup2: { zh: [] },
  exampleGroup3: { zh: [] },
  exampleGroup4: { zh: [] },
  vocabGuanxi: { zh: [] },
  proseRelation: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleRelation1: { zh: [] },
  exampleRelation2: { zh: [] },
  exampleRelation3: { zh: [] },
  exampleRelation4: { zh: [] },
  infoInsideASentence: {
    title: { zh: [] },
    items: [
      { zh: [] },
      { zh: [] },
      { zh: [] },
      { zh: [] },
      { zh: [] },
      { zh: [] },
    ],
  },
  exercise1: { zh: [] },
  exercise2: { zh: [] },
  exercise3: { zh: [] },
  exercise4: { zh: [] },
  exercise5: { zh: [] },
  exercise6: { zh: [] },
  exercise7: { zh: [] },
  exercise8: { zh: [] },
  exercise9: { zh: [] },
  exercise10: { zh: [] },
  answer1: { zh: [] },
  answer2: { zh: [] },
  answer3: { zh: [] },
  answer4: { zh: [] },
  answer5: { zh: [] },
  answer6: { zh: [] },
  answer7: { zh: [] },
  answer8: { zh: [] },
  answer9: { zh: [] },
  answer10: { zh: [] },
  faqAndSentences: { question: { zh: [] }, zh: [] },
  faqGeiForOrTo: { question: { zh: [] }, zh: [] },
  faqHuozheQuestion: { question: { zh: [] }, zh: [] },
};

export default zh;
