// Russian text for linking-sentences, matching shape.ts's keys. Typed as
// `PartialByKey<LessonShape>`.
// Not translated yet -- every `ru` is the empty-array placeholder.
import type { PartialByKey } from "../../../lib/chapter-shape-types.ts";
import type { LessonShape } from "./shape.ts";

const ru: PartialByKey<LessonShape> = {
  title: { ru: [] },
  summary: { ru: [] },
  vocabYinwei: { ru: [] },
  vocabSi: { ru: [] },
  vocabHuo: { ru: [] },
  proseBecause: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleBecause1: { ru: [] },
  exampleBecause2: { ru: [] },
  exampleBecause3: { ru: [] },
  exampleBecause4: { ru: [] },
  exampleBecause5: { ru: [] },
  exampleBecause6: { ru: [] },
  exampleBecause7: { ru: [] },
  exampleBecause8: { ru: [] },
  exampleBecause9: { ru: [] },
  exampleBecause10: { ru: [] },
  exampleBecause11: { ru: [] },
  exampleBecause12: { ru: [] },
  vocabDanshi: { ru: [] },
  proseBut: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleBut1: { ru: [] },
  exampleBut2: { ru: [] },
  exampleBut3: { ru: [] },
  exampleBut4: { ru: [] },
  exampleBut5: { ru: [] },
  exampleBut6: { ru: [] },
  exampleBut7: { ru: [] },
  exampleBut8: { ru: [] },
  exampleBut9: { ru: [] },
  exampleBut10: { ru: [] },
  vocabRuguo: { ru: [] },
  proseIf: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleIf1: { ru: [] },
  exampleIf2: { ru: [] },
  exampleIf3: { ru: [] },
  exampleIf4: { ru: [] },
  exampleIf5: { ru: [] },
  exampleIf6: { ru: [] },
  exampleIf7: { ru: [] },
  exampleIf8: { ru: [] },
  exampleIf9: { ru: [] },
  exampleIf10: { ru: [] },
  infoLinkingSentences: {
    title: { ru: [] },
    items: [{ ru: [] }, { ru: [] }, { ru: [] }],
  },
  exercise1: { ru: [] },
  exercise2: { ru: [] },
  exercise3: { ru: [] },
  exercise4: { ru: [] },
  exercise5: { ru: [] },
  exercise6: { ru: [] },
  exercise7: { ru: [] },
  answer1: { ru: [] },
  answer2: { ru: [] },
  answer3: { ru: [] },
  answer4: { ru: [] },
  answer5: { ru: [] },
  answer6: { ru: [] },
  answer7: { ru: [] },
  faqSo: { question: { ru: [] }, ru: [] },
  faqIfWord: { question: { ru: [] }, ru: [] },
};

export default ru;
