// Chinese text for linking-sentences, matching shape.ts's keys. Typed as
// `PartialByKey<LessonShape>`.
// Not translated yet -- every `zh` is the empty-array placeholder.
import type { PartialByKey } from "../../../lib/chapter-shape-types.ts";
import type { LessonShape } from "./shape.ts";

const zh: PartialByKey<LessonShape> = {
  title: { zh: [] },
  summary: { zh: [] },
  vocabYinwei: { zh: [] },
  vocabSi: { zh: [] },
  vocabHuo: { zh: [] },
  proseBecause: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleBecause1: { zh: [] },
  exampleBecause5: { zh: [] },
  exampleBecause7: { zh: [] },
  exampleBecause8: { zh: [] },
  exampleBecause9: { zh: [] },
  exampleBecause10: { zh: [] },
  exampleBecause11: { zh: [] },
  exampleBecause12: { zh: [] },
  vocabDanshi: { zh: [] },
  proseBut: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleBut1: { zh: [] },
  exampleBut2: { zh: [] },
  exampleBut3: { zh: [] },
  exampleBut4: { zh: [] },
  exampleBut5: { zh: [] },
  exampleBut6: { zh: [] },
  exampleBut7: { zh: [] },
  exampleBut10: { zh: [] },
  vocabRuguo: { zh: [] },
  proseIf: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleIf1: { zh: [] },
  exampleIf2: { zh: [] },
  exampleIf3: { zh: [] },
  exampleIf5: { zh: [] },
  exampleIf6: { zh: [] },
  exampleIf7: { zh: [] },
  exampleIf9: { zh: [] },
  exampleIf10: { zh: [] },
  vocabJiu: { zh: [] },
  proseThen: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleThen1: { zh: [] },
  exampleThen2: { zh: [] },
  exampleThen3: { zh: [] },
  exampleThen4: { zh: [] },
  exampleThen5: { zh: [] },
  exampleThen6: { zh: [] },
  exampleThen7: { zh: [] },
  exampleThen8: { zh: [] },
  infoLinkingSentences: {
    title: { zh: [] },
    items: [{ zh: [] }, { zh: [] }, { zh: [] }, { zh: [] }],
  },
  exercise1: { zh: [] },
  exercise2: { zh: [] },
  exercise3: { zh: [] },
  exercise4: { zh: [] },
  exercise5: { zh: [] },
  exercise6: { zh: [] },
  exercise7: { zh: [] },
  exercise8: { zh: [] },
  exercise9: { zh: [] },
  answer1: { zh: [] },
  answer2: { zh: [] },
  answer3: { zh: [] },
  answer4: { zh: [] },
  answer5: { zh: [] },
  answer6: { zh: [] },
  answer7: { zh: [] },
  answer8: { zh: [] },
  answer9: { zh: [] },
  faqSo: { question: { zh: [] }, zh: [] },
  faqIfWord: { question: { zh: [] }, zh: [] },
  faqJiu: { question: { zh: [] }, zh: [] },
};

export default zh;
