// GENERATED by scripts/generate-grammar-overview.js from every lesson's
// grammar boxes -- don't edit by hand. Edit the lesson's grammar box, then
// run `npm run grammar-overview` (or `npm run build`).
import type { Entry } from "../lib/chapter-entry-types.ts";

export const meta = {
  id: "appendix-grammar",
  type: "appendix",
  order: 4,
};

const content: Entry[] = [
  {
    "type": "title",
    "en": [
      "Grammar Patterns Reference"
    ],
    "zh": [
      "语法结构参考"
    ],
    "ru": [
      "Справочник грамматических конструкций"
    ]
  },
  {
    "type": "summary",
    "en": [
      "Every grammar box from the 24 lessons, in one place, in lesson order."
    ],
    "zh": [],
    "ru": []
  },
  {
    "type": "prose",
    "en": [
      "Each box below comes from a lesson, and its title says which one.",
      "Use this page to look up a pattern, then go back to its lesson for examples and practice."
    ],
    "zh": [],
    "ru": [],
    "tldr": {
      "en": [
        "Every grammar box from the lessons, in lesson order."
      ],
      "zh": [],
      "ru": []
    },
    "necessity": {
      "en": [
        "You can look up a pattern without hunting through the lessons."
      ],
      "zh": [],
      "ru": []
    }
  },
  {
    "type": "info",
    "ordered": true,
    "subtype": "grammar",
    "tag": "pinyin/helpers",
    "items": [
      {
        "text": {
          "en": [
            "**Words are written solid**. When several syllables form one dictionary word, they are never split apart, no matter how long the word is — {{word:dong4wu4}}, {{word:shui4jiao4}}, {{word:dan4shi4}}.",
            "Read the whole solid block as a single unit."
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "**A hyphen joins words into one**. A hyphen glues a small word onto another word, so the two work as one word. Sometimes that gives the word a new job, like turning a verb into a describing word (an adjective)."
          ],
          "ru": [],
          "zh": []
        },
        "items": [
          {
            "text": {
              "en": [
                "{{word:zhe4}}-**ge** — this"
              ],
              "ru": [],
              "zh": []
            }
          },
          {
            "text": {
              "en": [
                "{{word:yi1}}-**ge** — one thing"
              ],
              "ru": [],
              "zh": []
            }
          },
          {
            "text": {
              "en": [
                "{{word:hen3}}-**{{word:da4}}-de** — very big"
              ],
              "ru": [],
              "zh": []
            }
          },
          {
            "text": {
              "en": [
                "A hyphen always shows that the parts it joins work together as a single word."
              ],
              "ru": [],
              "zh": []
            }
          }
        ]
      },
      {
        "text": {
          "en": [
            "**Quotes set off the untranslatable**. Proper names and onomatopoeia — things that aren't really Hao-shuo-de vocabulary — are enclosed in quotes:"
          ],
          "ru": [],
          "zh": []
        },
        "items": [
          {
            "text": {
              "en": [
                "\"Beijing\" — Beijing"
              ],
              "ru": [],
              "zh": []
            }
          },
          {
            "text": {
              "en": [
                "{{word:jiao4}} \"wāng-wāng\" — barks \"woof-woof\""
              ],
              "ru": [],
              "zh": []
            }
          },
          {
            "text": {
              "en": [
                "If you see quotes, don't look the word up in the dictionary — it isn't a dictionary word."
              ],
              "ru": [],
              "zh": []
            }
          }
        ]
      }
    ],
    "title": {
      "en": [
        "Lesson 1 · Hao-shuo-de pinyin helpers"
      ],
      "ru": [],
      "zh": []
    }
  },
  {
    "type": "info",
    "subtype": "grammar",
    "tag": "sentences/is-and-is-not",
    "items": [
      {
        "text": {
          "en": [
            "NOUN + {{word:shi4}} + NOUN: {{Word:zhe4}} {{word:shi4}} {{word:ren2}}. (This is a person.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "NOUN + {{word:bu4}} {{word:shi4}} + NOUN: {{Word:dong4wu4}} {{word:bu4}} {{word:shi4}} {{word:shui3guo3}}. (An animal is not a fruit.)"
          ],
          "ru": [],
          "zh": []
        }
      }
    ],
    "title": {
      "en": [
        "Lesson 2 · Saying What Something Is"
      ],
      "ru": [],
      "zh": []
    }
  },
  {
    "type": "info",
    "subtype": "grammar",
    "tag": "describing/hen-and-de",
    "items": [
      {
        "text": {
          "en": [
            "NOUN + {{word:hen3}} + adjective: {{Word:shui3}} {{word:hen3}} {{word:hao3}}. (The water is good.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "adjective + -{{word:de}} + NOUN: {{word:da4}}-{{word:de}} {{word:di4fang1}} (a big place)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:hen3}}-{{word:duo1}}-{{word:de}} + NOUN: {{word:hen3}}-{{word:duo1}}-{{word:de}} {{word:ren2}} (many people)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "NOUN + {{word:hen3}} {{word:shao3}}: {{Word:ren2}} {{word:hen3}} {{word:shao3}}. (There are very few people.)"
          ],
          "ru": [],
          "zh": []
        }
      }
    ],
    "title": {
      "en": [
        "Lesson 3 · Describing a Noun"
      ],
      "ru": [],
      "zh": []
    }
  },
  {
    "type": "info",
    "subtype": "grammar",
    "tag": "pointers/counting-word",
    "items": [
      {
        "text": {
          "en": [
            "{{word:zhe4}}, {{word:na4}}, or a number + ge + noun. The same `{{word:ge4}}` works with every noun."
          ],
          "ru": [],
          "zh": []
        }
      }
    ],
    "title": {
      "en": [
        "Lesson 4 · One Counting Word for Everything"
      ],
      "ru": [],
      "zh": []
    }
  },
  {
    "type": "info",
    "subtype": "grammar",
    "tag": "verbs/who-does-what",
    "items": [
      {
        "text": {
          "en": [
            "Who + verb + what: {{Word:wo3}} {{word:chi1}} {{word:mi3fan4}}. (I eat rice.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:bu4}} + verb, for \"not\": {{Word:ta1}} {{word:bu4}} {{word:xie3}}. (She doesn't write.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:mei2}}-{{word:you3}}, for \"don't have\": {{Word:wo3}} {{word:mei2}}-{{word:you3}} {{word:jin1}}. (I don't have money.)"
          ],
          "ru": [],
          "zh": []
        }
      }
    ],
    "title": {
      "en": [
        "Lesson 5 · Who Does What"
      ],
      "ru": [],
      "zh": []
    }
  },
  {
    "type": "info",
    "subtype": "grammar",
    "tag": "questions/asking",
    "items": [
      {
        "text": {
          "en": [
            "sentence + {{word:ma}}?, yes or no: {{Word:ni3}} {{word:you3}} {{word:gong1ju4}} {{word:ma}}? (Do you have a tool?)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "verb-{{word:bu4}}-verb?, yes or no: {{Word:ni3}} {{word:ting1}}-{{word:bu4}}-{{word:ting1}}? (Do you listen?)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:shen2me}} where the answer goes: {{Word:ni3}} {{word:zhao3}} {{word:shen2me}}? (What are you looking for?)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:wei4shen2me}} + verb, why: {{Word:ni3}} {{word:wei4shen2me}} {{word:bu4}} {{word:chi1}}? (Why don't you eat?)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:zen3me}} + verb, how: {{Word:zhe4}}-ge {{word:zen3me}} {{word:shuo1}}? (How do you say this?)"
          ],
          "ru": [],
          "zh": []
        }
      }
    ],
    "title": {
      "en": [
        "Lesson 6 · Asking Questions"
      ],
      "ru": [],
      "zh": []
    }
  },
  {
    "type": "info",
    "subtype": "grammar",
    "tag": "pre-verbs/want-can-know-love",
    "items": [
      {
        "text": {
          "en": [
            "{{word:yao4}} + verb, want to: {{Word:wo3}} {{word:yao4}} {{word:chi1}}. (I want to eat.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:neng2}} + verb, can: {{Word:wo3}} {{word:neng2}} {{word:ting1}}. (I can hear.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:xue2}} + verb, learn to: {{Word:wo3}} {{word:xue2}} {{word:xie3}}. (I'm learning to write.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:zhi1dao4}} {{word:zen3me}} + verb, know how to: {{Word:wo3}} {{word:zhi1dao4}} {{word:zen3me}} {{word:xie3}}. (I know how to write.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:ai4}} + verb, love to: {{Word:wo3}} {{word:ai4}} {{word:chi1}}. (I love to eat.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:ke3neng2}} + verb, maybe: {{Word:ta1}} {{word:ke3neng2}} {{word:zhi1dao4}}. (He might know.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "For \"not\", put {{word:bu4}} first: {{Word:ta1}} {{word:bu4}} {{word:neng2}} {{word:chi1}}. (He can't eat.)"
          ],
          "ru": [],
          "zh": []
        }
      }
    ],
    "title": {
      "en": [
        "Lesson 7 · Words Before a Verb"
      ],
      "ru": [],
      "zh": []
    }
  },
  {
    "type": "info",
    "subtype": "grammar",
    "tag": "time/done-now-will-before",
    "items": [
      {
        "text": {
          "en": [
            "verb + {{word:le}}, done: {{Word:wo3}} {{word:chi1}} {{word:le}}. (I ate.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:zai4}} + verb, right now: {{Word:wo3}} {{word:zai4}} {{word:chi1}}. (I'm eating.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:hui4}} + verb, will: {{Word:wo3}} {{word:hui4}} {{word:chi1}}. (I will eat.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "verb-{{word:guo4}}, done before: {{Word:wo3}} {{word:chi1}}-{{word:guo4}} {{word:mi3fan4}}. (I've eaten rice before.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "Time first: {{Word:yue4}}-{{word:de}} {{word:shi2jian1}}, {{word:wo3}} {{word:shui4jiao4}}. (At night, I sleep.) {{Word:xian4zai4}}, … (Now, …)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{Word:fa1sheng1}} {{word:le}} {{word:shen2me}}? (What happened?)"
          ],
          "ru": [],
          "zh": []
        }
      }
    ],
    "title": {
      "en": [
        "Lesson 8 · When It Happens"
      ],
      "ru": [],
      "zh": []
    }
  },
  {
    "type": "info",
    "subtype": "grammar",
    "tag": "time/when-finish-after-start",
    "items": [
      {
        "text": {
          "en": [
            "verb-{{word:de}} {{word:shi2jian1}}, when: {{Word:wo3}} {{word:chi1}}-{{word:de}} {{word:shi2jian1}}, {{word:wo3}} {{word:bu4}} {{word:shuo1}}. (When I eat, I don't talk.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "verb-{{word:wan2}} {{word:le}}, finished: {{Word:wo3}} {{word:chi1}}-{{word:wan2}} {{word:le}}. (I finished eating.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "verb-{{word:wan2}} {{word:hou4}}, after: {{Word:chi1}}-{{word:wan2}} {{word:hou4}}, {{word:wo3}} {{word:shui4jiao4}}. (After eating, I sleep.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:kai1shi3}} + verb, start: {{Word:wo3}} {{word:kai1shi3}} {{word:wan2r}} {{word:le}}. (I started to play.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "verb + {{word:yi1xia4}}, for a moment: {{Word:deng3}} {{word:yi1xia4}}! (Wait a moment!)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:you4}} + verb + {{word:le}}, again: {{Word:ta1}} {{word:you4}} {{word:chi1}} {{word:le}}. (He ate again.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:hen3}} {{word:duo1}} {{word:ci4}}, many times: {{Word:wo3}} {{word:kan4}}-{{word:guo4}} {{word:hen3}} {{word:duo1}} {{word:ci4}}. (I've seen it many times.)"
          ],
          "ru": [],
          "zh": []
        }
      }
    ],
    "title": {
      "en": [
        "Lesson 9 · Around an Action"
      ],
      "ru": [],
      "zh": []
    }
  },
  {
    "type": "info",
    "subtype": "grammar",
    "tag": "place/where-and-sides",
    "items": [
      {
        "text": {
          "en": [
            "{{word:zai4}} + place: {{Word:wo3}} {{word:zai4}} {{word:jia1}}. (I'm at home.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:na3li3}}, where: {{Word:ni3}} {{word:zai4}} {{word:na3li3}}? (Where are you?)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "place-{{word:li3}} (in), place-{{word:shang4}} (on): {{Word:shui3}} {{word:zai4}} {{word:he2zi}}-{{word:li3}}. (The water is in the box.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "X-{{word:de}} {{word:qian2}}-{{word:mian4}} / {{word:hou4}}-{{word:mian4}} / {{word:xia4}}-{{word:mian4}} / {{word:pang2bian1}}: {{Word:wo3}} {{word:zai4}} {{word:ni3}}-{{word:de}} {{word:pang2bian1}}. (I'm beside you.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:zuo3bian1}} / {{word:you4bian1}}, left / right: {{Word:he2zi}} {{word:zai4}} {{word:wo3}}-{{word:de}} {{word:zuo3bian1}}. (The box is on my left.)"
          ],
          "ru": [],
          "zh": []
        }
      }
    ],
    "title": {
      "en": [
        "Lesson 10 · Where Things Are"
      ],
      "ru": [],
      "zh": []
    }
  },
  {
    "type": "info",
    "subtype": "grammar",
    "tag": "place/coming-and-going",
    "items": [
      {
        "text": {
          "en": [
            "{{word:lai2}} / {{word:qu4}} + place: {{Word:wo3}} {{word:qu4}} {{word:fu4mu3}}-{{word:de}} {{word:jia1}}. (I'm going to my parents' home.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:cong2}} + place + {{word:lai2}}: {{Word:wo3}} {{word:cong2}} {{word:jia1}} {{word:lai2}}. (I come from home.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:dao4}} + place, arrive: {{Word:wo3}} {{word:dao4}} {{word:jia1}} {{word:le}}. (I've arrived home.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:qi3}}-{{word:lai2}} (get up), {{word:shang4}}-{{word:lai2}} (come up), {{word:xia4}}-{{word:lai2}} (come down); with {{word:qu4}} for going away."
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:dong4}}, move: {{Word:bu4}} {{word:yao4}} {{word:dong4}}! (Don't move!)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:yuan3}} / {{word:fu4jin4}}, far / nearby: {{Word:na4}}-ge {{word:di4fang1}} {{word:hen3}} {{word:yuan3}}. (That place is far.) {{Word:wo3}}-{{word:de}} {{word:jia1}} {{word:zai4}} {{word:fu4jin4}}. (My home is nearby.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:lu4}}, road, way: {{Word:ni3}} {{word:zhi1dao4}} {{word:lu4}} {{word:ma}}? (Do you know the way?)"
          ],
          "ru": [],
          "zh": []
        }
      }
    ],
    "title": {
      "en": [
        "Lesson 11 · Coming and Going"
      ],
      "ru": [],
      "zh": []
    }
  },
  {
    "type": "info",
    "subtype": "grammar",
    "tag": "describing/how-much",
    "items": [
      {
        "text": {
          "en": [
            "{{word:hen3}} + adjective, very: {{Word:shui3}} {{word:hen3}} {{word:re4}}. (The water is very hot.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:zhen1}} + adjective, really: {{Word:zhen1}} {{word:re4}}! (It's really hot!)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:bu4}} / {{word:bu4}} {{word:hen3}} + adjective, not / not very: {{Word:shui3}} {{word:bu4}} {{word:leng3}}. (The water isn't cold.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "adjective + {{word:ma}}?, asking: {{Word:ni3}} {{word:leng3}} {{word:ma}}? (Are you cold?)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:hen3}} {{word:you3}} {{word:jia4zhi2}}, valuable: {{Word:zhe4}}-ge {{word:gong1ju4}} {{word:hen3}} {{word:you3}} {{word:jia4zhi2}}. (This tool is very valuable.)"
          ],
          "ru": [],
          "zh": []
        }
      }
    ],
    "title": {
      "en": [
        "Lesson 12 · How Much"
      ],
      "ru": [],
      "zh": []
    }
  },
  {
    "type": "info",
    "subtype": "grammar",
    "tag": "describing/comparing",
    "items": [
      {
        "text": {
          "en": [
            "A {{word:bi3}} B + adjective: {{Word:wo3}} {{word:bi3}} {{word:ni3}} {{word:da4}}. (I'm bigger than you.) No {{word:hen3}} here."
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:yi1yang4}}, the same: {{Word:ta1}}-{{word:men}} {{word:yi1yang4}}. (They're the same.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:bu4tong2}}, different: {{Word:wo3}} {{word:yao4}} {{word:bu4tong2}}-{{word:de}} {{word:yi1fu}}. (I want different clothes.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:bie2de}}, other: {{Word:wo3}} {{word:yao4}} {{word:bie2de}}. (I want something else.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:zhe4}}-{{word:zhong3}} + noun, this kind of: {{word:zhe4}}-{{word:zhong3}} {{word:shui3guo3}} (this kind of fruit)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:zui4}} + adjective, the most: {{Word:zhe4}}-ge {{word:zui4}} {{word:da4}}. (This one is the biggest.)"
          ],
          "ru": [],
          "zh": []
        }
      }
    ],
    "title": {
      "en": [
        "Lesson 13 · Comparing"
      ],
      "ru": [],
      "zh": []
    }
  },
  {
    "type": "info",
    "subtype": "grammar",
    "tag": "describing/also-and-all",
    "items": [
      {
        "text": {
          "en": [
            "{{word:ye3}} + verb, also: {{Word:wo3}} {{word:ye3}} {{word:chi1}}. (I eat too.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:ye3}} {{word:hen3}} + adjective: {{Word:ta1}} {{word:ye3}} {{word:hen3}} {{word:leng3}}. (She's cold too.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:dou1}} + verb, all: {{Word:wo3}}-{{word:men}} {{word:dou1}} {{word:chi1}}. (We all eat.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:shen2me}}-{{word:dou1}} + verb, everything: {{Word:wo3}} {{word:shen2me}}-{{word:dou1}} {{word:chi1}}. (I eat everything.) With {{word:bu4}}: nothing. {{word:na3li3}}-{{word:dou1}}: everywhere."
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:bu4fen}}, part: {{Word:zhe4}} {{word:bu4fen}} {{word:hen3}} {{word:hao3}}. (This part is good.) {{word:da4}} {{word:bu4fen}}: most."
          ],
          "ru": [],
          "zh": []
        }
      }
    ],
    "title": {
      "en": [
        "Lesson 14 · Also and All"
      ],
      "ru": [],
      "zh": []
    }
  },
  {
    "type": "info",
    "subtype": "grammar",
    "tag": "describing/becoming-and-making",
    "items": [
      {
        "text": {
          "en": [
            "adjective + {{word:le}}, it changed: {{Word:shui3}} {{word:re4}} {{word:le}}. (The water got hot.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:bian4}} + adjective + {{word:le}}, became: {{Word:shui3}} {{word:bian4}} {{word:leng3}} {{word:le}}. (The water turned cold.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:nong4}} + result, make it so: {{Word:wo3}} {{word:nong4}} {{word:hao3}} {{word:le}}. (I fixed it.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:ba3}} + thing + {{word:nong4}} + result: {{Word:wo3}} {{word:ba3}} {{word:gong1ju4}} {{word:nong4}} {{word:hao3}} {{word:le}}. (I fixed the tool.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:ba3}} + thing + {{word:fang4}} {{word:zai4}} + place, put: {{Word:wo3}} {{word:ba3}} {{word:yi1fu}} {{word:fang4}} {{word:zai4}} {{word:di4}}-{{word:shang4}} {{word:le}}. (I put the clothes on the floor.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:you3}} {{word:li4liang4}}, strong: {{Word:ta1}} {{word:hen3}} {{word:you3}} {{word:li4liang4}}. (He's very strong.)"
          ],
          "ru": [],
          "zh": []
        }
      }
    ],
    "title": {
      "en": [
        "Lesson 15 · Becoming and Making"
      ],
      "ru": [],
      "zh": []
    }
  },
  {
    "type": "info",
    "subtype": "grammar",
    "tag": "verbs/direction-and-result",
    "items": [
      {
        "text": {
          "en": [
            "verb-{{word:lai2}} / verb-{{word:qu4}}, toward you / away: {{Word:ba3}} {{word:shui3}} {{word:na2}}-{{word:lai2}}! (Bring the water!)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:jin4}} / {{word:chu1}} / {{word:hui2}} + {{word:lai2}} / {{word:qu4}}, in / out / back: {{Word:ni3}} {{word:jin4}}-{{word:lai2}}! (Come in!) {{Word:wo3}} {{word:yao4}} {{word:hui2}} {{word:jia1}}. (I want to go home.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "verb + direction words: {{Word:ta1}} {{word:ba3}} {{word:jin1}} {{word:na2}}-{{word:chu1}}-{{word:lai2}} {{word:le}}. (He took out the money.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "verb-result: {{Word:wo3}} {{word:zhao3}}-{{word:dao4}} {{word:le}}. (I found it.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "verb-{{word:de}}-result / verb-{{word:bu4}}-result, can / can't: {{Word:wo3}} {{word:kan4}}-{{word:bu4}}-{{word:dao4}}. (I can't see it.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "verb-{{word:qi3}}-{{word:lai2}}, seems: {{Word:zhe4}}-ge {{word:kan4}}-{{word:qi3}}-{{word:lai2}} {{word:hen3}} {{word:hao3}}. (This looks good.) verb-{{word:xia4}}-{{word:qu4}}, keep going: {{Word:shuo1}}-{{word:xia4}}-{{word:qu4}}! (Keep talking!)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:zuo4}}-{{word:xia4}} / {{word:zhan4}}-{{word:qi3}}-{{word:lai2}} / {{word:tang3}}-{{word:xia4}}, sit down / stand up / lie down: {{Word:ni3}} {{word:zuo4}}-{{word:xia4}}! (Sit down!)"
          ],
          "ru": [],
          "zh": []
        }
      }
    ],
    "title": {
      "en": [
        "Lesson 16 · Direction and Result"
      ],
      "ru": [],
      "zh": []
    }
  },
  {
    "type": "info",
    "subtype": "grammar",
    "tag": "numbers/counting",
    "items": [
      {
        "text": {
          "en": [
            "1 {{word:yi1}}, 2 {{word:er4}}, 3 {{word:san1}}, 4 {{word:si4}}, 5 {{word:wu3}}, 6 {{word:liu4}}, 7 {{word:qi1}}, 8 {{word:ba1}}, 9 {{word:jiu3}}, 10 {{word:shi2}}"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "number + {{word:ge4}} + noun: {{Word:san1}}-ge {{word:ren2}} (three people). For two things, {{word:liang3}}-ge."
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "Above ten: {{word:shi2}}-{{word:er4}} (12), {{word:er4}}-{{word:shi2}} (20)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "number + {{word:hao4}}, number …: {{Word:er4}}-{{word:hao4}} (number two)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "number + {{word:dian3}}, o'clock: {{Word:xian4zai4}} {{word:shi4}} {{word:san1}}-{{word:dian3}}. (It's three o'clock now.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:yi1}}-{{word:dian3}}, a little: {{Word:wo3}} {{word:yao4}} {{word:yi1}}-{{word:dian3}} {{word:shui3}}. (I want a little water.) {{Word:zhe4}}-ge {{word:da4}} {{word:yi1}}-{{word:dian3}}. (This one is a bit bigger.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "A, B {{word:fang4}} {{word:zai4}} {{word:yi1}}-{{word:qi3}}, add: {{Word:san1}}, {{word:si4}} {{word:fang4}} {{word:zai4}} {{word:yi1}}-{{word:qi3}}, {{word:shi4}} {{word:qi1}}. (3 + 4 = 7) {{word:cong2}} A {{word:li3}}-{{word:mian4}} {{word:na2}} B, take away: {{Word:cong2}} {{word:qi1}} {{word:li3}}-{{word:mian4}} {{word:na2}} {{word:san1}}, {{word:shi4}} {{word:si4}}. (7 − 3 = 4)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:fang4}} {{word:zai4}} {{word:yi1}}-{{word:qi3}} B-{{word:ci4}}, multiply: {{Word:ba3}} {{word:si4}} {{word:fang4}} {{word:zai4}} {{word:yi1}}-{{word:qi3}} {{word:san1}}-{{word:ci4}}, {{word:shi4}} {{word:shi2}}-{{word:er4}}. (3 × 4 = 12) {{word:na2}} A, {{word:neng2}} {{word:na2}} B-{{word:ci4}}, divide: {{Word:cong2}} {{word:shi2}}-{{word:er4}} {{word:li3}}-{{word:mian4}} {{word:na2}} {{word:si4}}, {{word:neng2}} {{word:na2}} {{word:san1}}-{{word:ci4}}. (12 ÷ 4 = 3)"
          ],
          "ru": [],
          "zh": []
        }
      }
    ],
    "title": {
      "en": [
        "Lesson 17 · Counting"
      ],
      "ru": [],
      "zh": []
    }
  },
  {
    "type": "info",
    "subtype": "grammar",
    "tag": "describing/colors",
    "items": [
      {
        "text": {
          "en": [
            "color-{{word:de}} + noun: {{word:hong2se4}}-{{word:de}} {{word:he2zi}} (a red box)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "Thing + {{word:shi4}} + color-{{word:de}}: {{Word:he2zi}} {{word:shi4}} {{word:hong2se4}}-{{word:de}}. (The box is red.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:shen2me}} {{word:yan2se4}}, what color: {{Word:ni3}}-{{word:de}} {{word:yi1fu}} {{word:shi4}} {{word:shen2me}} {{word:yan2se4}}? (What color are your clothes?)"
          ],
          "ru": [],
          "zh": []
        }
      }
    ],
    "title": {
      "en": [
        "Lesson 18 · Colors"
      ],
      "ru": [],
      "zh": []
    }
  },
  {
    "type": "info",
    "subtype": "grammar",
    "tag": "de/making-words",
    "items": [
      {
        "text": {
          "en": [
            "verb-{{word:de}}, the thing: {{word:chi1}}-{{word:de}} (food, something to eat)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "verb-{{word:de}} {{word:ren2}}, the one who: {{word:xie3}}-{{word:de}} {{word:ren2}} (the one who writes)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "verb-{{word:de}} + adjective, how: {{Word:ta1}} {{word:shuo1}}-{{word:de}} {{word:hao3}}. (She speaks well.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "adjective-{{word:de}} + noun: {{word:hao3}}-{{word:de}} {{word:ren2}} (a good person). Whose: {{word:wo3}}-{{word:de}} {{word:bi2zi}} (my nose)."
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "a longer description-{{word:de}} + noun: {{word:zai4}}-{{word:shui3}}-{{word:li3}}-{{word:de}} {{word:dong4wu4}} (an animal in the water)"
          ],
          "ru": [],
          "zh": []
        }
      }
    ],
    "title": {
      "en": [
        "Lesson 19 · The Jobs of -de"
      ],
      "ru": [],
      "zh": []
    }
  },
  {
    "type": "info",
    "subtype": "grammar",
    "tag": "relationships/inside-a-sentence",
    "items": [
      {
        "text": {
          "en": [
            "{{word:gei3}} + person + thing, give: {{Word:wo3}} {{word:gei3}} {{word:ni3}} {{word:shui3}}. (I give you water.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:yong4}} + thing + verb, with: {{Word:wo3}} {{word:yong4}} {{word:gong1ju4}} {{word:xie3}}. (I write with a tool.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "A {{word:he2}} B, and (nouns only): {{word:ni3}} {{word:he2}} {{word:wo3}} (you and me)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "A {{word:huo4zhe3}} B, or: {{word:zhe4}}-ge {{word:huo4zhe3}} {{word:na4}}-ge (this one or that one)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "A {{word:dui4}} B + adjective, toward / for: {{Word:ta1}} {{word:dui4}} {{word:wo3}} {{word:hen3}} {{word:hao3}}. (He's good to me.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "A {{word:he2}} B-{{word:de}} {{word:guan1xi}}, relationship: {{Word:wo3}} {{word:he2}} {{word:ta1}}-{{word:de}} {{word:guan1xi}} {{word:hen3}} {{word:hao3}}. (He and I get along well.) {{Word:mei2}}-{{word:you3}} {{word:guan1xi}}! (It doesn't matter!)"
          ],
          "ru": [],
          "zh": []
        }
      }
    ],
    "title": {
      "en": [
        "Lesson 20 · Joining Words in a Sentence"
      ],
      "ru": [],
      "zh": []
    }
  },
  {
    "type": "info",
    "subtype": "grammar",
    "tag": "relationships/linking-sentences",
    "items": [
      {
        "text": {
          "en": [
            "{{word:yin1wei4}} + reason, result: {{Word:yin1wei4}} {{word:wo3}} {{word:hen3}} {{word:leng3}}, {{word:wo3}} {{word:bu4}} {{word:qu4}}. (Because I'm cold, I'm not going.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "…, {{word:dan4shi4}} …, but: {{Word:zhe4}}-ge {{word:hen3}} {{word:hao3}}, {{word:dan4shi4}} {{word:mei2}}-{{word:you3}} {{word:yan2}}. (It's good, but there's no salt.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:ru2guo3}} X, …, if: {{Word:ru2guo3}} {{word:ni3}} {{word:lai2}}, {{word:wo3}} {{word:deng3}} {{word:ni3}}. (If you come, I'll wait for you.)"
          ],
          "ru": [],
          "zh": []
        }
      }
    ],
    "title": {
      "en": [
        "Lesson 21 · Linking Sentences"
      ],
      "ru": [],
      "zh": []
    }
  },
  {
    "type": "info",
    "subtype": "grammar",
    "tag": "expressions/greetings-and-feelings",
    "items": [
      {
        "text": {
          "en": [
            "{{Word:ni3}} {{word:hao3}}!, hello. {{Word:ni3}} {{word:hao3}} {{word:ma}}?, how are you?"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:jiao4}} + \"name\": {{Word:wo3}} {{word:jiao4}} \"Lisa\". (My name is Lisa.) {{Word:ni3}} {{word:jiao4}} {{word:shen2me}}? (What's your name?)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "A verb on its own is an order: {{Word:chi1}}! (Eat!) {{Word:bu4}} {{word:yao4}} + verb: don't."
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:jue2de}} + adjective, feel: {{Word:wo3}} {{word:jue2de}} {{word:leng3}}. (I feel cold.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:pa4}} + thing, scared of: {{Word:wo3}} {{word:pa4}} {{word:chong2zi}}. (I'm scared of bugs.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:xie4}}-xie, thank you: {{Word:xie4}}-xie {{word:ni3}}! (Thank you!) {{Word:bu4}} {{word:yong4}} {{word:xie4}}. (You're welcome.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:kai1}}-{{word:xin1}}, happy: {{Word:wo3}} {{word:hen3}} {{word:kai1}}-{{word:xin1}}. (I'm very happy.) {{Word:xiao3}}-{{word:xin1}}! (Be careful!)"
          ],
          "ru": [],
          "zh": []
        }
      }
    ],
    "title": {
      "en": [
        "Lesson 22 · Greetings and Feelings"
      ],
      "ru": [],
      "zh": []
    }
  },
  {
    "type": "info",
    "subtype": "grammar",
    "tag": "words/doubling",
    "items": [
      {
        "text": {
          "en": [
            "verb-verb, a little: {{Word:wo3}} {{word:kan4}}-kan. (Let me have a look.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "adjective-adjective-{{word:de}}, stronger: {{Word:yue4}} {{word:yuan2}}-{{word:yuan2}}-{{word:de}}. (The moon is nice and round.) {{word:hao3}}-{{word:hao3}} + verb, well: {{Word:hao3}}-{{word:hao3}} {{word:xue2}}! (Study hard!)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:ren2}}-{{word:ren2}} / {{word:ge4}}-{{word:ge4}} + {{word:dou1}}, every: {{Word:ren2}}-{{word:ren2}} {{word:dou1}} {{word:yao4}} {{word:shui3}}. (Everyone needs water.)"
          ],
          "ru": [],
          "zh": []
        }
      }
    ],
    "title": {
      "en": [
        "Lesson 23 · Doubling Words"
      ],
      "ru": [],
      "zh": []
    }
  },
  {
    "type": "info",
    "subtype": "grammar",
    "tag": "everyday/let-and-help",
    "items": [
      {
        "text": {
          "en": [
            "{{word:wo3}} {{word:lai2}} + verb, let me: {{Word:wo3}} {{word:lai2}} {{word:na2}}. (Let me carry it.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:gei3}} {{word:wo3}} + verb + {{word:yi1xia4}}, let me have a turn: {{Word:gei3}} {{word:wo3}} {{word:kan4}} {{word:yi1xia4}}. (Let me take a look.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:bang1}} + person + verb, help: {{Word:ni3}} {{word:bang1}} {{word:wo3}} {{word:na2}} {{word:yi1xia4}}. (Could you hold this for me?)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:jiao4}} + person + verb, have or let: {{Word:jiao4}} {{word:ta1}} {{word:jin4}}-{{word:lai2}}. (Let him in.) {{word:bu4}} {{word:jiao4}}, won't let: {{Word:fu4mu3}} {{word:bu4}} {{word:jiao4}} {{word:wo3}} {{word:chu1}}-{{word:qu4}}. (My parents won't let me go out.)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:neng2}} … {{word:ma}}?, may I: {{Word:wo3}} {{word:neng2}} {{word:jin4}}-{{word:lai2}} {{word:ma}}? (Can I come in?) …, {{word:hao3}} {{word:ma}}?, let's or please: {{Word:wo3}}-{{word:men}} {{word:chu1}}-{{word:qu4}} {{word:wan2r}}, {{word:hao3}} {{word:ma}}? (Let's go out and play, okay?)"
          ],
          "ru": [],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:jiao1}} + person + verb, teach: {{Word:wo3}} {{word:jiao1}} {{word:ni3}} {{word:xie3}}. (I'll teach you to write.)"
          ],
          "ru": [],
          "zh": []
        }
      }
    ],
    "title": {
      "en": [
        "Lesson 24 · Let and Help"
      ],
      "ru": [],
      "zh": []
    }
  }
];

export default content;
