// GENERATED by scripts/generate-grammar-overview.js from every lesson's
// grammar boxes -- don't edit by hand. Edit the lesson's grammar box, then
// run `npm run grammar-overview` (or `npm run build`).
import type { Entry } from "../lib/chapter-entry-types.ts";

export const meta = {
  id: "appendix-grammar",
  type: "appendix",
  order: 4,
};

const content: Entry[] = [
  {
    "type": "title",
    "en": [
      "Grammar Patterns Reference"
    ],
    "zh": [
      "语法结构参考"
    ],
    "ru": [
      "Справочник грамматических конструкций"
    ]
  },
  {
    "type": "summary",
    "en": [
      "Every pattern from the 24 lessons, in one place, in lesson order."
    ],
    "zh": [],
    "ru": [
      "Все грамматические схемы из 24 уроков в одном месте, по порядку уроков."
    ]
  },
  {
    "type": "prose",
    "en": [
      "Each box below holds one lesson's patterns, and its title says which lesson.",
      "Use this page to look up a pattern, then go back to its lesson for examples and practice."
    ],
    "zh": [],
    "ru": [
      "В каждом блоке ниже — схемы одного урока, и заголовок говорит, какого.",
      "Найдите здесь нужную схему, а потом вернитесь к её уроку за примерами и упражнениями."
    ],
    "tldr": {
      "en": [
        "Every pattern from the lessons, in lesson order."
      ],
      "zh": [],
      "ru": [
        "Все грамматические схемы из уроков, по порядку."
      ]
    },
    "necessity": {
      "en": [
        "You can look up a pattern without hunting through the lessons."
      ],
      "zh": [],
      "ru": [
        "Схему можно найти, не листая все уроки."
      ]
    }
  },
  {
    "type": "info",
    "subtype": "grammar",
    "title": {
      "en": [
        "Lesson 1 · Sounds and Symbols"
      ],
      "zh": [],
      "ru": [
        "Урок 1 · Звуки и знаки"
      ]
    },
    "items": [
      {
        "text": {
          "en": [
            "**Words are written solid**. When several syllables form one dictionary word, they are never split apart, no matter how long the word is — {{word:dong4}}-{{word:wu4}}, {{word:shui4jiao4}}, {{word:dan4}}-{{word:shi4}}.",
            "Read the whole solid block as a single unit."
          ],
          "ru": [
            "**Слова пишутся слитно**. Если несколько слогов составляют одно слово из словаря, их никогда не разделяют, какой бы длины ни было слово: {{word:dong4}}-{{word:wu4}}, {{word:shui4jiao4}}, {{word:dan4}}-{{word:shi4}}.",
            "Читайте весь слитный блок как одно целое."
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "**A hyphen joins words into one**. A hyphen glues a small word onto another word, so the two work as one word. Sometimes that gives the word a new job, like turning a verb into a describing word (an adjective)."
          ],
          "ru": [
            "**Дефис соединяет слова в одно**. Дефис приклеивает маленькое слово к другому слову, и они работают как одно слово. Иногда так слово получает новую работу: например, глагол становится описательным словом (прилагательным)."
          ],
          "zh": []
        },
        "items": [
          {
            "text": {
              "en": [
                "{{word:zhe4}}-**ge** — this"
              ],
              "ru": [
                "{{word:zhe4}}-**ge** — этот"
              ],
              "zh": []
            }
          },
          {
            "text": {
              "en": [
                "{{word:yi1}}-**ge** — one thing"
              ],
              "ru": [
                "{{word:yi1}}-**ge** — одна вещь"
              ],
              "zh": []
            }
          },
          {
            "text": {
              "en": [
                "{{word:hen3}}-**{{word:da4}}-de** — very big"
              ],
              "ru": [
                "{{word:hen3}}-**{{word:da4}}-de** — очень большой"
              ],
              "zh": []
            }
          },
          {
            "text": {
              "en": [
                "A hyphen always shows that the parts it joins work together as a single word."
              ],
              "ru": [
                "Дефис всегда показывает, что части, которые он соединяет, работают вместе как одно слово."
              ],
              "zh": []
            }
          }
        ]
      },
      {
        "text": {
          "en": [
            "**Quotes set off the untranslatable**. Proper names and onomatopoeia — things that aren't really Hao-shuo-de vocabulary — are enclosed in quotes:"
          ],
          "ru": [
            "**Кавычки выделяют то, что не переводится**. Имена и звукоподражания — то, что на самом деле не входит в словарь Hǎo-shuō-de, — пишутся в кавычках:"
          ],
          "zh": []
        },
        "items": [
          {
            "text": {
              "en": [
                "\"Beijing\" — Beijing"
              ],
              "ru": [
                "\"Beijing\" — Пекин"
              ],
              "zh": []
            }
          },
          {
            "text": {
              "en": [
                "{{word:jiao4}} \"wāng-wāng\" — barks \"woof-woof\""
              ],
              "ru": [
                "{{word:jiao4}} \"wāng-wāng\" — лает «гав-гав»"
              ],
              "zh": []
            }
          },
          {
            "text": {
              "en": [
                "If you see quotes, don't look the word up in the dictionary — it isn't a dictionary word."
              ],
              "ru": [
                "Если видите кавычки, не ищите слово в словаре — это не словарное слово."
              ],
              "zh": []
            }
          }
        ]
      }
    ]
  },
  {
    "type": "info",
    "subtype": "grammar",
    "title": {
      "en": [
        "Lesson 2 · Words and Sentences"
      ],
      "zh": [],
      "ru": [
        "Урок 2 · Слова и предложения"
      ]
    },
    "items": [
      {
        "text": {
          "en": [
            "NOUN + {{word:shi4}} + NOUN: {{Word:nv3}}-{{word:ren2}} {{word:shi4}} {{word:ren2}}. (A woman is a person.)"
          ],
          "ru": [
            "СУЩЕСТВИТЕЛЬНОЕ + {{word:shi4}} + СУЩЕСТВИТЕЛЬНОЕ: {{Word:nv3}}-{{word:ren2}} {{word:shi4}} {{word:ren2}}. (Женщина — человек.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:zhe4}} {{word:shi4}} + NOUN, this is: {{Word:zhe4}} {{word:shi4}} {{word:ren2}}. (This is a person.)"
          ],
          "ru": [
            "{{word:zhe4}} {{word:shi4}} + СУЩЕСТВИТЕЛЬНОЕ — это: {{Word:zhe4}} {{word:shi4}} {{word:ren2}}. (Это человек.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "NOUN + {{word:bu4}} {{word:shi4}} + NOUN: {{Word:dong4}}-{{word:wu4}} {{word:bu4}} {{word:shi4}} {{word:zhi2wu4}}. (An animal is not a plant.)"
          ],
          "ru": [
            "СУЩЕСТВИТЕЛЬНОЕ + {{word:bu4}} {{word:shi4}} + СУЩЕСТВИТЕЛЬНОЕ: {{Word:dong4}}-{{word:wu4}} {{word:bu4}} {{word:shi4}} {{word:zhi2wu4}}. (Животное — не растение.)"
          ],
          "zh": []
        }
      }
    ]
  },
  {
    "type": "info",
    "subtype": "grammar",
    "title": {
      "en": [
        "Lesson 3 · Modifying Nouns"
      ],
      "zh": [],
      "ru": [
        "Урок 3 · Описание существительных"
      ]
    },
    "items": [
      {
        "text": {
          "en": [
            "NOUN + {{word:hen3}} + adjective: {{Word:shui3}} {{word:hen3}} {{word:hao3}}. (The water is good.)"
          ],
          "ru": [
            "СУЩЕСТВИТЕЛЬНОЕ + {{word:hen3}} + прилагательное: {{Word:shui3}} {{word:hen3}} {{word:hao3}}. (Вода хорошая.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "adjective + -{{word:de}} + NOUN: {{word:da4}}-{{word:de}} {{word:di4}}-{{light:fang1}} (a big place)"
          ],
          "ru": [
            "прилагательное + -{{word:de}} + СУЩЕСТВИТЕЛЬНОЕ: {{word:da4}}-{{word:de}} {{word:di4}}-{{light:fang1}} (большое место)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:hen3}}-{{word:duo1}}-{{word:de}} + NOUN: {{word:hen3}}-{{word:duo1}}-{{word:de}} {{word:ren2}} (many people)"
          ],
          "ru": [
            "{{word:hen3}}-{{word:duo1}}-{{word:de}} + СУЩЕСТВИТЕЛЬНОЕ: {{word:hen3}}-{{word:duo1}}-{{word:de}} {{word:ren2}} (много людей)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "NOUN + {{word:hen3}} {{word:shao3}}: {{Word:ren2}} {{word:hen3}} {{word:shao3}}. (There are few people.)"
          ],
          "ru": [
            "СУЩЕСТВИТЕЛЬНОЕ + {{word:hen3}} {{word:shao3}}: {{Word:ren2}} {{word:hen3}} {{word:shao3}}. (Людей мало.)"
          ],
          "zh": []
        }
      }
    ]
  },
  {
    "type": "info",
    "subtype": "grammar",
    "title": {
      "en": [
        "Lesson 4 · Pointing at People and Things"
      ],
      "zh": [],
      "ru": [
        "Урок 4 · Указываем на людей и вещи"
      ]
    },
    "items": [
      {
        "text": {
          "en": [
            "{{word:zhe4}}, this; {{word:na4}}, that. They work like nouns: {{Word:zhe4}}. (This.)"
          ],
          "ru": [
            "{{word:zhe4}} — это, {{word:na4}} — то. Они работают как существительные: {{Word:zhe4}}. (Это.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:zhe4}}, {{word:na4}}, or a number + ge + noun. The same `{{word:ge4}}` works with every noun."
          ],
          "ru": [
            "{{word:zhe4}}, {{word:na4}} или число + ge + существительное. Одно и то же `{{word:ge4}}` подходит к любому существительному."
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:wo3}}, I; {{word:ni3}}, you; {{word:ta1}}, he or she. They work like nouns: {{Word:ni3}}. (You.)"
          ],
          "ru": [
            "{{word:wo3}} — я, {{word:ni3}} — ты, {{word:ta1}} — он или она. Они работают как существительные: {{Word:ni3}}. (Ты.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:wo3}} / {{word:ni3}} / {{word:ta1}} + -{{word:men}}, more than one: {{Word:wo3}}-{{word:men}}. (We.)"
          ],
          "ru": [
            "{{word:wo3}} / {{word:ni3}} / {{word:ta1}} + -{{word:men}} — больше одного: {{Word:wo3}}-{{word:men}}. (Мы.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:wo3}}-{{word:de}} / {{word:ni3}}-{{word:de}} + noun, whose: {{word:wo3}}-{{word:de}} {{word:zhi2wu4}} (my plant)"
          ],
          "ru": [
            "{{word:wo3}}-{{word:de}} / {{word:ni3}}-{{word:de}} + существительное — чей: {{word:wo3}}-{{word:de}} {{word:zhi2wu4}} (моё растение)"
          ],
          "zh": []
        }
      }
    ]
  },
  {
    "type": "info",
    "subtype": "grammar",
    "title": {
      "en": [
        "Lesson 5 · Verbs 1 — Who does what"
      ],
      "zh": [],
      "ru": [
        "Урок 5 · Глаголы 1 — Кто что делает"
      ]
    },
    "items": [
      {
        "text": {
          "en": [
            "Who + verb + what: {{Word:wo3}} {{word:he1}} {{word:shui3}}. (I drink water.)"
          ],
          "ru": [
            "Кто + глагол + что: {{Word:wo3}} {{word:he1}} {{word:shui3}}. (Я пью воду.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:bu4}} + verb, for \"not\": {{Word:ta1}} {{word:bu4}} {{word:xie3}}. (She doesn't write.)"
          ],
          "ru": [
            "{{word:bu4}} + глагол — «не»: {{Word:ta1}} {{word:bu4}} {{word:xie3}}. (Она не пишет.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:mei2}}-{{word:you3}}, for \"don't have\": {{Word:wo3}} {{word:mei2}}-{{word:you3}} {{word:jin1}}. (I don't have money.)"
          ],
          "ru": [
            "{{word:mei2}}-{{word:you3}} — «нет, не иметь»: {{Word:wo3}} {{word:mei2}}-{{word:you3}} {{word:jin1}}. (У меня нет денег.)"
          ],
          "zh": []
        }
      }
    ]
  },
  {
    "type": "info",
    "subtype": "grammar",
    "title": {
      "en": [
        "Lesson 6 · Questions and Answers"
      ],
      "zh": [],
      "ru": [
        "Урок 6 · Вопросы и ответы"
      ]
    },
    "items": [
      {
        "text": {
          "en": [
            "sentence + {{word:ma}}?, yes or no: {{Word:ni3}} {{word:you3}} {{word:gong1}}-{{word:ju4}} {{word:ma}}? (Do you have a tool?)"
          ],
          "ru": [
            "предложение + {{word:ma}}? — да или нет: {{Word:ni3}} {{word:you3}} {{word:gong1}}-{{word:ju4}} {{word:ma}}? (У тебя есть инструмент?)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "verb-{{word:bu4}}-verb?, yes or no: {{Word:ni3}} {{word:ting1}}-{{word:bu4}}-{{word:ting1}}? (Do you listen?)"
          ],
          "ru": [
            "глагол-{{word:bu4}}-глагол? — да или нет: {{Word:ni3}} {{word:ting1}}-{{word:bu4}}-{{word:ting1}}? (Ты слушаешь?)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:shen2me}} where the answer goes: {{Word:ni3}} {{word:zhao3}} {{word:shen2me}}? (What are you looking for?)"
          ],
          "ru": [
            "{{word:shen2me}} там, где стоит ответ: {{Word:ni3}} {{word:zhao3}} {{word:shen2me}}? (Что ты ищешь?)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:wei4}}-{{word:shen2me}} + verb, why: {{Word:ni3}} {{word:wei4}}-{{word:shen2me}} {{word:bu4}} {{word:chi1}}? (Why don't you eat?)"
          ],
          "ru": [
            "{{word:wei4}}-{{word:shen2me}} + глагол — почему: {{Word:ni3}} {{word:wei4}}-{{word:shen2me}} {{word:bu4}} {{word:chi1}}? (Почему ты не ешь?)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:zen3me}} + verb, how: {{Word:zhe4}}-ge {{word:zen3me}} {{word:shuo1}}? (How do you say this?)"
          ],
          "ru": [
            "{{word:zen3me}} + глагол — как: {{Word:zhe4}}-ge {{word:zen3me}} {{word:shuo1}}? (Как это сказать?)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "verb. / {{word:bu4}} + verb., yes / no: {{Word:ni3}} {{word:ting1}}-{{word:bu4}}-{{word:ting1}}? {{Word:ting1}}. (Do you listen? Yes, I do.)"
          ],
          "ru": [
            "глагол. / {{word:bu4}} + глагол. — да / нет: {{Word:ni3}} {{word:ting1}}-{{word:bu4}}-{{word:ting1}}? {{Word:ting1}}. (Ты слушаешь? Да, слушаю.)"
          ],
          "zh": []
        }
      }
    ]
  },
  {
    "type": "info",
    "subtype": "grammar",
    "title": {
      "en": [
        "Lesson 7 · Pre-Verbs"
      ],
      "zh": [],
      "ru": [
        "Урок 7 · Слова перед глаголом"
      ]
    },
    "items": [
      {
        "text": {
          "en": [
            "{{word:yao4}} + verb, want to: {{Word:wo3}} {{word:yao4}} {{word:chi1}}. (I want to eat.)"
          ],
          "ru": [
            "{{word:yao4}} + глагол — хотеть: {{Word:wo3}} {{word:yao4}} {{word:chi1}}. (Я хочу есть.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:neng2}} + verb, can: {{Word:wo3}} {{word:neng2}} {{word:ting1}}. (I can hear.)"
          ],
          "ru": [
            "{{word:neng2}} + глагол — мочь: {{Word:wo3}} {{word:neng2}} {{word:ting1}}. (Я могу слышать.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "For \"not\", put {{word:bu4}} first: {{Word:ta1}} {{word:bu4}} {{word:neng2}} {{word:chi1}}. (He can't eat.)"
          ],
          "ru": [
            "Чтобы сказать «не», поставьте {{word:bu4}} в начало: {{Word:ta1}} {{word:bu4}} {{word:neng2}} {{word:chi1}}. (Он не может есть.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:xue2}} + verb, learn to: {{Word:wo3}} {{word:xue2}} {{word:xie3}}. (I'm learning to write.)"
          ],
          "ru": [
            "{{word:xue2}} + глагол — учиться: {{Word:wo3}} {{word:xue2}} {{word:xie3}}. (Я учусь писать.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:zhi1dao4}} {{word:zen3me}} + verb, know how to: {{Word:wo3}} {{word:zhi1dao4}} {{word:zen3me}} {{word:xie3}}. (I know how to write.)"
          ],
          "ru": [
            "{{word:zhi1dao4}} {{word:zen3me}} + глагол — уметь: {{Word:wo3}} {{word:zhi1dao4}} {{word:zen3me}} {{word:xie3}}. (Я умею писать.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:ai4}} + verb, love to: {{Word:wo3}} {{word:ai4}} {{word:chi1}}. (I love to eat.)"
          ],
          "ru": [
            "{{word:ai4}} + глагол — любить: {{Word:wo3}} {{word:ai4}} {{word:chi1}}. (Я люблю поесть.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:ke3}}-{{word:neng2}} + verb, maybe: {{Word:ta1}} {{word:ke3}}-{{word:neng2}} {{word:zhi1dao4}}. (He might know.)"
          ],
          "ru": [
            "{{word:ke3}}-{{word:neng2}} + глагол — может быть: {{Word:ta1}} {{word:ke3}}-{{word:neng2}} {{word:zhi1dao4}}. (Он, может быть, знает.)"
          ],
          "zh": []
        }
      }
    ]
  },
  {
    "type": "info",
    "subtype": "grammar",
    "title": {
      "en": [
        "Lesson 8 · Time 1 — When it happens"
      ],
      "zh": [],
      "ru": [
        "Урок 8 · Время 1 — Когда это происходит"
      ]
    },
    "items": [
      {
        "text": {
          "en": [
            "verb + {{word:le}}, done: {{Word:wo3}} {{word:chi1}} {{word:le}}. (I ate.)"
          ],
          "ru": [
            "глагол + {{word:le}} — сделано: {{Word:wo3}} {{word:chi1}} {{word:le}}. (Я поел.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{Word:fa1}}-{{word:sheng1}} {{word:le}} {{word:shen2me}}? (What happened?)"
          ],
          "ru": [
            "{{Word:fa1}}-{{word:sheng1}} {{word:le}} {{word:shen2me}}? (Что случилось?)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:zai4}} + verb, right now: {{Word:wo3}} {{word:zai4}} {{word:chi1}}. (I'm eating.)"
          ],
          "ru": [
            "{{word:zai4}} + глагол — как раз сейчас: {{Word:wo3}} {{word:zai4}} {{word:chi1}}. (Я как раз ем.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:hui4}} + verb, will: {{Word:wo3}} {{word:hui4}} {{word:chi1}}. (I will eat.)"
          ],
          "ru": [
            "{{word:hui4}} + глагол — будет: {{Word:wo3}} {{word:hui4}} {{word:chi1}}. (Я буду есть.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "verb-{{word:guo4}}, done before: {{Word:wo3}} {{word:kan4}}-{{word:guo4}} {{word:zhe4}}-ge {{word:dong4}}-{{word:wu4}}. (I've seen this animal before.)"
          ],
          "ru": [
            "глагол-{{word:guo4}} — уже когда-то делал: {{Word:wo3}} {{word:kan4}}-{{word:guo4}} {{word:zhe4}}-ge {{word:dong4}}-{{word:wu4}}. (Я уже видел это животное.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "Time first: {{Word:yue4}}-{{word:de}} {{word:shi2}}-{{word:jian1}}, {{word:wo3}} {{word:shui4jiao4}}. (At night, I sleep.) {{Word:xian4}}-{{word:zai4}}, … (Now, …)"
          ],
          "ru": [
            "Сначала время: {{Word:yue4}}-{{word:de}} {{word:shi2}}-{{word:jian1}}, {{word:wo3}} {{word:shui4jiao4}}. (Ночью я сплю.) {{Word:xian4}}-{{word:zai4}}, … (Сейчас …)"
          ],
          "zh": []
        }
      }
    ]
  },
  {
    "type": "info",
    "subtype": "grammar",
    "title": {
      "en": [
        "Lesson 9 · Time 2 — Around an action"
      ],
      "zh": [],
      "ru": [
        "Урок 9 · Время 2 — Вокруг действия"
      ]
    },
    "items": [
      {
        "text": {
          "en": [
            "verb-{{word:de}} {{word:shi2}}-{{word:jian1}}, when: {{Word:wo3}} {{word:chi1}}-{{word:de}} {{word:shi2}}-{{word:jian1}}, {{word:wo3}} {{word:bu4}} {{word:shuo1}}. (When I eat, I don't talk.)"
          ],
          "ru": [
            "глагол-{{word:de}} {{word:shi2}}-{{word:jian1}} — когда: {{Word:wo3}} {{word:chi1}}-{{word:de}} {{word:shi2}}-{{word:jian1}}, {{word:wo3}} {{word:bu4}} {{word:shuo1}}. (Когда я ем, я не разговариваю.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "verb-{{word:wan2}} {{word:le}}, finished: {{Word:wo3}} {{word:chi1}}-{{word:wan2}} {{word:le}}. (I finished eating.)"
          ],
          "ru": [
            "глагол-{{word:wan2}} {{word:le}} — закончил: {{Word:wo3}} {{word:chi1}}-{{word:wan2}} {{word:le}}. (Я доел.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "verb-{{word:wan2}} {{word:hou4}}, after: {{Word:chi1}}-{{word:wan2}} {{word:hou4}}, {{word:wo3}} {{word:shui4jiao4}}. (After eating, I sleep.)"
          ],
          "ru": [
            "глагол-{{word:wan2}} {{word:hou4}} — после: {{Word:chi1}}-{{word:wan2}} {{word:hou4}}, {{word:wo3}} {{word:shui4jiao4}}. (После еды я сплю.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:kai1shi3}} + verb, start: {{Word:wo3}} {{word:kai1shi3}} {{word:wan2r}} {{word:le}}. (I started to play.)"
          ],
          "ru": [
            "{{word:kai1shi3}} + глагол — начать: {{Word:wo3}} {{word:kai1shi3}} {{word:wan2r}} {{word:le}}. (Я начал играть.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "verb + {{word:yi1}}-{{word:xia4}}, for a moment: {{Word:deng3}} {{word:yi1}}-{{word:xia4}}! (Wait a moment!)"
          ],
          "ru": [
            "глагол + {{word:yi1}}-{{word:xia4}} — на минутку: {{Word:deng3}} {{word:yi1}}-{{word:xia4}}! (Подожди минутку!)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:you4}} + verb + {{word:le}}, again: {{Word:ta1}} {{word:you4}} {{word:chi1}} {{word:le}}. (He ate again.)"
          ],
          "ru": [
            "{{word:you4}} + глагол + {{word:le}} — опять: {{Word:ta1}} {{word:you4}} {{word:chi1}} {{word:le}}. (Он опять поел.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:hen3}} {{word:duo1}} {{word:ci4}}, many times: {{Word:wo3}} {{word:kan4}}-{{word:guo4}} {{word:hen3}} {{word:duo1}} {{word:ci4}}. (I've seen it many times.)"
          ],
          "ru": [
            "{{word:hen3}} {{word:duo1}} {{word:ci4}} — много раз: {{Word:wo3}} {{word:kan4}}-{{word:guo4}} {{word:hen3}} {{word:duo1}} {{word:ci4}}. (Я видел это много раз.)"
          ],
          "zh": []
        }
      }
    ]
  },
  {
    "type": "info",
    "subtype": "grammar",
    "title": {
      "en": [
        "Lesson 10 · Space 1 — Where it is"
      ],
      "zh": [],
      "ru": [
        "Урок 10 · Пространство 1 — Где это"
      ]
    },
    "items": [
      {
        "text": {
          "en": [
            "{{word:zai4}} + place: {{Word:wo3}} {{word:zai4}} {{word:jia1}}. (I'm at home.)"
          ],
          "ru": [
            "{{word:zai4}} + место: {{Word:wo3}} {{word:zai4}} {{word:jia1}}. (Я дома.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:na3}}-{{word:li3}}, where: {{Word:ni3}} {{word:zai4}} {{word:na3}}-{{word:li3}}? (Where are you?)"
          ],
          "ru": [
            "{{word:na3}}-{{word:li3}} — где: {{Word:ni3}} {{word:zai4}} {{word:na3}}-{{word:li3}}? (Где ты?)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "place-{{word:li3}} (in), place-{{word:shang4}} (on): {{Word:shui3}} {{word:zai4}} {{word:he2zi}}-{{word:li3}}. (The water is in the box.) {{word:wang3}}-{{word:shang4}}, online: {{Word:wo3}} {{word:zai4}} {{word:wang3}}-{{word:shang4}} {{word:zhao3}}. (I'm looking online.)"
          ],
          "ru": [
            "место-{{word:li3}} (в), место-{{word:shang4}} (на): {{Word:shui3}} {{word:zai4}} {{word:he2zi}}-{{word:li3}}. (Вода в коробке.) {{word:wang3}}-{{word:shang4}} — в интернете: {{Word:wo3}} {{word:zai4}} {{word:wang3}}-{{word:shang4}} {{word:zhao3}}. (Я ищу в интернете.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "X-{{word:de}} {{word:qian2}}-{{word:mian4}} / {{word:hou4}}-{{word:mian4}} / {{word:xia4}}-{{word:mian4}} / {{word:pang2bian1}}: {{Word:wo3}} {{word:zai4}} {{word:ni3}}-{{word:de}} {{word:pang2bian1}}. (I'm beside you.)"
          ],
          "ru": [
            "X-{{word:de}} {{word:qian2}}-{{word:mian4}} / {{word:hou4}}-{{word:mian4}} / {{word:xia4}}-{{word:mian4}} / {{word:pang2bian1}}: {{Word:wo3}} {{word:zai4}} {{word:ni3}}-{{word:de}} {{word:pang2bian1}}. (Я рядом с тобой.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:zai4}} {{word:zhong1}}-{{word:jian1}}, in the middle: {{Word:he2zi}} {{word:zai4}} {{word:zhong1}}-{{word:jian1}}. (The box is in the middle.)"
          ],
          "ru": [
            "{{word:zai4}} {{word:zhong1}}-{{word:jian1}} — посередине: {{Word:he2zi}} {{word:zai4}} {{word:zhong1}}-{{word:jian1}}. (Коробка посередине.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:zuo3}}-{{word:bian1}} / {{word:you4}}-{{word:bian1}}, left / right: {{Word:he2zi}} {{word:zai4}} {{word:wo3}}-{{word:de}} {{word:zuo3}}-{{word:bian1}}. (The box is on my left.)"
          ],
          "ru": [
            "{{word:zuo3}}-{{word:bian1}} / {{word:you4}}-{{word:bian1}} — слева / справа: {{Word:he2zi}} {{word:zai4}} {{word:wo3}}-{{word:de}} {{word:zuo3}}-{{word:bian1}}. (Коробка слева от меня.)"
          ],
          "zh": []
        }
      }
    ]
  },
  {
    "type": "info",
    "subtype": "grammar",
    "title": {
      "en": [
        "Lesson 11 · Space 2 — Moving"
      ],
      "zh": [],
      "ru": [
        "Урок 11 · Пространство 2 — Движение"
      ]
    },
    "items": [
      {
        "text": {
          "en": [
            "{{word:lai2}} / {{word:qu4}} + place: {{Word:wo3}} {{word:qu4}} {{word:ba4ba}}-{{word:ma1ma}}-{{word:de}} {{word:jia1}}. (I'm going to my parents' home.)"
          ],
          "ru": [
            "{{word:lai2}} / {{word:qu4}} + место: {{Word:wo3}} {{word:qu4}} {{word:ba4ba}}-{{word:ma1ma}}-{{word:de}} {{word:jia1}}. (Я иду домой к родителям.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:cong2}} + place + {{word:lai2}}: {{Word:wo3}} {{word:cong2}} {{word:jia1}} {{word:lai2}}. (I come from home.)"
          ],
          "ru": [
            "{{word:cong2}} + место + {{word:lai2}}: {{Word:wo3}} {{word:cong2}} {{word:jia1}} {{word:lai2}}. (Я пришёл из дома.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:dao4}} + place, arrive: {{Word:wo3}} {{word:dao4}} {{word:jia1}} {{word:le}}. (I've arrived home.)"
          ],
          "ru": [
            "{{word:dao4}} + место — добраться: {{Word:wo3}} {{word:dao4}} {{word:jia1}} {{word:le}}. (Я пришёл домой.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:qi3}}-{{word:lai2}} (get up), {{word:shang4}}-{{word:lai2}} (come up), {{word:xia4}}-{{word:lai2}} (come down); with {{word:qu4}} for going away."
          ],
          "ru": [
            "{{word:qi3}}-{{word:lai2}} (вставать), {{word:shang4}}-{{word:lai2}} (подняться сюда), {{word:xia4}}-{{word:lai2}} (спуститься сюда); с {{word:qu4}} — движение от говорящего."
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:dong4}}, move: {{Word:bu4}} {{word:yao4}} {{word:dong4}}! (Don't move!)"
          ],
          "ru": [
            "{{word:dong4}} — двигаться: {{Word:bu4}} {{word:yao4}} {{word:dong4}}! (Не двигайся!)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:yuan3}} / {{word:fu4jin4}}, far / nearby: {{Word:wo3}}-{{word:de}} {{word:guo2}} {{word:hen3}} {{word:yuan3}}. (My country is far.) {{Word:wo3}}-{{word:de}} {{word:jia1}} {{word:zai4}} {{word:fu4jin4}}. (My home is nearby.)"
          ],
          "ru": [
            "{{word:yuan3}} / {{word:fu4jin4}} — далеко / поблизости: {{Word:wo3}}-{{word:de}} {{word:guo2}} {{word:hen3}} {{word:yuan3}}. (Моя страна далеко.) {{Word:wo3}}-{{word:de}} {{word:jia1}} {{word:zai4}} {{word:fu4jin4}}. (Мой дом поблизости.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:lu4}}, road, way: {{Word:ni3}} {{word:zhi1dao4}} {{word:lu4}} {{word:ma}}? (Do you know the way?) {{word:che1}}, car: {{Word:che1}} {{word:zai4}} {{word:lu4}}-{{word:shang4}}. (The car is on the road.)"
          ],
          "ru": [
            "{{word:lu4}} — дорога, путь: {{Word:ni3}} {{word:zhi1dao4}} {{word:lu4}} {{word:ma}}? (Ты знаешь дорогу?) {{word:che1}} — машина: {{Word:che1}} {{word:zai4}} {{word:lu4}}-{{word:shang4}}. (Машина на дороге.)"
          ],
          "zh": []
        }
      }
    ]
  },
  {
    "type": "info",
    "subtype": "grammar",
    "title": {
      "en": [
        "Lesson 12 · Modifiers 1 — How much"
      ],
      "zh": [],
      "ru": [
        "Урок 12 · Уточнения 1 — Насколько"
      ]
    },
    "items": [
      {
        "text": {
          "en": [
            "{{word:hen3}} + adjective, very: {{Word:shui3}} {{word:hen3}} {{word:re4}}. (The water is very hot.)"
          ],
          "ru": [
            "{{word:hen3}} + прилагательное — очень: {{Word:shui3}} {{word:hen3}} {{word:re4}}. (Вода очень горячая.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:hen3}} {{word:you3}} {{word:jia4zhi2}}, valuable: {{Word:zhe4}}-ge {{word:gong1}}-{{word:ju4}} {{word:hen3}} {{word:you3}} {{word:jia4zhi2}}. (This tool is very valuable.)"
          ],
          "ru": [
            "{{word:hen3}} {{word:you3}} {{word:jia4zhi2}} — ценный: {{Word:zhe4}}-ge {{word:gong1}}-{{word:ju4}} {{word:hen3}} {{word:you3}} {{word:jia4zhi2}}. (Этот инструмент очень ценный.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:zhen1}} + adjective, really: {{Word:zhen1}} {{word:re4}}! (It's really hot!)"
          ],
          "ru": [
            "{{word:zhen1}} + прилагательное — правда: {{Word:zhen1}} {{word:re4}}! (Правда жарко!)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:bu4}} / {{word:bu4}} {{word:hen3}} + adjective, not / not very: {{Word:shui3}} {{word:bu4}} {{word:leng3}}. (The water isn't cold.)"
          ],
          "ru": [
            "{{word:bu4}} / {{word:bu4}} {{word:hen3}} + прилагательное — не / не очень: {{Word:shui3}} {{word:bu4}} {{word:leng3}}. (Вода не холодная.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:hen3}} {{word:nan2}}, difficult; {{word:hao3}}-{{word:kan4}} / {{word:nan2}}-{{word:kan4}}, beautiful / ugly: {{Word:ta1}} {{word:hen3}} {{word:hao3}}-{{word:kan4}}. (She's beautiful.)"
          ],
          "ru": [
            "{{word:hen3}} {{word:nan2}} — трудно; {{word:hao3}}-{{word:kan4}} / {{word:nan2}}-{{word:kan4}} — красивый / некрасивый: {{Word:ta1}} {{word:hen3}} {{word:hao3}}-{{word:kan4}}. (Она красивая.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "adjective + {{word:ma}}?, asking: {{Word:ni3}} {{word:leng3}} {{word:ma}}? (Are you cold?)"
          ],
          "ru": [
            "прилагательное + {{word:ma}}? — вопрос: {{Word:ni3}} {{word:leng3}} {{word:ma}}? (Тебе холодно?)"
          ],
          "zh": []
        }
      }
    ]
  },
  {
    "type": "info",
    "subtype": "grammar",
    "title": {
      "en": [
        "Lesson 13 · Modifiers 2 — Comparing"
      ],
      "zh": [],
      "ru": [
        "Урок 13 · Уточнения 2 — Сравнение"
      ]
    },
    "items": [
      {
        "text": {
          "en": [
            "A {{word:bi3}} B + adjective: {{Word:wo3}} {{word:bi3}} {{word:ni3}} {{word:da4}}. (I'm bigger than you.) No {{word:hen3}} here."
          ],
          "ru": [
            "A {{word:bi3}} B + прилагательное: {{Word:wo3}} {{word:bi3}} {{word:ni3}} {{word:da4}}. (Я больше тебя.) Без {{word:hen3}}."
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:zui4}} + adjective, the most: {{Word:zhe4}}-ge {{word:zui4}} {{word:da4}}. (This one is the biggest.)"
          ],
          "ru": [
            "{{word:zui4}} + прилагательное — самый: {{Word:zhe4}}-ge {{word:zui4}} {{word:da4}}. (Этот самый большой.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:yi1}}-{{word:yang4}}, the same: {{Word:ta1}}-{{word:men}} {{word:yi1}}-{{word:yang4}}. (They're the same.)"
          ],
          "ru": [
            "{{word:yi1}}-{{word:yang4}} — одинаковый: {{Word:ta1}}-{{word:men}} {{word:yi1}}-{{word:yang4}}. (Они одинаковые.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:bu4}} {{word:yi1}}-{{word:yang4}}, different: {{Word:wo3}} {{word:yao4}} {{word:bu4}}-{{word:yi1}}-{{word:yang4}}-{{word:de}} {{word:yi1fu}}. (I want different clothes.)"
          ],
          "ru": [
            "{{word:bu4}} {{word:yi1}}-{{word:yang4}} — разный: {{Word:wo3}} {{word:yao4}} {{word:bu4}}-{{word:yi1}}-{{word:yang4}}-{{word:de}} {{word:yi1fu}}. (Мне нужна другая одежда.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:bie2}}-{{word:de}}, other: {{Word:wo3}} {{word:yao4}} {{word:bie2}}-{{word:de}}. (I want something else.)"
          ],
          "ru": [
            "{{word:bie2}}-{{word:de}} — другой: {{Word:wo3}} {{word:yao4}} {{word:bie2}}-{{word:de}}. (Мне нужно что-то другое.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:zhe4}}-{{word:zhong3}} + noun, this kind of: {{word:zhe4}}-{{word:zhong3}} {{word:zhi2wu4}} (this kind of plant)"
          ],
          "ru": [
            "{{word:zhe4}}-{{word:zhong3}} + существительное — такой вид: {{word:zhe4}}-{{word:zhong3}} {{word:zhi2wu4}} (такие растения)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "Thing + {{word:hen3}} + {{word:ying4}} / {{word:yuan2}} / {{word:gao1}}, how it feels or looks: {{Word:yue4}} {{word:hen3}} {{word:yuan2}}. (The moon is round.)"
          ],
          "ru": [
            "Вещь + {{word:hen3}} + {{word:ying4}} / {{word:yuan2}} / {{word:gao1}} — какая она на ощупь или на вид: {{Word:yue4}} {{word:hen3}} {{word:yuan2}}. (Луна круглая.)"
          ],
          "zh": []
        }
      }
    ]
  },
  {
    "type": "info",
    "subtype": "grammar",
    "title": {
      "en": [
        "Lesson 14 · Modifiers 3 — Also and all"
      ],
      "zh": [],
      "ru": [
        "Урок 14 · Уточнения 3 — Тоже и все"
      ]
    },
    "items": [
      {
        "text": {
          "en": [
            "{{word:ye3}} + verb, also: {{Word:wo3}} {{word:ye3}} {{word:chi1}}. (I eat too.)"
          ],
          "ru": [
            "{{word:ye3}} + глагол — тоже: {{Word:wo3}} {{word:ye3}} {{word:chi1}}. (Я тоже ем.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:kai1}} / {{word:guan1}} {{word:deng1}}, light on / off: {{Word:kai1}} {{word:deng1}}! (Turn on the light!) {{word:hen3}} {{word:ming2}}, bright: {{Word:deng1}} {{word:hen3}} {{word:ming2}}. (The light is bright.)"
          ],
          "ru": [
            "{{word:kai1}} / {{word:guan1}} {{word:deng1}} — включить / выключить свет: {{Word:kai1}} {{word:deng1}}! (Включи свет!) {{word:hen3}} {{word:ming2}} — яркий: {{Word:deng1}} {{word:hen3}} {{word:ming2}}. (Свет яркий.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:ye3}} {{word:hen3}} + adjective: {{Word:ta1}} {{word:ye3}} {{word:hen3}} {{word:leng3}}. (She's cold too.)"
          ],
          "ru": [
            "{{word:ye3}} {{word:hen3}} + прилагательное: {{Word:ta1}} {{word:ye3}} {{word:hen3}} {{word:leng3}}. (Ей тоже холодно.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:dou1}} + verb, all: {{Word:wo3}}-{{word:men}} {{word:dou1}} {{word:chi1}}. (We all eat.)"
          ],
          "ru": [
            "{{word:dou1}} + глагол — все: {{Word:wo3}}-{{word:men}} {{word:dou1}} {{word:chi1}}. (Мы все едим.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:shen2me}}-{{word:dou1}} + verb, everything: {{Word:wo3}} {{word:shen2me}}-{{word:dou1}} {{word:chi1}}. (I eat everything.) With {{word:bu4}}: nothing. {{word:na3}}-{{word:li3}}-{{word:dou1}}: everywhere."
          ],
          "ru": [
            "{{word:shen2me}}-{{word:dou1}} + глагол — всё: {{Word:wo3}} {{word:shen2me}}-{{word:dou1}} {{word:chi1}}. (Я ем всё.) С {{word:bu4}} — ничего. {{word:na3}}-{{word:li3}}-{{word:dou1}} — везде."
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:bu4}}-{{light:fen1}}, part: {{Word:zhe4}} {{word:bu4}}-{{light:fen1}} {{word:hen3}} {{word:hao3}}. (This part is good.) {{word:da4}} {{word:bu4}}-{{light:fen1}}: most."
          ],
          "ru": [
            "{{word:bu4}}-{{light:fen1}} — часть: {{Word:zhe4}} {{word:bu4}}-{{light:fen1}} {{word:hen3}} {{word:hao3}}. (Эта часть хорошая.) {{word:da4}} {{word:bu4}}-{{light:fen1}} — большинство."
          ],
          "zh": []
        }
      }
    ]
  },
  {
    "type": "info",
    "subtype": "grammar",
    "title": {
      "en": [
        "Lesson 15 · Modifiers 4 — Becoming and making"
      ],
      "zh": [],
      "ru": [
        "Урок 15 · Уточнения 4 — Становиться и делать"
      ]
    },
    "items": [
      {
        "text": {
          "en": [
            "adjective + {{word:le}}, it changed: {{Word:shui3}} {{word:re4}} {{word:le}}. (The water got hot.)"
          ],
          "ru": [
            "прилагательное + {{word:le}} — изменилось: {{Word:shui3}} {{word:re4}} {{word:le}}. (Вода нагрелась.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:bian4}} + adjective + {{word:le}}, became: {{Word:shui3}} {{word:bian4}} {{word:leng3}} {{word:le}}. (The water turned cold.)"
          ],
          "ru": [
            "{{word:bian4}} + прилагательное + {{word:le}} — стало: {{Word:shui3}} {{word:bian4}} {{word:leng3}} {{word:le}}. (Вода стала холодной.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:zuo4}} + result, make it so: {{Word:wo3}} {{word:zuo4}} {{word:hao3}} {{word:le}}. (I fixed it.)"
          ],
          "ru": [
            "{{word:zuo4}} + результат — сделать таким: {{Word:wo3}} {{word:zuo4}} {{word:hao3}} {{word:le}}. (Я починил.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:ba3}} + thing + {{word:zuo4}} + result: {{Word:wo3}} {{word:ba3}} {{word:gong1}}-{{word:ju4}} {{word:zuo4}} {{word:hao3}} {{word:le}}. (I fixed the tool.)"
          ],
          "ru": [
            "{{word:ba3}} + вещь + {{word:zuo4}} + результат: {{Word:wo3}} {{word:ba3}} {{word:gong1}}-{{word:ju4}} {{word:zuo4}} {{word:hao3}} {{word:le}}. (Я починил инструмент.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:ba3}} + thing + {{word:fang4}} {{word:zai4}} + place, put: {{Word:wo3}} {{word:ba3}} {{word:yi1fu}} {{word:fang4}} {{word:zai4}} {{word:di4}}-{{word:shang4}} {{word:le}}. (I put the clothes on the floor.)"
          ],
          "ru": [
            "{{word:ba3}} + вещь + {{word:fang4}} {{word:zai4}} + место — положить: {{Word:wo3}} {{word:ba3}} {{word:yi1fu}} {{word:fang4}} {{word:zai4}} {{word:di4}}-{{word:shang4}} {{word:le}}. (Я положил одежду на пол.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:you3}} {{word:li4}}, strong: {{Word:ta1}} {{word:hen3}} {{word:you3}} {{word:li4}}. (He's very strong.)"
          ],
          "ru": [
            "{{word:you3}} {{word:li4}} — сильный: {{Word:ta1}} {{word:hen3}} {{word:you3}} {{word:li4}}. (Он очень сильный.)"
          ],
          "zh": []
        }
      }
    ]
  },
  {
    "type": "info",
    "subtype": "grammar",
    "title": {
      "en": [
        "Lesson 16 · Verbs 2 — Direction and result"
      ],
      "zh": [],
      "ru": [
        "Урок 16 · Глаголы 2 — Направление и результат"
      ]
    },
    "items": [
      {
        "text": {
          "en": [
            "verb-{{word:lai2}} / verb-{{word:qu4}}, toward you / away: {{Word:ba3}} {{word:shui3}} {{word:na2}}-{{word:lai2}}! (Bring the water!)"
          ],
          "ru": [
            "глагол-{{word:lai2}} / глагол-{{word:qu4}} — к вам / от вас: {{Word:ba3}} {{word:shui3}} {{word:na2}}-{{word:lai2}}! (Принеси воду!)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:jin4}} / {{word:chu1}} / {{word:hui2}} + {{word:lai2}} / {{word:qu4}}, in / out / back: {{Word:ni3}} {{word:jin4}}-{{word:lai2}}! (Come in!) {{Word:wo3}} {{word:yao4}} {{word:hui2}} {{word:jia1}}. (I want to go home.)"
          ],
          "ru": [
            "{{word:jin4}} / {{word:chu1}} / {{word:hui2}} + {{word:lai2}} / {{word:qu4}} — внутрь / наружу / обратно: {{Word:ni3}} {{word:jin4}}-{{word:lai2}}! (Входи!) {{Word:wo3}} {{word:yao4}} {{word:hui2}} {{word:jia1}}. (Я хочу домой.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:zuo4}}-{{word:xia4}} / {{word:zhan4}}-{{word:qi3}}-{{word:lai2}} / {{word:tang3}}-{{word:xia4}}, sit down / stand up / lie down: {{Word:ni3}} {{word:zuo4}}-{{word:xia4}}! (Sit down!)"
          ],
          "ru": [
            "{{word:zuo4}}-{{word:xia4}} / {{word:zhan4}}-{{word:qi3}}-{{word:lai2}} / {{word:tang3}}-{{word:xia4}} — сесть / встать / лечь: {{Word:ni3}} {{word:zuo4}}-{{word:xia4}}! (Садись!)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "verb + direction words: {{Word:ta1}} {{word:ba3}} {{word:jin1}} {{word:na2}}-{{word:chu1}}-{{word:lai2}} {{word:le}}. (He took out the money.)"
          ],
          "ru": [
            "глагол + слова направления: {{Word:ta1}} {{word:ba3}} {{word:jin1}} {{word:na2}}-{{word:chu1}}-{{word:lai2}} {{word:le}}. (Он вынул деньги.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "verb-result: {{Word:wo3}} {{word:zhao3}}-{{word:dao4}} {{word:le}}. (I found it.)"
          ],
          "ru": [
            "глагол-результат: {{Word:wo3}} {{word:zhao3}}-{{word:dao4}} {{word:le}}. (Я нашёл.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "verb-{{word:de}}-result / verb-{{word:bu4}}-result, can / can't: {{Word:wo3}}-{{word:de}} {{word:yan3jing}} {{word:bu4}} {{word:hao3}}, {{word:kan4}}-{{word:bu4}}-{{word:dao4}}. (My eyes are bad, I can't see.)"
          ],
          "ru": [
            "глагол-{{word:de}}-результат / глагол-{{word:bu4}}-результат — получается / не получается: {{Word:wo3}}-{{word:de}} {{word:yan3jing}} {{word:bu4}} {{word:hao3}}, {{word:kan4}}-{{word:bu4}}-{{word:dao4}}. (У меня плохие глаза, мне не видно.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:tong1}}-{{word:guo4}} + place, go through; {{word:tong1}}-{{word:dao4}} + place, lead to: {{Word:zhe4}}-ge {{word:lu4}} {{word:tong1}}-{{word:dao4}} {{word:wo3}}-{{word:de}} {{word:jia1}}. (This road leads to my home.)"
          ],
          "ru": [
            "{{word:tong1}}-{{word:guo4}} + место — пройти через; {{word:tong1}}-{{word:dao4}} + место — вести туда: {{Word:zhe4}}-ge {{word:lu4}} {{word:tong1}}-{{word:dao4}} {{word:wo3}}-{{word:de}} {{word:jia1}}. (Эта дорога ведёт к моему дому.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "verb-{{word:qi3}}-{{word:lai2}}, seems: {{Word:zhe4}}-ge {{word:kan4}}-{{word:qi3}}-{{word:lai2}} {{word:hen3}} {{word:hao3}}. (This looks good.) verb-{{word:xia4}}-{{word:qu4}}, keep going: {{Word:shuo1}}-{{word:xia4}}-{{word:qu4}}! (Keep talking!)"
          ],
          "ru": [
            "глагол-{{word:qi3}}-{{word:lai2}} — кажется: {{Word:zhe4}}-ge {{word:kan4}}-{{word:qi3}}-{{word:lai2}} {{word:hen3}} {{word:hao3}}. (Это выглядит хорошо.) глагол-{{word:xia4}}-{{word:qu4}} — продолжать: {{Word:shuo1}}-{{word:xia4}}-{{word:qu4}}! (Говори дальше!)"
          ],
          "zh": []
        }
      }
    ]
  },
  {
    "type": "info",
    "subtype": "grammar",
    "title": {
      "en": [
        "Lesson 17 · Numbers"
      ],
      "zh": [],
      "ru": [
        "Урок 17 · Числа"
      ]
    },
    "items": [
      {
        "text": {
          "en": [
            "1 {{word:yi1}}, 2 {{word:er4}}, 3 {{word:san1}}, 4 {{word:si4}}, 5 {{word:wu3}}, 6 {{word:liu4}}, 7 {{word:qi1}}, 8 {{word:ba1}}, 9 {{word:jiu3}}, 10 {{word:shi2}}"
          ],
          "ru": [
            "1 {{word:yi1}}, 2 {{word:er4}}, 3 {{word:san1}}, 4 {{word:si4}}, 5 {{word:wu3}}, 6 {{word:liu4}}, 7 {{word:qi1}}, 8 {{word:ba1}}, 9 {{word:jiu3}}, 10 {{word:shi2}}"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "number + {{word:ge4}} + noun: {{Word:san1}}-ge {{word:ren2}} (three people). For two things, {{word:liang3}}-ge."
          ],
          "ru": [
            "число + {{word:ge4}} + существительное: {{Word:san1}}-ge {{word:ren2}} (три человека). Для двух вещей — {{word:liang3}}-ge."
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "number-ge, without the noun: {{Word:ta1}} {{word:yao4}} {{word:liu4}}-ge. (He wants six.)"
          ],
          "ru": [
            "число-ge без существительного: {{Word:ta1}} {{word:yao4}} {{word:liu4}}-ge. (Он хочет шесть.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "number-{{word:zhong3}} / -{{word:ci4}} / -{{word:bu4}}-{{light:fen1}}, kinds / times / parts: {{Word:wo3}} {{word:qu4}}-{{word:guo4}} {{word:san1}}-{{word:ci4}}. (I've been there three times.)"
          ],
          "ru": [
            "число-{{word:zhong3}} / -{{word:ci4}} / -{{word:bu4}}-{{light:fen1}} — виды / разы / части: {{Word:wo3}} {{word:qu4}}-{{word:guo4}} {{word:san1}}-{{word:ci4}}. (Я был там три раза.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "Above ten: {{word:shi2}}-{{word:er4}} (12), {{word:er4}}-{{word:shi2}} (20)"
          ],
          "ru": [
            "Больше десяти: {{word:shi2}}-{{word:er4}} (12), {{word:er4}}-{{word:shi2}} (20)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "number + {{word:hao4}}, number …: {{Word:er4}}-{{word:hao4}} (number two)"
          ],
          "ru": [
            "число + {{word:hao4}} — номер: {{Word:er4}}-{{word:hao4}} (номер два)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "number + {{word:dian3}}, o'clock: {{Word:xian4}}-{{word:zai4}} {{word:shi4}} {{word:san1}}-{{word:dian3}}. (It's three o'clock now.)"
          ],
          "ru": [
            "число + {{word:dian3}} — час: {{Word:xian4}}-{{word:zai4}} {{word:shi4}} {{word:san1}}-{{word:dian3}}. (Сейчас три часа.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "number + {{word:tian1}} / {{word:nian2}}: {{word:san1}} {{word:tian1}} (three days); {{word:ming2}}-{{word:tian1}} (tomorrow), {{word:qu4}}-{{word:nian2}} (last year)"
          ],
          "ru": [
            "число + {{word:tian1}} / {{word:nian2}}: {{word:san1}} {{word:tian1}} (три дня); {{word:ming2}}-{{word:tian1}} (завтра), {{word:qu4}}-{{word:nian2}} (в прошлом году)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:yi1}}-{{word:dian3}}, a little: {{Word:wo3}} {{word:yao4}} {{word:yi1}}-{{word:dian3}} {{word:shui3}}. (I want a little water.) {{Word:zhe4}}-ge {{word:da4}} {{word:yi1}}-{{word:dian3}}. (This one is a bit bigger.)"
          ],
          "ru": [
            "{{word:yi1}}-{{word:dian3}} — немного: {{Word:wo3}} {{word:yao4}} {{word:yi1}}-{{word:dian3}} {{word:shui3}}. (Я хочу немного воды.) {{Word:zhe4}}-ge {{word:da4}} {{word:yi1}}-{{word:dian3}}. (Этот чуть больше.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "A, B {{word:fang4}} {{word:zai4}} {{word:yi1}}-{{word:qi3}}, add: {{Word:san1}}, {{word:si4}} {{word:fang4}} {{word:zai4}} {{word:yi1}}-{{word:qi3}}, {{word:shi4}} {{word:qi1}}. (3 + 4 = 7) {{word:cong2}} A {{word:li3}}-{{word:mian4}} {{word:na2}} B, take away: {{Word:cong2}} {{word:qi1}} {{word:li3}}-{{word:mian4}} {{word:na2}} {{word:san1}}, {{word:shi4}} {{word:si4}}. (7 − 3 = 4)"
          ],
          "ru": [
            "A, B {{word:fang4}} {{word:zai4}} {{word:yi1}}-{{word:qi3}} — сложить: {{Word:san1}}, {{word:si4}} {{word:fang4}} {{word:zai4}} {{word:yi1}}-{{word:qi3}}, {{word:shi4}} {{word:qi1}}. (3 + 4 = 7) {{word:cong2}} A {{word:li3}}-{{word:mian4}} {{word:na2}} B — отнять: {{Word:cong2}} {{word:qi1}} {{word:li3}}-{{word:mian4}} {{word:na2}} {{word:san1}}, {{word:shi4}} {{word:si4}}. (7 − 3 = 4)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:fang4}} {{word:zai4}} {{word:yi1}}-{{word:qi3}} B-{{word:ci4}}, multiply: {{Word:ba3}} {{word:si4}} {{word:fang4}} {{word:zai4}} {{word:yi1}}-{{word:qi3}} {{word:san1}}-{{word:ci4}}, {{word:shi4}} {{word:shi2}}-{{word:er4}}. (3 × 4 = 12) {{word:na2}} A, {{word:neng2}} {{word:na2}} B-{{word:ci4}}, divide: {{Word:cong2}} {{word:shi2}}-{{word:er4}} {{word:li3}}-{{word:mian4}} {{word:na2}} {{word:si4}}, {{word:neng2}} {{word:na2}} {{word:san1}}-{{word:ci4}}. (12 ÷ 4 = 3)"
          ],
          "ru": [
            "{{word:fang4}} {{word:zai4}} {{word:yi1}}-{{word:qi3}} B-{{word:ci4}} — умножить: {{Word:ba3}} {{word:si4}} {{word:fang4}} {{word:zai4}} {{word:yi1}}-{{word:qi3}} {{word:san1}}-{{word:ci4}}, {{word:shi4}} {{word:shi2}}-{{word:er4}}. (3 × 4 = 12) {{word:na2}} A, {{word:neng2}} {{word:na2}} B-{{word:ci4}} — разделить: {{Word:cong2}} {{word:shi2}}-{{word:er4}} {{word:li3}}-{{word:mian4}} {{word:na2}} {{word:si4}}, {{word:neng2}} {{word:na2}} {{word:san1}}-{{word:ci4}}. (12 ÷ 4 = 3)"
          ],
          "zh": []
        }
      }
    ]
  },
  {
    "type": "info",
    "subtype": "grammar",
    "title": {
      "en": [
        "Lesson 18 · Colors"
      ],
      "zh": [],
      "ru": [
        "Урок 18 · Цвета"
      ]
    },
    "items": [
      {
        "text": {
          "en": [
            "color-{{word:de}} + noun: {{word:hong2}}-{{word:se4}}-{{word:de}} {{word:he2zi}} (a red box)"
          ],
          "ru": [
            "цвет-{{word:de}} + существительное: {{word:hong2}}-{{word:se4}}-{{word:de}} {{word:he2zi}} (красная коробка)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "Thing + {{word:shi4}} + color-{{word:de}}: {{Word:he2zi}} {{word:shi4}} {{word:hong2}}-{{word:se4}}-{{word:de}}. (The box is red.)"
          ],
          "ru": [
            "Вещь + {{word:shi4}} + цвет-{{word:de}}: {{Word:he2zi}} {{word:shi4}} {{word:hong2}}-{{word:se4}}-{{word:de}}. (Коробка красная.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:shen2me}} {{word:yan2se4}}, what color: {{Word:ni3}}-{{word:de}} {{word:yi1fu}} {{word:shi4}} {{word:shen2me}} {{word:yan2se4}}? (What color are your clothes?)"
          ],
          "ru": [
            "{{word:shen2me}} {{word:yan2se4}} — какого цвета: {{Word:ni3}}-{{word:de}} {{word:yi1fu}} {{word:shi4}} {{word:shen2me}} {{word:yan2se4}}? (Какого цвета твоя одежда?)"
          ],
          "zh": []
        }
      }
    ]
  },
  {
    "type": "info",
    "subtype": "grammar",
    "title": {
      "en": [
        "Lesson 19 · Changing the Role of a Word"
      ],
      "zh": [],
      "ru": [
        "Урок 19 · Слово в новой роли"
      ]
    },
    "items": [
      {
        "text": {
          "en": [
            "verb-{{word:de}}, the thing: {{word:chi1}}-{{word:de}} (food, something to eat)"
          ],
          "ru": [
            "глагол-{{word:de}} — вещь: {{word:chi1}}-{{word:de}} (еда, то, что едят)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "verb-{{word:de}} {{word:ren2}}, the one who: {{word:xie3}}-{{word:de}} {{word:ren2}} (the one who writes)"
          ],
          "ru": [
            "глагол-{{word:de}} {{word:ren2}} — тот, кто: {{word:xie3}}-{{word:de}} {{word:ren2}} (тот, кто пишет)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "verb-{{word:de}} + adjective, how: {{Word:ta1}} {{word:shuo1}}-{{word:de}} {{word:hao3}}. (She speaks well.)"
          ],
          "ru": [
            "глагол-{{word:de}} + прилагательное — как: {{Word:ta1}} {{word:shuo1}}-{{word:de}} {{word:hao3}}. (Она хорошо говорит.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "a longer description-{{word:de}} + noun: {{word:zai4}}-{{word:shui3}}-{{word:li3}}-{{word:de}} {{word:dong4}}-{{word:wu4}} (an animal in the water), {{word:zhi2wu4}} {{word:sheng1}}-{{word:de}} {{word:dong1}}-{{light:xi1}} (fruit)"
          ],
          "ru": [
            "более длинное описание-{{word:de}} + существительное: {{word:zai4}}-{{word:shui3}}-{{word:li3}}-{{word:de}} {{word:dong4}}-{{word:wu4}} (животное в воде), {{word:zhi2wu4}} {{word:sheng1}}-{{word:de}} {{word:dong1}}-{{light:xi1}} (фрукт)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "adjective-{{word:de}} + noun: {{word:hao3}}-{{word:de}} {{word:ren2}} (a good person). Whose: {{word:wo3}}-{{word:de}} {{word:bi2zi}} (my nose)."
          ],
          "ru": [
            "прилагательное-{{word:de}} + существительное: {{word:hao3}}-{{word:de}} {{word:ren2}} (хороший человек). Чьё: {{word:wo3}}-{{word:de}} {{word:bi2zi}} (мой нос)."
          ],
          "zh": []
        }
      }
    ]
  },
  {
    "type": "info",
    "subtype": "grammar",
    "title": {
      "en": [
        "Lesson 20 · Relationships 1 — Inside a sentence"
      ],
      "zh": [],
      "ru": [
        "Урок 20 · Связи 1 — Внутри предложения"
      ]
    },
    "items": [
      {
        "text": {
          "en": [
            "{{word:gei3}} + person + thing, give: {{Word:wo3}} {{word:gei3}} {{word:ni3}} {{word:shui3}}. (I give you water.)"
          ],
          "ru": [
            "{{word:gei3}} + человек + вещь — давать: {{Word:wo3}} {{word:gei3}} {{word:ni3}} {{word:shui3}}. (Я даю тебе воду.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:yong4}} + thing + verb, with: {{Word:wo3}} {{word:yong4}} {{word:gong1}}-{{word:ju4}} {{word:xie3}}. (I write with a tool.)"
          ],
          "ru": [
            "{{word:yong4}} + вещь + глагол — чем: {{Word:wo3}} {{word:yong4}} {{word:gong1}}-{{word:ju4}} {{word:xie3}}. (Я пишу инструментом.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "A {{word:he2}} B, and (nouns only): {{word:ni3}} {{word:he2}} {{word:wo3}} (you and me)"
          ],
          "ru": [
            "A {{word:he2}} B — и (только для существительных): {{word:ni3}} {{word:he2}} {{word:wo3}} (ты и я)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "A {{word:huo4}}-{{word:zhe3}} B, or: {{word:zhe4}}-ge {{word:huo4}}-{{word:zhe3}} {{word:na4}}-ge (this one or that one)"
          ],
          "ru": [
            "A {{word:huo4}}-{{word:zhe3}} B — или: {{word:zhe4}}-ge {{word:huo4}}-{{word:zhe3}} {{word:na4}}-ge (это или то)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "A {{word:dui4}} B + adjective, toward / for: {{Word:ta1}} {{word:dui4}} {{word:wo3}} {{word:hen3}} {{word:hao3}}. (He's good to me.)"
          ],
          "ru": [
            "A {{word:dui4}} B + прилагательное — к кому / для кого: {{Word:ta1}} {{word:dui4}} {{word:wo3}} {{word:hen3}} {{word:hao3}}. (Он ко мне хорошо относится.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:yi1}} / {{word:zhe4}} / {{word:na4}} + {{word:qun2}} + noun, a group: {{Word:yi1}}-{{word:qun2}} {{word:ren2}} {{word:zai4}} {{word:wai4}}-{{word:mian4}}. (A group of people is outside.)"
          ],
          "ru": [
            "{{word:yi1}} / {{word:zhe4}} / {{word:na4}} + {{word:qun2}} + существительное — группа: {{Word:yi1}}-{{word:qun2}} {{word:ren2}} {{word:zai4}} {{word:wai4}}-{{word:mian4}}. (На улице группа людей.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "A {{word:he2}} B-{{word:de}} {{word:guan1xi}}, relationship: {{Word:wo3}} {{word:he2}} {{word:ta1}}-{{word:de}} {{word:guan1xi}} {{word:hen3}} {{word:hao3}}. (He and I get along well.) {{Word:mei2}}-{{word:you3}} {{word:guan1xi}}! (It doesn't matter!)"
          ],
          "ru": [
            "A {{word:he2}} B-{{word:de}} {{word:guan1xi}} — отношения: {{Word:wo3}} {{word:he2}} {{word:ta1}}-{{word:de}} {{word:guan1xi}} {{word:hen3}} {{word:hao3}}. (У нас с ним хорошие отношения.) {{Word:mei2}}-{{word:you3}} {{word:guan1xi}}! (Ничего страшного!)"
          ],
          "zh": []
        }
      }
    ]
  },
  {
    "type": "info",
    "subtype": "grammar",
    "title": {
      "en": [
        "Lesson 21 · Relationships 2 — Linking sentences"
      ],
      "zh": [],
      "ru": [
        "Урок 21 · Связи 2 — Как связать предложения"
      ]
    },
    "items": [
      {
        "text": {
          "en": [
            "{{word:yin1wei4}} + reason, result: {{Word:yin1wei4}} {{word:wo3}} {{word:hen3}} {{word:leng3}}, {{word:wo3}} {{word:bu4}} {{word:qu4}}. (Because I'm cold, I'm not going.)"
          ],
          "ru": [
            "{{word:yin1wei4}} + причина, результат: {{Word:yin1wei4}} {{word:wo3}} {{word:hen3}} {{word:leng3}}, {{word:wo3}} {{word:bu4}} {{word:qu4}}. (Так как мне холодно, я не пойду.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "…, {{word:dan4}}-{{word:shi4}} …, but: {{Word:zhe4}}-ge {{word:kan4}}-{{word:qi3}}-{{word:lai2}} {{word:hen3}} {{word:hao3}}, {{word:dan4}}-{{word:shi4}} {{word:wei4}}-{{word:dao4}} {{word:bu4}} {{word:hao3}}. (It looks good, but it doesn't taste good.)"
          ],
          "ru": [
            "…, {{word:dan4}}-{{word:shi4}} … — но: {{Word:zhe4}}-ge {{word:kan4}}-{{word:qi3}}-{{word:lai2}} {{word:hen3}} {{word:hao3}}, {{word:dan4}}-{{word:shi4}} {{word:wei4}}-{{word:dao4}} {{word:bu4}} {{word:hao3}}. (Выглядит хорошо, но невкусно.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:ru2guo3}} X, …, if: {{Word:ru2guo3}} {{word:ni3}} {{word:lai2}}, {{word:wo3}} {{word:deng3}} {{word:ni3}}. (If you come, I'll wait for you.)"
          ],
          "ru": [
            "{{word:ru2guo3}} X, … — если: {{Word:ru2guo3}} {{word:ni3}} {{word:lai2}}, {{word:wo3}} {{word:deng3}} {{word:ni3}}. (Если ты придёшь, я тебя подожду.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "who + {{word:jiu4}} + verb, then / right away: {{Word:ru2guo3}} {{word:ni3}} {{word:lai2}}, {{word:wo3}} {{word:jiu4}} {{word:deng3}} {{word:ni3}}. (If you come, I'll wait for you.)"
          ],
          "ru": [
            "кто + {{word:jiu4}} + глагол — то / сразу: {{Word:ru2guo3}} {{word:ni3}} {{word:lai2}}, {{word:wo3}} {{word:jiu4}} {{word:deng3}} {{word:ni3}}. (Если ты придёшь, то я тебя подожду.)"
          ],
          "zh": []
        }
      }
    ]
  },
  {
    "type": "info",
    "subtype": "grammar",
    "title": {
      "en": [
        "Lesson 22 · Greetings and Feelings"
      ],
      "zh": [],
      "ru": [
        "Урок 22 · Приветствия и чувства"
      ]
    },
    "items": [
      {
        "text": {
          "en": [
            "{{Word:ni3}} {{word:hao3}}!, hello. {{Word:ni3}} {{word:hao3}} {{word:ma}}?, how are you?"
          ],
          "ru": [
            "{{Word:ni3}} {{word:hao3}}! — привет. {{Word:ni3}} {{word:hao3}} {{word:ma}}? — как дела?"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:xie4}}-xie, thank you: {{Word:xie4}}-xie {{word:ni3}}! (Thank you!) {{Word:bu4}} {{word:yong4}} {{word:xie4}}. (You're welcome.)"
          ],
          "ru": [
            "{{word:xie4}}-xie — спасибо: {{Word:xie4}}-xie {{word:ni3}}! (Спасибо тебе!) {{Word:bu4}} {{word:yong4}} {{word:xie4}}. (Не за что.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:jiao4}} + \"name\": {{Word:wo3}} {{word:jiao4}} \"Lisa\". (My name is Lisa.) {{Word:ni3}} {{word:jiao4}} {{word:shen2me}}? (What's your name?)"
          ],
          "ru": [
            "{{word:jiao4}} + \"имя\": {{Word:wo3}} {{word:jiao4}} \"Lisa\". (Меня зовут Лиза.) {{Word:ni3}} {{word:jiao4}} {{word:shen2me}}? (Как тебя зовут?)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "A verb on its own is an order: {{Word:chi1}}! (Eat!) {{Word:bu4}} {{word:yao4}} + verb: don't."
          ],
          "ru": [
            "Глагол сам по себе — просьба: {{Word:chi1}}! (Ешь!) {{Word:bu4}} {{word:yao4}} + глагол — не делай."
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:jue2}}-{{light:de2}} + adjective, feel: {{Word:wo3}} {{word:jue2}}-{{light:de2}} {{word:leng3}}. (I feel cold.)"
          ],
          "ru": [
            "{{word:jue2}}-{{light:de2}} + прилагательное — чувствовать: {{Word:wo3}} {{word:jue2}}-{{light:de2}} {{word:leng3}}. (Мне холодно.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:pa4}} + thing, scared of: {{Word:wo3}} {{word:pa4}} {{word:huo3}}. (I'm scared of fire.)"
          ],
          "ru": [
            "{{word:pa4}} + вещь — бояться: {{Word:wo3}} {{word:pa4}} {{word:huo3}}. (Я боюсь огня.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "Who + {{word:xiao4}}, laugh or smile: {{Word:ta1}} {{word:xiao4}} {{word:le}}. (She smiled.)"
          ],
          "ru": [
            "Кто + {{word:xiao4}} — смеяться или улыбаться: {{Word:ta1}} {{word:xiao4}} {{word:le}}. (Она улыбнулась.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:kai1}}-{{word:xin1}}, happy: {{Word:wo3}} {{word:hen3}} {{word:kai1}}-{{word:xin1}}. (I'm very happy.) {{Word:xiao3}}-{{word:xin1}}! (Be careful!)"
          ],
          "ru": [
            "{{word:kai1}}-{{word:xin1}} — радостный: {{Word:wo3}} {{word:hen3}} {{word:kai1}}-{{word:xin1}}. (Я очень рад.) {{Word:xiao3}}-{{word:xin1}}! (Осторожно!)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:ting1}}-{{word:dao4}} + {{word:sheng1yin1}}, hear a sound: {{Word:wo3}} {{word:ting1}}-{{word:dao4}} {{word:qi2guai4}}-{{word:de}} {{word:sheng1yin1}}. (I hear a strange sound.)"
          ],
          "ru": [
            "{{word:ting1}}-{{word:dao4}} + {{word:sheng1yin1}} — слышать звук: {{Word:wo3}} {{word:ting1}}-{{word:dao4}} {{word:qi2guai4}}-{{word:de}} {{word:sheng1yin1}}. (Я слышу странный звук.)"
          ],
          "zh": []
        }
      }
    ]
  },
  {
    "type": "info",
    "subtype": "grammar",
    "title": {
      "en": [
        "Lesson 23 · Doubling Words"
      ],
      "zh": [],
      "ru": [
        "Урок 23 · Удвоение слов"
      ]
    },
    "items": [
      {
        "text": {
          "en": [
            "verb-verb, a little: {{Word:wo3}} {{word:kan4}}-kan. (Let me have a look.)"
          ],
          "ru": [
            "глагол-глагол — немного: {{Word:wo3}} {{word:kan4}}-kan. (Дай-ка я посмотрю.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "adjective-adjective-{{word:de}}, stronger: {{Word:yue4}} {{word:yuan2}}-{{word:yuan2}}-{{word:de}}. (The moon is nice and round.) {{word:hao3}}-{{word:hao3}} + verb, well: {{Word:hao3}}-{{word:hao3}} {{word:xue2}}! (Study hard!)"
          ],
          "ru": [
            "прилагательное-прилагательное-{{word:de}} — сильнее: {{Word:yue4}} {{word:yuan2}}-{{word:yuan2}}-{{word:de}}. (Луна круглая-круглая.) {{word:hao3}}-{{word:hao3}} + глагол — как следует: {{Word:hao3}}-{{word:hao3}} {{word:xue2}}! (Учись хорошенько!)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:ren2}}-{{word:ren2}} / {{word:ge4}}-{{word:ge4}} + {{word:dou1}}, every: {{Word:ren2}}-{{word:ren2}} {{word:dou1}} {{word:yao4}} {{word:shui3}}. (Everyone needs water.)"
          ],
          "ru": [
            "{{word:ren2}}-{{word:ren2}} / {{word:ge4}}-{{word:ge4}} + {{word:dou1}} — каждый: {{Word:ren2}}-{{word:ren2}} {{word:dou1}} {{word:yao4}} {{word:shui3}}. (Всем людям нужна вода.)"
          ],
          "zh": []
        }
      }
    ]
  },
  {
    "type": "info",
    "subtype": "grammar",
    "title": {
      "en": [
        "Lesson 24 · Everyday Patterns"
      ],
      "zh": [],
      "ru": [
        "Урок 24 · Обороты на каждый день"
      ]
    },
    "items": [
      {
        "text": {
          "en": [
            "{{word:wo3}} {{word:lai2}} + verb, let me: {{Word:wo3}} {{word:lai2}} {{word:na2}}. (Let me carry it.)"
          ],
          "ru": [
            "{{word:wo3}} {{word:lai2}} + глагол — давай я: {{Word:wo3}} {{word:lai2}} {{word:na2}}. (Давай я понесу.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:gei3}} {{word:wo3}} + verb + {{word:yi1}}-{{word:xia4}}, let me have a turn: {{Word:gei3}} {{word:wo3}} {{word:kan4}} {{word:yi1}}-{{word:xia4}}. (Let me take a look.)"
          ],
          "ru": [
            "{{word:gei3}} {{word:wo3}} + глагол + {{word:yi1}}-{{word:xia4}} — дай мне попробовать: {{Word:gei3}} {{word:wo3}} {{word:kan4}} {{word:yi1}}-{{word:xia4}}. (Дай посмотреть.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:bang1}} + person + verb, help: {{Word:ni3}} {{word:bang1}} {{word:wo3}} {{word:na2}} {{word:yi1}}-{{word:xia4}}. (Could you hold this for me?)"
          ],
          "ru": [
            "{{word:bang1}} + человек + глагол — помочь: {{Word:ni3}} {{word:bang1}} {{word:wo3}} {{word:na2}} {{word:yi1}}-{{word:xia4}}. (Подержишь это за меня?)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:jiao1}} + person + verb, teach: {{Word:wo3}} {{word:jiao1}} {{word:ni3}} {{word:xie3}}. (I'll teach you to write.)"
          ],
          "ru": [
            "{{word:jiao1}} + человек + глагол — научить: {{Word:wo3}} {{word:jiao1}} {{word:ni3}} {{word:xie3}}. (Я научу тебя писать.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:jiao4}} + person + verb, have or let: {{Word:jiao4}} {{word:ta1}} {{word:jin4}}-{{word:lai2}}. (Let him in.) {{word:bu4}} {{word:jiao4}}, won't let: {{Word:ba4ba}}-{{word:ma1ma}} {{word:bu4}} {{word:jiao4}} {{word:wo3}} {{word:chu1}}-{{word:qu4}}. (My parents won't let me go out.)"
          ],
          "ru": [
            "{{word:jiao4}} + человек + глагол — велеть или позволить: {{Word:jiao4}} {{word:ta1}} {{word:jin4}}-{{word:lai2}}. (Пусть войдёт.) {{word:bu4}} {{word:jiao4}} — не позволять: {{Word:ba4ba}}-{{word:ma1ma}} {{word:bu4}} {{word:jiao4}} {{word:wo3}} {{word:chu1}}-{{word:qu4}}. (Родители не пускают меня гулять.)"
          ],
          "zh": []
        }
      },
      {
        "text": {
          "en": [
            "{{word:neng2}} … {{word:ma}}?, may I: {{Word:wo3}} {{word:neng2}} {{word:jin4}}-{{word:lai2}} {{word:ma}}? (Can I come in?) …, {{word:hao3}} {{word:ma}}?, let's or please: {{Word:wo3}}-{{word:men}} {{word:chu1}}-{{word:qu4}} {{word:wan2r}}, {{word:hao3}} {{word:ma}}? (Let's go out and play, okay?)"
          ],
          "ru": [
            "{{word:neng2}} … {{word:ma}}? — можно ли: {{Word:wo3}} {{word:neng2}} {{word:jin4}}-{{word:lai2}} {{word:ma}}? (Можно войти?) …, {{word:hao3}} {{word:ma}}? — давай или пожалуйста: {{Word:wo3}}-{{word:men}} {{word:chu1}}-{{word:qu4}} {{word:wan2r}}, {{word:hao3}} {{word:ma}}? (Давай выйдем поиграть, хорошо?)"
          ],
          "zh": []
        }
      }
    ]
  }
];

export default content;
