// See src/lib/chapter-content.js for the schema this is transformed by.
// GENERATED from a plain-pinyin spec, but safe to edit by hand: every
// {{word:..}} must be a dictionary word (scripts/check-book.js checks).
// The sections follow the usual travel phrase book (basics, the way,
// transport, lodging, eating, shopping, problems, the doctor).
import type { Entry } from "../lib/chapter-entry-types.ts";

export const meta = {
  id: "phrase-book",
  type: "appendix",
  order: 0,
};

const content: Entry[] = [
  {
    type: "title",
    en: ["Phrase Book"],
    zh: ["常用语手册"],
    ru: ["Разговорник"],
  },
  {
    type: "summary",
    en: ["About a hundred ready-made sentences for travel and daily life, from hello to finding a doctor, made only from dictionary words."],
    zh: ["大约一百个旅行和日常生活中的现成句子，从\"你好\"到\"我要看医生\"，只用词典里的词。"],
    ru: ["Около ста готовых фраз для поездок и повседневной жизни, от «привет» до «мне нужен врач», только из слов словаря."],
  },
  {
    type: "prose",
    en: ["Ready-made sentences for the situations a travel phrase book covers: meeting people, finding your way, eating, shopping, a place to sleep, and getting help.", "Every sentence uses only words from the dictionary.", "When there is no word for something, the sentence describes it, the same way the composite dictionary does: a doctor is \"the person who makes a sick body good.\"", "Next to each sentence is what it means; \"literally\" shows how Hao-shuo-de says it."],
    zh: ["这里是旅行常用语手册里常见场景的现成句子：认识人、问路、吃饭、买东西、住宿和求助。", "每个句子都只用词典里的词。", "没有词的东西，就像组合词词典那样把它描述出来：医生是\"把不好的身体弄好的人\"。", "每句后面是普通话里平常的说法。"],
    ru: ["Готовые фразы для тех случаев, которые есть в любом разговорнике: знакомство, дорога, еда, покупки, ночлег и помощь.", "Каждая фраза построена только из слов словаря.", "Если для чего-то нет слова, фраза это описывает, как и словарь составных слов: врач — это «человек, который делает больное тело хорошим».", "Рядом с каждой фразой — её смысл, а «дословно» показывает, как это сказано на Hǎo-shuō-de."],
    tldr: {
      en: ["Everyday sentences for travel and daily life, using only dictionary words."],
      zh: ["旅行和日常生活的现成句子，只用词典里的词。"],
      ru: ["Готовые фразы для поездок и повседневной жизни, только из слов словаря."],
    },
    necessity: {
      en: ["You can use Hao-shuo-de in real situations right away."],
      zh: ["这样你马上就能在真实场景里用 Hǎo-shuō-de。"],
      ru: ["Так Hǎo-shuō-de можно сразу использовать в жизни."],
    },
  },
  {
    type: "prose",
    en: ["## Basics", "The sentences you will say every day."],
    zh: ["## 基本用语", "每天都会说的话。"],
    ru: ["## Самое нужное", "Фразы, которые говорят каждый день."],
    tldr: {
      en: ["Hello, how are you, thank you, sorry, and goodbye."],
      zh: ["你好、你好吗、谢谢、对不起和再见。"],
      ru: ["Привет, как дела, спасибо, извините и до свидания."],
    },
    necessity: {
      en: ["These are the first things anyone needs to say."],
      zh: ["这是每个人最先需要的几句话。"],
      ru: ["Это первые фразы, которые нужны каждому."],
    },
  },
  {
    type: "example",
    pinyin: "{{Word:ni3}} {{word:hao3}}!",
    ttsText: "你好！",
    en: ["Hello!"],
    zh: ["你好！"],
    ru: ["Здравствуйте!"],
  },
  {
    type: "example",
    pinyin: "{{Word:ni3}} {{word:hao3}} {{word:ma}}?",
    ttsText: "你好吗？",
    en: ["How are you?"],
    zh: ["你好吗？"],
    ru: ["Как дела?"],
  },
  {
    type: "example",
    pinyin: "{{Word:wo3}} {{word:hen3}} {{word:hao3}}, {{word:xie4}}-xie.",
    ttsText: "我很好，谢谢。",
    en: ["I'm fine, thanks."],
    zh: ["我很好，谢谢。"],
    ru: ["Хорошо, спасибо."],
  },
  {
    type: "example",
    pinyin: "{{Word:xie4}}-xie {{word:ni3}}!",
    ttsText: "谢谢你！",
    en: ["Thank you!"],
    zh: ["谢谢你！"],
    ru: ["Спасибо!"],
  },
  {
    type: "example",
    pinyin: "{{Word:bu4}} {{word:yong4}} {{word:xie4}}.",
    ttsText: "不用谢。",
    en: ["You're welcome."],
    zh: ["不客气。"],
    ru: ["Не за что."],
  },
  {
    type: "example",
    pinyin: "{{Word:shi4}} {{word:wo3}} {{word:bu4}} {{word:hao3}}.",
    ttsText: "是我不好。",
    en: ["Sorry. (Literally: \"it's my fault.\")"],
    zh: ["对不起。"],
    ru: ["Извините. (Дословно: «это я виноват».)"],
  },
  {
    type: "example",
    pinyin: "{{Word:mei2}}-{{word:you3}} {{word:guan1xi}}.",
    ttsText: "没有关系。",
    en: ["That's okay. / It doesn't matter."],
    zh: ["没关系。"],
    ru: ["Ничего страшного."],
  },
  {
    type: "example",
    pinyin: "{{Word:wo3}} {{word:qu4}} {{word:le}}, {{word:wo3}} {{word:hui4}} {{word:kan4}}-{{word:dao4}} {{word:ni3}}!",
    ttsText: "我去了，我会看到你！",
    en: ["Goodbye, see you! (Literally: \"I'm going; I'll see you.\")"],
    zh: ["再见！"],
    ru: ["До свидания, увидимся! (Дословно: «я пошёл, я тебя увижу».)"],
  },
  {
    type: "prose",
    en: ["## Yes, no, and please", "There is no word for \"please\". Ask with …, {{word:hao3}} {{word:ma}}? (\"…, okay?\") at the end."],
    zh: ["## 是、不是和请", "没有\"请\"这个词。请别人做事时，在句子后面加 …, {{word:hao3}} {{word:ma}}?（……，好吗？）。"],
    ru: ["## Да, нет и пожалуйста", "Слова «пожалуйста» нет. В конце просьбы говорят …, {{word:hao3}} {{word:ma}}? («…, хорошо?»)."],
    tldr: {
      en: ["Yes, no, okay, please, wait, and careful."],
      zh: ["对、不对、好、请、等一下和小心。"],
      ru: ["Да, нет, хорошо, пожалуйста, подождите и осторожно."],
    },
    necessity: {
      en: ["Short answers and requests carry most of a conversation."],
      zh: ["简短的回答和请求撑起了大部分对话。"],
      ru: ["Короткие ответы и просьбы — основа любого разговора."],
    },
  },
  {
    type: "example",
    pinyin: "{{Word:dui4}}.",
    ttsText: "对。",
    en: ["Yes, that's right."],
    zh: ["对。"],
    ru: ["Да, верно."],
  },
  {
    type: "example",
    pinyin: "{{Word:bu4}} {{word:dui4}}.",
    ttsText: "不对。",
    en: ["No, that's not right."],
    zh: ["不对。"],
    ru: ["Нет, это не так."],
  },
  {
    type: "example",
    pinyin: "{{Word:hao3}}!",
    ttsText: "好！",
    en: ["Okay!"],
    zh: ["好！"],
    ru: ["Хорошо!"],
  },
  {
    type: "example",
    pinyin: "{{Word:bu4}} {{word:yao4}}, {{word:xie4}}-xie.",
    ttsText: "不要，谢谢。",
    en: ["No, thank you."],
    zh: ["不要，谢谢。"],
    ru: ["Нет, спасибо."],
  },
  {
    type: "example",
    pinyin: "{{Word:gei3}} {{word:wo3}} {{word:kan4}} {{word:yi1xia4}}, {{word:hao3}} {{word:ma}}?",
    ttsText: "给我看一下，好吗？",
    en: ["Can I have a look, please?"],
    zh: ["请让我看一下。"],
    ru: ["Можно посмотреть?"],
  },
  {
    type: "example",
    pinyin: "{{Word:deng3}} {{word:yi1xia4}}!",
    ttsText: "等一下！",
    en: ["Wait a moment!"],
    zh: ["等一下！"],
    ru: ["Подождите минутку!"],
  },
  {
    type: "example",
    pinyin: "{{Word:kuai4}} {{word:lai2}}!",
    ttsText: "快来！",
    en: ["Come quickly!"],
    zh: ["快来！"],
    ru: ["Иди скорее!"],
  },
  {
    type: "example",
    pinyin: "{{Word:xiao3}}-{{word:xin1}}!",
    ttsText: "小心！",
    en: ["Careful!"],
    zh: ["小心！"],
    ru: ["Осторожно!"],
  },
  {
    type: "prose",
    en: ["## When you don't understand", "At first you will need these in almost every conversation."],
    zh: ["## 听不懂的时候", "刚开始的时候，几乎每次说话都会用到这些句子。"],
    ru: ["## Когда вы не понимаете", "Поначалу они нужны почти в каждом разговоре."],
    tldr: {
      en: ["I don't understand, what did you say, slower, and how do you say this."],
      zh: ["我听不懂、你说什么、慢一点和这个怎么说。"],
      ru: ["Я не понимаю, что вы сказали, помедленнее и как это сказать."],
    },
    necessity: {
      en: ["When you don't understand, these let the conversation go on."],
      zh: ["听不懂的时候，有了这些句子，对话就能继续下去。"],
      ru: ["Когда вы не понимаете, с ними разговор не обрывается."],
    },
  },
  {
    type: "example",
    pinyin: "{{Word:wo3}} {{word:bu4}} {{word:zhi1dao4}} {{word:ni3}} {{word:shuo1}}-{{word:de}}.",
    ttsText: "我不知道你说的。",
    en: ["I don't understand what you said."],
    zh: ["我听不懂你说的。"],
    ru: ["Я не понимаю, что вы сказали."],
  },
  {
    type: "example",
    pinyin: "{{Word:ni3}} {{word:shuo1}} {{word:shen2me}}?",
    ttsText: "你说什么？",
    en: ["What did you say?"],
    zh: ["你说什么？"],
    ru: ["Что вы сказали?"],
  },
  {
    type: "example",
    pinyin: "{{Word:ni3}} {{word:shuo1}}-{{word:de}} {{word:hen3}} {{word:kuai4}}. {{Word:ni3}} {{word:neng2}} {{word:shuo1}}-{{word:de}} {{word:bu4}} {{word:kuai4}} {{word:ma}}?",
    ttsText: "你说的很快。你能说的不快吗？",
    en: ["You speak fast. Can you speak more slowly? (Literally: \"not fast?\")"],
    zh: ["你说得太快了。能说慢一点吗？"],
    ru: ["Вы говорите быстро. Можно помедленнее? (Дословно: «не быстро?»)"],
  },
  {
    type: "example",
    pinyin: "{{Word:zhe4}}-ge {{word:zen3me}} {{word:shuo1}}?",
    ttsText: "这个怎么说？",
    en: ["How do you say this?"],
    zh: ["这个怎么说？"],
    ru: ["Как это сказать?"],
  },
  {
    type: "example",
    pinyin: "{{Word:zhe4}}-ge {{word:shi4}} {{word:shen2me}}?",
    ttsText: "这个是什么？",
    en: ["What is this?"],
    zh: ["这是什么？"],
    ru: ["Что это?"],
  },
  {
    type: "example",
    pinyin: "{{Word:ni3}} {{word:neng2}} {{word:xie3}}-{{word:xia4}}-{{word:lai2}} {{word:ma}}?",
    ttsText: "你能写下来吗？",
    en: ["Can you write it down?"],
    zh: ["你能写下来吗？"],
    ru: ["Можете записать?"],
  },
  {
    type: "example",
    pinyin: "{{Word:wo3}} {{word:shuo1}}-{{word:de}} {{word:bu4}} {{word:hao3}}.",
    ttsText: "我说的不好。",
    en: ["I don't speak it well."],
    zh: ["我说得不好。"],
    ru: ["Я плохо говорю."],
  },
  {
    type: "example",
    pinyin: "{{Word:ni3}} {{word:hui4}} {{word:shuo1}} \"Yīngguó\"-{{word:de}} {{word:shuo1}}-{{word:de}} {{word:ma}}?",
    ttsText: "你会说英国的说的吗？",
    en: ["Do you speak English? (Literally: \"England's speech.\")"],
    zh: ["你会说英语吗？"],
    ru: ["Вы говорите по-английски? (Дословно: «английскую речь».)"],
  },
  {
    type: "prose",
    en: ["## Meeting people", "Small talk starts with the same few questions everywhere."],
    zh: ["## 认识新朋友", "无论在哪里，闲聊都从这几个问题开始。"],
    ru: ["## Знакомство", "Светская беседа везде начинается с одних и тех же вопросов."],
    tldr: {
      en: ["Names, nice to meet you, where you're from, where you live, and age."],
      zh: ["名字、很高兴认识你、从哪里来、住在哪里和年龄。"],
      ru: ["Имена, приятно познакомиться, откуда вы, где живёте и возраст."],
    },
    necessity: {
      en: ["Meeting people is the reason most of us learn a language."],
      zh: ["认识新朋友，是很多人学语言的原因。"],
      ru: ["Ради знакомства с людьми многие и учат язык."],
    },
  },
  {
    type: "example",
    pinyin: "{{Word:ni3}} {{word:jiao4}} {{word:shen2me}}?",
    ttsText: "你叫什么？",
    en: ["What's your name?"],
    zh: ["你叫什么名字？"],
    ru: ["Как тебя зовут?"],
  },
  {
    type: "example",
    pinyin: "{{Word:wo3}} {{word:jiao4}} \"Ānnà\".",
    ttsText: "我叫安娜。",
    en: ["My name is Anna."],
    zh: ["我叫安娜。"],
    ru: ["Меня зовут Анна."],
  },
  {
    type: "example",
    pinyin: "{{Word:hen3}} {{word:kai1}}-{{word:xin1}} {{word:kan4}}-{{word:dao4}} {{word:ni3}}!",
    ttsText: "很开心看到你！",
    en: ["Nice to meet you! (Literally: \"very happy to see you.\")"],
    zh: ["很高兴认识你！"],
    ru: ["Приятно познакомиться! (Дословно: «очень рад тебя видеть».)"],
  },
  {
    type: "example",
    pinyin: "{{Word:ni3}} {{word:cong2}} {{word:na3li3}} {{word:lai2}}?",
    ttsText: "你从哪里来？",
    en: ["Where are you from?"],
    zh: ["你从哪里来？"],
    ru: ["Откуда ты?"],
  },
  {
    type: "example",
    pinyin: "{{Word:wo3}} {{word:cong2}} \"Měiguó\" {{word:lai2}}.",
    ttsText: "我从美国来。",
    en: ["I'm from the United States."],
    zh: ["我从美国来。"],
    ru: ["Я из США."],
  },
  {
    type: "example",
    pinyin: "{{Word:ni3}}-{{word:de}} {{word:jia1}} {{word:zai4}} {{word:na3li3}}?",
    ttsText: "你的家在哪里？",
    en: ["Where do you live? (Literally: \"where is your home?\")"],
    zh: ["你住在哪里？"],
    ru: ["Где ты живёшь? (Дословно: «где твой дом?»)"],
  },
  {
    type: "example",
    pinyin: "{{Word:ni3}} {{word:duo1}} {{word:da4}}?",
    ttsText: "你多大？",
    en: ["How old are you?"],
    zh: ["你多大？"],
    ru: ["Сколько тебе лет?"],
  },
  {
    type: "example",
    pinyin: "{{Word:zhe4}} {{word:shi4}} {{word:wo3}}-{{word:de}} {{word:fu4mu3}}.",
    ttsText: "这是我的父母。",
    en: ["These are my parents."],
    zh: ["这是我的父母。"],
    ru: ["Это мои родители."],
  },
  {
    type: "prose",
    en: ["## Feelings and small talk", "Saying how you feel makes a conversation warmer."],
    zh: ["## 心情和闲聊", "说出自己的感受，聊天就更亲切。"],
    ru: ["## Чувства и разговор", "Если сказать, что вы чувствуете, разговор становится теплее."],
    tldr: {
      en: ["Happy, tired, cold, scared, and I love it."],
      zh: ["高兴、累、冷、害怕和我喜欢。"],
      ru: ["Рад, устал, холодно, страшно и мне нравится."],
    },
    necessity: {
      en: ["Feelings come up in every conversation, not only in emergencies."],
      zh: ["不只是遇到麻烦时，每次聊天都会说到心情。"],
      ru: ["О чувствах говорят в любом разговоре, а не только в беде."],
    },
  },
  {
    type: "example",
    pinyin: "{{Word:wo3}} {{word:hen3}} {{word:kai1}}-{{word:xin1}}.",
    ttsText: "我很开心。",
    en: ["I'm happy."],
    zh: ["我很高兴。"],
    ru: ["Я рад."],
  },
  {
    type: "example",
    pinyin: "{{Word:wo3}} {{word:yao4}} {{word:shui4jiao4}}.",
    ttsText: "我要睡觉。",
    en: ["I'm tired. (Literally: \"I want to sleep.\")"],
    zh: ["我累了。"],
    ru: ["Я устал. (Дословно: «я хочу спать».)"],
  },
  {
    type: "example",
    pinyin: "{{Word:wai4}}-{{word:mian4}} {{word:hen3}} {{word:leng3}}.",
    ttsText: "外面很冷。",
    en: ["It's cold outside."],
    zh: ["外面很冷。"],
    ru: ["На улице холодно."],
  },
  {
    type: "example",
    pinyin: "{{Word:wo3}} {{word:jue2de}} {{word:hen3}} {{word:hao3}}.",
    ttsText: "我觉得很好。",
    en: ["I feel great."],
    zh: ["我感觉很好。"],
    ru: ["Я чувствую себя отлично."],
  },
  {
    type: "example",
    pinyin: "{{Word:wo3}} {{word:pa4}}!",
    ttsText: "我怕！",
    en: ["I'm scared!"],
    zh: ["我害怕！"],
    ru: ["Мне страшно!"],
  },
  {
    type: "example",
    pinyin: "{{Word:wo3}} {{word:ai4}} {{word:zhe4}}-ge {{word:di4fang1}}!",
    ttsText: "我爱这个地方！",
    en: ["I love this place!"],
    zh: ["我喜欢这个地方！"],
    ru: ["Мне очень нравится это место!"],
  },
  {
    type: "example",
    pinyin: "{{Word:zhen1}} {{word:hao3}}!",
    ttsText: "真好！",
    en: ["Great! (Literally: \"really good!\")"],
    zh: ["真好！"],
    ru: ["Здорово!"],
  },
  {
    type: "example",
    pinyin: "{{Word:fang4}}-{{word:xin1}}, {{word:mei2}}-{{word:you3}} {{word:guan1xi}}.",
    ttsText: "放心，没有关系。",
    en: ["Don't worry, it's fine."],
    zh: ["放心，没关系。"],
    ru: ["Не волнуйся, всё в порядке."],
  },
  {
    type: "prose",
    en: ["## Time", "Today is {{word:xian4zai4}}-{{word:de}} {{word:ri4}} (\"the day that's now\"), tomorrow is {{word:xia4}} {{word:yi1}}-ge {{word:ri4}} (\"the next day\"), and yesterday is {{word:qian2}} {{word:yi1}}-ge {{word:ri4}}."],
    zh: ["## 时间", "今天是 {{word:xian4zai4}}-{{word:de}} {{word:ri4}}（现在的日），明天是 {{word:xia4}} {{word:yi1}}-ge {{word:ri4}}（下一个日），昨天是 {{word:qian2}} {{word:yi1}}-ge {{word:ri4}}（前一个日）。"],
    ru: ["## Время", "Сегодня — {{word:xian4zai4}}-{{word:de}} {{word:ri4}} («день, который сейчас»), завтра — {{word:xia4}} {{word:yi1}}-ge {{word:ri4}} («следующий день»), вчера — {{word:qian2}} {{word:yi1}}-ge {{word:ri4}}."],
    tldr: {
      en: ["What time it is, when, today, tomorrow, and yesterday."],
      zh: ["几点了、什么时候、今天、明天和昨天。"],
      ru: ["Который час, когда, сегодня, завтра и вчера."],
    },
    necessity: {
      en: ["Plans and meetings all need times and days."],
      zh: ["安排事情、约见面都要说时间和日子。"],
      ru: ["Для планов и встреч нужны часы и дни."],
    },
  },
  {
    type: "example",
    pinyin: "{{Word:xian4zai4}} {{word:shi4}} {{word:shen2me}} {{word:shi2jian1}}?",
    ttsText: "现在是什么时间？",
    en: ["What time is it?"],
    zh: ["现在几点？"],
    ru: ["Который час?"],
  },
  {
    type: "example",
    pinyin: "{{Word:xian4zai4}} {{word:shi4}} {{word:san1}}-{{word:dian3}}.",
    ttsText: "现在是三点。",
    en: ["It's three o'clock."],
    zh: ["现在三点。"],
    ru: ["Сейчас три часа."],
  },
  {
    type: "example",
    pinyin: "{{Word:ni3}} {{word:shen2me}} {{word:shi2jian1}} {{word:lai2}}?",
    ttsText: "你什么时间来？",
    en: ["When are you coming?"],
    zh: ["你什么时候来？"],
    ru: ["Когда ты придёшь?"],
  },
  {
    type: "example",
    pinyin: "{{Word:wo3}} {{word:xia4}} {{word:yi1}}-ge {{word:ri4}} {{word:lai2}}.",
    ttsText: "我下一个日来。",
    en: ["I'll come tomorrow."],
    zh: ["我明天来。"],
    ru: ["Я приду завтра."],
  },
  {
    type: "example",
    pinyin: "{{Word:wo3}} {{word:qian2}} {{word:yi1}}-ge {{word:ri4}} {{word:dao4}} {{word:le}}.",
    ttsText: "我前一个日到了。",
    en: ["I arrived yesterday."],
    zh: ["我昨天到的。"],
    ru: ["Я приехал вчера."],
  },
  {
    type: "example",
    pinyin: "{{Word:xian4zai4}}-{{word:de}} {{word:ri4}} {{word:hen3}} {{word:re4}}.",
    ttsText: "现在的日很热。",
    en: ["It's hot today."],
    zh: ["今天很热。"],
    ru: ["Сегодня жарко."],
  },
  {
    type: "example",
    pinyin: "{{Word:wo3}}-{{word:men}} {{word:shi2}}-{{word:er4}}-{{word:dian3}} {{word:chi1}} {{word:mi3fan4}}.",
    ttsText: "我们十二点吃米饭。",
    en: ["We eat at twelve."],
    zh: ["我们十二点吃饭。"],
    ru: ["Мы обедаем в двенадцать."],
  },
  {
    type: "example",
    pinyin: "{{Word:deng3}} {{word:yi1xia4}}, {{word:wo3}} {{word:xian4zai4}} {{word:jiu4}} {{word:lai2}}!",
    ttsText: "等一下，我现在就来！",
    en: ["Just a moment, I'm coming right now!"],
    zh: ["等一下，我马上来！"],
    ru: ["Минутку, я сейчас приду!"],
  },
  {
    type: "prose",
    en: ["## Asking the way", "To ask where something is, say the place, then {{word:zai4}} {{word:na3li3}}? (\"is where?\")."],
    zh: ["## 问路", "问某个地方在哪里，先说地方，再加 {{word:zai4}} {{word:na3li3}}?（在哪里？）。"],
    ru: ["## Как пройти", "Чтобы спросить, где что-то находится, назовите место и добавьте {{word:zai4}} {{word:na3li3}}? («где?»)."],
    tldr: {
      en: ["Where is it, how to get there, is it far, left, right, and straight ahead."],
      zh: ["在哪里、怎么走、远不远、左边、右边和往前走。"],
      ru: ["Где это, как пройти, далеко ли, налево, направо и прямо."],
    },
    necessity: {
      en: ["Asking the way is what a phrase book is used for most."],
      zh: ["问路是常用语手册最常见的用处。"],
      ru: ["Спросить дорогу — то, для чего разговорник нужен чаще всего."],
    },
  },
  {
    type: "example",
    pinyin: "{{Word:yong4}} {{word:shui3}} {{word:nong4}} {{word:shou3}}-{{word:de}} {{word:di4fang1}} {{word:zai4}} {{word:na3li3}}?",
    ttsText: "用水弄手的地方在哪里？",
    en: ["Where's the toilet? (Literally: \"the place where you wash your hands.\")"],
    zh: ["厕所在哪里？"],
    ru: ["Где туалет? (Дословно: «место, где моют руки».)"],
  },
  {
    type: "example",
    pinyin: "{{Word:zen3me}} {{word:qu4}} \"Tiān'ānmén\"?",
    ttsText: "怎么去天安门？",
    en: ["How do I get to Tiananmen?"],
    zh: ["天安门怎么走？"],
    ru: ["Как пройти к Тяньаньмэнь?"],
  },
  {
    type: "example",
    pinyin: "{{Word:yuan3}} {{word:ma}}?",
    ttsText: "远吗？",
    en: ["Is it far?"],
    zh: ["远吗？"],
    ru: ["Это далеко?"],
  },
  {
    type: "example",
    pinyin: "{{Word:bu4}} {{word:yuan3}}, {{word:zai4}} {{word:fu4jin4}}.",
    ttsText: "不远，在附近。",
    en: ["It's not far, it's nearby."],
    zh: ["不远，就在附近。"],
    ru: ["Недалеко, рядом."],
  },
  {
    type: "example",
    pinyin: "{{Word:zai4}} {{word:zuo3bian1}}.",
    ttsText: "在左边。",
    en: ["It's on the left."],
    zh: ["在左边。"],
    ru: ["Слева."],
  },
  {
    type: "example",
    pinyin: "{{Word:zai4}} {{word:you4bian1}}.",
    ttsText: "在右边。",
    en: ["It's on the right."],
    zh: ["在右边。"],
    ru: ["Справа."],
  },
  {
    type: "example",
    pinyin: "{{Word:dui4}} {{word:qian2}}-{{word:mian4}} {{word:qu4}}.",
    ttsText: "对前面去。",
    en: ["Go straight ahead. (Literally: \"go toward the front.\")"],
    zh: ["往前走。"],
    ru: ["Идите прямо. (Дословно: «идите вперёд».)"],
  },
  {
    type: "example",
    pinyin: "{{Word:zai4}} {{word:lu4}}-{{word:de}} {{word:dui4}}-{{word:mian4}}.",
    ttsText: "在路的对面。",
    en: ["It's across the road."],
    zh: ["在马路对面。"],
    ru: ["Это через дорогу."],
  },
  {
    type: "prose",
    en: ["## Getting around", "There is no word for car, train, or plane: they are all {{word:qu4}}-{{word:hen3}}-{{word:duo1}}-{{word:di4fang1}}-{{word:de}} {{word:gong1ju4}}, \"the tool that goes to many places.\"", "Most of the time you don't need the word at all."],
    zh: ["## 交通", "没有\"车\"\"火车\"\"飞机\"这些词，它们都是 {{word:qu4}}-{{word:hen3}}-{{word:duo1}}-{{word:di4fang1}}-{{word:de}} {{word:gong1ju4}}（去很多地方的工具）。", "大多数时候，根本用不着这个词。"],
    ru: ["## Транспорт", "Слов «машина», «поезд» и «самолёт» нет: всё это {{word:qu4}}-{{word:hen3}}-{{word:duo1}}-{{word:di4fang1}}-{{word:de}} {{word:gong1ju4}}, «инструмент, который ездит во многие места».", "Чаще всего это слово и не нужно."],
    tldr: {
      en: ["Where to, how much, the airport, faster, right here, and getting off."],
      zh: ["去哪里、多少钱、机场、快一点、就在这里和下车。"],
      ru: ["Куда, сколько стоит, аэропорт, быстрее, прямо здесь и выйти."],
    },
    necessity: {
      en: ["Taxis and buses need only a few sentences."],
      zh: ["坐出租车和公共汽车只需要几句话。"],
      ru: ["В такси и автобусе хватает нескольких фраз."],
    },
  },
  {
    type: "example",
    pinyin: "{{Word:wo3}} {{word:yao4}} {{word:qu4}} \"Běijīng\".",
    ttsText: "我要去北京。",
    en: ["I want to go to Beijing."],
    zh: ["我要去北京。"],
    ru: ["Мне нужно в Пекин."],
  },
  {
    type: "example",
    pinyin: "{{Word:wo3}} {{word:yao4}} {{word:qu4}} {{word:zhe4}}-ge {{word:di4fang1}}.",
    ttsText: "我要去这个地方。",
    en: ["I want to go to this place. (Show the address.)"],
    zh: ["我要去这个地方。"],
    ru: ["Мне нужно вот сюда. (Покажите адрес.)"],
  },
  {
    type: "example",
    pinyin: "{{Word:qu4}} {{word:na4}}-{{word:li3}} {{word:duo1}}-{{word:shao3}} {{word:jin1}}?",
    ttsText: "去那里多少金？",
    en: ["How much is it to go there?"],
    zh: ["去那里多少钱？"],
    ru: ["Сколько стоит доехать туда?"],
  },
  {
    type: "example",
    pinyin: "{{Word:zhe4}}-ge {{word:qu4}} \"Shànghǎi\" {{word:ma}}?",
    ttsText: "这个去上海吗？",
    en: ["Does this one go to Shanghai?"],
    zh: ["这个去上海吗？"],
    ru: ["Это идёт в Шанхай?"],
  },
  {
    type: "example",
    pinyin: "{{Word:wo3}} {{word:yao4}} {{word:qu4}} {{word:fei1}}-{{word:de}}-{{word:gong1ju4}} {{word:zai4}}-{{word:de}} {{word:di4fang1}}.",
    ttsText: "我要去飞的工具在的地方。",
    en: ["I want to go to the airport. (Literally: \"the place where the flying tools are.\")"],
    zh: ["我要去机场。"],
    ru: ["Мне нужно в аэропорт. (Дословно: «место, где стоят летающие машины».)"],
  },
  {
    type: "example",
    pinyin: "{{Word:kuai4}} {{word:yi1}}-{{word:dian3}}, {{word:hao3}} {{word:ma}}?",
    ttsText: "快一点，好吗？",
    en: ["A bit faster, please."],
    zh: ["请快一点。"],
    ru: ["Побыстрее, пожалуйста."],
  },
  {
    type: "example",
    pinyin: "{{Word:jiu4}} {{word:zai4}} {{word:zhe4}}-{{word:li3}}!",
    ttsText: "就在这里！",
    en: ["Right here! (Stop here.)"],
    zh: ["就在这儿停！"],
    ru: ["Прямо здесь! (Остановите здесь.)"],
  },
  {
    type: "example",
    pinyin: "{{Word:wo3}} {{word:yao4}} {{word:xia4}}-{{word:qu4}}.",
    ttsText: "我要下去。",
    en: ["I want to get off."],
    zh: ["我要下车。"],
    ru: ["Я выхожу."],
  },
  {
    type: "prose",
    en: ["## A place to sleep", "A hotel room is simply {{word:shui4jiao4}}-{{word:de}} {{word:di4fang1}}, \"a place to sleep.\""],
    zh: ["## 住宿", "酒店房间就是 {{word:shui4jiao4}}-{{word:de}} {{word:di4fang1}}（睡觉的地方）。"],
    ru: ["## Где переночевать", "Номер в гостинице — это просто {{word:shui4jiao4}}-{{word:de}} {{word:di4fang1}}, «место, где спать»."],
    tldr: {
      en: ["A room, the price, how long you stay, the key, and leaving."],
      zh: ["房间、价钱、住几天、钥匙和退房。"],
      ru: ["Комната, цена, на сколько вы остаётесь, ключ и отъезд."],
    },
    necessity: {
      en: ["These cover checking in and out of a hotel."],
      zh: ["这些句子够你办理入住和退房。"],
      ru: ["Этого хватает, чтобы заселиться и выехать."],
    },
  },
  {
    type: "example",
    pinyin: "{{Word:you3}} {{word:shui4jiao4}}-{{word:de}} {{word:di4fang1}} {{word:ma}}?",
    ttsText: "有睡觉的地方吗？",
    en: ["Do you have a room? (Literally: \"is there a place to sleep?\")"],
    zh: ["有房间吗？"],
    ru: ["Есть свободная комната? (Дословно: «есть где поспать?»)"],
  },
  {
    type: "example",
    pinyin: "{{Word:yi1}}-ge {{word:ri4}} {{word:duo1}}-{{word:shao3}} {{word:jin1}}?",
    ttsText: "一个日多少金？",
    en: ["How much for one night? (Literally: \"one day.\")"],
    zh: ["一晚多少钱？"],
    ru: ["Сколько стоит за ночь? (Дословно: «за один день».)"],
  },
  {
    type: "example",
    pinyin: "{{Word:wo3}} {{word:zai4}} {{word:zhe4}}-{{word:li3}} {{word:liu2}} {{word:san1}}-ge {{word:ri4}}.",
    ttsText: "我在这里留三个日。",
    en: ["I'll stay three nights."],
    zh: ["我住三天。"],
    ru: ["Я останусь на три ночи."],
  },
  {
    type: "example",
    pinyin: "{{Word:wo3}} {{word:neng2}} {{word:kan4}} {{word:yi1xia4}} {{word:ma}}?",
    ttsText: "我能看一下吗？",
    en: ["Can I see it?"],
    zh: ["我能看一下吗？"],
    ru: ["Можно посмотреть?"],
  },
  {
    type: "example",
    pinyin: "{{Word:gei3}} {{word:wo3}} {{word:kai1}} {{word:kou3}}-{{word:de}} {{word:xiao3}} {{word:gong1ju4}}, {{word:hao3}} {{word:ma}}?",
    ttsText: "给我开口的小工具，好吗？",
    en: ["Could I have the key? (Literally: \"the little tool that opens the door.\")"],
    zh: ["请给我钥匙。"],
    ru: ["Дайте, пожалуйста, ключ. (Дословно: «маленький инструмент, который открывает дверь».)"],
  },
  {
    type: "example",
    pinyin: "{{Word:zhe4}}-{{word:li3}} {{word:hen3}} {{word:leng3}}.",
    ttsText: "这里很冷。",
    en: ["It's cold in here."],
    zh: ["这里很冷。"],
    ru: ["Здесь холодно."],
  },
  {
    type: "example",
    pinyin: "{{Word:liu4}}-{{word:dian3}} {{word:jiao4}} {{word:wo3}}, {{word:hao3}} {{word:ma}}?",
    ttsText: "六点叫我，好吗？",
    en: ["Please wake me at six. (Literally: \"call me at six, okay?\")"],
    zh: ["请六点叫醒我。"],
    ru: ["Разбудите меня в шесть, пожалуйста. (Дословно: «позовите меня в шесть».)"],
  },
  {
    type: "example",
    pinyin: "{{Word:wo3}} {{word:xian4zai4}} {{word:jiu4}} {{word:qu4}}.",
    ttsText: "我现在就去。",
    en: ["I'm leaving now. (Checking out.)"],
    zh: ["我现在就退房。"],
    ru: ["Я уже уезжаю. (Выезжаю из номера.)"],
  },
  {
    type: "prose",
    en: ["## Eating", "{{Word:chi1}} covers both eating and drinking: {{word:chi1}} {{word:shui3}} is \"drink water.\""],
    zh: ["## 吃饭", "{{Word:chi1}} 既是\"吃\"也是\"喝\"：{{word:chi1}} {{word:shui3}} 就是\"喝水\"。"],
    ru: ["## Еда", "{{Word:chi1}} — это и «есть», и «пить»: {{word:chi1}} {{word:shui3}} значит «пить воду»."],
    tldr: {
      en: ["Hungry, the menu, ordering, no meat, water, tasty, and the bill."],
      zh: ["饿了、菜单、点菜、不吃肉、水、好吃和买单。"],
      ru: ["Голод, меню, заказ, без мяса, вода, вкусно и счёт."],
    },
    necessity: {
      en: ["Food is where many first conversations happen."],
      zh: ["很多第一次的对话都发生在饭桌上。"],
      ru: ["Многие первые разговоры случаются за едой."],
    },
  },
  {
    type: "example",
    pinyin: "{{Word:wo3}} {{word:yao4}} {{word:chi1}} {{word:dong1xi}}.",
    ttsText: "我要吃东西。",
    en: ["I'm hungry. (Literally: \"I want to eat something.\")"],
    zh: ["我饿了。"],
    ru: ["Я хочу есть. (Дословно: «я хочу что-нибудь съесть».)"],
  },
  {
    type: "example",
    pinyin: "{{Word:ni3}}-{{word:men}} {{word:you3}} {{word:shen2me}} {{word:chi1}}-{{word:de}}?",
    ttsText: "你们有什么吃的？",
    en: ["What do you have to eat? (Instead of asking for the menu.)"],
    zh: ["你们有什么吃的？"],
    ru: ["Что у вас есть поесть? (Вместо «дайте меню».)"],
  },
  {
    type: "example",
    pinyin: "{{Word:wo3}} {{word:yao4}} {{word:zhe4}}-ge.",
    ttsText: "我要这个。",
    en: ["I'll have this."],
    zh: ["我要这个。"],
    ru: ["Мне вот это."],
  },
  {
    type: "example",
    pinyin: "{{Word:wo3}} {{word:bu4}} {{word:chi1}} {{word:dong4wu4}}-{{word:de}} {{word:shen1ti3}}.",
    ttsText: "我不吃动物的身体。",
    en: ["I don't eat meat. (Literally: \"animals' bodies.\")"],
    zh: ["我不吃肉。"],
    ru: ["Я не ем мясо. (Дословно: «тела животных».)"],
  },
  {
    type: "example",
    pinyin: "{{Word:gei3}} {{word:wo3}} {{word:yi1}}-{{word:dian3}} {{word:shui3}}, {{word:hao3}} {{word:ma}}?",
    ttsText: "给我一点水，好吗？",
    en: ["Some water, please."],
    zh: ["请给我一点水。"],
    ru: ["Дайте немного воды, пожалуйста."],
  },
  {
    type: "example",
    pinyin: "{{Word:zhe4}}-ge {{word:wei4dao4}} {{word:hen3}} {{word:hao3}}!",
    ttsText: "这个味道很好！",
    en: ["This tastes great!"],
    zh: ["这个味道很好！"],
    ru: ["Очень вкусно!"],
  },
  {
    type: "example",
    pinyin: "{{Word:wo3}} {{word:chi1}}-{{word:wan2}} {{word:le}}.",
    ttsText: "我吃完了。",
    en: ["I've finished eating."],
    zh: ["我吃完了。"],
    ru: ["Я поел."],
  },
  {
    type: "example",
    pinyin: "{{Word:wo3}} {{word:yao4}} {{word:gei3}} {{word:jin1}}.",
    ttsText: "我要给金。",
    en: ["The bill, please. (Literally: \"I want to pay.\")"],
    zh: ["买单。"],
    ru: ["Счёт, пожалуйста. (Дословно: «я хочу заплатить».)"],
  },
  {
    type: "prose",
    en: ["## Shopping and money", "To bargain, ask for a little less: {{word:shao3}} {{word:yi1}}-{{word:dian3}}."],
    zh: ["## 购物和钱", "讲价的时候，就说少一点：{{word:shao3}} {{word:yi1}}-{{word:dian3}}。"],
    ru: ["## Покупки и деньги", "Чтобы поторговаться, просите немного меньше: {{word:shao3}} {{word:yi1}}-{{word:dian3}}."],
    tldr: {
      en: ["A shop, how much, too expensive, cheaper, other colors, bigger, and I'll take it."],
      zh: ["商店、多少钱、太贵了、便宜一点、别的颜色、大一点和我买了。"],
      ru: ["Магазин, сколько стоит, дорого, дешевле, другой цвет, побольше и беру."],
    },
    necessity: {
      en: ["With these you can shop at any market."],
      zh: ["有了这些句子，在哪个市场都能买东西。"],
      ru: ["С этими фразами можно покупать на любом рынке."],
    },
  },
  {
    type: "example",
    pinyin: "{{Word:mai3}} {{word:dong1xi}}-{{word:de}} {{word:di4fang1}} {{word:zai4}} {{word:na3li3}}?",
    ttsText: "买东西的地方在哪里？",
    en: ["Where's a shop? (Literally: \"the place to buy things.\")"],
    zh: ["商店在哪里？"],
    ru: ["Где здесь магазин? (Дословно: «место, где покупают вещи».)"],
  },
  {
    type: "example",
    pinyin: "{{Word:zhe4}}-ge {{word:duo1}}-{{word:shao3}} {{word:jin1}}?",
    ttsText: "这个多少金？",
    en: ["How much is this?"],
    zh: ["这个多少钱？"],
    ru: ["Сколько это стоит?"],
  },
  {
    type: "example",
    pinyin: "{{Word:zhe4}}-ge {{word:yao4}} {{word:hen3}} {{word:duo1}} {{word:jin1}}!",
    ttsText: "这个要很多金！",
    en: ["That's expensive! (Literally: \"this needs a lot of money.\")"],
    zh: ["这个太贵了！"],
    ru: ["Это дорого! (Дословно: «на это нужно много денег».)"],
  },
  {
    type: "example",
    pinyin: "{{Word:shao3}} {{word:yi1}}-{{word:dian3}}, {{word:hao3}} {{word:ma}}?",
    ttsText: "少一点，好吗？",
    en: ["A bit cheaper? (Literally: \"a little less, okay?\")"],
    zh: ["便宜一点，好吗？"],
    ru: ["А подешевле можно? (Дословно: «немного меньше, хорошо?»)"],
  },
  {
    type: "example",
    pinyin: "{{Word:wo3}} {{word:kan4}}-kan.",
    ttsText: "我看看。",
    en: ["I'm just looking."],
    zh: ["我看看。"],
    ru: ["Я просто смотрю."],
  },
  {
    type: "example",
    pinyin: "{{Word:you3}} {{word:bie2de}} {{word:yan2se4}} {{word:ma}}?",
    ttsText: "有别的颜色吗？",
    en: ["Do you have another color?"],
    zh: ["有别的颜色吗？"],
    ru: ["Есть другой цвет?"],
  },
  {
    type: "example",
    pinyin: "{{Word:you3}} {{word:da4}} {{word:yi1}}-{{word:dian3}}-{{word:de}} {{word:ma}}?",
    ttsText: "有大一点的吗？",
    en: ["Do you have a bigger one?"],
    zh: ["有大一点的吗？"],
    ru: ["Есть побольше?"],
  },
  {
    type: "example",
    pinyin: "{{Word:hao3}}, {{word:wo3}} {{word:mai3}}.",
    ttsText: "好，我买。",
    en: ["Okay, I'll take it."],
    zh: ["好，我买了。"],
    ru: ["Хорошо, беру."],
  },
  {
    type: "prose",
    en: ["## Problems", "In trouble, short and clear sentences work best."],
    zh: ["## 遇到麻烦", "遇到麻烦时，简短清楚的句子最管用。"],
    ru: ["## Если что-то случилось", "В беде лучше всего работают короткие и ясные фразы."],
    tldr: {
      en: ["Help, don't touch me, go away, I'm lost, it's gone, and call the police."],
      zh: ["救命、别碰我、走开、我迷路了、东西丢了和叫警察。"],
      ru: ["Помогите, не трогайте, уходите, я заблудился, пропало и вызовите полицию."],
    },
    necessity: {
      en: ["You hope you won't need them, but you should know them."],
      zh: ["希望你用不上，但最好会说。"],
      ru: ["Надеемся, они не понадобятся, но знать их стоит."],
    },
  },
  {
    type: "example",
    pinyin: "{{Word:bang1}}-bang {{word:wo3}}!",
    ttsText: "帮帮我！",
    en: ["Help! (Literally: \"help me!\")"],
    zh: ["救命！"],
    ru: ["Помогите!"],
  },
  {
    type: "example",
    pinyin: "{{Word:bu4}} {{word:yao4}} {{word:mo1}} {{word:wo3}}!",
    ttsText: "不要摸我！",
    en: ["Don't touch me!"],
    zh: ["别碰我！"],
    ru: ["Не трогайте меня!"],
  },
  {
    type: "example",
    pinyin: "{{Word:ni3}} {{word:chu1}}-{{word:qu4}}!",
    ttsText: "你出去！",
    en: ["Go away! (Literally: \"get out!\")"],
    zh: ["走开！"],
    ru: ["Уходите! (Дословно: «выйдите!»)"],
  },
  {
    type: "example",
    pinyin: "{{Word:wo3}} {{word:bu4}} {{word:zhi1dao4}} {{word:wo3}} {{word:zai4}} {{word:na3li3}}.",
    ttsText: "我不知道我在哪里。",
    en: ["I'm lost. (Literally: \"I don't know where I am.\")"],
    zh: ["我迷路了。"],
    ru: ["Я заблудился. (Дословно: «я не знаю, где я».)"],
  },
  {
    type: "example",
    pinyin: "{{Word:wo3}}-{{word:de}} {{word:he2zi}} {{word:mei2}}-{{word:you3}} {{word:le}}!",
    ttsText: "我的盒子没有了！",
    en: ["My bag is gone!"],
    zh: ["我的包不见了！"],
    ru: ["Моя сумка пропала!"],
  },
  {
    type: "example",
    pinyin: "{{Word:you3}} {{word:huai4}} {{word:ren2}} {{word:na2}} {{word:le}} {{word:wo3}}-{{word:de}} {{word:jin1}}!",
    ttsText: "有坏人拿了我的金！",
    en: ["Someone stole my money! (Literally: \"a bad person took my money.\")"],
    zh: ["有人偷了我的钱！"],
    ru: ["У меня украли деньги! (Дословно: «плохой человек взял мои деньги».)"],
  },
  {
    type: "example",
    pinyin: "{{Word:jiao4}} {{word:ba3}} {{word:huai4}} {{word:ren2}} {{word:na2}}-{{word:qu4}}-{{word:de}} {{word:ren2}} {{word:lai2}}!",
    ttsText: "叫把坏人拿去的人来！",
    en: ["Call the police! (Literally: \"the people who take bad people away.\")"],
    zh: ["快叫警察！"],
    ru: ["Вызовите полицию! (Дословно: «людей, которые забирают плохих людей».)"],
  },
  {
    type: "example",
    pinyin: "{{Word:wo3}} {{word:mei2}}-{{word:you3}} {{word:nong4}} {{word:huai4}}-{{word:de}} {{word:dong1xi}}.",
    ttsText: "我没有弄坏的东西。",
    en: ["I haven't done anything wrong. (Literally: \"I didn't do bad things.\")"],
    zh: ["我没做坏事。"],
    ru: ["Я ничего плохого не сделал."],
  },
  {
    type: "prose",
    en: ["## At the doctor", "There are no words for doctor, hospital, or medicine. Each is something that makes the body good."],
    zh: ["## 看病", "没有\"医生\"\"医院\"\"药\"这些词，它们都是把身体弄好的东西。"],
    ru: ["## У врача", "Слов «врач», «больница» и «лекарство» нет. Каждое из них — то, что делает тело хорошим."],
    tldr: {
      en: ["I'm sick, it hurts, a fever, lying down, a doctor, a hospital, and medicine."],
      zh: ["不舒服、疼、发烧、躺下、医生、医院和药。"],
      ru: ["Мне плохо, болит, температура, прилечь, врач, больница и лекарство."],
    },
    necessity: {
      en: ["If you fall ill on a trip, these help you get care."],
      zh: ["在外地生病时，这些句子能帮你看病。"],
      ru: ["Если вы заболели в поездке, эти фразы помогут получить помощь."],
    },
  },
  {
    type: "example",
    pinyin: "{{Word:wo3}} {{word:shen1ti3}} {{word:bu4}} {{word:hao3}}.",
    ttsText: "我身体不好。",
    en: ["I'm sick. (Literally: \"my body isn't good.\")"],
    zh: ["我身体不舒服。"],
    ru: ["Мне плохо. (Дословно: «моё тело нехорошо».)"],
  },
  {
    type: "example",
    pinyin: "{{Word:wo3}}-{{word:de}} {{word:tou2}} {{word:jue2de}} {{word:hen3}} {{word:bu4}} {{word:hao3}}.",
    ttsText: "我的头觉得很不好。",
    en: ["My head hurts. (Literally: \"my head feels very bad.\")"],
    zh: ["我头疼。"],
    ru: ["У меня болит голова. (Дословно: «голова чувствует себя очень плохо».)"],
  },
  {
    type: "example",
    pinyin: "{{Word:wo3}}-{{word:de}} {{word:shen1ti3}} {{word:hen3}} {{word:re4}}.",
    ttsText: "我的身体很热。",
    en: ["I have a fever. (Literally: \"my body is very hot.\")"],
    zh: ["我发烧了。"],
    ru: ["У меня температура. (Дословно: «моё тело очень горячее».)"],
  },
  {
    type: "example",
    pinyin: "{{Word:wo3}} {{word:chi1}} {{word:le}} {{word:huai4}}-{{word:de}} {{word:dong1xi}}.",
    ttsText: "我吃了坏的东西。",
    en: ["I ate something bad."],
    zh: ["我吃坏东西了。"],
    ru: ["Я съел что-то не то."],
  },
  {
    type: "example",
    pinyin: "{{Word:wo3}} {{word:yao4}} {{word:tang3}}-{{word:xia4}}.",
    ttsText: "我要躺下。",
    en: ["I need to lie down."],
    zh: ["我要躺下。"],
    ru: ["Мне нужно прилечь."],
  },
  {
    type: "example",
    pinyin: "{{Word:wo3}} {{word:yao4}} {{word:ba3}}-{{word:bu4}}-{{word:hao3}}-{{word:de}}-{{word:shen1ti3}}-{{word:nong4}}-{{word:hao3}}-{{word:de}} {{word:ren2}}.",
    ttsText: "我要把不好的身体弄好的人。",
    en: ["I need a doctor. (Literally: \"the person who makes a sick body good.\")"],
    zh: ["我要看医生。"],
    ru: ["Мне нужен врач. (Дословно: «человек, который делает больное тело хорошим».)"],
  },
  {
    type: "example",
    pinyin: "{{Word:ba3}}-{{word:shen1ti3}}-{{word:nong4}}-{{word:hao3}}-{{word:de}} {{word:di4fang1}} {{word:zai4}} {{word:na3li3}}?",
    ttsText: "把身体弄好的地方在哪里？",
    en: ["Where's the hospital? (Literally: \"the place that makes bodies good.\")"],
    zh: ["医院在哪里？"],
    ru: ["Где больница? (Дословно: «место, где тело делают хорошим».)"],
  },
  {
    type: "example",
    pinyin: "{{Word:wo3}} {{word:yao4}} {{word:ba3}} {{word:shen1ti3}} {{word:nong4}}-{{word:hao3}}-{{word:de}} {{word:dong1xi}}.",
    ttsText: "我要把身体弄好的东西。",
    en: ["I need medicine. (Literally: \"the thing that makes the body good.\")"],
    zh: ["我需要药。"],
    ru: ["Мне нужно лекарство. (Дословно: «то, что делает тело хорошим».)"],
  },
];

export default content;
