// Russian text for pointing, matching shape.ts's keys. Typed as
// `PartialByKey<LessonShape>`.
// Not translated yet -- every `ru` is the empty-array placeholder.
import type { PartialByKey } from "../../../lib/chapter-shape-types.ts";
import type { LessonShape } from "./shape.ts";

const ru: PartialByKey<LessonShape> = {
  title: { ru: [] },
  summary: { ru: [] },
  vocabNa: { ru: [] },
  prosePointersAreNouns: { ru: [] },
  pointersExample01: { ru: [] },
  pointersExample02: { ru: [] },
  proseMandarinMeasureWords: { ru: [] },
  vocabGe: { ru: [] },
  proseGeIsUniversal: { ru: [] },
  infoUniversalClassifier: { items: [{ ru: [] }] },
  example1L11: { ru: [] },
  example2L11: { ru: [] },
  example3L11: { ru: [] },
  example4L11: { ru: [] },
  example5L11: { ru: [] },
  vocabWo: { ru: [] },
  vocabNi: { ru: [] },
  vocabTa: { ru: [] },
  prosePointingToPeople: { ru: [] },
  pointToPeopleExample01: { ru: [] },
  pointToPeopleExample02: { ru: [] },
  pointToPeopleExample03: { ru: [] },
  vocabMen: { ru: [] },
  prosePluralPointers: { ru: [] },
  pluralPointersExample01: { ru: [] },
  pluralPointersExample02: { ru: [] },
  pluralPointersExample03: { ru: [] },
  vocabJia: { ru: [] },
  vocabTou: { ru: [] },
  vocabShou: { ru: [] },
  vocabJiao: { ru: [] },
  prosePossessionDe: { ru: [] },
  posessionDeExample01: { ru: [] },
  posessionDeExample02: { ru: [] },
  posessionDeExample03: { ru: [] },
  posessionDeExample04: { ru: [] },
  posessionDeExample05: { ru: [] },
  posessionDeExample06: { ru: [] },
  posessionDeExample07: { ru: [] },
  posessionDeExample08: { ru: [] },
  exercise1L03: { ru: [] },
  exercise2L03: { ru: [] },
  exercise1L11: { ru: [] },
  exercise2L11: { ru: [] },
  exercise3L11: { ru: [] },
  exercise1: { ru: [] },
  exercise2: { ru: [] },
  exercise3: { ru: [] },
  exercise4: { ru: [] },
  exercise5: { ru: [] },
  exercise6: { ru: [] },
  exercise7: { ru: [] },
  answer1L03: { ru: [] },
  answer2L03: { ru: [] },
  answer1L11: { ru: [] },
  answer2L11: { ru: [] },
  answer3L11: { ru: [] },
  answer1: { ru: [] },
  answer2: { ru: [] },
  answer3: { ru: [] },
  answer4: { ru: [] },
  answer5: { ru: [] },
  answer6: { ru: [] },
  answer7: { ru: [] },
  faqGeForEverything: { question: { ru: [] }, ru: [] },
  faqTaHeOrShe: { question: { ru: [] }, ru: [] },
  faqDropDe: { question: { ru: [] }, ru: [] },
};

export default ru;
