// Chinese text for lesson-13, matching shape.ts's keys. Typed as
// `PartialByKey<LessonShape>`.
// Not translated yet -- every `zh` is the empty-array placeholder.
import type { PartialByKey } from "../../lib/chapter-shape-types.ts";
import type { LessonShape } from "./shape.ts";

const zh: PartialByKey<LessonShape> = {
  title: { zh: [] },
  summary: { zh: [] },
  vocabBi: { zh: [] },
  vocabYing: { zh: [] },
  vocabYuan: { zh: [] },
  vocabGunzi: { zh: [] },
  vocabXian: { zh: [] },
  proseThan: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleThan1: { zh: [] },
  exampleThan2: { zh: [] },
  exampleThan3: { zh: [] },
  exampleThan4: { zh: [] },
  exampleThan5: { zh: [] },
  exampleThan6: { zh: [] },
  exampleThan7: { zh: [] },
  exampleThan8: { zh: [] },
  exampleThan9: { zh: [] },
  vocabYiyang: { zh: [] },
  proseSame: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleSame1: { zh: [] },
  exampleSame2: { zh: [] },
  exampleSame3: { zh: [] },
  vocabButong: { zh: [] },
  vocabBiede: { zh: [] },
  proseDifferent: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleDifferent1: { zh: [] },
  exampleDifferent2: { zh: [] },
  exampleDifferent3: { zh: [] },
  exampleDifferent4: { zh: [] },
  exampleDifferent5: { zh: [] },
  exampleDifferent6: { zh: [] },
  vocabZhong: { zh: [] },
  proseKind: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleKind1: { zh: [] },
  exampleKind2: { zh: [] },
  exampleKind3: { zh: [] },
  proseShapeFeel: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleShapeFeel1: { zh: [] },
  exampleShapeFeel2: { zh: [] },
  exampleShapeFeel3: { zh: [] },
  exampleShapeFeel4: { zh: [] },
  exampleShapeFeel5: { zh: [] },
  infoComparing: {
    title: { zh: [] },
    items: [
      { zh: [] },
      { zh: [] },
      { zh: [] },
      { zh: [] },
      { zh: [] },
    ],
  },
  exercise1: { zh: [] },
  exercise2: { zh: [] },
  exercise3: { zh: [] },
  exercise4: { zh: [] },
  exercise5: { zh: [] },
  exercise6: { zh: [] },
  exercise7: { zh: [] },
  exercise8: { zh: [] },
  exercise9: { zh: [] },
  answer1: { zh: [] },
  answer2: { zh: [] },
  answer3: { zh: [] },
  answer4: { zh: [] },
  answer5: { zh: [] },
  answer6: { zh: [] },
  answer7: { zh: [] },
  answer8: { zh: [] },
  answer9: { zh: [] },
  faqMuchBigger: { question: { zh: [] }, zh: [] },
  faqNotAsBig: { question: { zh: [] }, zh: [] },
  faqButongOrBiede: { question: { zh: [] }, zh: [] },
};

export default zh;
