// Chinese text for how-much, matching shape.ts's keys. Typed as
// `PartialByKey<LessonShape>`.
// Not translated yet -- every `zh` is the empty-array placeholder.
import type { PartialByKey } from "../../../lib/chapter-shape-types.ts";
import type { LessonShape } from "./shape.ts";

const zh: PartialByKey<LessonShape> = {
  title: { zh: [] },
  summary: { zh: [] },
  vocabZhen: { zh: [] },
  vocabRe: { zh: [] },
  vocabLeng: { zh: [] },
  vocabTian: { zh: [] },
  vocabWeidao: { zh: [] },
  vocabQiguai: { zh: [] },
  vocabShenti: { zh: [] },
  vocabJiazhi: { zh: [] },
  vocabKuai: { zh: [] },
  proseVery: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleVery1: { zh: [] },
  exampleVery2: { zh: [] },
  exampleVery3: { zh: [] },
  exampleVery4: { zh: [] },
  exampleVery5: { zh: [] },
  exampleVery6: { zh: [] },
  exampleVery8: { zh: [] },
  exampleVery9: { zh: [] },
  proseReally: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleReally1: { zh: [] },
  exampleReally2: { zh: [] },
  exampleReally3: { zh: [] },
  exampleReally4: { zh: [] },
  exampleReally5: { zh: [] },
  proseNot: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleNot1: { zh: [] },
  exampleNot2: { zh: [] },
  exampleNot3: { zh: [] },
  exampleNot4: { zh: [] },
  exampleNot5: { zh: [] },
  vocabLao: { zh: [] },
  proseAsk: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleAsk1: { zh: [] },
  exampleAsk2: { zh: [] },
  exampleAsk3: { zh: [] },
  exampleAsk4: { zh: [] },
  exampleAsk5: { zh: [] },
  exampleAsk6: { zh: [] },
  exampleAsk7: { zh: [] },
  exampleAsk8: { zh: [] },
  infoHowMuch: {
    title: { zh: [] },
    items: [
      { zh: [] },
      { zh: [] },
      { zh: [] },
      { zh: [] },
      { zh: [] },
    ],
  },
  exercise1: { zh: [] },
  exercise2: { zh: [] },
  exercise3: { zh: [] },
  exercise4: { zh: [] },
  exercise5: { zh: [] },
  exercise6: { zh: [] },
  exercise7: { zh: [] },
  exercise8: { zh: [] },
  exercise9: { zh: [] },
  exercise10: { zh: [] },
  exercise11: { zh: [] },
  answer1: { zh: [] },
  answer2: { zh: [] },
  answer3: { zh: [] },
  answer4: { zh: [] },
  answer5: { zh: [] },
  answer6: { zh: [] },
  answer7: { zh: [] },
  answer8: { zh: [] },
  answer9: { zh: [] },
  answer10: { zh: [] },
  answer11: { zh: [] },
  faqHenStress: { question: { zh: [] }, zh: [] },
  faqBuHenOrder: { question: { zh: [] }, zh: [] },
  faqNoHenInQuestion: { question: { zh: [] }, zh: [] },
};

export default zh;
