// Writes the index files of the data folders, so a word, a composite entry
// or a coverage group is added or removed by adding or deleting its file:
//
//   src/data/words/index.ts       every src/data/words/<id>.ts      (WORDS, WordId)
//   src/data/composites/index.ts  every src/data/composites/*.ts    (ENTRIES)
//   src/data/coverage/index.ts    every src/data/coverage/<group>.ts (GROUPS)
//
// One list works everywhere (Vite, node scripts, bun tests), which
// import.meta.glob wouldn't. The dev server reruns this when a file is added
// or removed (vite-plugin-data.js), and `--check` (scripts/check-data.js)
// fails when an index doesn't match its folder.
//
//   node scripts/build-data.js          rewrite the indexes
//   node scripts/build-data.js --check  only report stale ones (exit 1)

import { readdirSync, readFileSync, writeFileSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
export const DATA_DIR = resolve(ROOT, 'src/data');

const HEADER = '// GENERATED by scripts/build-data.js from the files in this folder -- don\'t edit.\n// Add or delete a file instead; `npm run data` (or the dev server) rewrites this list.\n';

// -> the .ts files of a data folder, sorted, without the folder's own extras.
export function dataFiles(folder, skip = []) {
  const dir = resolve(DATA_DIR, folder);
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => f.endsWith('.ts') && f !== 'index.ts' && !skip.includes(f))
    .sort((a, b) => (a < b ? -1 : a > b ? 1 : 0));
}

const quote = (s) => JSON.stringify(s);

function wordsIndex() {
  const files = dataFiles('words');
  const ids = files.map((f) => f.slice(0, -3));
  return (
    HEADER +
    files.map((f, i) => `import w${i} from ${quote(`./${f}`)};`).join('\n') +
    '\n\nexport const WORDS = {\n' +
    ids.map((id, i) => `  ${quote(id)}: w${i},`).join('\n') +
    '\n};\n\nexport type WordId = keyof typeof WORDS;\n'
  );
}

function listIndex(folder, skip, name) {
  const files = dataFiles(folder, skip);
  return (
    HEADER +
    files.map((f, i) => `import m${i} from ${quote(`./${f}`)};`).join('\n') +
    `\n\nexport const ${name} = [\n` +
    files.map((_, i) => `  m${i},`).join('\n') +
    '\n];\n'
  );
}

// -> [{ path, text }] for every index file.
export function indexFiles() {
  return [
    { path: resolve(DATA_DIR, 'words/index.ts'), text: wordsIndex() },
    { path: resolve(DATA_DIR, 'composites/index.ts'), text: listIndex('composites', ['meta.ts'], 'ENTRIES') },
    { path: resolve(DATA_DIR, 'coverage/index.ts'), text: listIndex('coverage', ['about.ts'], 'GROUPS') },
  ];
}

// -> the index files that don't match their folders (rewritten unless check).
export function buildData({ check = false } = {}) {
  const stale = [];
  for (const { path, text } of indexFiles()) {
    const old = existsSync(path) ? readFileSync(path, 'utf-8') : null;
    if (old === text) continue;
    stale.push(path);
    if (!check) writeFileSync(path, text);
  }
  return stale;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const check = process.argv.includes('--check');
  const stale = buildData({ check });
  const rel = (p) => p.slice(ROOT.length + 1).replace(/\\/g, '/');
  if (check && stale.length) {
    console.error(`build-data: ${stale.map(rel).join(', ')} out of date -- run npm run data.`);
    process.exit(1);
  }
  console.log(stale.length ? `build-data: wrote ${stale.map(rel).join(', ')}` : 'build-data: indexes up to date.');
}
