#!/usr/bin/env node
// Checks that the lessons match the book's plan (see BOOK_PLAN.md §3-§4):
//
//   1. src/content/book.js and the lesson folders agree: every folder in
//      src/content/lessons/ is listed exactly once, every listed id has a
//      folder, and each lesson's index.ts has that id. Every other chapter
//      (not an intro) is in exactly one BACK_MATTER group of book.js. intro-3's
//      table of contents (built from book.js) has a line for every lesson and
//      every back-matter chapter, and no others.
//   2. Every dictionary word is introduced (has a `vocab` block) in exactly
//      one lesson. If BOOK_PLAN.md is present, each lesson's vocab list must
//      also match its row in the §4b table (rows are keyed by lesson id).
//   3. Every summary and tldr/necessity line (lessons and intros) is
//      jargon-free (scripts/jargon.js) and within the limits in
//      scripts/limits.js -- for every lesson, finished or not.
//   4. (The dictionary's own files -- word files, categories, opposites,
//      the data indexes -- are checked by scripts/check-data.js.)
//   5. The grammar overview (src/content/appendix-grammar.ts) matches the
//      lessons' grammar boxes -- it's generated by
//      scripts/generate-grammar-overview.js.
//   6. The Chinese in the phrase book (src/content/phrase-book.ts), the
//      stories (src/content/appendix-stories.ts), and the frontier
//      (src/content/appendix-frontier.ts) uses only dictionary words:
//      every example and story line's pinyin.
//   7. The composite dictionary (src/data/composites/) uses only
//      dictionary words, in its Hao-shuo-de forms and in the pinyin of its
//      notes, lists each word once, and gives a Hao-shuo-de form for every
//      entry that isn't a gap or a skip. When an entry's Chinese is made of
//      Hao-shuo-de words (爱好 = ài + hǎo), one of its forms says exactly
//      that real compound: its hanzi (`tts`) is the entry's Chinese, or it
//      is exactly those words.
//
// The other gates (jargon in the rest of the text, early words, word use,
// grammar boxes) are separate scripts; scripts/check-all.js runs them all on
// every build.
//
// Prints the New / Total so far counts per lesson. Exits non-zero on failure.
//
//   node scripts/check-book.js

import { readFileSync, readdirSync, existsSync } from 'fs';
import { resolve } from 'path';
import { fileURLToPath, pathToFileURL } from 'url';
import { LESSON_IDS, lessonNumber, lessonFolders, lessonFile } from './lessons.js';
import { BACK_MATTER_IDS } from '../src/content/book.js';
import { findJargon } from './jargon.js';
import { SUMMARY_MAX_WORDS, TLDR_MAX_WORDS, countWords } from './limits.js';
import { buildOverview, renderOverview } from './generate-grammar-overview.js';
import { wordsIn, termIndex } from './early-words.js';
import { wordHanzi } from '../src/lib/hanzi-map.js';
import dictionaryData from '../src/data/dictionary.ts';
import compositesData from '../src/data/composites.ts';
import { wordRefIds, soleWordRef } from '../src/lib/word-refs.js';
import { senseKey, refSenses } from '../src/lib/senses.js';
import { compoundSplitter } from '../src/lib/compound-rule.js';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const ROOT = resolve(__dirname, '..');
const CONTENT_DIR = resolve(ROOT, 'src/content');
const PLAN_PATH = resolve(ROOT, 'BOOK_PLAN.md');

const errors = [];

const dictionary = dictionaryData.words;
const termToId = new Map(Object.entries(dictionary).map(([id, w]) => [w.term.normalize('NFC'), id]));

// ---------- 1. book.js, the lesson folders, and intro-3 agree ----------
const folders = lessonFolders();
for (const id of folders) if (!LESSON_IDS.includes(id)) errors.push(`src/content/lessons/${id}/ isn't in src/content/book.js`);
for (const id of LESSON_IDS) if (!folders.includes(id)) errors.push(`src/content/book.js lists "${id}", but src/content/lessons/${id}/ doesn't exist`);
const duplicates = LESSON_IDS.filter((id, i) => LESSON_IDS.indexOf(id) !== i);
if (duplicates.length) errors.push(`src/content/book.js lists ${duplicates.join(', ')} more than once`);

// ---------- load lessons, in book order ----------
const lessons = [];
for (const id of LESSON_IDS.filter((id) => folders.includes(id))) {
  const { meta, default: entries } = await import(pathToFileURL(lessonFile(id, 'index.ts')));
  if (meta.id !== id) errors.push(`src/content/lessons/${id}/index.ts: meta.id is "${meta.id}", expected "${id}"`);
  const title = entries.find((e) => e.type === 'title')?.en?.join(' ') ?? '';
  const vocab = [];
  const senseCards = [];
  for (const entry of entries) {
    if (entry.type !== 'vocab') continue;
    const wordId = soleWordRef(entry.term);
    if (!wordId) errors.push(`${id}: vocab term "${entry.term}" is not a single dictionary word`);
    else if (entry.sense) senseCards.push(senseKey(wordId, entry.sense));
    else vocab.push(wordId);
  }
  lessons.push({ id, number: lessonNumber(id), title, vocab, senseCards, entries });
}

{
  const { LESSON_BLURBS, CHAPTER_BLURBS } = await import(pathToFileURL(resolve(CONTENT_DIR, 'intro-3.ts')));
  for (const id of LESSON_IDS) if (!LESSON_BLURBS[id]?.en?.length) errors.push(`intro-3: no table-of-contents line for "${id}" (LESSON_BLURBS)`);
  for (const id of Object.keys(LESSON_BLURBS)) if (!LESSON_IDS.includes(id)) errors.push(`intro-3: LESSON_BLURBS has "${id}", which isn't in src/content/book.js`);

  // Every chapter that isn't an intro or a lesson is in one BACK_MATTER group
  // of book.js, and intro-3 has a line for it.
  const chapters = [];
  for (const file of readdirSync(CONTENT_DIR)) {
    const path = resolve(CONTENT_DIR, file);
    if (/\.(rus|zh)\.md$/.test(file) || /^intro-\d+\.ts$/.test(file)) continue;
    if (/\.(md|ya?ml)$/.test(file)) {
      const id = readFileSync(path, 'utf-8').match(/^id:\s*(\S+)/m)?.[1];
      if (id) chapters.push(id);
    } else if (file.endsWith('.ts')) {
      chapters.push((await import(pathToFileURL(path))).meta.id);
    }
  }
  for (const id of chapters) if (!BACK_MATTER_IDS.includes(id)) errors.push(`chapter "${id}" isn't in a BACK_MATTER group of src/content/book.js`);
  for (const id of BACK_MATTER_IDS) if (!chapters.includes(id)) errors.push(`src/content/book.js BACK_MATTER lists "${id}", but no chapter has that id`);
  const twice = BACK_MATTER_IDS.filter((id, i) => BACK_MATTER_IDS.indexOf(id) !== i);
  if (twice.length) errors.push(`src/content/book.js BACK_MATTER lists ${twice.join(', ')} more than once`);
  for (const id of BACK_MATTER_IDS) if (!CHAPTER_BLURBS[id]?.en?.length) errors.push(`intro-3: no table-of-contents line for "${id}" (CHAPTER_BLURBS)`);
  for (const id of Object.keys(CHAPTER_BLURBS)) if (!BACK_MATTER_IDS.includes(id)) errors.push(`intro-3: CHAPTER_BLURBS has "${id}", which isn't in BACK_MATTER`);
}

// ---------- 2. every word introduced exactly once ----------
const home = new Map();
for (const lesson of lessons) {
  for (const wordId of lesson.vocab) {
    if (!dictionary[wordId]) errors.push(`${lesson.id}: vocab word "${wordId}" is not in the dictionary`);
    else if (home.has(wordId)) errors.push(`"${wordId}" is introduced twice: ${home.get(wordId).id} and ${lesson.id}`);
    else home.set(wordId, lesson);
  }
}
// A catch-all word's other senses get a card each, once (src/lib/senses.js).
const senseHome = new Map();
for (const lesson of lessons) {
  for (const key of lesson.senseCards) {
    const [wordId, sense] = key.split('#');
    if (!dictionary[wordId]?.senses?.[sense]) errors.push(`${lesson.id}: a card teaches sense "${sense}" of ${wordId}, which its word file doesn't list`);
    else if (senseHome.has(key)) errors.push(`"${key}" is introduced twice: ${senseHome.get(key).id} and ${lesson.id}`);
    else senseHome.set(key, lesson);
  }
}
const neverIntroduced = Object.keys(dictionary).filter((wordId) => !home.has(wordId));
if (neverIntroduced.length) errors.push(`words no lesson introduces: ${neverIntroduced.join(', ')}`);

if (existsSync(PLAN_PATH)) {
  const plan = readFileSync(PLAN_PATH, 'utf-8');
  const table = plan.split('### 4b.')[1]?.split('\n###')[0] ?? '';
  // Any column padding (a markdown formatter may align the table).
  // Rows are keyed by lesson id (first column), so they survive reordering.
  const rows = table.split(/\r?\n/).filter((line) => /^\|\s*[a-z][a-z0-9-]*\s*\|/.test(line));
  if (!rows.length) errors.push('BOOK_PLAN.md: no §4b table found');
  for (const lesson of lessons) {
    if (!rows.some((row) => row.split('|')[1].trim() === lesson.id)) errors.push(`BOOK_PLAN.md §4b: no row for ${lesson.id}`);
  }
  for (const row of rows) {
    const cells = row.split('|').map((c) => c.trim());
    const id = cells[1];
    const planned = cells
      .slice(3, 6)
      .flatMap((c) => (c === '—' ? [] : c.split(',').map((w) => w.trim().normalize('NFC'))))
      .map((term) => termToId.get(term) ?? `?${term}`);
    const lesson = lessons.find((l) => l.id === id);
    if (!lesson) { errors.push(`BOOK_PLAN.md §4b: "${id}" isn't a lesson in src/content/book.js`); continue; }
    const actual = [...lesson.vocab].sort().join();
    if ([...planned].sort().join() !== actual) {
      errors.push(`${lesson.id}: vocab [${lesson.vocab.join(', ')}] doesn't match BOOK_PLAN.md §4b [${planned.join(', ')}]`);
    }
  }
}

// ---------- 3. summaries and TL;DR lines ----------
function checkShortLine(where, field, sentences, maxWords) {
  const text = (sentences ?? []).join(' ');
  if (!text) return errors.push(`${where}: ${field} is missing`);
  const jargon = findJargon(text).map((h) => h.term);
  if (jargon.length) errors.push(`${where}: ${field} uses jargon (${[...new Set(jargon)].join(', ')}): "${text}"`);
  const words = countWords(text);
  if (words > maxWords) errors.push(`${where}: ${field} is ${words} words, max ${maxWords}: "${text}"`);
}

for (const lesson of lessons) {
  lesson.entries.forEach((entry, i) => {
    if (entry.type === 'summary') checkShortLine(lesson.id, 'summary', entry.en, SUMMARY_MAX_WORDS);
    if (entry.type === 'prose') {
      checkShortLine(`${lesson.id} block ${i}`, 'tldr', entry.tldr?.en, TLDR_MAX_WORDS);
      checkShortLine(`${lesson.id} block ${i}`, 'necessity', entry.necessity?.en, TLDR_MAX_WORDS);
    }
  });
}
for (const n of [1, 2, 3]) {
  const entries = (await import(pathToFileURL(resolve(CONTENT_DIR, `intro-${n}.ts`)))).default;
  entries.forEach((entry, i) => {
    if (entry.type === 'summary') checkShortLine(`intro-${n}`, 'summary', entry.en, SUMMARY_MAX_WORDS);
    if (entry.type === 'prose' && (entry.tldr || entry.necessity)) {
      checkShortLine(`intro-${n} block ${i}`, 'tldr', entry.tldr?.en, TLDR_MAX_WORDS);
      checkShortLine(`intro-${n} block ${i}`, 'necessity', entry.necessity?.en, TLDR_MAX_WORDS);
    }
  });
}

// ---------- 5. grammar overview is up to date ----------
{
  const path = resolve(CONTENT_DIR, 'appendix-grammar.ts');
  const current = existsSync(path) ? readFileSync(path, 'utf-8').replace(/\r\n/g, '\n') : '';
  if (current !== renderOverview(await buildOverview())) {
    errors.push('src/content/appendix-grammar.ts is out of date with the lessons\' grammar boxes -- run npm run grammar-overview');
  }
}

// ---------- 6. the phrase book and the stories use only dictionary words ----------
{
  const terms = termIndex(dictionary);
  for (const file of ['phrase-book.ts', 'appendix-stories.ts', 'appendix-frontier.ts']) {
    const entries = (await import(pathToFileURL(resolve(CONTENT_DIR, file)))).default;
    entries.forEach((e, i) => {
      if (!e.pinyin) return;
      // Names and animal sounds go in quotes (Lesson 1), so they don't count as words.
      const unknown = wordsIn(e.pinyin.replace(/"[^"]*"/g, ' '), terms, { pinyinField: true }).filter((w) => !w.id || !dictionary[w.id]);
      if (unknown.length) errors.push(`${file} entry ${i}: ${unknown.map((w) => w.token).join(', ')} not in the dictionary: "${e.pinyin}"`);
    });
  }
}

// ---------- 7. the composite dictionary uses only dictionary words ----------
{
  const terms = termIndex(dictionary);
  const { entries } = compositesData;
  const seen = new Set();
  for (const e of entries) {
    const where = `composite "${e.zh}"`;
    if (seen.has(e.zh)) errors.push(`${where}: listed twice`);
    seen.add(e.zh);
    if (!e.hsd) {
      if (e.fit !== 'gap' && e.fit !== 'skip') errors.push(`${where}: no Hao-shuo-de form, but fit is "${e.fit}"`);
      continue;
    }
    // Names go in quotes (Lesson 1), so they don't count as words.
    const unknown = wordsIn(e.hsd.replace(/"[^"]*"/g, ' '), terms, { pinyinField: true }).filter((w) => !w.id || !dictionary[w.id]);
    if (unknown.length) errors.push(`${where}: ${unknown.map((w) => w.token).join(', ')} not in the dictionary: "${e.hsd}"`);
  }
  // A Chinese word made of Hao-shuo-de words is said with that compound.
  const compound = compoundSplitter(dictionary);
  for (const e of entries) {
    if (!e.hsd || e.fit === 'name' || e.fit === 'skip') continue;
    const ids = compound(e.zh);
    if (!ids || (e.tts ?? '').split(' / ').includes(e.zh)) continue;
    // A form that is exactly those words counts too (the builder speaks a bare 上 as 上面).
    const sequences = e.hsd.split(' / ').map((f) => wordRefIds(f).join(' '));
    if (sequences.includes(ids.join(' '))) continue;
    const form = ids.map((id) => dictionary[id].term).join('-');
    errors.push(`composite "${e.zh}": it's made of Hao-shuo-de words, so say it the Mandarin way first: ${form}`);
  }
  // A colloquial form (Mandarin's own compound, or a word read in one of its
  // senses) comes with a constructive one after " / ", so the meaning can be
  // built up from the core: míng-tiān / xià yī-ge rì. Required from phase 4
  // on; older entries are counted (--list-colloquial names them).
  const colloquialOnly = [];
  for (const e of entries) {
    if (!e.hsd || e.transparent || !['natural', 'word'].includes(e.fit)) continue;
    const forms = e.hsd.split(' / ');
    if (forms.length > 1) continue;
    const ids = wordRefIds(forms[0]);
    const usesSense = refSenses(forms[0], dictionary).some((u) => u.sense);
    if (ids.length < 2 && !usesSense) continue;
    if (e.phase >= 4) errors.push(`composite "${e.zh}": ${forms[0]} is the colloquial form -- add a constructive one after " / " (or mark it transparent: true)`);
    else colloquialOnly.push(`${e.zh} ${e.hsd}`);
  }
  if (colloquialOnly.length) {
    console.log(`check-book: ${colloquialOnly.length} older composite(s) give only the colloquial form${process.argv.includes('--list-colloquial') ? ':' : ' (--list-colloquial to name them).'}`);
    if (process.argv.includes('--list-colloquial')) for (const c of colloquialOnly) console.log(`  ${c}`);
  }
  // Notes are English, but any pinyin in them must be dictionary words too.
  for (const e of entries) {
    if (!e.note) continue;
    const unknown = wordsIn(e.note.replace(/"[^"]*"/g, ' '), terms).filter((w) => !w.id || !dictionary[w.id]);
    if (unknown.length) errors.push(`composite "${e.zh}" note: ${unknown.map((w) => w.token).join(', ')} not in the dictionary: "${e.note}"`);
  }
}

// ---------- report ----------
const total = Object.keys(dictionary).length;
let soFar = 0;
console.log(`L   New  Total so far  Lesson`);
for (const lesson of lessons) {
  soFar += lesson.vocab.length;
  const pct = Math.round((soFar / total) * 100);
  console.log(
    `${String(lesson.number).padEnd(3)} ${String(lesson.vocab.length).padStart(3)}  ${`${soFar} / ${total}`.padStart(9)} ${`${pct}%`.padStart(4)}  ${lesson.title}`,
  );
}
if (errors.length) {
  console.error(`\ncheck-book: ${errors.length} error(s):`);
  for (const e of errors) console.error(`  - ${e}`);
  process.exit(1);
}
console.log(`\ncheck-book: OK -- ${lessons.length} lessons match intro-3, ${home.size}/${total} words introduced once.`);
