// The engine behind `npm run word` and `npm run refactor`: word refactors
// (add, split, replace, rename, move a card, ...) applied to an in-memory
// copy of the content, so a whole list of them can be shown as a dry run
// before anything is written.
//
// What it edits, and how:
//   - Data files (src/data/words, composites, maps, coverage) are loaded as
//     objects and written back with the same writer that formats them, so a
//     change is a small diff.
//   - Everything else under src/ (lesson modules, stories, the phrase book,
//     YAML and Markdown chapters, tests) is text. In JS/TS files only string
//     literals are rewritten (comments are left alone), and a sentence's
//     `hanzi`/`ttsText` follows its `pinyin`/`answer` when an op gives a
//     hanzi change. A vocabulary card is an object with `word: "<id>"`.
//   - What it can't decide is collected as notes for a hand edit: changed
//     sentences whose English/Russian may need a look, plain-text mentions
//     of a removed word, dropped relations, id strings in code.

import { readdirSync, readFileSync, writeFileSync, unlinkSync, existsSync, mkdirSync, statSync } from 'fs';
import { resolve, dirname, relative, extname } from 'path';
import { fileURLToPath } from 'url';
import { tsLiteral, compositeFileName } from './data-files.js';
import { wordRefRe, wordRefIds, toneless } from '../src/lib/word-refs.js';
import { compoundSplitter, compoundForm } from '../src/lib/compound-rule.js';
import { LESSON_IDS } from '../src/content/book.js';

export const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

// -- the workspace -------------------------------------------------------------

const TEXT_EXT = new Set(['.ts', '.js', '.jsx', '.yaml', '.md']);
const SKIP = new Set([
  'src/data/words/index.ts',
  'src/data/composites/index.ts',
  'src/data/coverage/index.ts',
  // generated by scripts/generate-dictionary.js
  'src/content/dictionary.md',
  'src/content/dictionary.rus.md',
  'src/content/dictionary.zh.md',
]);

function walk(dir, out) {
  for (const name of readdirSync(dir)) {
    const p = resolve(dir, name);
    if (statSync(p).isDirectory()) walk(p, out);
    else if (TEXT_EXT.has(extname(name))) out.push(p);
  }
  return out;
}

const rel = (p) => relative(ROOT, p).replace(/\\/g, '/');
const WORDS_DIR = 'src/data/words/';
const COMPOSITES_DIR = 'src/data/composites/';
const LESSONS_DIR = 'src/content/lessons/';

// A data file: "<prefix><literal>);\n" -- the prefix holds the comments, the
// import and "export default helper(" (plus "id", for a word).
function splitData(text, path) {
  const m = text.match(/^([\s\S]*?export default \w+\((?:"[^"]+", )?)([\s\S]*)\);\n$/);
  if (!m) throw new Error(`${path}: not a data file`);
  return { prefix: m[1], value: Function(`return (${m[2]});`)() };
}

const LF = String.fromCharCode(10);
const CRLF = String.fromCharCode(13, 10);

export class Workspace {
  constructor() {
    this.orig = new Map();
    this.text = new Map();
    // files are edited with LF line ends and written back with the ones they had
    this.crlf = new Set();
    const files = [...walk(resolve(ROOT, 'src'), []), ...walk(resolve(ROOT, 'scripts'), []).filter((p) => p.endsWith('.test.js'))];
    for (const p of files) {
      const r = rel(p);
      if (SKIP.has(r)) continue;
      let t = readFileSync(p, 'utf-8');
      if (t.includes(CRLF)) {
        this.crlf.add(r);
        t = t.split(CRLF).join(LF);
      }
      this.orig.set(r, t);
      this.text.set(r, t);
    }
    this.notes = [];
  }

  note(kind, text) {
    this.notes.push({ kind, text });
  }

  has(r) {
    return this.text.get(r) != null;
  }
  get(r) {
    const t = this.text.get(r);
    if (t == null) throw new Error(`no file ${r}`);
    return t;
  }
  set(r, t) {
    this.text.set(r, t);
  }
  remove(r) {
    this.text.set(r, null);
  }
  files(prefix = '') {
    return [...this.text.keys()].filter((r) => r.startsWith(prefix) && this.text.get(r) != null);
  }

  // -- data files --
  data(r) {
    return splitData(this.get(r), r).value;
  }
  setData(r, value) {
    const { prefix } = splitData(this.get(r), r);
    this.set(r, `${prefix}${tsLiteral(value)});\n`);
  }

  wordPath(id) {
    return `${WORDS_DIR}${id}.ts`;
  }
  wordIds() {
    return this.files(WORDS_DIR).map((r) => r.slice(WORDS_DIR.length, -3));
  }
  hasWord(id) {
    return this.has(this.wordPath(id));
  }
  word(id) {
    if (!this.hasWord(id)) throw new Error(`no word ${id}`);
    return this.data(this.wordPath(id));
  }
  setWord(id, value) {
    const order = ['term', 'hanzi', 'pos', 'definition', 'necessity', 'maps', 'senses'];
    const out = {};
    for (const k of [...order, ...Object.keys(value).filter((k) => !order.includes(k))]) if (value[k] !== undefined) out[k] = value[k];
    this.set(this.wordPath(id), `import { word } from "../../lib/word.ts";\n\nexport default word(${JSON.stringify(id)}, ${tsLiteral(out)});\n`);
  }

  composites() {
    return this.files(COMPOSITES_DIR).filter((r) => !r.endsWith('/meta.ts')).map((r) => ({ path: r, entry: this.data(r) }));
  }
  setComposite(path, entry) {
    const want = COMPOSITES_DIR + compositeFileName(entry);
    if (want !== path) this.remove(path);
    const text = `import { composite } from "../../lib/composite.ts";\n\nexport default composite(${tsLiteral(entry)});\n`;
    this.set(want, text);
  }

  // -> [{ path, before, after }] for every file that changed.
  changes() {
    const out = [];
    for (const [r, after] of this.text) {
      const before = this.orig.get(r) ?? null;
      if (before !== after) out.push({ path: r, before, after });
    }
    return out.sort((a, b) => (a.path < b.path ? -1 : 1));
  }

  write() {
    for (const { path, after } of this.changes()) {
      const p = resolve(ROOT, path);
      if (after == null) {
        if (existsSync(p)) unlinkSync(p);
      } else {
        mkdirSync(dirname(p), { recursive: true });
        writeFileSync(p, this.crlf.has(path) ? after.split(LF).join(CRLF) : after);
      }
    }
  }
}

// -- string literals in JS/TS -----------------------------------------------------

// -> { strings, objects } for a JS/TS source: every string literal with its
// span, the key it's the value of (or the key of the array it's in), and the
// innermost object it sits in; every object literal with its span and the
// key it's the value of. Comments are skipped. Good enough for the content
// files, which are plain data.
export function scanSource(src) {
  const strings = [];
  const objects = [];
  const stack = []; // { type: '{' | '[', key, obj, lastKey }
  let i = 0;
  const top = () => stack[stack.length - 1];
  const innerObj = () => {
    for (let k = stack.length - 1; k >= 0; k--) if (stack[k].type === '{') return stack[k];
    return null;
  };
  const valueKey = () => {
    const t = top();
    if (!t) return null;
    return t.type === '{' ? t.lastKey : t.key;
  };
  while (i < src.length) {
    const c = src[i];
    if (c === '/' && src[i + 1] === '/') {
      while (i < src.length && src[i] !== '\n') i++;
      continue;
    }
    if (c === '/' && src[i + 1] === '*') {
      i = src.indexOf('*/', i + 2) + 2;
      continue;
    }
    if (c === '"' || c === "'" || c === '`') {
      let j = i + 1;
      while (j < src.length && src[j] !== c) j += src[j] === '\\' ? 2 : 1;
      const start = i;
      const end = j + 1;
      // A string followed by ':' is a key ("lóng": ...), not a value.
      const after = src.slice(end).match(/^\s*:/);
      const t = top();
      if (after && t?.type === '{') t.lastKey = src.slice(start + 1, end - 1);
      else strings.push({ start, end, key: valueKey(), obj: innerObj()?.obj ?? null });
      i = end;
      continue;
    }
    if (c === '{' || c === '[') {
      const key = valueKey();
      const frame = { type: c, key, lastKey: null, obj: null };
      if (c === '{') {
        frame.obj = { id: objects.length, start: i, end: -1, key, parent: innerObj()?.obj ?? null };
        objects.push(frame.obj);
      }
      stack.push(frame);
      i++;
      continue;
    }
    if (c === '}' || c === ']') {
      const f = stack.pop();
      if (f?.obj) f.obj.end = i + 1;
      i++;
      continue;
    }
    if (c === ',') {
      const t = top();
      if (t?.type === '{') t.lastKey = null;
      i++;
      continue;
    }
    if (/[A-Za-z_$]/.test(c)) {
      let j = i;
      while (j < src.length && /[\w$]/.test(src[j])) j++;
      const ident = src.slice(i, j);
      const t = top();
      if (t?.type === '{' && /^\s*:/.test(src.slice(j))) t.lastKey = ident;
      i = j;
      continue;
    }
    i++;
  }
  return { strings, objects };
}

// -> a string literal's value (the content files only use JSON-style escapes).
export function literalValue(src, s) {
  const raw = src.slice(s.start, s.end);
  if (raw[0] === '"') return JSON.parse(raw);
  return raw.slice(1, -1).replace(/\\(.)/g, '$1');
}

// -> literal text for a value, quoted the way the original was.
function literalText(value, quote) {
  if (quote === '"') return JSON.stringify(value);
  return quote + value.replace(/\\/g, '\\\\').replace(new RegExp(quote, 'g'), `\\${quote}`) + quote;
}

const SENTENCE_KEYS = new Set(['pinyin', 'answer']);
const HANZI_KEYS = new Set(['hanzi', 'ttsText']);

// Rewrites a JS/TS source's string literals with fn(value, s) -> value. When a
// sentence (`pinyin`/`answer`) changes, hanziFn(hanzi) -> hanzi rewrites the
// `hanzi`/`ttsText` of the same object. -> { text, changed: [{ obj, key, before, after, hanzi? }] }
export function rewriteStrings(src, fn, hanziFn) {
  const { strings } = scanSource(src);
  const edits = [];
  const changed = [];
  const sentenceObjs = new Set();
  for (const s of strings) {
    const v = literalValue(src, s);
    const nv = fn(v, s);
    if (nv === v) continue;
    edits.push({ s, value: nv });
    changed.push({ obj: s.obj?.id ?? null, key: s.key, before: v, after: nv });
    if (SENTENCE_KEYS.has(s.key) && s.obj) sentenceObjs.add(s.obj.id);
  }
  if (hanziFn) {
    for (const s of strings) {
      if (!HANZI_KEYS.has(s.key) || !s.obj || !sentenceObjs.has(s.obj.id)) continue;
      const v = literalValue(src, s);
      const nv = hanziFn(v);
      const c = changed.find((x) => x.obj === s.obj.id && SENTENCE_KEYS.has(x.key));
      if (c) c.hanzi = { before: v, after: nv };
      if (nv !== v) edits.push({ s, value: nv });
    }
  }
  edits.sort((a, b) => b.s.start - a.s.start);
  let out = src;
  for (const { s, value } of edits) out = out.slice(0, s.start) + literalText(value, src[s.start]) + out.slice(s.end);
  return { text: out, changed };
}

// -> text with each ref to `id` replaced by make(kind) (kind: word, Word, light, Light).
export function replaceRefsTo(text, id, make) {
  return text.replace(wordRefRe(), (full, kind, ref) => (ref === id ? make(kind) : full));
}

// -> a ref of a kind, with the case of `kind` kept and its lightness given.
const ref = (kind, id, light = false) => {
  const cap = kind === 'Word' || kind === 'Light';
  const k = light || kind === 'light' || kind === 'Light' ? 'light' : 'word';
  return `{{${cap ? k[0].toUpperCase() + k.slice(1) : k}:${id}}}`;
};

// -> the form with its first ref capitalized (for a sentence-initial use).
function capitalizeForm(form) {
  if (/^\{\{(word|light):/.test(form)) return form.replace(/^\{\{(\w)/, (_, c) => `{{${c.toUpperCase()}`);
  return form.charAt(0).toUpperCase() + form.slice(1);
}

// -- lesson cards --------------------------------------------------------------

// -> the module files of a lesson, in reading order (from its index.ts).
function moduleFiles(ws, lesson) {
  const index = ws.get(`${LESSONS_DIR}${lesson}/index.ts`);
  const imports = new Map([...index.matchAll(/^import (\w+) from "\.\/([\w-]+\.ts)";/gm)].map((m) => [m[1], m[2]]));
  const list = index.match(/modules:\s*\[([^\]]*)\]/)?.[1] ?? '';
  return list.split(',').map((s) => s.trim()).filter(Boolean).map((name) => `${LESSONS_DIR}${lesson}/${imports.get(name)}`);
}

// -> every card in the book, in reading order:
// [{ word, sense, file, lesson, module, order, obj, src }]
export function cards(ws) {
  const out = [];
  LESSON_IDS.forEach((lesson) => {
    if (!ws.has(`${LESSONS_DIR}${lesson}/index.ts`)) return;
    for (const file of moduleFiles(ws, lesson)) {
      if (!ws.has(file)) continue;
      const src = ws.get(file);
      const { strings, objects } = scanSource(src);
      const module = src.match(/lessonModule\(\{\s*id:\s*"([^"]+)"/)?.[1];
      for (const o of objects) {
        if (o.key !== 'words') continue;
        const own = strings.filter((s) => s.obj?.id === o.id);
        const w = own.find((s) => s.key === 'word');
        if (!w) continue;
        const sense = own.find((s) => s.key === 'sense');
        out.push({
          word: literalValue(src, w),
          sense: sense ? literalValue(src, sense) : undefined,
          file,
          lesson,
          module,
          order: out.length,
          obj: o,
        });
      }
    }
  });
  return out;
}

const cardKey = (word, sense) => `${word}${sense ? `#${sense}` : ''}`;

// -> the card's text at an indent: the house style, one field per line.
function cardText(card, indent) {
  const inner = indent + '  ';
  const lines = [`${indent}{`, `${inner}word: ${JSON.stringify(card.word)},`];
  if (card.sense) lines.push(`${inner}sense: ${JSON.stringify(card.sense)},`);
  if (card.hanzi) lines.push(`${inner}hanzi: ${JSON.stringify(card.hanzi)},`);
  lines.push(`${inner}en: ${JSON.stringify(card.en)},`, `${inner}ru: ${JSON.stringify(card.ru)},`, `${indent}},`);
  return lines.join('\n');
}

// -> the span of a card object's lines: its whole lines, trailing comma included.
function cardLines(src, obj) {
  const start = src.lastIndexOf('\n', obj.start) + 1;
  let end = obj.end;
  if (src[end] === ',') end++;
  if (src[end] === '\n') end++;
  return { start, end, indent: src.slice(start, obj.start) };
}

// -> a card object's fields as data.
function cardData(src, obj) {
  return Function(`return (${src.slice(obj.start, obj.end)});`)();
}

// Replaces one card (by `at`) with a list of cards (data), in place.
function spliceCards(ws, at, list) {
  const src = ws.get(at.file);
  const { start, end, indent } = cardLines(src, at.obj);
  const text = list.map((c) => cardText(c, indent) + '\n').join('');
  ws.set(at.file, src.slice(0, start) + text + src.slice(end));
}

function removeCard(ws, at) {
  spliceCards(ws, at, []);
  const src = ws.get(at.file);
  if (/words:\s*\[\s*\],?/.test(src)) {
    ws.set(at.file, src.replace(/\n\s*words:\s*\[\s*\],?/, ''));
  }
}

// Adds a card at the end of a module's words (creating the list if needed).
function appendCard(ws, file, card) {
  const src = ws.get(file);
  const m = src.match(/\n(\s*)words:\s*\[/);
  if (m) {
    const { objects } = scanSource(src);
    const listStart = m.index + m[0].length - 1;
    // the array's closing bracket: the first ']' after the last card object in it
    const inList = objects.filter((o) => o.key === 'words' && o.start > listStart);
    let close = src.indexOf(']', inList.length ? inList[inList.length - 1].end : listStart);
    const lineStart = src.lastIndexOf('\n', close) + 1;
    const indent = m[1] + '  ';
    ws.set(file, src.slice(0, lineStart) + cardText(card, indent) + '\n' + src.slice(lineStart));
    return;
  }
  const idLine = src.match(/\n(\s*)id: "[^"]+",\n/);
  if (!idLine) throw new Error(`${file}: no place for a words list`);
  const at = idLine.index + idLine[0].length;
  const indent = idLine[1];
  ws.set(file, src.slice(0, at) + `${indent}words: [\n${cardText(card, indent + '  ')}\n${indent}],\n` + src.slice(at));
}

// -> "lesson/module" -> the module's file.
export function moduleFile(ws, spec) {
  const [lesson, module] = spec.split('/');
  for (const file of moduleFiles(ws, lesson)) {
    if (ws.get(file).match(/lessonModule\(\{\s*id:\s*"([^"]+)"/)?.[1] === module) return file;
  }
  throw new Error(`no module "${spec}" (lesson/module ids, e.g. moving/far)`);
}

// -- glosses -------------------------------------------------------------------

// -> a short gloss from a definition: its first sense, refs written as terms.
function firstSense(ws, text) {
  const plain = text.replace(wordRefRe(), (full, kind, id) => (ws.hasWord(id) ? ws.word(id).term : id));
  return plain.split(/[;(]/)[0].split(',').slice(0, 2).join(',').trim();
}

function newCard(ws, id, sense) {
  const w = ws.word(id);
  if (sense) {
    const s = w.senses?.[sense];
    if (!s) throw new Error(`${id} has no sense "${sense}"`);
    return { word: id, sense, en: s.eng, ru: s.rus };
  }
  return { word: id, en: firstSense(ws, w.definition.eng), ru: firstSense(ws, w.definition.rus) };
}

// -- maps and coverage -------------------------------------------------------------

const MAPS = 'src/data/maps/';
const COVERAGE = 'src/data/coverage/';

function walkCategories(cats, fn) {
  for (const c of cats) {
    fn(c);
    walkCategories(c.children ?? [], fn);
  }
}

function categoryOf(ws, id) {
  let leaf = null;
  walkCategories(ws.data(`${MAPS}categories.ts`), (c) => {
    if ((c.wordIds ?? []).includes(id)) leaf = c.key;
  });
  return leaf;
}

// Rewrites every leaf's word list with fn(ids) -> ids.
function editCategories(ws, fn) {
  const cats = ws.data(`${MAPS}categories.ts`);
  walkCategories(cats, (c) => {
    if (c.wordIds) c.wordIds = fn(c.wordIds, c);
  });
  ws.setData(`${MAPS}categories.ts`, cats);
}

// Rewrites the antonym and synonym maps: pairs by pairFn([a, b]) -> pair | null,
// phrases by phraseFn(id, forms) -> [id, forms] | null; refs are rewritten later.
function editRelations(ws, pairFn, phraseFn, why) {
  for (const name of ['antonyms', 'synonyms']) {
    const path = `${MAPS}${name}.ts`;
    const r = ws.data(path);
    const pairs = [];
    for (const p of r.pairs) {
      const np = pairFn(p);
      if (np) pairs.push(np);
      else ws.note('relation', `${name}: dropped [${p.join(', ')}] (${why}) -- re-add by hand if it still holds`);
    }
    const phrases = {};
    for (const [id, forms] of Object.entries(r.phrases)) {
      const np = phraseFn(id, forms);
      if (np) phrases[np[0]] = np[1];
      else ws.note('relation', `${name}: dropped the phrase for ${id} (${why})`);
    }
    ws.setData(path, { pairs, phrases });
  }
}

function coverageFiles(ws) {
  return ws.files(COVERAGE).filter((r) => !r.endsWith('/index.ts') && !r.endsWith('/about.ts'));
}

function editCoverageWords(ws, fn) {
  for (const path of coverageFiles(ws)) {
    const g = ws.data(path);
    let touched = false;
    for (const item of g.items) {
      const nw = fn(item.words, item);
      if (nw !== item.words) {
        item.words = [...new Set(nw)];
        touched = true;
      }
    }
    if (touched) ws.setData(path, g);
  }
}

// -- rewriting references everywhere ----------------------------------------------

const isCode = (r) => /\.(ts|js|jsx)$/.test(r);

// Rewrites every ref to `id` in every file with make(kind). hanziFn, when
// given, rewrites the hanzi of each sentence that changed; every changed
// sentence is noted when noteSentences is set.
function rewriteAll(ws, id, make, opts = {}) {
  rewriteText(ws, (t) => replaceRefsTo(t, id, make), { ...opts, has: (t) => t.includes(`:${id}}}`) });
}

// Rewrites text everywhere with fn(text) -> text: string literals in code,
// whole files elsewhere, composite forms with their hanzi kept in step.
function rewriteText(ws, fn, { hanziFn, noteSentences = false, label, has = () => true } = {}) {
  const apply = (v) => fn(v);
  for (const path of ws.files()) {
    let src = ws.get(path);
    if (!has(src)) continue;
    if (path.startsWith(WORDS_DIR) || path.startsWith(COMPOSITES_DIR) || path.startsWith(MAPS) || path.startsWith(COVERAGE)) {
      // data: refs are inside string values; composites keep hsd/tts in step
      const r = rewriteStrings(src, (v) => apply(v));
      if (path.startsWith(COMPOSITES_DIR) && hanziFn) {
        const e = ws.data(path);
        const before = splitData(src, path).value;
        ws.set(path, r.text);
        const after = ws.data(path);
        (after.hsd ?? []).forEach((f, i) => {
          if (f !== before.hsd[i] && after.tts?.[i] != null) after.tts[i] = hanziFn(after.tts[i]);
        });
        ws.setComposite(path, after);
        void e;
      } else ws.set(path, r.text);
      continue;
    }
    if (isCode(path)) {
      const r = rewriteStrings(src, (v) => apply(v), hanziFn);
      ws.set(path, r.text);
      if (noteSentences) {
        for (const c of r.changed) {
          if (!SENTENCE_KEYS.has(c.key)) continue;
          const h = c.hanzi ? `  [${c.hanzi.before} -> ${c.hanzi.after}]` : '';
          ws.note('sentence', `${path}: ${label}: ${c.after}${h} -- check its en/ru`);
        }
      }
    } else {
      ws.set(path, apply(src));
      if (noteSentences && /\.yaml$/.test(path)) ws.note('sentence', `${path}: ${label}: YAML text changed -- check hanzi there by hand`);
    }
  }
}

// Rewrites plain-pinyin mentions of `term` (outside refs, and not a
// composite's own Mandarin pinyin) to `to`, capitalized where they were.
function rewriteMentions(ws, id, term, to) {
  const esc = term.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const re = new RegExp(`(^|[^\\p{L}])(${esc})(?![\\p{L}])`, 'giu');
  const cap = (s) => s.charAt(0).toUpperCase() + s.slice(1);
  for (const path of ws.files()) {
    if (path === ws.wordPath(id)) continue;
    const src = ws.get(path);
    if (!src.toLowerCase().includes(term.toLowerCase())) continue;
    let n = 0;
    const out = src
      .split('\n')
      .map((line) => {
        if (path.startsWith(COMPOSITES_DIR) && /^\s*py:/.test(line)) return line;
        // leave refs alone: rewrite only the text between them
        return line
          .split(/(\{\{[^}]*\}\})/)
          .map((piece, k) => (k % 2 ? piece : piece.replace(re, (m, pre, word) => (n++, pre + (word[0] === word[0].toUpperCase() ? cap(to) : to)))))
          .join('');
      })
      .join('\n');
    if (n) {
      ws.set(path, out);
      ws.note('mention', `${path}: rewrote ${n} plain "${term}" as "${to}"`);
    }
  }
}

// Notes plain-text mentions of a word's term outside refs, and id strings in code.
function noteMentions(ws, id, term, why) {
  const forms = [...new Set([term, toneless(term)])].filter((f) => f.length > 2);
  for (const path of ws.files()) {
    if (path === ws.wordPath(id)) continue;
    const src = ws.get(path);
    const lines = src.split('\n');
    lines.forEach((line, i) => {
      if (path.startsWith(COMPOSITES_DIR) && /^\s*py:/.test(line)) return; // Mandarin's own pinyin
      const plain = line.replace(wordRefRe(), ' ');
      for (const f of forms) {
        const re = new RegExp(`(^|[^\\p{L}])${f.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}(?![\\p{L}])`, 'iu');
        if (re.test(plain)) {
          ws.note('mention', `${path}:${i + 1}: "${f}" in plain text (${why})`);
          break;
        }
      }
      if (isCode(path) && !path.startsWith('src/data/') && new RegExp(`["']${id}["']`).test(line) && !/word:\s*"/.test(line))
        ws.note('code', `${path}:${i + 1}: the id "${id}" as a string in code (${why})`);
    });
  }
}

// -- pinyin --------------------------------------------------------------------

const TONE_MARKS = { a: 'āáǎà', e: 'ēéěè', i: 'īíǐì', o: 'ōóǒò', u: 'ūúǔù', ü: 'ǖǘǚǜ' };

// -> the syllables of an id: "dong1xi" -> ["dong1", "xi"], "de" -> ["de"].
export const idSyllables = (id) => id.match(/[a-z]+[1-5]|[a-z]+$/g) ?? [id];

// -> "dong1" -> "dōng", "nv3" -> "nǚ", "shi2jian1" -> "shíjiān", "de" -> "de".
export function idToTerm(id) {
  return idSyllables(id)
    .map((syl) => {
      const tone = /[1-5]$/.test(syl) ? Number(syl.slice(-1)) : 5;
      const s = syl.replace(/[1-5]$/, '').replace(/v/g, 'ü');
      if (tone === 5) return s;
      let at = s.search(/[ae]/);
      if (at < 0) at = s.indexOf('ou');
      if (at < 0) for (let k = 0; k < s.length; k++) if ('iouü'.includes(s[k])) at = k;
      if (at < 0) return s;
      return s.slice(0, at) + TONE_MARKS[s[at]][tone - 1] + s.slice(at + 1);
    })
    .join('');
}

// -- the ops ----------------------------------------------------------------------

const TODO = { eng: 'TODO', rus: 'TODO', zh: 'TODO' };

// -> a new word's data from an op's partial data (TODO where not given).
function newWordData(id, partial = {}) {
  return {
    term: partial.term ?? idToTerm(id),
    hanzi: partial.hanzi,
    pos: partial.pos ?? TODO,
    definition: partial.definition ?? TODO,
    necessity: partial.necessity ?? { index: 1, eng: 'TODO', rus: 'TODO' },
    ...(partial.senses ? { senses: partial.senses } : {}),
  };
}

// -> the hanzi a word has inside a given compound (its sense's, if listed).
function hanziIn(ws, id, compound) {
  const w = ws.word(id);
  for (const s of Object.values(w.senses ?? {})) if (s.compounds.includes(compound)) return s.hanzi;
  return w.hanzi;
}

const OPS = {
  // { op: "add", id, hanzi, term?, pos?, definition?, necessity?, senses?, category }
  add(ws, op) {
    if (ws.hasWord(op.id)) throw new Error(`${op.id} already exists`);
    if (!op.hanzi) throw new Error(`add ${op.id}: give its hanzi`);
    ws.setWord(op.id, newWordData(op.id, op));
    if (op.category) placeInCategory(ws, op.id, op.category);
    else ws.note('todo', `${op.id}: put it in a category (maps/categories.ts) -- check-data fails until then`);
    if (!op.definition || !op.pos || !op.necessity) ws.note('todo', `${op.id}: fill in its definition, part of speech and necessity (TODO in ${ws.wordPath(op.id)})`);
  },

  // { op: "edit", id, set: { term?, hanzi?, pos?, definition?, necessity?, senses? } }
  edit(ws, op) {
    const w = ws.word(op.id);
    ws.setWord(op.id, { ...w, ...op.set });
  },

  // { op: "sense", id, key, hanzi, eng, rus, why: { eng, rus }, compounds: ["shi2 jian1", ...] }
  sense(ws, op) {
    const w = ws.word(op.id);
    const { op: _op, id: _id, key, ...sense } = op;
    ws.setWord(op.id, { ...w, senses: { ...(w.senses ?? {}), [key]: sense } });
  },

  // { op: "senseCompounds", id, key, add: ["shi4 shi2", ...] } -- more compounds for a sense
  senseCompounds(ws, op) {
    const w = ws.word(op.id);
    const s = w.senses?.[op.key];
    if (!s) throw new Error(`${op.id} has no sense "${op.key}"`);
    s.compounds = [...new Set([...s.compounds, ...op.add])];
    ws.setWord(op.id, w);
  },

  // { op: "category", id, to: "<leaf key>" }
  category(ws, op) {
    editCategories(ws, (ids) => ids.filter((x) => x !== op.id));
    placeInCategory(ws, op.id, op.to);
  },

  // { op: "split", id, into: [ids], light?: [ids], senses?: { id: senseKey }, words?: { id: partial data }, cards?: { id: { en, ru } } }
  // Every ref to id becomes the parts joined by hyphens; the parts' hanzi
  // (a listed sense's, inside the new compound) must equal id's hanzi.
  split(ws, op) {
    const { id, into } = op;
    const old = ws.word(id);
    const light = new Set(op.light ?? []);
    const compound = into.join(' ');
    for (const p of into) {
      if (ws.hasWord(p)) continue;
      const partial = op.words?.[p] ?? {};
      if (!partial.hanzi) {
        // the old hanzi, one character per syllable, cut at the parts' syllables
        const chars = [...old.hanzi];
        const counts = into.map((x) => idSyllables(x).length);
        if (counts.reduce((a, b) => a + b, 0) !== chars.length) throw new Error(`split ${id}: give the hanzi of new part ${p} (words.${p}.hanzi)`);
        const at = counts.slice(0, into.indexOf(p)).reduce((a, b) => a + b, 0);
        partial.hanzi = chars.slice(at, at + counts[into.indexOf(p)]).join('');
      }
      ws.setWord(p, newWordData(p, partial));
      if (!partial.definition || !partial.necessity || !partial.pos) ws.note('todo', `${p}: new word from splitting ${id} -- fill in its definition, part of speech and necessity`);
    }
    const joined = into.map((p) => hanziIn(ws, p, compound)).join('');
    if (joined !== old.hanzi) throw new Error(`split ${id}: the parts write ${joined}, but ${id} is ${old.hanzi} -- list the compound "${compound}" under the right sense first, or use replace`);
    // refs
    rewriteAll(ws, id, (kind) => into.map((p, i) => ref(i === 0 ? kind : kind === 'light' || kind === 'Light' ? 'light' : 'word', p, light.has(p))).join('-'));
    // cards: the parts take the old card's place; a part taught later moves here
    const all = cards(ws);
    const mine = all.filter((c) => c.word === id);
    if (mine.length) {
      const at = mine[0];
      const list = [];
      const moved = [];
      for (const p of into) {
        const sense = op.senses?.[p];
        const existing = all.find((c) => c.word === p && c.sense === sense);
        if (existing && existing.order < at.order) continue;
        if (existing) {
          const src = ws.get(existing.file);
          list.push(cardData(src, existing.obj));
          moved.push(existing);
          ws.note('card', `${cardKey(p, sense)}: card moved from ${existing.lesson}/${existing.module} to ${at.lesson}/${at.module} (taught earlier now)`);
        } else {
          const c = op.cards?.[p] ? { word: p, ...(sense ? { sense } : {}), ...op.cards[p] } : newCard(ws, p, sense);
          list.push(c);
          if (!op.cards?.[p]) ws.note('card', `${cardKey(p, sense)}: new card in ${at.lesson}/${at.module}, gloss "${c.en}" / "${c.ru}" taken from the definition -- check it`);
        }
      }
      // remove moved cards first (later in the book, so the slot's position holds
      // unless they share its file -- re-find the slot after each removal)
      for (const m of moved.sort((a, b) => b.order - a.order)) {
        const fresh = cards(ws).find((c) => c.file === m.file && c.word === m.word && c.sense === m.sense);
        removeCard(ws, fresh);
      }
      const slot = cards(ws).find((c) => c.word === id);
      spliceCards(ws, slot, list);
      for (const extra of cards(ws).filter((c) => c.word === id)) removeCard(ws, extra);
    }
    // maps and coverage
    const leaf = categoryOf(ws, id);
    const placed = new Set();
    walkCategories(ws.data(`${MAPS}categories.ts`), (c) => (c.wordIds ?? []).forEach((w) => placed.add(w)));
    editCategories(ws, (ids) => ids.flatMap((x) => (x === id ? into.filter((p) => !placed.has(p)) : [x])));
    if (!leaf) ws.note('todo', `${id} had no category; place its new parts`);
    editRelations(ws, (p) => (p.includes(id) ? null : p), (w, forms) => (w === id ? null : [w, forms]), `${id} was split`);
    editCoverageWords(ws, (words) => (words.includes(id) ? words.flatMap((w) => (w === id ? into : [w])) : words));
    // the composite that was the word itself
    for (const { path, entry } of ws.composites()) {
      if (entry.zh === old.hanzi && entry.fit === 'word') ws.note('composite', `${path}: ${entry.zh} was the word ${id}; now ${into.join('-')} -- its fit "word" may now be "natural"`);
    }
    // plain pinyin of the old word becomes the parts' pinyin (dòngwù -> dòng-wù)
    const newTerm = into.map((p) => (light.has(p) ? toneless(ws.word(p).term) : ws.word(p).term)).join('-');
    rewriteMentions(ws, id, old.term, newTerm);
    noteMentions(ws, id, old.term, `${id} was split`);
    ws.remove(ws.wordPath(id));
  },

  // { op: "replace", id, with: "<form of refs>", hanzi?: { "部分": "分" }, keep?: true, words?: [ids] }
  // Every ref to id becomes the form; each changed sentence is noted for review.
  // keep: the id stays (it is reused with a new meaning by a later edit op).
  replace(ws, op) {
    const { id, with: form } = op;
    const old = ws.word(id);
    for (const m of form.matchAll(wordRefRe())) if (!ws.hasWord(m[2])) throw new Error(`replace ${id}: the form names ${m[2]}, which isn't a word (add it first)`);
    const map = Object.entries(op.hanzi ?? {});
    const hanziFn = map.length ? (h) => map.reduce((s, [a, b]) => s.split(a).join(b), h) : undefined;
    rewriteAll(ws, id, (kind) => (kind === 'Word' || kind === 'Light' ? capitalizeForm(form) : form), { hanziFn, noteSentences: true, label: `${id} -> ${form}` });
    const formIds = [...form.matchAll(wordRefRe())].map((m) => m[2]);
    const single = formIds.length === 1 && form === `{{word:${formIds[0]}}}` ? formIds[0] : null;
    editCoverageWords(ws, (words) => (words.includes(id) ? words.flatMap((w) => (w === id ? (op.words ?? formIds) : [w])) : words));
    if (!op.keep) {
      editRelations(
        ws,
        (p) => (p.includes(id) ? (single && !p.includes(single) ? p.map((x) => (x === id ? single : x)) : null) : p),
        (w, forms) => (w === id ? (single ? [single, forms] : null) : [w, forms]),
        `${id} was replaced`,
      );
      for (const c of cards(ws).filter((c) => c.word === id)) ws.note('card', `${c.lesson}/${c.module}: removed the card for ${id}; teach ${form} there if it's new`);
      let c;
      while ((c = cards(ws).find((x) => x.word === id))) removeCard(ws, c);
      editCategories(ws, (ids) => ids.filter((x) => x !== id));
      if (single) rewriteMentions(ws, id, old.term, ws.word(single).term);
      noteMentions(ws, id, old.term, `${id} was replaced`);
      ws.remove(ws.wordPath(id));
    } else {
      ws.note('todo', `${id} is kept for reuse: change its file and card with edit/move ops`);
    }
  },

  // { op: "refs", pattern, to, hanzi?: [pattern, to], label? } -- a regex over the
  // text (refs included, e.g. "\\{\\{(w|W)ord:zuo4\\}\\} \\{\\{word:zai4\\}\\}"); each
  // changed sentence's hanzi gets the hanzi regex, and is noted for review.
  refs(ws, op) {
    const re = new RegExp(op.pattern, 'g');
    const hz = op.hanzi ? [new RegExp(op.hanzi[0], 'g'), op.hanzi[1]] : null;
    rewriteText(ws, (t) => t.replace(re, op.to), {
      hanziFn: hz ? (h) => h.replace(hz[0], hz[1]) : undefined,
      noteSentences: true,
      label: op.label ?? op.pattern,
      has: (t) => new RegExp(op.pattern).test(t),
    });
  },

  // { op: "rename", id, to } -- a new id (and its refs, cards, maps, coverage, senses)
  rename(ws, op) {
    const { id, to } = op;
    if (ws.hasWord(to)) throw new Error(`rename ${id}: ${to} already exists`);
    const w = ws.word(id);
    rewriteAll(ws, id, (kind) => `{{${kind}:${to}}}`);
    for (const path of ws.files(LESSONS_DIR)) {
      const src = ws.get(path);
      const r = rewriteStrings(src, (v, s) => (s.key === 'word' && v === id && s.obj?.key === 'words' ? to : v));
      if (r.text !== src) ws.set(path, r.text);
    }
    editCategories(ws, (ids) => ids.map((x) => (x === id ? to : x)));
    editRelations(ws, (p) => p.map((x) => (x === id ? to : x)), (k, f) => [k === id ? to : k, f], 'rename');
    editCoverageWords(ws, (words) => (words.includes(id) ? words.map((x) => (x === id ? to : x)) : words));
    for (const other of ws.wordIds()) {
      const o = ws.word(other);
      if (!o.senses) continue;
      let touched = false;
      for (const s of Object.values(o.senses)) {
        const nc = s.compounds.map((c) => c.split(' ').map((p) => (p === id ? to : p)).join(' '));
        if (nc.join() !== s.compounds.join()) (s.compounds = nc), (touched = true);
      }
      if (touched) ws.setWord(other, o);
    }
    ws.remove(ws.wordPath(id));
    ws.setWord(to, w);
    if (w.senses) {
      for (const s of Object.values(w.senses)) s.compounds = s.compounds.map((c) => c.split(' ').map((p) => (p === id ? to : p)).join(' '));
      ws.setWord(to, w);
    }
    noteMentions(ws, id, '', 'renamed');
  },

  // { op: "remove", id } -- refuses while the word is used
  remove(ws, op) {
    const { id } = op;
    const uses = ws.files().filter((p) => p !== ws.wordPath(id) && ws.get(p).includes(`:${id}}}`));
    if (uses.length) throw new Error(`remove ${id}: still used in ${uses.length} file(s): ${uses.slice(0, 5).join(', ')}${uses.length > 5 ? ', ...' : ''}`);
    const w = ws.word(id);
    let c;
    while ((c = cards(ws).find((x) => x.word === id))) removeCard(ws, c);
    editCategories(ws, (ids) => ids.filter((x) => x !== id));
    editRelations(ws, (p) => (p.includes(id) ? null : p), (k, f) => (k === id ? null : [k, f]), `${id} was removed`);
    editCoverageWords(ws, (words) => (words.includes(id) ? words.filter((x) => x !== id) : words));
    noteMentions(ws, id, w.term, `${id} was removed`);
    ws.remove(ws.wordPath(id));
  },

  // { op: "card", id, sense?, to: "lesson/module", en, ru, hanzi? } -- add a card
  card(ws, op) {
    const file = moduleFile(ws, op.to);
    const c = { word: op.id, ...(op.sense ? { sense: op.sense } : {}), ...(op.hanzi ? { hanzi: op.hanzi } : {}), en: op.en, ru: op.ru };
    appendCard(ws, file, op.en ? c : newCard(ws, op.id, op.sense));
  },

  // { op: "uncard", id, sense? } -- remove the word's (sense's) card
  uncard(ws, op) {
    const c = cards(ws).find((x) => x.word === op.id && x.sense === op.sense);
    if (!c) throw new Error(`uncard: no card for ${cardKey(op.id, op.sense)}`);
    removeCard(ws, c);
  },

  // { op: "move", id, sense?, to: "lesson/module" } -- move the card
  move(ws, op) {
    const c = cards(ws).find((x) => x.word === op.id && x.sense === op.sense);
    if (!c) throw new Error(`move: no card for ${cardKey(op.id, op.sense)}`);
    const data = cardData(ws.get(c.file), c.obj);
    removeCard(ws, c);
    appendCard(ws, moduleFile(ws, op.to), data);
  },

  // { op: "relation", kind: "antonyms" | "synonyms", add?: [a, b], remove?: [a, b] }
  relation(ws, op) {
    const path = `${MAPS}${op.kind}.ts`;
    const r = ws.data(path);
    if (op.remove) r.pairs = r.pairs.filter((p) => !(p.includes(op.remove[0]) && p.includes(op.remove[1])));
    if (op.add) r.pairs.push(op.add);
    ws.setData(path, r);
  },

  // { op: "composite", zh, set?: { fit, role, transparent, ... }, addForm?: [form, hanzi], create?: { rank, phase, py, en, ru } }
  composite(ws, op) {
    let found = ws.composites().find(({ entry }) => entry.zh === op.zh);
    if (!found) {
      if (!op.create) throw new Error(`composite: no entry ${op.zh} (give create: { rank, phase, py, en, ru } to add one)`);
      found = { path: null, entry: { ...op.create, zh: op.zh, proposed: true } };
    }
    const e = { ...found.entry, ...(op.set ?? {}) };
    if (op.addForm) {
      const [form, hanzi] = op.addForm;
      if (!(e.hsd ?? []).includes(form)) {
        e.hsd = [...(e.hsd ?? []), form];
        e.tts = [...(e.tts ?? []), hanzi];
      }
    }
    if (found.path) ws.setComposite(found.path, e);
    else ws.set(`${COMPOSITES_DIR}${compositeFileName(e)}`, `import { composite } from "../../lib/composite.ts";\n\nexport default composite(${tsLiteral(e)});\n`);
  },

  // { op: "compounds" } -- the compound rule over every composite: a Chinese
  // word now made of Hao-shuo-de words gets that compound as its first form
  // (marked proposed), and its old forms follow after " / " as constructive ones.
  compounds(ws) {
    const words = Object.fromEntries(ws.wordIds().map((id) => [id, ws.word(id)]));
    const split = compoundSplitter(words);
    for (const { path, entry } of ws.composites()) {
      if (entry.fit === 'name' || entry.fit === 'skip') continue;
      const ids = split(entry.zh, entry.py);
      if (!ids) continue;
      const forms = entry.hsd ?? [];
      if ((entry.tts ?? []).includes(entry.zh) || forms.some((f) => wordRefIds(f).join(' ') === ids.join(' '))) continue;
      const form = compoundForm(ids);
      const e = { ...entry, hsd: [form, ...forms], tts: [entry.zh, ...(entry.tts ?? [])], fit: ids.length === 1 ? 'word' : 'natural', proposed: true };
      ws.setComposite(path, e);
      ws.note('composite', `${entry.zh} ${entry.en}: ${ids.map((id) => words[id].term).join('-')} first${forms.length ? ` (then ${forms.length} older form(s))` : ''}`);
    }
  },

  // { op: "text", file, from, to, all? } -- a hand edit kept in the list
  text(ws, op) {
    const src = ws.get(op.file);
    if (!src.includes(op.from)) throw new Error(`text: "${op.from.slice(0, 60)}" not found in ${op.file}`);
    ws.set(op.file, op.all ? src.split(op.from).join(op.to) : src.replace(op.from, op.to));
  },
};

function placeInCategory(ws, id, leafKey) {
  let found = false;
  editCategories(ws, (ids, c) => {
    if (c.key !== leafKey) return ids;
    found = true;
    return ids.includes(id) ? ids : [...ids, id];
  });
  if (!found) throw new Error(`no category leaf "${leafKey}"`);
}

export const OP_NAMES = Object.keys(OPS);

// Applies ops in order; an op that throws stops the run with its index.
export function applyOps(ws, ops) {
  ops.forEach((op, i) => {
    const fn = OPS[op.op];
    if (!fn) throw new Error(`op ${i + 1}: unknown op "${op.op}" (one of ${OP_NAMES.join(', ')})`);
    try {
      fn(ws, op);
    } catch (e) {
      e.message = `op ${i + 1} (${op.op} ${op.id ?? op.file ?? ''}): ${e.message}`;
      throw e;
    }
  });
}

// -- reporting ---------------------------------------------------------------------

// -> per-file line counts of a change.
function lineDelta(before, after) {
  const a = (before ?? '').split('\n');
  const b = (after ?? '').split('\n');
  const setA = new Map();
  for (const l of a) setA.set(l, (setA.get(l) ?? 0) + 1);
  let common = 0;
  for (const l of b) if (setA.get(l)) setA.set(l, setA.get(l) - 1), common++;
  if (before == null) return { removed: 0, added: b.length };
  if (after == null) return { removed: a.length, added: 0 };
  return { removed: a.length - common, added: b.length - common };
}

export function summary(ws, { diff = false } = {}) {
  const out = [];
  const ch = ws.changes();
  for (const { path, before, after } of ch) {
    const tag = before == null ? 'new    ' : after == null ? 'deleted' : 'changed';
    const { added, removed } = lineDelta(before, after);
    out.push(`  ${tag}  ${path}  (+${added} -${removed})`);
    if (diff && before != null && after != null) {
      const a = before.split('\n');
      const b = after.split('\n');
      const bs = new Set(b);
      const as = new Set(a);
      for (const l of a) if (!bs.has(l)) out.push(`      - ${l.trim()}`);
      for (const l of b) if (!as.has(l)) out.push(`      + ${l.trim()}`);
    }
  }
  out.push(`\n${ch.length} file(s).`);
  const byKind = new Map();
  for (const n of ws.notes) byKind.set(n.kind, [...(byKind.get(n.kind) ?? []), n.text]);
  const TITLES = {
    todo: 'To do',
    card: 'Cards',
    sentence: 'Changed sentences (check their en/ru)',
    relation: 'Relations',
    composite: 'Composites',
    mention: 'Plain-text mentions (edit by hand)',
    code: 'Ids in code (check by hand)',
  };
  for (const [kind, list] of byKind) {
    out.push(`\n${TITLES[kind] ?? kind}:`);
    for (const t of [...new Set(list)]) out.push(`  - ${t}`);
  }
  return out.join('\n');
}
