// Russian text for lesson-15, matching shape.ts's keys. Typed as
// `PartialByKey<LessonShape>`.
// Not translated yet -- every `ru` is the empty-array placeholder.
import type { PartialByKey } from "../../lib/chapter-shape-types.ts";
import type { LessonShape } from "./shape.ts";

const ru: PartialByKey<LessonShape> = {
  title: { ru: [] },
  summary: { ru: [] },
  vocabBian: { ru: [] },
  vocabBa: { ru: [] },
  vocabNong: { ru: [] },
  vocabDe: { ru: [] },
  vocabLiliang: { ru: [] },
  vocabHuai: { ru: [] },
  vocabNi: { ru: [] },
  proseChanged: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleChanged1: { ru: [] },
  exampleChanged2: { ru: [] },
  exampleChanged3: { ru: [] },
  exampleChanged4: { ru: [] },
  proseBecame: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleBecame1: { ru: [] },
  exampleBecame2: { ru: [] },
  exampleBecame3: { ru: [] },
  exampleBecame4: { ru: [] },
  exampleBecame5: { ru: [] },
  proseMake: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleMake1: { ru: [] },
  exampleMake2: { ru: [] },
  exampleMake3: { ru: [] },
  exampleMake4: { ru: [] },
  exampleMake5: { ru: [] },
  proseBa: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleBa1: { ru: [] },
  exampleBa2: { ru: [] },
  exampleBa3: { ru: [] },
  proseStrong: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleStrong1: { ru: [] },
  exampleStrong2: { ru: [] },
  exampleStrong3: { ru: [] },
  infoBecomingAndMaking: {
    title: { ru: [] },
    items: [
      { ru: [] },
      { ru: [] },
      { ru: [] },
      { ru: [] },
      { ru: [] },
    ],
  },
  exercise1: { ru: [] },
  exercise2: { ru: [] },
  exercise3: { ru: [] },
  exercise4: { ru: [] },
  exercise5: { ru: [] },
  exercise6: { ru: [] },
  exercise7: { ru: [] },
  answer1: { ru: [] },
  answer2: { ru: [] },
  answer3: { ru: [] },
  answer4: { ru: [] },
  answer5: { ru: [] },
  answer6: { ru: [] },
  answer7: { ru: [] },
};

export default ru;
