// Chinese text for lesson-15, matching shape.ts's keys. Typed as
// `PartialByKey<LessonShape>`.
// Not translated yet -- every `zh` is the empty-array placeholder.
import type { PartialByKey } from "../../lib/chapter-shape-types.ts";
import type { LessonShape } from "./shape.ts";

const zh: PartialByKey<LessonShape> = {
  title: { zh: [] },
  summary: { zh: [] },
  vocabBian: { zh: [] },
  vocabBa: { zh: [] },
  vocabNong: { zh: [] },
  vocabDe: { zh: [] },
  vocabLiliang: { zh: [] },
  vocabHuai: { zh: [] },
  vocabNi: { zh: [] },
  proseChanged: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleChanged1: { zh: [] },
  exampleChanged2: { zh: [] },
  exampleChanged3: { zh: [] },
  exampleChanged4: { zh: [] },
  proseBecame: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleBecame1: { zh: [] },
  exampleBecame2: { zh: [] },
  exampleBecame3: { zh: [] },
  exampleBecame4: { zh: [] },
  exampleBecame5: { zh: [] },
  proseMake: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleMake1: { zh: [] },
  exampleMake2: { zh: [] },
  exampleMake3: { zh: [] },
  exampleMake4: { zh: [] },
  exampleMake5: { zh: [] },
  proseBa: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleBa1: { zh: [] },
  exampleBa2: { zh: [] },
  exampleBa3: { zh: [] },
  exampleBa4: { zh: [] },
  exampleBa5: { zh: [] },
  proseStrong: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleStrong1: { zh: [] },
  exampleStrong2: { zh: [] },
  exampleStrong3: { zh: [] },
  exampleStrong4: { zh: [] },
  infoBecomingAndMaking: {
    title: { zh: [] },
    items: [
      { zh: [] },
      { zh: [] },
      { zh: [] },
      { zh: [] },
      { zh: [] },
    ],
  },
  exercise1: { zh: [] },
  exercise2: { zh: [] },
  exercise3: { zh: [] },
  exercise4: { zh: [] },
  exercise5: { zh: [] },
  exercise6: { zh: [] },
  exercise7: { zh: [] },
  answer1: { zh: [] },
  answer2: { zh: [] },
  answer3: { zh: [] },
  answer4: { zh: [] },
  answer5: { zh: [] },
  answer6: { zh: [] },
  answer7: { zh: [] },
};

export default zh;
