// Russian text for lesson-08, matching shape.ts's keys. Typed as
// `PartialByKey<LessonShape>`.
// Not translated yet -- every `ru` is the empty-array placeholder.
import type { PartialByKey } from "../../lib/chapter-shape-types.ts";
import type { LessonShape } from "./shape.ts";

const ru: PartialByKey<LessonShape> = {
  title: { ru: [] },
  summary: { ru: [] },
  vocabLe: { ru: [] },
  vocabShuijiao: { ru: [] },
  vocabFasheng: { ru: [] },
  proseDone: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleDone1: { ru: [] },
  exampleDone2: { ru: [] },
  exampleDone3: { ru: [] },
  exampleDone4: { ru: [] },
  exampleDone5: { ru: [] },
  vocabZai: { ru: [] },
  vocabXianzai: { ru: [] },
  proseNow: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleNow1: { ru: [] },
  exampleNow2: { ru: [] },
  exampleNow3: { ru: [] },
  exampleNow4: { ru: [] },
  exampleNow5: { ru: [] },
  exampleNow6: { ru: [] },
  exampleNow7: { ru: [] },
  vocabHui: { ru: [] },
  proseWill: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleWill1: { ru: [] },
  exampleWill2: { ru: [] },
  exampleWill3: { ru: [] },
  vocabYue: { ru: [] },
  vocabGuo: { ru: [] },
  proseBefore: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleBefore1: { ru: [] },
  exampleBefore2: { ru: [] },
  exampleBefore3: { ru: [] },
  exampleBefore4: { ru: [] },
  vocabShijian: { ru: [] },
  vocabRi: { ru: [] },
  proseTime: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleTime1: { ru: [] },
  exampleTime2: { ru: [] },
  exampleTime3: { ru: [] },
  exampleTime4: { ru: [] },
  exampleTime5: { ru: [] },
  exampleTime6: { ru: [] },
  exampleTime7: { ru: [] },
  infoWhenItHappens: {
    title: { ru: [] },
    items: [
      { ru: [] },
      { ru: [] },
      { ru: [] },
      { ru: [] },
      { ru: [] },
      { ru: [] },
    ],
  },
  exercise1: { ru: [] },
  exercise2: { ru: [] },
  exercise3: { ru: [] },
  exercise4: { ru: [] },
  exercise5: { ru: [] },
  exercise6: { ru: [] },
  exercise7: { ru: [] },
  exercise8: { ru: [] },
  exercise9: { ru: [] },
  exercise10: { ru: [] },
  answer1: { ru: [] },
  answer2: { ru: [] },
  answer3: { ru: [] },
  answer4: { ru: [] },
  answer5: { ru: [] },
  answer6: { ru: [] },
  answer7: { ru: [] },
  answer8: { ru: [] },
  answer9: { ru: [] },
  answer10: { ru: [] },
  faqLePast: { question: { ru: [] }, ru: [] },
  faqLeOrGuo: { question: { ru: [] }, ru: [] },
  faqHuiKnowHow: { question: { ru: [] }, ru: [] },
};

export default ru;
