// Chinese text for lesson-08, matching shape.ts's keys. Typed as
// `PartialByKey<LessonShape>`.
// Not translated yet -- every `zh` is the empty-array placeholder.
import type { PartialByKey } from "../../lib/chapter-shape-types.ts";
import type { LessonShape } from "./shape.ts";

const zh: PartialByKey<LessonShape> = {
  title: { zh: [] },
  summary: { zh: [] },
  vocabShijian: { zh: [] },
  vocabLe: { zh: [] },
  vocabHui: { zh: [] },
  vocabZai: { zh: [] },
  vocabRi: { zh: [] },
  vocabYue: { zh: [] },
  vocabShuijiao: { zh: [] },
  vocabGuo: { zh: [] },
  proseDone: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleDone1: { zh: [] },
  exampleDone2: { zh: [] },
  exampleDone3: { zh: [] },
  proseNow: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleNow1: { zh: [] },
  exampleNow2: { zh: [] },
  exampleNow3: { zh: [] },
  exampleNow4: { zh: [] },
  proseWill: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleWill1: { zh: [] },
  exampleWill2: { zh: [] },
  exampleWill3: { zh: [] },
  proseBefore: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleBefore1: { zh: [] },
  exampleBefore2: { zh: [] },
  exampleBefore3: { zh: [] },
  proseTime: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleTime1: { zh: [] },
  exampleTime2: { zh: [] },
  exampleTime3: { zh: [] },
  exampleTime4: { zh: [] },
  exampleTime5: { zh: [] },
  infoWhenItHappens: {
    title: { zh: [] },
    items: [
      { zh: [] },
      { zh: [] },
      { zh: [] },
      { zh: [] },
      { zh: [] },
    ],
  },
  exercise1: { zh: [] },
  exercise2: { zh: [] },
  exercise3: { zh: [] },
  exercise4: { zh: [] },
  exercise5: { zh: [] },
  exercise6: { zh: [] },
  exercise7: { zh: [] },
  exercise8: { zh: [] },
  answer1: { zh: [] },
  answer2: { zh: [] },
  answer3: { zh: [] },
  answer4: { zh: [] },
  answer5: { zh: [] },
  answer6: { zh: [] },
  answer7: { zh: [] },
  answer8: { zh: [] },
};

export default zh;
