// Russian text for greetings-and-feelings, matching shape.ts's keys. Typed as
// `PartialByKey<LessonShape>`.
// Not translated yet -- every `ru` is the empty-array placeholder.
import type { PartialByKey } from "../../../lib/chapter-shape-types.ts";
import type { LessonShape } from "./shape.ts";

const ru: PartialByKey<LessonShape> = {
  title: { ru: [] },
  summary: { ru: [] },
  proseHello: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleHello1: { ru: [] },
  exampleHello2: { ru: [] },
  exampleHello3: { ru: [] },
  exampleHello4: { ru: [] },
  exampleHello5: { ru: [] },
  exampleHello6: { ru: [] },
  exampleHello7: { ru: [] },
  vocabXie: { ru: [] },
  proseThanks: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleThanks1: { ru: [] },
  exampleThanks2: { ru: [] },
  exampleThanks3: { ru: [] },
  exampleThanks4: { ru: [] },
  vocabJiao: { ru: [] },
  proseName: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleName1: { ru: [] },
  exampleName2: { ru: [] },
  exampleName3: { ru: [] },
  exampleName4: { ru: [] },
  vocabPa: { ru: [] },
  vocabXiao: { ru: [] },
  proseOrder: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleOrder1: { ru: [] },
  exampleOrder2: { ru: [] },
  exampleOrder3: { ru: [] },
  exampleOrder4: { ru: [] },
  exampleOrder5: { ru: [] },
  exampleOrder6: { ru: [] },
  exampleOrder7: { ru: [] },
  exampleOrder8: { ru: [] },
  exampleOrder9: { ru: [] },
  exampleOrder10: { ru: [] },
  exampleOrder11: { ru: [] },
  exampleOrder12: { ru: [] },
  vocabJuede: { ru: [] },
  vocabChongzi: { ru: [] },
  vocabXing: { ru: [] },
  vocabXin: { ru: [] },
  proseFeel: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleFeel1: { ru: [] },
  exampleFeel2: { ru: [] },
  exampleFeel3: { ru: [] },
  exampleFeel4: { ru: [] },
  exampleFeel5: { ru: [] },
  exampleFeel6: { ru: [] },
  exampleFeel7: { ru: [] },
  exampleFeel8: { ru: [] },
  exampleFeel9: { ru: [] },
  exampleFeel10: { ru: [] },
  exampleFeel11: { ru: [] },
  exampleFeel12: { ru: [] },
  exampleFeel13: { ru: [] },
  exampleFeel14: { ru: [] },
  exampleFeel15: { ru: [] },
  exampleFeel16: { ru: [] },
  exampleFeel17: { ru: [] },
  exampleFeel18: { ru: [] },
  exampleFeel19: { ru: [] },
  exampleFeel20: { ru: [] },
  exampleFeel21: { ru: [] },
  exampleFeel22: { ru: [] },
  exampleFeel23: { ru: [] },
  vocabShengyin: { ru: [] },
  proseHear: { ru: [], tldr: { ru: [] }, necessity: { ru: [] } },
  exampleHear1: { ru: [] },
  exampleHear2: { ru: [] },
  exampleHear3: { ru: [] },
  exampleHear4: { ru: [] },
  exampleHear5: { ru: [] },
  exampleHear6: { ru: [] },
  exampleHear7: { ru: [] },
  infoGreetingsAndFeelings: {
    title: { ru: [] },
    items: [
      { ru: [] },
      { ru: [] },
      { ru: [] },
      { ru: [] },
      { ru: [] },
      { ru: [] },
      { ru: [] },
    ],
  },
  exercise1: { ru: [] },
  exercise2: { ru: [] },
  exercise3: { ru: [] },
  exercise4: { ru: [] },
  exercise5: { ru: [] },
  exercise6: { ru: [] },
  exercise7: { ru: [] },
  exercise8: { ru: [] },
  exercise9: { ru: [] },
  exercise10: { ru: [] },
  exercise11: { ru: [] },
  exercise12: { ru: [] },
  exercise13: { ru: [] },
  answer1: { ru: [] },
  answer2: { ru: [] },
  answer3: { ru: [] },
  answer4: { ru: [] },
  answer5: { ru: [] },
  answer6: { ru: [] },
  answer7: { ru: [] },
  answer8: { ru: [] },
  answer9: { ru: [] },
  answer10: { ru: [] },
  answer11: { ru: [] },
  answer12: { ru: [] },
  answer13: { ru: [] },
  faqNihaoma: { question: { ru: [] }, ru: [] },
  faqJuedeThink: { question: { ru: [] }, ru: [] },
};

export default ru;
