// Chinese text for greetings-and-feelings, matching shape.ts's keys. Typed as
// `PartialByKey<LessonShape>`.
// Not translated yet -- every `zh` is the empty-array placeholder.
import type { PartialByKey } from "../../../lib/chapter-shape-types.ts";
import type { LessonShape } from "./shape.ts";

const zh: PartialByKey<LessonShape> = {
  title: { zh: [] },
  summary: { zh: [] },
  proseHello: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleHello1: { zh: [] },
  exampleHello2: { zh: [] },
  exampleHello3: { zh: [] },
  exampleHello4: { zh: [] },
  exampleHello5: { zh: [] },
  exampleHello6: { zh: [] },
  exampleHello7: { zh: [] },
  vocabXie: { zh: [] },
  proseThanks: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleThanks1: { zh: [] },
  exampleThanks2: { zh: [] },
  exampleThanks3: { zh: [] },
  exampleThanks4: { zh: [] },
  vocabJiao: { zh: [] },
  proseName: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleName1: { zh: [] },
  exampleName2: { zh: [] },
  exampleName3: { zh: [] },
  exampleName4: { zh: [] },
  vocabPa: { zh: [] },
  vocabXiao: { zh: [] },
  proseOrder: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleOrder1: { zh: [] },
  exampleOrder3: { zh: [] },
  exampleOrder5: { zh: [] },
  exampleOrder6: { zh: [] },
  exampleOrder7: { zh: [] },
  exampleOrder8: { zh: [] },
  exampleOrder9: { zh: [] },
  exampleOrder11: { zh: [] },
  vocabJuede: { zh: [] },
  vocabChongzi: { zh: [] },
  proseFeel: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleFeel2: { zh: [] },
  exampleFeel4: { zh: [] },
  exampleFeel5: { zh: [] },
  exampleFeel8: { zh: [] },
  exampleFeel9: { zh: [] },
  exampleFeel10: { zh: [] },
  exampleFeel12: { zh: [] },
  exampleFeel22: { zh: [] },
  proseLaugh: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleFeel13: { zh: [] },
  exampleFeel14: { zh: [] },
  vocabXin: { zh: [] },
  proseHeart: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleFeel17: { zh: [] },
  exampleFeel18: { zh: [] },
  exampleFeel19: { zh: [] },
  exampleFeel20: { zh: [] },
  exampleFeel21: { zh: [] },
  exampleFeel23: { zh: [] },
  vocabShengyin: { zh: [] },
  proseHear: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleHear1: { zh: [] },
  exampleHear2: { zh: [] },
  exampleHear3: { zh: [] },
  exampleHear4: { zh: [] },
  exampleHear5: { zh: [] },
  exampleHear6: { zh: [] },
  exampleHear7: { zh: [] },
  infoGreetingsAndFeelings: {
    title: { zh: [] },
    items: [
      { zh: [] },
      { zh: [] },
      { zh: [] },
      { zh: [] },
      { zh: [] },
      { zh: [] },
      { zh: [] },
    ],
  },
  exercise1: { zh: [] },
  exercise2: { zh: [] },
  exercise3: { zh: [] },
  exercise4: { zh: [] },
  exercise5: { zh: [] },
  exercise6: { zh: [] },
  exercise7: { zh: [] },
  exercise8: { zh: [] },
  exercise9: { zh: [] },
  exercise10: { zh: [] },
  exercise11: { zh: [] },
  exercise12: { zh: [] },
  exercise13: { zh: [] },
  answer1: { zh: [] },
  answer2: { zh: [] },
  answer3: { zh: [] },
  answer4: { zh: [] },
  answer5: { zh: [] },
  answer6: { zh: [] },
  answer7: { zh: [] },
  answer8: { zh: [] },
  answer9: { zh: [] },
  answer10: { zh: [] },
  answer11: { zh: [] },
  answer12: { zh: [] },
  answer13: { zh: [] },
  faqNihaoma: { question: { zh: [] }, zh: [] },
  faqJuedeThink: { question: { zh: [] }, zh: [] },
};

export default zh;
