// Chinese text for around-an-action, matching shape.ts's keys. Typed as
// `PartialByKey<LessonShape>`.
// Not translated yet -- every `zh` is the empty-array placeholder.
import type { PartialByKey } from "../../../lib/chapter-shape-types.ts";
import type { LessonShape } from "./shape.ts";

const zh: PartialByKey<LessonShape> = {
  title: { zh: [] },
  summary: { zh: [] },
  vocabWanr: { zh: [] },
  proseWhen: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleWhen1: { zh: [] },
  exampleWhen2: { zh: [] },
  exampleWhen3: { zh: [] },
  vocabWan: { zh: [] },
  proseFinished: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleFinished1: { zh: [] },
  exampleFinished2: { zh: [] },
  exampleFinished3: { zh: [] },
  vocabHou: { zh: [] },
  vocabLiu: { zh: [] },
  proseAfter: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleAfter1: { zh: [] },
  exampleAfter2: { zh: [] },
  exampleAfter3: { zh: [] },
  exampleAfter4: { zh: [] },
  exampleAfter5: { zh: [] },
  exampleAfter6: { zh: [] },
  vocabKaishi: { zh: [] },
  proseStart: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleStart1: { zh: [] },
  exampleStart2: { zh: [] },
  exampleStart3: { zh: [] },
  exampleStart4: { zh: [] },
  exampleStart5: { zh: [] },
  vocabYixia: { zh: [] },
  proseMoment: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleMoment1: { zh: [] },
  exampleMoment2: { zh: [] },
  exampleMoment3: { zh: [] },
  exampleMoment4: { zh: [] },
  vocabYou: { zh: [] },
  proseAgain: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleAgain1: { zh: [] },
  exampleAgain2: { zh: [] },
  exampleAgain3: { zh: [] },
  exampleAgain4: { zh: [] },
  vocabCi: { zh: [] },
  proseTimes: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleTimes1: { zh: [] },
  exampleTimes2: { zh: [] },
  exampleTimes3: { zh: [] },
  exampleTimes4: { zh: [] },
  infoAroundAnAction: {
    title: { zh: [] },
    items: [
      { zh: [] },
      { zh: [] },
      { zh: [] },
      { zh: [] },
      { zh: [] },
      { zh: [] },
      { zh: [] },
    ],
  },
  exercise1: { zh: [] },
  exercise2: { zh: [] },
  exercise3: { zh: [] },
  exercise4: { zh: [] },
  exercise5: { zh: [] },
  exercise6: { zh: [] },
  exercise7: { zh: [] },
  exercise8: { zh: [] },
  exercise9: { zh: [] },
  answer1: { zh: [] },
  answer2: { zh: [] },
  answer3: { zh: [] },
  answer4: { zh: [] },
  answer5: { zh: [] },
  answer6: { zh: [] },
  answer7: { zh: [] },
  answer8: { zh: [] },
  answer9: { zh: [] },
  faqWanOrWanr: { question: { zh: [] }, zh: [] },
  faqWanAndLe: { question: { zh: [] }, zh: [] },
};

export default zh;
