// Chinese text for numbers, matching shape.ts's keys. Typed as
// `PartialByKey<LessonShape>`.
// Not translated yet -- every `zh` is the empty-array placeholder.
import type { PartialByKey } from "../../../lib/chapter-shape-types.ts";
import type { LessonShape } from "./shape.ts";

const zh: PartialByKey<LessonShape> = {
  title: { zh: [] },
  summary: { zh: [] },
  vocabYi: { zh: [] },
  vocabEr: { zh: [] },
  vocabSan: { zh: [] },
  vocabSi: { zh: [] },
  vocabWu: { zh: [] },
  vocabLiu: { zh: [] },
  vocabQi: { zh: [] },
  vocabBa: { zh: [] },
  vocabJiu: { zh: [] },
  vocabShi: { zh: [] },
  proseAloud: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleAloud1: { zh: [] },
  exampleAloud2: { zh: [] },
  exampleAloud3: { zh: [] },
  exampleAloud4: { zh: [] },
  exampleAloud5: { zh: [] },
  vocabLiang: { zh: [] },
  proseCount: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleCount1: { zh: [] },
  exampleCount2: { zh: [] },
  exampleCount3: { zh: [] },
  exampleCount4: { zh: [] },
  exampleCount5: { zh: [] },
  exampleCount6: { zh: [] },
  exampleCount7: { zh: [] },
  exampleCount8: { zh: [] },
  exampleCount9: { zh: [] },
  exampleCount10: { zh: [] },
  exampleCount11: { zh: [] },
  exampleCount12: { zh: [] },
  exampleCount13: { zh: [] },
  exampleCount14: { zh: [] },
  exampleCount15: { zh: [] },
  exampleCount16: { zh: [] },
  exampleCount17: { zh: [] },
  exampleCount18: { zh: [] },
  exampleCount19: { zh: [] },
  exampleCount20: { zh: [] },
  exampleCount21: { zh: [] },
  exampleCount22: { zh: [] },
  exampleCount23: { zh: [] },
  exampleCount24: { zh: [] },
  proseTeens: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleTeens1: { zh: [] },
  exampleTeens2: { zh: [] },
  exampleTeens3: { zh: [] },
  exampleTeens4: { zh: [] },
  exampleTeens5: { zh: [] },
  exampleTeens6: { zh: [] },
  vocabHao: { zh: [] },
  proseLabel: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleLabel1: { zh: [] },
  exampleLabel2: { zh: [] },
  exampleLabel3: { zh: [] },
  exampleLabel4: { zh: [] },
  exampleLabel5: { zh: [] },
  vocabDian: { zh: [] },
  proseClock: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleClock1: { zh: [] },
  exampleClock2: { zh: [] },
  exampleClock3: { zh: [] },
  exampleClock4: { zh: [] },
  exampleClock5: { zh: [] },
  proseLittle: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleLittle1: { zh: [] },
  exampleLittle2: { zh: [] },
  exampleLittle3: { zh: [] },
  exampleLittle4: { zh: [] },
  exampleLittle5: { zh: [] },
  vocabSuan: { zh: [] },
  proseAddTake: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleAddTake1: { zh: [] },
  exampleAddTake2: { zh: [] },
  exampleAddTake3: { zh: [] },
  exampleAddTake4: { zh: [] },
  exampleAddTake5: { zh: [] },
  exampleAddTake6: { zh: [] },
  exampleAddTake7: { zh: [] },
  exampleAddTake8: { zh: [] },
  proseTimesShare: { zh: [], tldr: { zh: [] }, necessity: { zh: [] } },
  exampleTimesShare1: { zh: [] },
  exampleTimesShare2: { zh: [] },
  exampleTimesShare3: { zh: [] },
  exampleTimesShare4: { zh: [] },
  infoCounting: {
    title: { zh: [] },
    items: [{ zh: [] }, { zh: [] }, { zh: [] }, { zh: [] }, { zh: [] }, { zh: [] }, { zh: [] }, { zh: [] }],
  },
  exercise1: { zh: [] },
  exercise2: { zh: [] },
  exercise3: { zh: [] },
  exercise4: { zh: [] },
  exercise5: { zh: [] },
  exercise6: { zh: [] },
  exercise7: { zh: [] },
  exercise8: { zh: [] },
  exercise9: { zh: [] },
  exercise10: { zh: [] },
  exercise11: { zh: [] },
  exercise12: { zh: [] },
  exercise13: { zh: [] },
  exercise14: { zh: [] },
  exercise15: { zh: [] },
  exercise16: { zh: [] },
  exercise17: { zh: [] },
  exercise18: { zh: [] },
  exercise19: { zh: [] },
  exercise20: { zh: [] },
  answer1: { zh: [] },
  answer2: { zh: [] },
  answer3: { zh: [] },
  answer4: { zh: [] },
  answer5: { zh: [] },
  answer6: { zh: [] },
  answer7: { zh: [] },
  answer8: { zh: [] },
  answer9: { zh: [] },
  answer10: { zh: [] },
  answer11: { zh: [] },
  answer12: { zh: [] },
  answer13: { zh: [] },
  answer14: { zh: [] },
  answer15: { zh: [] },
  answer16: { zh: [] },
  answer17: { zh: [] },
  answer18: { zh: [] },
  answer19: { zh: [] },
  answer20: { zh: [] },
  faqErInBigNumbers: { question: { zh: [] }, zh: [] },
  faqHaoDays: { question: { zh: [] }, zh: [] },
  faqYiTone: { question: { zh: [] }, zh: [] },
  faqPlusWords: { question: { zh: [] }, zh: [] },
};

export default zh;
